#!/usr/bin/env bash
# Reflect the C# program language's signature catalogue out of the SDK's own XML documentation
# comments, and write it to $GG_SIGNATURES_OUT_DIR/csharp.signatures.json.
#
# WHERE IT WRITES, AND WHY THERE IS NO DEFAULT. The catalogue is a BUILD ARTIFACT.
# `crates/gg/build.rs` runs `scripts/gg-signatures.sh` and embeds what lands in the build's own
# `OUT_DIR`, so the `<summary>` a model is shown is reflected on the same build that compiles the
# host showing it — a `<param>` edited without a regeneration is not a state this checkout can be in.
# A default here would be a second answer to a question the build already answers, and the old one,
# `crates/gg/src/sandbox/guests/`, is the answer that stopped being right: that directory held this
# arm's component last of all, and it no longer exists — the component is cut into a cargo `OUT_DIR`
# too. Run this by hand, into a directory of your choosing, to READ a catalogue —
# which is what `scripts/gg-signatures.sh` is for, and how a reflector bug gets found.
#
# WHY ROSLYN. Everything a model reads about this surface is written on the declaration it describes
# — a function's brief in its `<summary>`, its detail in its `<remarks>`, an argument's in that
# argument's `<param>`, a record component's in the `<param>` on the record, an enum constant's in
# the comment above it, a module's on the `static partial class` that IS the module — or, for the one
# module that is no class at all, on the `internal` class `src/Gg/Core/Errors.cs` ends with — and a
# type's on its own declaration nested inside that module, and Roslyn reads all of it. It is also the
# compiler this arm runs on every turn, so the catalogue is reflected by the same reading of the same
# sources a model's program is compiled against, rather than by a second tool that could disagree
# with the first.
#
# WHAT THIS NEEDS. Only the .NET toolchain `scripts/ci/install-gg-toolchains.sh` installs — the same
# ~122 MB tree that compiles a program. `Microsoft.CodeAnalysis.CSharp.dll` ships beside `csc.dll` in
# it, so nothing here fetches a package, and this script is runnable on any machine that can build
# gg — which, now that the build generates this catalogue, is every machine that builds gg.
#
# WHAT IT REFUSES. `tools/Signatures.cs` treats every Roslyn warning as fatal, including the
# documentation ones, and refuses to emit a catalogue with a blank anywhere in it. So a `<param>`
# naming an argument that is not there, a `<see cref>` pointing at nothing, an undocumented public
# member and an undocumented parameter each fail here rather than reaching a model.
#
# Usage:
#   GG_SIGNATURES_OUT_DIR=<dir> packages/gg-sandbox-csharp/signatures.sh
#   scripts/gg-signatures.sh                 # all eleven arms, into one directory
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -z "${GG_SIGNATURES_OUT_DIR:-}" ]; then
	echo "error: GG_SIGNATURES_OUT_DIR is not set. It names the directory this catalogue is" >&2
	echo "       written into, and there is no default — the catalogue is generated by the build" >&2
	echo "       rather than committed anywhere." >&2
	echo "       Run scripts/gg-signatures.sh (which sets it and regenerates every arm), or set" >&2
	echo "       it yourself to a directory you want the JSON in." >&2
	exit 1
fi
# Created, then made absolute: the reflector writes into a `mktemp -d` and the result is moved here,
# so a relative destination would be resolved against whatever directory the caller was in.
mkdir -p "$GG_SIGNATURES_OUT_DIR"
OUT="$(cd "$GG_SIGNATURES_OUT_DIR" && pwd)/csharp.signatures.json"

# shellcheck source=packages/gg-sandbox-csharp/csharp-version.sh
source "$HERE/csharp-version.sh"

DOTNET_HOME="$(gg_dotnet_home)"
LAUNCHER="$DOTNET_HOME/dotnet/dotnet"
BINCORE="$DOTNET_HOME/roslyn/bincore"

if [ ! -x "$LAUNCHER" ] || [ ! -f "$BINCORE/Microsoft.CodeAnalysis.CSharp.dll" ]; then
	echo "error: no .NET toolchain at $DOTNET_HOME — run scripts/ci/install-gg-toolchains.sh" >&2
	exit 1
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

export DOTNET_ROOT="$DOTNET_HOME/dotnet"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1

# The reflector runs beside Roslyn's own assemblies, because a .NET application with no `deps.json`
# resolves its dependencies out of its own directory. Symlinked rather than copied: they are 30 MB
# and they are read-only here.
for assembly in "$BINCORE"/*.dll; do
	ln -s "$assembly" "$WORK/$(basename "$assembly")"
done

{
	echo -nologo
	echo -nostdlib+
	echo -target:exe
	echo "-langversion:$GG_DOTNET_LANG_VERSION"
	echo -nullable:enable
	echo -warnaserror+
	echo "-main:Tools.Signatures"
	echo "-out:$WORK/Signatures.dll"
	find "$DOTNET_HOME/ref" -name '*.dll' | sort | sed 's/^/-r:/'
	echo "-r:$BINCORE/Microsoft.CodeAnalysis.dll"
	echo "-r:$BINCORE/Microsoft.CodeAnalysis.CSharp.dll"
	echo "$HERE/tools/Catalogue.cs"
	echo "$HERE/tools/Signatures.cs"
} >"$WORK/csc.rsp"

"$LAUNCHER" exec "$BINCORE/csc.dll" -noconfig "@$WORK/csc.rsp"

cat >"$WORK/Signatures.runtimeconfig.json" <<EOF
{
  "runtimeOptions": {
    "tfm": "$GG_DOTNET_TFM",
    "framework": { "name": "Microsoft.NETCore.App", "version": "$GG_DOTNET_RUNTIME_VERSION" },
    "configProperties": { "System.Reflection.Metadata.MetadataUpdater.IsSupported": false }
  }
}
EOF

"$LAUNCHER" exec "$WORK/Signatures.dll" \
	--sdk "$HERE/src/Gg" \
	--references "$DOTNET_HOME/ref" \
	--libraries "$HERE/libraries.txt" \
	--out "$WORK/csharp.signatures.json"

mv "$WORK/csharp.signatures.json" "$OUT"
echo "wrote $OUT ($(wc -c <"$OUT") bytes)"
