// generation/cave-mouth-open — the way down out of the camp is never sealed.
//
// `specs/world.md` fixes one cell of the first row of ground by name:
// `(CAVE_MOUTH_COL, 1)`, that is `(26, 1)`, is an open tunnel in every generated
// mine. It is the only opening the camp has, so a mine that generated rock there
// leaves the prospector standing on a lid it has to drill through before the
// expedition can begin — and a build that carved the mouth for one seed and not
// another leaves a run that cannot start.
//
// So the reading is taken across several seeds and every world size, and it is
// taken on a mine generated by the build's own generation rather than on a posed
// one: `clearMine` opens the whole grid and would report the mouth open however
// generation left it.

import { afterEach, beforeEach, it } from "vitest";
import { CAVE_MOUTH_COL, WORLD_SIZES } from "../constants";
import { assertEqual } from "../assert";
import { captureStill, createHarness, type Harness } from "../harness";
import { generatedMine, kindAt, look } from "./mine-scan";

/** The seeds the mouth is read at. Several, because the rule is every mine's. */
const SEEDS = [1, 2, 3, 7, 19] as const;

let h: Harness;

beforeEach(async () => {
  h = await createHarness();
});

afterEach(() => {
  h?.dispose();
});

it("leaves (26, 1) an open tunnel in every generated mine", async () => {
  for (const size of WORLD_SIZES) {
    for (const seed of SEEDS) {
      const at = `${size} mine on seed ${seed}`;
      const scan = generatedMine(h, seed, size);
      assertEqual(kindAt(scan, CAVE_MOUTH_COL, 1), "tunnel", at);
    }
  }

  // The picture the reviewer sees: the mouth at the edge of the camp, on the
  // mine the last reading was taken from.
  await look(h, CAVE_MOUTH_COL, 3);
  captureStill(h, "mouth");
});
