//! `GET /gg/reference` and `GET /gg/reference/{language}` — gg's model-facing surface,
//! served as data from files gg itself wrote.
//!
//! Two documents, because the surface has two halves. The **index** is everything that
//! belongs to no program language: every tool gg can offer a model — its description and
//! parameter schema, exactly as they go on the wire — grouped into gg's own families, plus
//! a line per [program language](https://docs.testcabinet.ai/gg/languages/overview/) gg
//! registers. Each arm's own
//! [responses-as-code](https://docs.testcabinet.ai/gg/languages/agent-surface/) surface is a
//! document of its own, fetched when a reader picks that arm, because the eleven SDKs are
//! deliberately idiomatic rather than transliterations of one another and a page showing
//! one of them would be documenting a tenth of gg while looking complete.
//!
//! # Why files read at run time rather than an artifact compiled in
//!
//! The honest way to answer "what was the model told `read_file` does?" is to ask a live
//! [`ToolRegistry`] — and that is what happens, just not in this process. The backend must
//! not depend on `test-cabinet-gg`, for two reasons that are worth stating exactly because
//! the obvious one is wrong. It is **not** wasmtime: this binary already links wasmtime,
//! statically, under musl, through `foray-host` and `lattice-host` by way of
//! `test-cabinet-core`. It is that gg pulls `oxc` and `tiktoken-rs`, neither of which is
//! anywhere in this crate's tree, and — the larger cost — that *building* gg reflects a
//! signature catalogue out of each of its eleven SDKs with that SDK's own documentation
//! tool and compiles every arm's artifacts, so every machine and every CI job that links it
//! needs eleven language toolchains on disk first. A backend that linked gg would make the
//! whole of that a prerequisite for compiling the server.
//!
//! So the projection runs in **gg**, whose `reference --out <dir>` writes the twelve
//! documents from its own tool registry and its own documentation runtime, and the backend
//! reads that directory.
//!
//! This crate used to embed the projection instead — one arm of it, generated by
//! `npm run gen:contract`, committed as `crates/backend/src/gg_reference.json` and gated by
//! a regenerate-and-diff check. That was a second source of truth with a guard bolted to
//! it, and a guard is not the same thing as not having the problem: the committed bytes
//! could disagree with the gg in the image beside them for as long as it took somebody to
//! run the gate. A file the *same build* produced cannot. It is the move
//! `crates/gg/build.rs` already made for the eleven signature catalogues and the arms'
//! artifacts, one level up.
//!
//! What it costs is that a missing file is now a run-time condition rather than a compile
//! error, so this module is deliberately loud about it: see [`unavailable`].
//!
//! # Where the directory comes from
//!
//! [`Config::gg_reference`](crate::config::Config::gg_reference) — `TCAB_GG_REFERENCE`.
//! The backend image bakes the documents at `/opt/gg-reference` out of the same build stage
//! that produces the gg binary the driver image ships, so a deployed backend and the gg its
//! runs execute are one build of one checkout. A developer running the binary from a
//! checkout points it at `target/gg-reference` by default and fills that with
//! `scripts/gg-reference.sh`.
//!
//! # Why it is ungated
//!
//! Everything under `/gg` so far is auth-gated, so this is the exception and it is a
//! deliberate one: the documents are static, identical for every caller, and contain no
//! account, run or deployment data — they are documentation of the harness, in the same
//! class as `/test-cases` and `/config`. Requiring a token would buy nothing and would stop
//! the public docs and a signed-out console from linking to it. `/gg/reference` is a static
//! path and `/gg/reference/{language}` its only child, so neither collides with anything
//! else mounted under `/gg`.
//!
//! [`ToolRegistry`]: https://docs.testcabinet.ai/gg/toolset-ablation/

#[cfg(test)]
#[path = "gg_reference.test.rs"]
mod tests;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use axum::Json;
use axum::extract::{Path as UrlPath, State};
use axum::http::StatusCode;

use test_cabinet_core::gg::GgProgramLanguage;
use test_cabinet_core::gg_reference::{
    GgReference, GgReferenceApi, GgReferenceEntryKind, GgReferenceLanguage, document_file,
    index_file,
};

use crate::error::ApiError;

use super::AppState;

/// The reference directory, decoded.
///
/// Keyed by [`GgProgramLanguage`] rather than by the raw path segment so a document whose
/// `language` field disagrees with its filename cannot be reached under the wrong name;
/// a [`BTreeMap`] rather than a hash map so the "arms present" list in a `404` comes out in
/// gg's own registration order, which is the order the picker shows them in.
#[derive(Debug)]
struct Loaded {
    /// The language-independent half: families, tools, and the arm list — the last of which
    /// is *this* deployment's, rebuilt from [`arms`](Self::arms) rather than taken from the
    /// file. See [`load`].
    index: GgReference,
    /// Every arm whose document was read and decoded, keyed by the id it is fetched under.
    arms: BTreeMap<GgProgramLanguage, GgReferenceApi>,
}

/// Why the reference could not be loaded.
///
/// Both variants are the *same operational fact* — this deployment has no reference
/// documents where it was told to look — and both carry the path, because the single most
/// common cause is a `TCAB_GG_REFERENCE` pointing somewhere plausible and empty.
#[derive(Debug, thiserror::Error)]
enum ReferenceError {
    /// The index file could not be read: no directory, no file, or no permission.
    #[error("cannot read {path}: {source}")]
    Unreadable {
        /// The index file that was looked for.
        path: PathBuf,
        /// The underlying filesystem error.
        source: std::io::Error,
    },
    /// The index file was read but is not a [`GgReference`].
    ///
    /// In practice this means a backend and a gg from different versions: the documents
    /// are machine-written, so nothing else edits them.
    #[error("cannot decode {path}: {source}")]
    Malformed {
        /// The document that failed to decode.
        path: PathBuf,
        /// The underlying decoding error.
        source: serde_json::Error,
    },
}

/// Read the whole reference directory: the index, then every arm the index lists.
///
/// An arm that is listed but cannot be read or decoded is **warned about and skipped**
/// rather than failing the load, so one bad document costs one arm instead of the page.
/// The reader who asks for it gets a `404` naming the arms that are present, which is a far
/// more useful thing to see than ten working arms replaced by a `503`.
///
/// # The index that is served is not the index that was read
///
/// [`GgReference::languages`] is rebuilt here from the arm documents this process actually
/// loaded, and that is the one substantive thing this function does beyond decoding. The
/// list in the file is a claim about eleven *other* files, written by a different process
/// at a different time; the picker in the console renders it as "these are the arms you can
/// open, and this is how big each one is". Serving the claim would mean advertising an arm
/// whose document is not beside the index — a chip that answers `404` — and advertising a
/// size taken from a document nobody read, which a hollowed-out or half-written file makes
/// a lie. Rebuilding costs one fold over documents that are already in memory and makes
/// every number the picker shows a number this process counted.
///
/// The filenames come from `core` rather than from a constant here, because the process
/// that writes them is `test-cabinet-gg` — a crate this one deliberately does not link, so
/// the layout is a contract with two sides and no compiler between them unless both sides
/// call the same function.
fn load(directory: &Path) -> Result<Loaded, ReferenceError> {
    let index_path = directory.join(index_file());
    let index_json =
        std::fs::read_to_string(&index_path).map_err(|source| ReferenceError::Unreadable {
            path: index_path.clone(),
            source,
        })?;
    let mut index: GgReference =
        serde_json::from_str(&index_json).map_err(|source| ReferenceError::Malformed {
            path: index_path,
            source,
        })?;

    let mut arms = BTreeMap::new();
    for language in &index.languages {
        let path = directory.join(document_file(language.id));
        let document = match std::fs::read_to_string(&path) {
            Ok(json) => json,
            Err(err) => {
                tracing::warn!(
                    path = %path.display(),
                    error = %err,
                    "gg reference: the index lists an arm whose document is not beside it"
                );
                continue;
            }
        };
        match serde_json::from_str::<GgReferenceApi>(&document) {
            Ok(api) => {
                // A document that decodes to nothing is as broken as one that does not decode
                // at all — the projection ran and produced no surface — and it is the quieter
                // of the two: it is served `200` and reads on the page as an arm somebody
                // filtered everything out of. There is no such thing as a legitimately empty
                // arm; every registered one carries at least the types-only module.
                if api.entries.is_empty() {
                    tracing::warn!(
                        path = %path.display(),
                        "gg reference: an arm's document carries no entries — it will be served, \
                         and it is empty"
                    );
                }
                arms.insert(api.language, api);
            }
            Err(err) => tracing::warn!(
                path = %path.display(),
                error = %err,
                "gg reference: an arm's document does not decode as GgReferenceApi"
            ),
        }
    }

    index.languages = arms.values().map(counted).collect();
    Ok(Loaded { index, arms })
}

/// One arm's line in the served index, **measured from the document itself**.
///
/// The same three numbers gg writes into `index.json`, recounted here rather than copied
/// across from it — see [`load`] for why the file's own line is not the thing to serve. The
/// order of the languages follows the [`BTreeMap`] the arms are kept in, which is gg's
/// registration order, so the picker's row is in the order gg lists its arms whatever order
/// the index file happened to use.
fn counted(document: &GgReferenceApi) -> GgReferenceLanguage {
    let of_kind = |kind: GgReferenceEntryKind| {
        document
            .entries
            .iter()
            .filter(|entry| entry.kind == kind)
            .count()
    };
    GgReferenceLanguage {
        id: document.language,
        module_count: document.modules.len(),
        function_count: of_kind(GgReferenceEntryKind::Function),
        type_count: of_kind(GgReferenceEntryKind::Type),
    }
}

/// The loaded reference, read on first use and kept for the process's lifetime.
///
/// **Lazily, not at startup**, and that is the point of the whole shape: a backend with no
/// reference documents must still serve runs, reviews and the catalog. The reference is a
/// documentation page; it is the only thing that degrades.
///
/// **Only success is cached.** A failure is left uncached deliberately, so that a developer
/// who starts the backend, sees the `503`, and runs `scripts/gg-reference.sh` gets a
/// working page on the next request instead of having to restart the process to clear a
/// memoized error. It costs one failed directory read per request in exactly the state
/// where nothing is being served anyway. (In a container the documents are baked into the
/// image and cannot appear later, so this branch is a developer affordance and nothing
/// more.)
fn reference(directory: &Path) -> Result<&'static Loaded, ApiError> {
    static LOADED: OnceLock<Loaded> = OnceLock::new();
    if let Some(loaded) = LOADED.get() {
        return Ok(loaded);
    }
    let loaded = load(directory).map_err(|err| unavailable(directory, &err))?;
    // Two concurrent first requests can both get here; `get_or_init` makes one of them the
    // winner and drops the loser's copy, and both then borrow the same documents.
    Ok(LOADED.get_or_init(|| loaded))
}

/// The `503` a deployment with no reference documents answers with.
///
/// It names **the two things that fix it**, because this is the one failure the move to
/// run-time files introduced and a blank page would be a worse trade than the drift it
/// replaced. `service_unavailable` rather than `internal`: nothing went wrong with the
/// request, and nothing about this backend's actual work is affected — the operator is
/// missing a file that ships beside the binary.
fn unavailable(directory: &Path, err: &ReferenceError) -> ApiError {
    ApiError::new(
        StatusCode::SERVICE_UNAVAILABLE,
        "gg_reference_unavailable",
        format!(
            "gg's reference documents are not available ({err}). They are written by \
             `gg reference --out <dir>`: the backend image bakes them and points \
             TCAB_GG_REFERENCE at them, and from a checkout `scripts/gg-reference.sh` \
             writes them to the default location. TCAB_GG_REFERENCE currently resolves to \
             {}.",
            directory.display()
        ),
    )
}

/// Resolve one arm's document by the id in the URL, or `404` naming what *is* here.
///
/// One branch for two failures — an id that is no program language at all, and one that is
/// but whose document did not load — because they are the same thing from the caller's
/// side: this deployment cannot serve that arm. Listing the arms it can serve is what makes
/// the answer actionable rather than merely negative, and it is the only place a reader can
/// see that a particular arm is the one that is missing.
fn arm<'a>(loaded: &'a Loaded, id: &str) -> Result<&'a GgReferenceApi, ApiError> {
    GgProgramLanguage::from_id(id)
        .and_then(|language| loaded.arms.get(&language))
        .ok_or_else(|| {
            let present = loaded
                .arms
                .keys()
                .map(|language| language.id())
                .collect::<Vec<_>>()
                .join(", ");
            ApiError::not_found(format!(
                "no gg reference document for `{id}`; this deployment serves: {present}"
            ))
        })
}

/// `GET /gg/reference`
///
/// gg's families, its whole tool vocabulary, and the arms whose surfaces are served
/// separately — verbatim. No auth, no state, no database read: the body is the index
/// document, decoded once for the process's lifetime and borrowed thereafter.
pub async fn gg_reference(
    State(state): State<AppState>,
) -> Result<Json<&'static GgReference>, ApiError> {
    Ok(Json(&reference(&state.config.gg_reference)?.index))
}

/// `GET /gg/reference/{language}`
///
/// One program language's whole responses-as-code surface: every function and type gg
/// offers on that arm, each carrying the bytes that arm's own documentation view renders
/// for a model. The `{language}` segment is a
/// [`GgProgramLanguage`] id (`typescript`, `kotlin`, …) — the same string a run's
/// `language` capability param is configured with.
pub async fn gg_reference_api(
    State(state): State<AppState>,
    UrlPath(language): UrlPath<String>,
) -> Result<Json<&'static GgReferenceApi>, ApiError> {
    let loaded = reference(&state.config.gg_reference)?;
    Ok(Json(arm(loaded, &language)?))
}
