import { useEffect, useMemo, useState } from "react";
import type { GgBoardIssue, GgIssueStatus } from "@test-cabinet/run-record/gg";
import type { BoardState, CodeReviewState } from "./useGgRunState";
import {
  Blockers,
  REVIEW_LABELS,
  READINESS_LABELS,
  ReviewItems,
  STATUS_LABELS,
  deriveIssue,
} from "./BoardView";
import { useGgExplorerNav } from "./GgExplorerNav";
import { EpicIcon, FolderIcon, FolderOpenIcon, IssueIcon } from "./ggIcons";
import panels from "./GgPanels.module.scss";

// The Project explorer: gg's run-global epic/issue board, read like a filesystem.
//
// Unlike the per-agent views in the Agents explorer, the board is *one* thing shared
// by the whole run (see gg/project-management): submitting an issue enqueues it, and
// gg dispatches a top-level agent to implement it once its blockers clear. So the
// board is a whole-run surface, not a per-agent file — this tab lays it out as a
// directory of epics-as-folders whose "files" are an autogenerated epic summary and
// each issue under it. Selecting a file opens that epic's or issue's detail on the
// right, the same master/detail shape the Agents explorer uses for agents.

function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

// The synthetic id of the "Ungrouped" bucket — issues with no (known) epic. It is not
// a real epic, so it carries no epic-summary file, just its issues.
const UNGROUPED_ID = "__ungrouped__";

// One epic bucket for rendering: the epic (a real one, or the synthetic Ungrouped
// bucket) and the issues under it, in board order.
interface EpicGroup {
  id: string;
  title: string;
  description: string | null;
  isEpic: boolean;
  issues: GgBoardIssue[];
}

// The lifecycle-status dot an issue shows in the tree — reusing the agent status-dot
// palette so open reads muted, in-progress accent, done positive, and failed negative
// (so a terminally failed issue is visually distinct).
function issueDotStatus(status: GgIssueStatus): string {
  switch (status) {
    case "in_progress":
      return "running";
    case "done":
      return "done";
    case "failed":
      return "failed";
    default:
      return "open";
  }
}

// Bucket the board's issues under their epic, preserving board order within each
// bucket, plus a trailing "Ungrouped" bucket for issues whose epic is unset or
// unknown. Mirrors `BoardView`'s grouping so the two surfaces read the same board the
// same way.
function groupBoard(board: BoardState): EpicGroup[] {
  const { epics, issues } = board;
  const epicIds = new Set(epics.map((e) => e.id));
  const groups: EpicGroup[] = epics.map((e) => ({
    id: e.id,
    title: e.title,
    description: e.description || null,
    isEpic: true,
    issues: [],
  }));
  const groupById = new Map(groups.map((g) => [g.id, g]));
  const ungrouped: EpicGroup = {
    id: UNGROUPED_ID,
    title: "Ungrouped",
    description: null,
    isEpic: false,
    issues: [],
  };
  for (const issue of issues) {
    const key = issue.epicId && epicIds.has(issue.epicId) ? issue.epicId : null;
    (key ? groupById.get(key)! : ungrouped).issues.push(issue);
  }
  return ungrouped.issues.length ? [...groups, ungrouped] : groups;
}

// A selected "file" in the tree: either an epic's summary, or one issue's detail.
type Selection =
  | { kind: "epic"; groupId: string }
  | { kind: "issue"; issueId: string };

interface ProjectExplorerProps {
  // The run-global board (latest `board_state` across the whole stream); null when the
  // project-management capability produced no snapshot yet.
  board: BoardState | null;
  // Per-issue Code Review lifecycle, keyed by issue id (see gg/code-reviews); empty
  // when the code-reviews capability is off, so no review badges are shown.
  codeReviews: Map<string, CodeReviewState>;
}

/**
 * The Project tab — the run-global epic/issue board, read as a filesystem of
 * epics-as-folders and epic/issue detail-as-files. Offered only when the run's
 * configuration has the project-management capability on (see {@link GgRunPanels}).
 */
export function ProjectExplorer({ board, codeReviews }: ProjectExplorerProps) {
  const groups = useMemo(() => (board ? groupBoard(board) : []), [board]);
  const byId = useMemo(
    () => new Map((board?.issues ?? []).map((i) => [i.id, i])),
    [board],
  );

  // The default landing: the first epic's summary, or — if the first bucket is the
  // Ungrouped one (no summary) — its first issue. Recomputed only for the initial
  // selection; `useEffect` below keeps it valid as the live board grows.
  const firstSelection = useMemo<Selection | null>(() => {
    for (const group of groups) {
      if (group.isEpic) return { kind: "epic", groupId: group.id };
      if (group.issues.length)
        return { kind: "issue", issueId: group.issues[0]!.id };
    }
    return null;
  }, [groups]);

  const [selection, setSelection] = useState<Selection | null>(firstSelection);

  // Folders open by default — a run's board is small, and seeing it whole is the
  // point — so the set holds only what the user has explicitly collapsed.
  const [collapsed, setCollapsed] = useState<ReadonlySet<string>>(
    () => new Set(),
  );
  const toggle = (key: string) =>
    setCollapsed((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });

  // Keep the selection valid as the stream reshapes the board: a selected epic that
  // was removed, or a selected issue that is gone, falls back to the first file.
  useEffect(() => {
    const stillValid =
      selection != null &&
      (selection.kind === "epic"
        ? groups.some((g) => g.isEpic && g.id === selection.groupId)
        : byId.has(selection.issueId));
    if (!stillValid) setSelection(firstSelection);
  }, [groups, byId, selection, firstSelection]);

  if (!board || (board.epics.length === 0 && board.issues.length === 0)) {
    return (
      <div className={panels.panelBody}>
        <p className={panels.empty}>
          No epics or issues yet — the project-management board streams the
          run's shared epics and issues here as the model decomposes and
          dispatches the work.
        </p>
      </div>
    );
  }

  const selectedIssue =
    selection?.kind === "issue" ? (byId.get(selection.issueId) ?? null) : null;
  const selectedGroup =
    selection?.kind === "epic"
      ? (groups.find((g) => g.id === selection.groupId) ?? null)
      : null;

  return (
    <div className={panels.explorer}>
      <nav className={panels.explorerSidebar} aria-label="Project board">
        <ul className={panels.fsTree}>
          {groups.map((group) => (
            <EpicFolder
              key={group.id}
              group={group}
              collapsed={collapsed}
              toggle={toggle}
              selection={selection}
              onSelect={setSelection}
            />
          ))}
        </ul>
      </nav>
      <div className={panels.explorerContent}>
        {selectedIssue ? (
          <IssueDetail
            issue={selectedIssue}
            byId={byId}
            review={codeReviews.get(selectedIssue.id) ?? null}
          />
        ) : selectedGroup ? (
          <EpicDetail group={selectedGroup} />
        ) : (
          <p className={panels.empty}>Select an epic or issue.</p>
        )}
      </div>
    </div>
  );
}

// One epic folder: its autogenerated epic-summary file (real epics only) followed by
// each of its issues as a file, each carrying a status dot.
function EpicFolder({
  group,
  collapsed,
  toggle,
  selection,
  onSelect,
}: {
  group: EpicGroup;
  collapsed: ReadonlySet<string>;
  toggle: (key: string) => void;
  selection: Selection | null;
  onSelect: (selection: Selection) => void;
}) {
  const folderKey = `epic:${group.id}`;
  const open = !collapsed.has(folderKey);
  const done = group.issues.filter((i) => i.status === "done").length;
  const epicSelected =
    selection?.kind === "epic" && selection.groupId === group.id;

  return (
    <li className={panels.fsNode}>
      <button
        type="button"
        className={panels.fsRow}
        aria-expanded={open}
        onClick={() => toggle(folderKey)}
      >
        <span className={panels.fsCaret} aria-hidden="true">
          {open ? "▾" : "▸"}
        </span>
        {open ? (
          <FolderOpenIcon className={panels.fsIcon} />
        ) : (
          <FolderIcon className={panels.fsIcon} />
        )}
        <span className={panels.fsName}>{group.title}</span>
        <span className={panels.fsMeta}>
          {done}/{group.issues.length}
        </span>
      </button>
      {open && (
        <ul className={panels.fsChildren}>
          {group.isEpic && (
            <li>
              <button
                type="button"
                className={cx(
                  panels.fsRow,
                  panels.fsFile,
                  epicSelected && panels.fsRowActive,
                )}
                aria-label={`${group.title} epic`}
                aria-current={epicSelected ? "true" : undefined}
                onClick={() => onSelect({ kind: "epic", groupId: group.id })}
              >
                <EpicIcon className={panels.fsIcon} />
                <span className={panels.fsName}>epic</span>
              </button>
            </li>
          )}
          {group.issues.map((issue) => {
            const selected =
              selection?.kind === "issue" && selection.issueId === issue.id;
            return (
              <li key={issue.id}>
                <button
                  type="button"
                  className={cx(
                    panels.fsRow,
                    panels.fsFile,
                    selected && panels.fsRowActive,
                  )}
                  aria-label={`issue ${issue.title}`}
                  aria-current={selected ? "true" : undefined}
                  onClick={() => onSelect({ kind: "issue", issueId: issue.id })}
                >
                  <IssueIcon className={panels.fsIcon} />
                  <span className={panels.fsName}>{issue.title}</span>
                  <span
                    className={panels.fsStatusDot}
                    data-status={issueDotStatus(issue.status)}
                    aria-hidden="true"
                  />
                </button>
              </li>
            );
          })}
        </ul>
      )}
    </li>
  );
}

// An epic's summary detail: its id, title, description, and a tally of its issues by
// status — the epic carries no status of its own, so its progress is read off the
// issues under it.
function EpicDetail({ group }: { group: EpicGroup }) {
  const counts = countByStatus(group.issues);
  return (
    <div className={panels.panelBody}>
      <div className={panels.projDetail}>
        <header className={panels.projDetailHead}>
          <h3 className={panels.projDetailTitle}>{group.title}</h3>
          <span className={panels.issueId}>{group.id}</span>
        </header>
        {group.description && (
          <p className={panels.issueDesc}>{group.description}</p>
        )}
        {group.issues.length === 0 ? (
          <p className={panels.empty}>No issues yet.</p>
        ) : (
          <div className={panels.projStatusSummary}>
            {(["open", "in_progress", "done", "failed"] as GgIssueStatus[]).map(
              (status) =>
                counts[status] > 0 ? (
                  <span
                    key={status}
                    className={panels.statusBadge}
                    data-status={status}
                  >
                    {counts[status]} {STATUS_LABELS[status]}
                  </span>
                ) : null,
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// One issue's detail: its readiness + status, the assigned agent (a link into the
// Agents explorer) and retry count, its blocked-by edges, any code-review items, and
// its full structured brief (shown open, since the detail pane is where you read it).
function IssueDetail({
  issue,
  byId,
  review,
}: {
  issue: GgBoardIssue;
  byId: Map<string, GgBoardIssue>;
  review: CodeReviewState | null;
}) {
  const nav = useGgExplorerNav();
  const { readiness, incomplete } = deriveIssue(issue, byId);
  return (
    <div className={panels.panelBody}>
      <div className={panels.projDetail}>
        <header className={panels.projDetailHead}>
          <span className={panels.taskBadge} data-task-state={readiness}>
            {READINESS_LABELS[readiness]}
          </span>
          <h3 className={panels.projDetailTitle} data-status={issue.status}>
            {issue.title}
          </h3>
          <span className={panels.statusBadge} data-status={issue.status}>
            {STATUS_LABELS[issue.status]}
          </span>
          {review && (
            <span
              className={panels.reviewBadge}
              data-review-phase={review.phase}
            >
              {REVIEW_LABELS[review.phase]}
            </span>
          )}
          <span className={panels.issueId}>{issue.id}</span>
        </header>

        {issue.description && (
          <p className={panels.issueDesc}>{issue.description}</p>
        )}

        <dl className={panels.projMeta}>
          <div className={panels.projMetaRow}>
            <dt className={panels.projMetaLabel}>Assigned agent</dt>
            <dd className={panels.projMetaValue}>
              {issue.assignedAgentId ? (
                nav ? (
                  <button
                    type="button"
                    className={panels.projAgentLink}
                    onClick={() => nav.openAgent(issue.assignedAgentId!)}
                  >
                    {issue.assignedAgentId}
                  </button>
                ) : (
                  issue.assignedAgentId
                )
              ) : (
                "—"
              )}
            </dd>
          </div>
          <div className={panels.projMetaRow}>
            <dt className={panels.projMetaLabel}>Retries</dt>
            <dd className={panels.projMetaValue}>{issue.retries}</dd>
          </div>
        </dl>

        {issue.blockedBy.length > 0 && (
          <Blockers
            issue={issue}
            byId={byId}
            incomplete={new Set(incomplete)}
          />
        )}

        {review?.phase === "changes_requested" && review.items.length > 0 && (
          <ReviewItems items={review.items} />
        )}

        <dl className={panels.briefGrid}>
          <BriefField label="In scope" body={issue.inScope} />
          <BriefField label="Out of scope" body={issue.outOfScope} />
          <BriefField
            label="Completion criteria"
            body={issue.completionCriteria}
          />
        </dl>
      </div>
    </div>
  );
}

function BriefField({ label, body }: { label: string; body: string }) {
  return (
    <div className={panels.briefField}>
      <dt className={panels.briefLabel}>{label}</dt>
      <dd className={panels.briefText}>{body || "—"}</dd>
    </div>
  );
}

// Count a bucket of issues by status, so an epic can show its progress.
function countByStatus(issues: GgBoardIssue[]): Record<GgIssueStatus, number> {
  const counts: Record<GgIssueStatus, number> = {
    open: 0,
    in_progress: 0,
    done: 0,
    failed: 0,
  };
  for (const issue of issues) counts[issue.status] += 1;
  return counts;
}
