//! The display catalog for the `code.*` namespace: one [`CodeMetricDef`] per numeric or
//! boolean leaf of [`CodeAnalysisSummary`](super::CodeAnalysisSummary).
//!
//! Split out of [`code_analysis`](super) because it is a long, flat table and the types it
//! describes are easier to read without it in the way.
//!
//! It is **not** a query vocabulary. The query language derives its field catalog from the
//! documents it has actually indexed, so a metric added to the summary is queryable the
//! moment a run carries it, with or without an entry here. What an entry buys is the
//! things a chart cannot infer from a number: a label, a unit, a family, a polarity, and —
//! the reason the table exists — the `approximate` flag, read by the field sidebar, the
//! chart axis, the symbol-table header and the docs page alike so the four cannot drift
//! apart.
//!
//! A missing entry is therefore a *display* defect, not a correctness one, which is why
//! `catalog_paths_resolve` asserts the other direction: every path here must resolve
//! against a serialized summary, so a renamed field fails the suite instead of silently
//! unlabelling a chart.

use super::{CodeMetricDef, CodeMetricUnit};

/// Build one entry. A free function rather than a literal per row because six fields
/// times ninety-odd rows is unreadable written out, and the positional form reads as a
/// table.
const fn metric(
    path: &'static str,
    label: &'static str,
    unit: CodeMetricUnit,
    family: &'static str,
    higher_is_better: Option<bool>,
    approximate: bool,
) -> CodeMetricDef {
    CodeMetricDef {
        path,
        label,
        unit,
        family,
        higher_is_better,
        approximate,
    }
}

use CodeMetricUnit::{Boolean, Bytes, Count, Lines, PerKiloLine, Ratio, Score};

/// Descriptive, with no good direction — the honest answer for most counts.
const NEUTRAL: Option<bool> = None;
/// More is better.
const MORE: Option<bool> = Some(true);
/// Less is better.
const LESS: Option<bool> = Some(false);

/// Display metadata for every leaf of the code-analysis summary.
///
/// Ordered by family, then roughly by how much a reader wants the figure, so a sidebar
/// that renders the table in order is already in a sensible shape.
pub static CODE_METRICS: &[CodeMetricDef] = &[
    // ---- provenance -------------------------------------------------------------
    metric(
        "analyzerVersion",
        "Analyzer version",
        Count,
        "provenance",
        NEUTRAL,
        false,
    ),
    // ---- size and shape ---------------------------------------------------------
    metric("size.files", "Files", Count, "size", NEUTRAL, false),
    metric(
        "size.parsedFiles",
        "Parsed files",
        Count,
        "size",
        NEUTRAL,
        false,
    ),
    metric(
        "size.sizeOnlyFiles",
        "Size-only files",
        Count,
        "size",
        LESS,
        false,
    ),
    metric("size.bytes", "Bytes", Bytes, "size", NEUTRAL, false),
    metric(
        "size.codeLines",
        "Code lines",
        Lines,
        "size",
        NEUTRAL,
        false,
    ),
    metric(
        "size.commentLines",
        "Comment lines",
        Lines,
        "size",
        NEUTRAL,
        false,
    ),
    metric(
        "size.blankLines",
        "Blank lines",
        Lines,
        "size",
        NEUTRAL,
        false,
    ),
    metric(
        "size.directories",
        "Directories",
        Count,
        "size",
        NEUTRAL,
        false,
    ),
    metric(
        "size.maxDirectoryDepth",
        "Max directory depth",
        Count,
        "size",
        NEUTRAL,
        false,
    ),
    metric(
        "size.meanFilesPerDirectory",
        "Files per directory",
        Count,
        "size",
        NEUTRAL,
        false,
    ),
    metric(
        "size.giniCodeLines",
        "Size Gini",
        Ratio,
        "size",
        LESS,
        false,
    ),
    metric("size.rootShare", "Root share", Ratio, "size", LESS, false),
    metric(
        "size.maxFileCodeLines",
        "Largest file",
        Lines,
        "size",
        LESS,
        false,
    ),
    metric(
        "size.medianFileCodeLines",
        "Median file",
        Lines,
        "size",
        NEUTRAL,
        false,
    ),
    metric(
        "size.p90FileCodeLines",
        "P90 file",
        Lines,
        "size",
        NEUTRAL,
        false,
    ),
    metric(
        "size.filesOver500Lines",
        "Files over 500 lines",
        Count,
        "size",
        LESS,
        false,
    ),
    metric(
        "size.filesOver1000Lines",
        "Files over 1000 lines",
        Count,
        "size",
        LESS,
        false,
    ),
    // ---- complexity -------------------------------------------------------------
    metric(
        "complexity.functions",
        "Functions",
        Count,
        "complexity",
        NEUTRAL,
        false,
    ),
    metric(
        "complexity.totalCyclomatic",
        "Total cyclomatic",
        Score,
        "complexity",
        NEUTRAL,
        false,
    ),
    metric(
        "complexity.maxCyclomatic",
        "Max cyclomatic",
        Score,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.meanCyclomatic",
        "Mean cyclomatic",
        Score,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.totalCognitive",
        "Total cognitive",
        Score,
        "complexity",
        NEUTRAL,
        false,
    ),
    metric(
        "complexity.maxCognitive",
        "Max cognitive",
        Score,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.meanCognitive",
        "Mean cognitive",
        Score,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.maxNesting",
        "Max nesting",
        Count,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.meanMaxNesting",
        "Mean max nesting",
        Count,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.maxParameters",
        "Max parameters",
        Count,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.meanParameters",
        "Mean parameters",
        Count,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.maxExits",
        "Max exits",
        Count,
        "complexity",
        NEUTRAL,
        false,
    ),
    metric(
        "complexity.meanExits",
        "Mean exits",
        Count,
        "complexity",
        NEUTRAL,
        false,
    ),
    metric(
        "complexity.functionsOver10Cyclomatic",
        "Functions over 10",
        Count,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.functionsOver20Cyclomatic",
        "Functions over 20",
        Count,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.maxFunctionLines",
        "Longest function",
        Lines,
        "complexity",
        LESS,
        false,
    ),
    metric(
        "complexity.meanFunctionLines",
        "Mean function length",
        Lines,
        "complexity",
        NEUTRAL,
        false,
    ),
    // ---- module graph -----------------------------------------------------------
    metric("graph.nodes", "Modules", Count, "graph", NEUTRAL, false),
    metric("graph.edges", "Imports", Count, "graph", NEUTRAL, false),
    metric("graph.cycles", "Import cycles", Count, "graph", LESS, false),
    metric(
        "graph.largestCycle",
        "Largest cycle",
        Count,
        "graph",
        LESS,
        false,
    ),
    metric(
        "graph.filesInCycles",
        "Files in cycles",
        Count,
        "graph",
        LESS,
        false,
    ),
    metric(
        "graph.meanInstability",
        "Instability",
        Ratio,
        "graph",
        NEUTRAL,
        false,
    ),
    metric(
        "graph.meanFanOut",
        "Mean fan-out",
        Count,
        "graph",
        LESS,
        false,
    ),
    metric(
        "graph.maxFanOut",
        "Max fan-out",
        Count,
        "graph",
        LESS,
        false,
    ),
    metric(
        "graph.meanFanIn",
        "Mean fan-in",
        Count,
        "graph",
        NEUTRAL,
        false,
    ),
    metric(
        "graph.maxFanIn",
        "Max fan-in",
        Count,
        "graph",
        NEUTRAL,
        false,
    ),
    // Orphans and depth are downstream of entry-point discovery, which rests on the
    // same hand-rolled resolution as reference counting: an entry point named only in a
    // bundler config is invisible, and its whole subtree reads as dead.
    metric(
        "graph.orphans",
        "Orphan modules",
        Count,
        "graph",
        LESS,
        true,
    ),
    metric(
        "graph.maxDepth",
        "Dependency depth",
        Count,
        "graph",
        NEUTRAL,
        true,
    ),
    metric(
        "graph.externalPackages",
        "External packages",
        Count,
        "graph",
        NEUTRAL,
        false,
    ),
    metric(
        "graph.entryPoints",
        "Entry points",
        Count,
        "graph",
        NEUTRAL,
        true,
    ),
    // ---- API surface ------------------------------------------------------------
    metric("api.exports", "Exports", Count, "api", NEUTRAL, false),
    metric(
        "api.meanExportsPerModule",
        "Exports per module",
        Count,
        "api",
        NEUTRAL,
        false,
    ),
    // The two figures the `approximate` flag exists for. Cross-file attribution is
    // hand-rolled in both languages and is blind to dynamic imports, computed member
    // access, and references that exist only in a bundler config.
    metric(
        "api.unreferencedExports",
        "Unreferenced exports",
        Count,
        "api",
        LESS,
        true,
    ),
    metric(
        "api.unreferencedExportRatio",
        "Unreferenced export share",
        Ratio,
        "api",
        LESS,
        true,
    ),
    // ---- TypeScript -------------------------------------------------------------
    metric(
        "typescript.files",
        "TypeScript files",
        Count,
        "typescript",
        NEUTRAL,
        false,
    ),
    metric(
        "typescript.codeLines",
        "TypeScript code lines",
        Lines,
        "typescript",
        NEUTRAL,
        false,
    ),
    metric(
        "typescript.anyOccurrences",
        "`any` annotations",
        Count,
        "typescript",
        LESS,
        false,
    ),
    metric(
        "typescript.anyDensity",
        "`any` density",
        PerKiloLine,
        "typescript",
        LESS,
        false,
    ),
    metric(
        "typescript.unknownOccurrences",
        "`unknown` annotations",
        Count,
        "typescript",
        MORE,
        false,
    ),
    metric(
        "typescript.suppressionComments",
        "Suppression comments",
        Count,
        "typescript",
        LESS,
        false,
    ),
    metric(
        "typescript.nonNullAssertions",
        "Non-null assertions",
        Count,
        "typescript",
        LESS,
        false,
    ),
    metric(
        "typescript.assertionCasts",
        "Assertion casts",
        Count,
        "typescript",
        LESS,
        false,
    ),
    metric(
        "typescript.annotatedParameterRatio",
        "Annotated parameters",
        Ratio,
        "typescript",
        MORE,
        false,
    ),
    metric(
        "typescript.annotatedReturnRatio",
        "Annotated returns",
        Ratio,
        "typescript",
        MORE,
        false,
    ),
    metric(
        "typescript.exportedAnnotatedRatio",
        "Annotated exported API",
        Ratio,
        "typescript",
        MORE,
        false,
    ),
    metric(
        "typescript.typeDeclarations",
        "Type declarations",
        Count,
        "typescript",
        MORE,
        false,
    ),
    metric(
        "typescript.typeDeclarationsPerKloc",
        "Type declaration density",
        PerKiloLine,
        "typescript",
        MORE,
        false,
    ),
    // ---- Rust -------------------------------------------------------------------
    metric("rust.files", "Rust files", Count, "rust", NEUTRAL, false),
    metric(
        "rust.codeLines",
        "Rust code lines",
        Lines,
        "rust",
        NEUTRAL,
        false,
    ),
    metric(
        "rust.unsafeItems",
        "`unsafe` items",
        Count,
        "rust",
        LESS,
        false,
    ),
    metric(
        "rust.unwrapCalls",
        "`unwrap` calls",
        Count,
        "rust",
        LESS,
        false,
    ),
    metric(
        "rust.expectCalls",
        "`expect` calls",
        Count,
        "rust",
        LESS,
        false,
    ),
    metric(
        "rust.unwrapDensity",
        "`unwrap`/`expect` density",
        PerKiloLine,
        "rust",
        LESS,
        false,
    ),
    metric("rust.panicSites", "Panic sites", Count, "rust", LESS, false),
    metric(
        "rust.todoMacros",
        "`todo!` macros",
        Count,
        "rust",
        LESS,
        false,
    ),
    metric(
        "rust.suppressedLints",
        "Suppressed lints",
        Count,
        "rust",
        LESS,
        false,
    ),
    metric(
        "rust.cloneCalls",
        "`clone` calls",
        Count,
        "rust",
        LESS,
        false,
    ),
    metric(
        "rust.cloneDensity",
        "`clone` density",
        PerKiloLine,
        "rust",
        LESS,
        false,
    ),
    metric(
        "rust.publicItems",
        "Public items",
        Count,
        "rust",
        NEUTRAL,
        false,
    ),
    metric(
        "rust.publicRatio",
        "Public share",
        Ratio,
        "rust",
        LESS,
        false,
    ),
    metric("rust.traits", "Traits", Count, "rust", NEUTRAL, false),
    metric(
        "rust.genericItems",
        "Generic items",
        Count,
        "rust",
        NEUTRAL,
        false,
    ),
    // ---- tests ------------------------------------------------------------------
    // Static counts of test code the model chose to write. Never coverage.
    metric("tests.testFiles", "Test files", Count, "tests", MORE, false),
    metric(
        "tests.testFunctions",
        "Test functions",
        Count,
        "tests",
        MORE,
        false,
    ),
    metric(
        "tests.testCodeLines",
        "Test code lines",
        Lines,
        "tests",
        MORE,
        false,
    ),
    metric(
        "tests.testLineRatio",
        "Test line share",
        Ratio,
        "tests",
        MORE,
        false,
    ),
    // ---- duplication ------------------------------------------------------------
    metric(
        "duplication.clonedLines",
        "Cloned lines",
        Lines,
        "duplication",
        LESS,
        false,
    ),
    metric(
        "duplication.clonedLineRatio",
        "Cloned line share",
        Ratio,
        "duplication",
        LESS,
        false,
    ),
    metric(
        "duplication.cloneGroups",
        "Clone groups",
        Count,
        "duplication",
        LESS,
        false,
    ),
    metric(
        "duplication.largestCloneLines",
        "Largest clone",
        Lines,
        "duplication",
        LESS,
        false,
    ),
    // ---- notes ------------------------------------------------------------------
    metric(
        "notes.truncated",
        "Truncated",
        Boolean,
        "notes",
        LESS,
        false,
    ),
    metric(
        "notes.gitignoreApplied",
        "Ignore files applied",
        Boolean,
        "notes",
        NEUTRAL,
        false,
    ),
    metric(
        "notes.filesSkipped",
        "Files skipped",
        Count,
        "notes",
        NEUTRAL,
        false,
    ),
    metric(
        "notes.bytesSkipped",
        "Bytes skipped",
        Bytes,
        "notes",
        NEUTRAL,
        false,
    ),
    metric(
        "notes.filesUnparsable",
        "Unparsable files",
        Count,
        "notes",
        LESS,
        false,
    ),
];
