#!/usr/bin/env bash
#
# Reflect the Ruby guest's signature catalogue out of its SDK, and write
# `$GG_SIGNATURES_OUT_DIR/ruby.signatures.json`.
#
# It is the whole of what a model is *told* about this arm's surface — every signature, every
# argument description, every type and every one of a type's members — and it is reflected out of
# the YARD documentation written on `packages/gg-sandbox-ruby/src/gg/`, plus the library set
# `src/library.rb` declares. Nothing about the SDK is authored anywhere else, which is what stops a
# description from drifting from the thing it describes.
#
# WHERE IT WRITES, AND WHY THERE IS NO DEFAULT. The catalogue is a BUILD ARTIFACT.
# `crates/gg/build.rs` runs `scripts/gg-signatures.sh` and embeds what lands in the build's own
# `OUT_DIR`, so the documentation is reflected on the same build that compiles the host rendering it
# — it cannot be stale, because no copy of it outlives a build. A default here would be a second
# answer to a question the build already answers, and the old one,
# `crates/gg/src/sandbox/guests/`, is the answer that stopped being right. Run it by hand, into a
# directory of your choosing, to READ a catalogue: an emitted catalogue is where a reflector bug
# shows itself, and a person has to be able to open one. `scripts/gg-signatures.sh` is the easy way.
#
# Split from `build.sh` for the reason the Python guest's `signatures.sh` is split from its own
# build: this needs only Ruby and YARD, which is little enough that every machine that builds gg can
# have them, where baking the component needs `componentize-js` and emits 20 MB.
#
# YARD is pinned and installed with `gem install --user-install`, which needs no root and no
# `bundle`: every machine that builds gg — a devcontainer, an Azure agent, a GitHub runner, an image
# build — ships a Ruby, and what has to be the same across them is the reflector, not the
# interpreter. `scripts/ci/install-gg-toolchains.sh` is what puts it there ahead of time, so a build
# does not discover it needs a gem halfway through.
#
# Usage:
#   GG_SIGNATURES_OUT_DIR=<dir> packages/gg-sandbox-ruby/signatures.sh
#   scripts/gg-signatures.sh                 # all eleven arms, into one directory
set -euo pipefail

# Repo root, independent of the caller's working directory.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

# The YARD release the catalogue is reflected with, and the same one
# `scripts/ci/install-gg-toolchains.sh` puts on the machine ahead of a build. One file, sourced
# twice, because a pre-installed YARD and a reflecting YARD that were two literals in two scripts
# would be one edit away from disagreeing silently.
# shellcheck source=packages/gg-sandbox-ruby/yard-version.sh
source "$ROOT/packages/gg-sandbox-ruby/yard-version.sh"

if [ -z "${GG_SIGNATURES_OUT_DIR:-}" ]; then
	echo "error: GG_SIGNATURES_OUT_DIR is not set. It names the directory this catalogue is" >&2
	echo "       written into, and there is no default — the catalogue is generated by the build" >&2
	echo "       rather than committed anywhere." >&2
	echo "       Run scripts/gg-signatures.sh (which sets it and regenerates every arm), or set" >&2
	echo "       it yourself to a directory you want the JSON in." >&2
	exit 1
fi
mkdir -p "$GG_SIGNATURES_OUT_DIR"
# Made absolute before the reflector reads it: this script has already changed directory, and the
# other ten arms hand the path to tools they run from elsewhere again. One relative path meaning two
# directories depending on the arm is the kind of difference nobody finds until a file is missing.
GG_SIGNATURES_OUT_DIR="$(cd "$GG_SIGNATURES_OUT_DIR" && pwd)"
export GG_SIGNATURES_OUT_DIR

if ! command -v ruby >/dev/null 2>&1; then
	echo "error: this needs a Ruby on PATH to run YARD with." >&2
	echo "       scripts/ci/install-gg-toolchains.sh checks for one and says how to get it;" >&2
	echo "       on a Debian-derived machine that is \`sudo apt-get install -y ruby\`." >&2
	exit 1
fi

if ! ruby -e 'gem "yard", ARGV[0]' "$YARD_VERSION" >/dev/null 2>&1; then
	echo "Installing yard $YARD_VERSION ..."
	gem install --user-install --no-document yard -v "$YARD_VERSION" >/dev/null
fi

GG_YARD_VERSION="$YARD_VERSION" ruby packages/gg-sandbox-ruby/tools/signatures.rb
