#!/usr/bin/env bash
#
# Reflect the PureScript arm's signature catalogue out of its SDK, and write
# `$GG_SIGNATURES_OUT_DIR/purescript.signatures.json`.
#
# gg embeds that file and renders the responses-as-code system prompt and every documentation view
# from it, so it is the whole of what a model is told about this arm's surface. Every word of it is
# reflected out of the SDK's own declarations by `tools/signatures.mjs`, which reads the `docs.json`
# `purs` itself emits — so a sentence a model reads is the compiler's own reading of the declaration
# it describes rather than prose typed into a table beside it.
#
# WHERE IT WRITES, AND WHY THERE IS NO DEFAULT. The catalogue is a BUILD ARTIFACT.
# `crates/gg/build.rs` runs `scripts/gg-signatures.sh` and embeds what lands in the build's own
# `OUT_DIR`, so a doc comment edited without a regeneration is not a state this checkout can be in:
# the next build of gg reflects it. A default here would be a second answer to a question the build
# already answers, and the old one — `crates/gg/src/sandbox/guests/` — is the answer that stopped
# being right. Run this by hand, into a directory of your choosing, to READ a catalogue; that is
# what `scripts/gg-signatures.sh` is for, and it is how a reflector bug gets found.
#
# WHAT IT COMPILES AGAINST. The committed library tree (`purescript.libraries.tar.gz`), unpacked into
# a scratch directory with this package's *working* `src/` staged over the copy inside it. That is
# what makes this a reflection of the sources on disk rather than a re-read of whatever was baked:
# the catalogue describes the SDK in the working tree, against the libraries the arm really ships,
# without needing Spago or the registry.
#
# It needs `purs` — `scripts/ci/install-gg-toolchains.sh` puts the pinned release on PATH, and the gg
# run image carries it at /opt/gg/toolchains/bin — and Node. It does NOT need `esbuild`, Spago, or
# network access.
#
# Usage:
#   GG_SIGNATURES_OUT_DIR=<dir> packages/gg-sandbox-purescript/signatures.sh
#   scripts/gg-signatures.sh                 # all eleven arms, into one directory
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

if [ -z "${GG_SIGNATURES_OUT_DIR:-}" ]; then
	echo "error: GG_SIGNATURES_OUT_DIR is not set. It names the directory this catalogue is" >&2
	echo "       written into, and there is no default — the catalogue is generated by the build" >&2
	echo "       rather than committed anywhere." >&2
	echo "       Run scripts/gg-signatures.sh (which sets it and regenerates every arm), or set" >&2
	echo "       it yourself to a directory you want the JSON in." >&2
	exit 1
fi
mkdir -p "$GG_SIGNATURES_OUT_DIR"
# Made absolute before the reflector reads it. This script has already changed directory, and the
# reflector below is handed scratch paths under a `mktemp -d` — a relative destination resolved
# against the wrong one of those is a catalogue written into a directory that is deleted on exit.
GG_SIGNATURES_OUT_DIR="$(cd "$GG_SIGNATURES_OUT_DIR" && pwd)"
export GG_SIGNATURES_OUT_DIR

PACKAGE="packages/gg-sandbox-purescript"
TARBALL="crates/gg/src/sandbox/checkers/purescript.libraries.tar.gz"

# The same lookup order the host uses at run time: what an operator named, then what the gg run image
# installs, then whatever PATH finds.
PURS="${TCAB_GG_PURS:-}"
if [ -z "$PURS" ]; then
	if [ -x /opt/gg/toolchains/bin/purs ]; then
		PURS=/opt/gg/toolchains/bin/purs
	else
		PURS=purs
	fi
fi
if ! command -v "$PURS" > /dev/null 2>&1; then
	echo "error: this needs the pinned \`purs\` on PATH; run scripts/ci/install-gg-toolchains.sh." >&2
	exit 1
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "Unpacking the committed library tree ..."
tar -xzf "$TARBALL" -C "$WORK"

# The SDK inside the committed tarball is whatever was there when it was last built. What this
# catalogue must describe is what is in the working tree, so it is staged over the top — exactly as
# build.sh stages it before compiling the tree in the first place.
rm -rf "$WORK/libs/gg-sdk/src"
mkdir -p "$WORK/libs/gg-sdk"
cp -a "$PACKAGE/src" "$WORK/libs/gg-sdk/src"

# A fresh output directory rather than the tree's own: `purs` emits a module's `docs.json` only when
# it compiles that module, and against the tarball's up-to-date cache it would compile nothing and
# emit nothing. ~20 s, and it is the only slow step here.
echo "Compiling the SDK for its documentation ..."
(cd "$WORK" && "$PURS" compile --codegen docs --output docs 'libs/*/src/**/*.purs' > /dev/null)

echo "Reflecting the catalogue ..."
node "$PACKAGE/tools/signatures.mjs" "$WORK/docs" "$WORK"
