//! The data contract's generator, as a library: the TypeScript modules and JSON
//! Schema documents whose types all belong to `test-cabinet-contracts`, and the
//! emission machinery ([`emit`]) that turns them into files.
//!
//! Two binaries drive it. `contract-codegen` (this crate's own) writes what is
//! listed here: the asset contract (`packages/asset-contract/src/`), the run-record
//! contract (`packages/run-record/src/`) and their JSON Schemas under
//! `apps/docs/public/schema/`. It compiles `test-cabinet-contracts` alone.
//! `api-codegen` (`crates/api-codegen`) writes the backend's API package
//! (`packages/backend-api/src/`) and its schemas, and compiles the core and the
//! backend to reach their types; it passes [`contract_modules`] and
//! [`contract_schema_docs`] to [`emit::finalize_ts`] and [`emit::finalize_schemas`]
//! as *external* homes, so a backend type that refers to a contract type imports it
//! from the run-record package and `$ref`s it at the contract document's URL, exactly
//! as one generator over both sets did.
//!
//! Nothing listed here may name a backend-owned type: the run-record package is
//! below the backend API package, never beside it.

pub mod emit;

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use ts_rs::Config;

use emit::{SchemaDoc, TsModule, root_schema};

use test_cabinet_contracts::{
    code_analysis as code, event as ev, gg, gg_query as ggq, gg_reference as ggref,
    gg_session_record as ggr, metrics as m, review as rv, run_record as rr, test_case as tc,
    test_suite as suite, toolchain as tch, validation as val,
};

/// Collect the [`emit::TsDecl`]s for the listed types, in declaration order.
#[macro_export]
macro_rules! ts_decls {
    ($cfg:expr; $($t:ty),+ $(,)?) => {
        vec![ $( $crate::emit::ts_decl::<$t>($cfg) ),+ ]
    };
}

/// The header stamped on every TypeScript module this generator writes.
///
/// Its wording still names the core and the backend, where the contract types lived
/// before `test-cabinet-contracts` took them; it is kept byte for byte so the
/// generated packages do not change with the move.
pub const TS_HEADER: &str = "\
// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` and `crates/backend`, which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.\n\n";

/// The run-record schema's `$defs`: every type in the `RunRecord` tree except the
/// root. Names are the published (TS-facing) names, so renamed Rust types appear
/// here under their contract name (`TokenMetrics`, `RunValidation`, `AssetSheet`).
pub const RUN_RECORD_DEFS: &[&str] = &[
    "RunSubject",
    "RunTooling",
    "RunEnvironment",
    "RunMetrics",
    "TokenMetrics",
    "CostMetrics",
    "RunValidation",
    "RunLinks",
    "RunStatus",
    "PriorGameJamEntry",
    "HarnessSlug",
    "RunState",
    "AuthMode",
    "TestType",
    "MediaKind",
    "StepResult",
    "CheckResult",
    "ProofResult",
    "DebugScriptResult",
    "Inconclusive",
    "AutoVerdict",
    "Assertion",
    "DebugScriptOutput",
    "RequirementOutcome",
    "RequirementStatus",
    "RequirementAssertion",
    "AssetGenResult",
    "AssetFrameResult",
    "AssetSheet",
    "AssetSheetSequence",
    "VoxelGenResult",
    "VoxelPartResult",
    "NineSlice",
    "UiGenResult",
    "UiElementResult",
    "MaterialGenResult",
    "MaterialMapResult",
    "ParticleGenResult",
    "AudioGenResult",
    "ModelSpec",
    "PartSpec",
    "JointSpec",
    "JointKindSpec",
    "AxisSpec",
    "DriveKindSpec",
    "InterpSpec",
    "KeyframeSpec",
    "AnimationSpec",
    "AnimationTrackSpec",
    "AdversarialResult",
    "AdversarialReplay",
    "AdversarialTeam",
    "AdversarialOutcome",
    "PerformanceResult",
    "PerformanceCaseResult",
    "PerformanceCaseKind",
    "PerformanceSnapshotCheck",
    "ToolchainSummary",
    "ToolchainCommandResult",
    "ToolchainTestRun",
    "ToolchainTests",
    "ToolchainTest",
    "ToolchainTestStatus",
    "ToolchainTestFile",
    "ToolchainTestFailure",
    "ToolchainCoverage",
    "CoverageFile",
    "CoverageMetrics",
    "CoverageMetric",
    "ToolchainSmokeResult",
];

/// The code-analysis schema's `$defs`: every type in the `CodeAnalysisDocument` tree
/// except the root. `CodeAnalysisSummary` is listed here rather than with the run record's
/// defs even though the record carries it — the document embeds the same block, and one
/// owner per type is what turns the record's reference into a cross-document `$ref`
/// instead of a second copy that can drift.
pub const CODE_ANALYSIS_DEFS: &[&str] = &[
    "CodeAnalysisSummary",
    "CodeAuthoredBasis",
    "CodeTreeBasis",
    "CodeLanguage",
    "CodeTruncationCap",
    "CodeSizeSummary",
    "CodeComplexitySummary",
    "CodeGraphSummary",
    "CodeApiSummary",
    "CodeTypeScriptSummary",
    "CodeRustSummary",
    "CodeTestSummary",
    "CodeDuplicationSummary",
    "CodeAnalysisNotes",
    "CodeFileEntry",
    "CodeSymbolEntry",
    "CodeImportEdge",
    "CodeCloneGroup",
    "CodeCloneInstance",
];

/// The test suite schema's `$defs`: every type of the suite model except the
/// version folder itself, which is the root.
pub const TEST_SUITE_DEFS: &[&str] = &[
    "SuiteManifest",
    "VersionManifest",
    "SpecificationFolder",
    "SpecificationManifest",
    "SuiteRequirement",
    "SuiteRequirementKind",
    "SuiteDebugApi",
    "DebugApiModule",
    "DebugApiModuleRef",
    "DebugApiFunction",
    "DebugApiFunctionKind",
    "DebugApiParameter",
    "SuiteTestCaseFile",
    "SuiteTestCaseDefinition",
    "SuiteTestCaseType",
    "SuiteDifficulty",
    "SpriteCase",
    "VoxelCase",
    "AssetCase",
    "BuildCommands",
    "ToolchainCommands",
    "AssetFolder",
    "AssetManifest",
    "SuiteAssetKind",
    "DemoFolder",
    "DemoManifest",
    "SuiteShowcase",
    "ShowcaseManifest",
    "ShowcaseMediaEntry",
    "SuiteTrees",
];

/// The package holding the evaluation contract: run records, reviews, events, gg's
/// configuration, telemetry and session record, the query language, the code analysis
/// and the test suite format. Consumed by the console, the gallery and the backend API
/// package, which are ours; **never** vendored into a run, because those shapes would
/// tell a model that its output is scored, ranked and reviewed.
pub const RUN_RECORD_PKG: &str = "@clockwyrks/run-record";

/// The package holding the asset shapes a produced rig is described by — the
/// `rig.json` a run *writes* and the runtimes then pose and render.
///
/// Split out of [`RUN_RECORD_PKG`] because its audience is different in kind: the
/// voxel and particle runtimes are vendored into a model's own workspace, so
/// whatever they depend on travels with them. These types describe the artifact
/// the model is building and say nothing about evaluation, so they are safe to
/// seed; the rest of the contract is not, and no longer rides along.
pub const ASSET_CONTRACT_PKG: &str = "@clockwyrks/asset-contract";

/// The asset shapes [`ASSET_CONTRACT_PKG`] owns. `index.ts` still uses them (a
/// voxel result carries the rig it resolved), and the console imports them from
/// the aggregate package, so the run-record module both imports and re-exports
/// them — named once here so the two lists cannot drift apart.
pub const ASSET_SPEC_TYPES: &[&str] = &[
    "ModelSpec",
    "PartSpec",
    "JointSpec",
    "JointKindSpec",
    "AxisSpec",
    "DriveKindSpec",
    "InterpSpec",
    "KeyframeSpec",
    "AnimationSpec",
    "AnimationTrackSpec",
];

/// The generated module that carries the `code.*` display catalog.
///
/// Named once because it is referenced twice — as the module's file name and as the
/// target of the appended [`CODE_METRICS`](test_cabinet_contracts::CODE_METRICS) table — and a
/// mismatch between the two would silently emit the types without the data.
pub const CODE_METRICS_MODULE: &str = "code-metrics.ts";

/// The generated module that carries the gg contract, and with it the **error-label tables**.
///
/// Named once for the reason [`CODE_METRICS_MODULE`] is: it is both the module's file name and the
/// target of the appended tables, and a mismatch would silently emit the types without the labels a
/// console needs to render them.
pub const GG_MODULE: &str = "gg.ts";

/// The data appended to a contract module after its declarations, if it carries any.
///
/// `ts_rs` renders types, not data, so the two tables that ship as values — the
/// `code.*` catalog and the gg error labels — are serialized here and appended to the
/// module that declares their element types. Both are matched on the package as well
/// as the file name, because `index.ts` is a file name more than one package has, and
/// a rename could otherwise silently append a console's lookup table to the package
/// that gets vendored into runs.
pub fn contract_appendix(package: &str, file: &str) -> Result<String> {
    let run_record = package == RUN_RECORD_PKG;
    // The one module that carries a value as well as its types, which is why the file
    // name is a constant rather than a literal in two places.
    if run_record && file == CODE_METRICS_MODULE {
        return code_metrics_catalog();
    }
    // The gg module carries the error taxonomy's labels for the same reason: a label is
    // data, and a hand-kept copy of it in the console is exactly the drift the tables
    // exist to prevent.
    if run_record && file == GG_MODULE {
        return gg_error_labels();
    }
    Ok(String::new())
}

/// Render the `code.*` display catalog as a TypeScript value.
///
/// The table is Rust's, verbatim: it is serialized with the same `serde` derive the
/// contract types use, so the emitted rows carry exactly the paths, labels, units,
/// families, polarities and `approximate` flags the analyzer and the CLI read. Prettier
/// (in the generator wrapper) reformats the JSON into idiomatic TypeScript, so the shape
/// written here only has to be valid.
fn code_metrics_catalog() -> Result<String> {
    /// The JSDoc stamped above the emitted table. A constant rather than part of the
    /// format string because the prose contains `{@link …}`, which a Rust format string
    /// would read as an interpolation.
    const DOC: &str = "/**\n\
         * Display metadata for every leaf of the code-analysis summary, in the order a\n\
         * reader wants the figures: by family, and within a family by how much the figure\n\
         * says.\n\
         *\n\
         * This is **not** a query vocabulary — the query language derives its field catalog\n\
         * from the documents it has indexed, so a metric is queryable with or without an\n\
         * entry here. What an entry buys is what a number cannot carry on its own: a label,\n\
         * a unit, a polarity, and the {@link CodeMetricDef.approximate} flag that the Code\n\
         * tab's headers, the field sidebar and the docs page all read, so the four cannot\n\
         * drift apart.\n\
         */\n";
    let rows = serde_json::to_string(&test_cabinet_contracts::CODE_METRICS)
        .context("serializing the code-metric catalog")?;
    Ok(format!(
        "{DOC}export const CODE_METRICS: readonly CodeMetricDef[] = {rows};\n"
    ))
}

/// The error-taxonomy label tables, appended to the gg module.
///
/// Every specific error type, every base kind and every call-failure class has a stable id **and** a
/// human-readable label, and both live in Rust beside the variant they name. Emitting them here is
/// what keeps a console from carrying a second hand-written table: a type added to the taxonomy
/// arrives with its label, its base and its ordering already in the contract, so the row it should
/// occupy in a *"top error types"* ranking cannot be missing, mislabelled, or filed under the wrong
/// base.
///
/// The maps are keyed by the *wire id* rather than by the enum, so they can be indexed with whatever
/// a record actually carried — including, for the ranking's fallback path, a key from a newer gg
/// than the console was built against. They are declared `Record<GgTurnErrorType, string>` all the
/// same, which makes an omission a TypeScript error at generation time rather than a blank row at
/// run time.
fn gg_error_labels() -> Result<String> {
    /// The JSDoc above each table, kept out of the format strings because the prose contains
    /// `{@link …}`, which a Rust format string would read as an interpolation.
    const KIND_DOC: &str = "/**\n\
         * How each **base** error kind reads on screen — the coarse bucket, which is what the\n\
         * error ceilings act on and what a cross-run comparison groups by.\n\
         *\n\
         * Generated from the Rust taxonomy, so it is total by construction and cannot drift from\n\
         * the values a record carries.\n\
         */\n";
    const TYPE_DOC: &str = "/**\n\
         * How each **specific** error type reads on screen — one row per type in a ranking, so\n\
         * every label stands alone and names the layer it came from without a heading.\n\
         */\n";
    const BASE_DOC: &str = "/**\n\
         * Each specific type's base kind, so a ranked row can be badged with the bucket it belongs\n\
         * to, and a per-type breakdown can be regrouped into the per-kind counters beside it.\n\
         */\n";
    const ORDER_DOC: &str = "/**\n\
         * Every specific type, grouped by base in the contract's own declaration order — the\n\
         * reading order for a full split, as opposed to the frequency order a *top N* ranking\n\
         * sorts into.\n\
         */\n";
    const FAILURE_DOC: &str = "/**\n\
         * How each call-failure class reads on screen — the class a failed tool call or a failed\n\
         * model-facing API call is recorded with.\n\
         */\n";

    let map = |rows: Vec<(&str, String)>| -> String {
        let body: String = rows
            .into_iter()
            .map(|(key, value)| {
                format!(
                    "  {}: {},\n",
                    serde_json::to_string(key).unwrap_or_default(),
                    value
                )
            })
            .collect();
        format!("{{\n{body}}}")
    };
    let quoted = |value: &str| serde_json::to_string(value).unwrap_or_default();

    let kinds = map(gg::GgTurnErrorKind::ALL
        .iter()
        .map(|kind| (kind.wire_id(), quoted(kind.label())))
        .collect());
    let types = map(gg::GgTurnErrorType::ALL
        .iter()
        .map(|error| (error.wire_id(), quoted(error.label())))
        .collect());
    let bases = map(gg::GgTurnErrorType::ALL
        .iter()
        .map(|error| (error.wire_id(), quoted(error.kind().wire_id())))
        .collect());
    let failures = map(gg::GgCallFailure::ALL
        .iter()
        .map(|failure| (failure.wire_id(), quoted(failure.label())))
        .collect());
    let order = serde_json::to_string(
        &gg::GgTurnErrorType::ALL
            .iter()
            .map(|error| error.wire_id())
            .collect::<Vec<_>>(),
    )
    .context("serializing the error-type order")?;

    Ok(format!(
        "\n{KIND_DOC}export const GG_TURN_ERROR_KIND_LABELS: Readonly<Record<GgTurnErrorKind, string>> = {kinds};\n\n\
         {TYPE_DOC}export const GG_TURN_ERROR_TYPE_LABELS: Readonly<Record<GgTurnErrorType, string>> = {types};\n\n\
         {BASE_DOC}export const GG_TURN_ERROR_TYPE_BASE: Readonly<Record<GgTurnErrorType, GgTurnErrorKind>> = {bases};\n\n\
         {ORDER_DOC}export const GG_TURN_ERROR_TYPES: readonly GgTurnErrorType[] = {order};\n\n\
         {FAILURE_DOC}export const GG_TOOL_FAILURE_LABELS: Readonly<Record<GgCallFailure, string>> = {failures};\n"
    ))
}

/// The TypeScript modules whose declarations are all contract types: the asset
/// contract and the run-record package. A module the backend owns, or a declaration
/// in one, is `api-codegen`'s.
pub fn contract_modules(cfg: &Config) -> Vec<TsModule> {
    vec![
        // The asset contract: the resolved rig a produced model is described by and
        // the F-curve animations that drive it. Its own package because it is the
        // only slice of the contract that may be seeded — see [`ASSET_CONTRACT_PKG`].
        // Ordered structure-first: the rig, then the joints, then the animation.
        TsModule {
            package: ASSET_CONTRACT_PKG,
            reexports: &[],
            file: "index.ts",
            decls: ts_decls![cfg;
                tc::ModelSpec, tc::PartSpec,
                tc::JointSpec, tc::JointKindSpec, tc::AxisSpec, tc::DriveKindSpec,
                tc::InterpSpec, tc::KeyframeSpec, tc::AnimationSpec, tc::AnimationTrackSpec,
            ],
        },
        // The run-record contract. Ordered to mirror the run-record document:
        // identity, metrics, validation results, the record. The persisted tournament
        // document is the arena's, so its types are `api-codegen`'s (`tournament.ts`
        // in the backend API package).
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: ASSET_SPEC_TYPES,
            file: "index.ts",
            decls: ts_decls![cfg;
                rr::HarnessSlug, rr::HarnessFamily, rr::RunState, rr::AuthMode, rr::RunEnvironment, rr::RunTooling,
                tc::TestType, tc::AssetKind, tc::AssetDimension, rr::RunSubject, m::TokenCounts, m::TokenPrices, m::Cost, m::RunMetrics,
                tc::MediaKind, val::ProofResult, val::CheckResult, val::StepResult,
                val::DebugScriptResult, val::Inconclusive, val::AutoVerdict, val::Assertion, val::DebugScriptOutput,
                val::AssetGenResult, val::AssetFrameResult, tc::SheetSpec, tc::SheetSequence,
                val::VoxelGenResult, val::VoxelPartResult,
                tc::NineSlice, val::UiGenResult, val::UiElementResult, val::MaterialGenResult,
                val::MaterialMapResult, val::ParticleGenResult, val::AudioGenResult,
                val::AdversarialTeam, val::AdversarialOutcome, val::AdversarialReplay,
                val::AdversarialResult, val::PerformanceCaseKind, val::PerformanceCaseResult,
                val::PerformanceResult, val::PerformanceSnapshotCheck,
                val::ValidationSummary,
                tch::ToolchainCommandResult, tch::CoverageMetric, tch::CoverageMetrics,
                tch::CoverageFile, tch::ToolchainCoverage, tch::ToolchainTestFile,
                tch::ToolchainTestFailure, tch::ToolchainTestStatus, tch::ToolchainTest,
                tch::ToolchainTests, tch::ToolchainTestRun,
                tch::ToolchainSmokeResult, tch::ToolchainSummary,
                rr::RunLinks, rr::RunStatus,
                rr::PriorGameJamEntry, rr::ShowcaseMedia, rr::RunShowcase, rr::RunRecord,
            ],
        },
        // The review value types, shared by the backend and snapshot contracts. The
        // published `Review` wire shape is the backend's (`review.ts` in the backend
        // API package). The scoring and aggregation logic stays hand-written in the UI.
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: &[],
            file: "review.ts",
            decls: ts_decls![cfg;
                rv::Rating, rv::AestheticRating, rv::FailureCap, rv::VerdictStatus,
                rv::ReviewVerdict, rv::DomainRating, rv::DomainAesthetic,
                rv::RatingChange, rv::AestheticChange, rv::VerdictChange, rv::WriteupChange,
                rv::ReviewDiff,
                rv::ReviewRevision,
            ],
        },
        // The normalized harness event stream: the live monitor and the
        // published Events tab both render these. `HarnessEvent` carries the
        // common fields with the `EventKind` discriminator flattened inline.
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: &[],
            file: "event.ts",
            decls: ts_decls![cfg;
                ev::OrchestrationAction, ev::SystemStage, ev::SystemStatus, ev::EventKind,
                ev::HarnessEvent,
            ],
        },
        // The gg harness contract: the capability set that configures a gg run
        // (the "independent variable") and the first-party telemetry v1 stream the
        // console renders live. The telemetry `Usage` variant reuses the shared
        // token/cost types (`TokenMetrics`, `CostMetrics`) owned by the run-record
        // document, so they are imported from `index.ts`. The saved-configuration
        // (`/gg/configs`) and saved-agent (`/gg/agents`) shapes wrap these, but they
        // are the backend's own, so they are `api-codegen`'s (`gg.ts` in the backend
        // API package).
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: &[],
            file: GG_MODULE,
            decls: ts_decls![cfg;
                gg::GgAgentConfig, gg::GgOpeningTurn, gg::GgOpeningTree, gg::GgSubagentRef,
                gg::GgSubagentScope,
                gg::GgPromptCacheTtl, gg::GgReasoning, gg::GgReasoningEffort,
                gg::GgLoopDetection, gg::GgModelSlot,
                gg::GgConfigSlot, gg::GgSlotTarget,
                gg::GgCapabilityConfig, gg::GgCapabilitySet,
                gg::GgModuleKind, gg::GgModuleOrigin,
                gg::GgAgentModule, gg::GgModuleDisposition, gg::GgTransitionModule,
                gg::GgAgentApi, gg::GgAgentApiFunction,
                gg::GgArchiveEntry,
                gg::GgFsmState, gg::GgFsmTransition,
                gg::GgContextSource, gg::GgContextSourceUsage,
                gg::GgPromptRef, gg::GgLoggedToolCall, gg::GgLoggedImage,
                gg::GgSkillState,
                gg::GgMemoryCaps, gg::GgMemoryEntry, gg::GgMemoryChange,
                gg::GgMemoryPeak, gg::GgMemoryScope,
                gg::GgTaskStatus, gg::GgTaskEntry,
                gg::GgIssueStatus, gg::GgBoardEpic, gg::GgBoardIssue,
                gg::GgRetainedState, gg::GgContextAction,
                gg::GgAgentStatus, gg::GgAgentTransitionKind,
                gg::GgIssueReviewPhase, gg::GgReviewer,
                gg::GgRunLimits, gg::GgLimitKind, gg::GgLimitBreach,
                gg::GgHook, gg::GgHookEvent, gg::GgHookAction, gg::GgHookAgentKind,
                gg::GgHookOutcomeKind,
                gg::GgTurnOutcome, gg::GgTurnErrorKind, gg::GgTurnErrorType,
                gg::GgCallFailure,
                gg::GgProgramLanguage,
                gg::GgErrorSummary, gg::GgUndocumentedCalls,
                gg::GgRejectedResponses,
                gg::GgSlotCost, gg::GgProviderStat, gg::GgProviderFault, gg::GgProviderCandidate,
                gg::GgSessionSummary,
                gg::GgTelemetryKind, gg::GgTelemetryEvent, gg::GgUsageFigure,
            ],
        },
        // The gg session record: the content-addressed input log a run's session is
        // captured into. Its own module rather than more of `gg.ts` because it is a
        // self-contained document with its own pools, provenance table and entry
        // vocabulary.
        // `GgCapabilitySet`, `GgAgentStatus`, `GgLimitBreach` and `GgContextSource` are
        // owned by `gg.ts`, so those imports resolve cross-module.
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: &[],
            file: "gg-session-record.ts",
            decls: ts_decls![cfg;
                ggr::GgSessionRecorder,
                ggr::GgSessionModalities, ggr::GgSessionSeed,
                ggr::GgSessionMessage, ggr::GgSessionToolset,
                ggr::GgSessionTextClip,
                ggr::GgSessionAgentOrigin, ggr::GgSessionAgent,
                ggr::GgClientRole, ggr::GgSessionRequestShape, ggr::GgSessionRequest,
                ggr::GgSessionModelErrorKind, ggr::GgSessionModelError,
                ggr::GgShellCwd, ggr::GgShellOrigin, ggr::GgSessionCommand,
                ggr::GgSessionImage, ggr::GgSessionToolCall, ggr::GgSessionToolOutcome,
                ggr::GgSessionPromptSlot, ggr::GgSessionRetention, ggr::GgSessionFileRegion,
                ggr::GgSessionPromptItem,
                ggr::GgSessionEntryKind, ggr::GgSessionEntry,
                ggr::GgSessionTruncationReason, ggr::GgSessionTruncation,
                ggr::GgSessionRecord,
            ],
        },
        // The gg analysis query language (TCQ): the flat run document every query runs
        // over, the compiled query the client sends, the results it produces, and the
        // field catalog the editor's completer and sidebar read. The parser/compiler
        // are TypeScript-only by design, so this module is what they compile *to*; the
        // evaluator is mirrored against these same shapes. The batch envelope and the
        // saved views (`/gg/saved-queries`, `/gg/dashboards`) are the backend's own,
        // so they are `api-codegen`'s (`gg-query.ts` in the backend API package).
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: &[],
            file: "gg-query.ts",
            decls: ts_decls![cfg;
                ggq::GgValue, ggq::GgRunDoc,
                ggq::GgCompareOp, ggq::GgFilter,
                ggq::GgAggFunc, ggq::GgAgg,
                ggq::GgIntervalUnit, ggq::GgInterval, ggq::GgGroupKey,
                ggq::GgStatsStage, ggq::GgSortKey, ggq::GgQuery,
                ggq::GgDistribution, ggq::GgAggValue, ggq::GgBucketKeyPart, ggq::GgBucket,
                ggq::GgAggColumn, ggq::GgQueryResponse,
                ggq::GgFieldKind, ggq::GgFieldValueCount, ggq::GgFieldInfo, ggq::GgFieldCatalog,
            ],
        },
        // The gg **reference**: gg's whole model-facing surface — every tool as it is
        // sent on the wire (description and parameter schema, verbatim) and every
        // responses-as-code function as the guest SDK declares it — grouped into the
        // families gg itself groups them by.
        //
        // Its own module because it is a self-contained document fetched on one console
        // section (`GET /gg/reference`), and because it describes what gg *offers* rather
        // than what a run *did*: nothing that renders a run record, a replay or a query
        // result touches these types. There are two documents rather than one — the
        // language-independent index, and one per program language — for the reason the
        // module's rustdoc gives, and both are declared here because a console that fetches
        // the second by picking an arm off the first needs both shapes.
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: &[],
            file: "gg-reference.ts",
            decls: ts_decls![cfg;
                ggref::GgReferenceCategory, ggref::GgReferenceModule, ggref::GgToolVariant,
                ggref::GgToolCondition, ggref::GgRunDataStandIn, ggref::GgToolReference,
                ggref::GgReferenceLanguage, ggref::GgReference,
                ggref::GgReferenceEntryKind, ggref::GgReferenceEntry, ggref::GgReferenceApi,
            ],
        },
        // The code-analysis contract: the deterministic, execute-nothing static read of
        // the code a run's model wrote. Two tiers in one module, because they are one
        // pass and the document embeds the summary: `CodeAnalysisSummary` is the bounded
        // block that rides on the run record (so `index.ts` imports it from here), and
        // `CodeAnalysisDocument` is the unbounded per-run artifact the Code tab loads.
        //
        // Its own module rather than more of `index.ts` for the reason the replay record
        // has one: the document is a self-contained artifact fetched on one tab, and
        // nothing that merely lists runs should pay for its types.
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: &[],
            file: "code-analysis.ts",
            decls: ts_decls![cfg;
                code::CodeAuthoredBasis, code::CodeTreeBasis, code::CodeLanguage,
                code::CodeTruncationCap,
                code::CodeSizeSummary, code::CodeComplexitySummary, code::CodeGraphSummary,
                code::CodeApiSummary, code::CodeTypeScriptSummary, code::CodeRustSummary,
                code::CodeTestSummary, code::CodeDuplicationSummary, code::CodeAnalysisNotes,
                code::CodeAnalysisSummary,
                code::CodeFileEntry, code::CodeSymbolEntry, code::CodeImportEdge,
                code::CodeCloneInstance, code::CodeCloneGroup, code::CodeAnalysisDocument,
            ],
        },
        // The `code.*` display catalog: the label, unit, family, polarity and — the
        // reason it crosses the contract boundary at all — the `approximate` flag for
        // every leaf of the code-analysis summary.
        //
        // Its own module because it is the one contract artifact that ships *data* and
        // not only types: the table itself is appended below, generated from the Rust
        // `CODE_METRICS` static, so the Code tab's headers, the CLI's report and the
        // docs page cannot disagree about whether a figure rests on approximation. A
        // hand-kept TypeScript copy is exactly the drift the flag exists to prevent.
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: &[],
            file: CODE_METRICS_MODULE,
            decls: ts_decls![cfg; code::CodeMetricUnit, code::CodeMetricDef],
        },
        // The test suite format: every entity a suite version folder declares, as the
        // typed model `crates/core` reads and writes it. The Spec Cabinet's frontend
        // edits these shapes and the docs site documents them, so both read the same
        // declarations the two backends do.
        //
        // Ordered the way the format is: the manifests, the specifications, the debug
        // API, the assets and demonstrations, the showcase, the test case definitions,
        // and finally the suite tree that holds them all.
        //
        // The requirement outcomes a run records sit with the specifications that
        // declare the requirements, because they are read together: a console showing
        // what a suite run came to holds the requirement beside its outcome. They are
        // part of the run record's document rather than the suite's, so the JSON
        // schema that owns them is the run record's (see `RUN_RECORD_DEFS`).
        TsModule {
            package: RUN_RECORD_PKG,
            reexports: &[],
            file: "test-suite.ts",
            decls: ts_decls![cfg;
                suite::SuiteManifest, suite::VersionManifest,
                suite::SuiteRequirementKind, suite::SuiteRequirement, suite::SpecificationManifest,
                suite::RequirementStatus, suite::RequirementAssertion, suite::RequirementOutcome,
                suite::DebugApiFunctionKind, suite::DebugApiParameter, suite::DebugApiFunction,
                suite::DebugApiModuleRef, suite::DebugApiModule,
                suite::SuiteAssetKind, suite::AssetManifest, suite::DemoManifest,
                suite::ShowcaseMediaEntry, suite::ShowcaseManifest,
                suite::SuiteTestCaseType, suite::SuiteDifficulty,
                suite::SpriteCase, suite::VoxelCase, suite::AssetCase,
                suite::BuildCommands, suite::ToolchainCommands, suite::SuiteTestCaseDefinition,
                suite::SpecificationFolder, suite::SuiteDebugApi, suite::SuiteTestCaseFile,
                suite::AssetFolder, suite::DemoFolder, suite::SuiteShowcase, suite::SuiteTrees,
                suite::SuiteVersion,
                // The partial model The Spec Cabinet reads a draft through: the same
                // formats with every required key optional, and the tree holding them
                // together with the files that do not parse. Its API serves these, so
                // its frontend edits exactly the shapes an incomplete draft can take.
                suite::PartialVersionManifest, suite::PartialRequirement,
                suite::PartialSpecificationManifest,
                suite::PartialDebugApiParameter, suite::PartialDebugApiFunction,
                suite::PartialDebugApiModuleRef, suite::PartialDebugApiModule,
                suite::PartialAssetManifest, suite::PartialDemoManifest,
                suite::PartialShowcaseMediaEntry, suite::PartialShowcaseManifest,
                suite::PartialSpriteCase, suite::PartialVoxelCase, suite::PartialAssetCase,
                suite::PartialBuildCommands, suite::PartialToolchainCommands,
                suite::PartialTestCaseDefinition,
                suite::PartialSpecificationFolder, suite::PartialDebugApi,
                suite::PartialTestCaseFile, suite::PartialAssetFolder, suite::PartialDemoFolder,
                suite::PartialShowcase,
                // Last, because they are about the model rather than part of it:
                // the address a problem is written against, the rule class it
                // belongs to, where in a file it sits, and the problem itself, with
                // the file that does not parse the tree carries beside it. The Spec
                // Cabinet's API returns these beside every read and save, and its
                // frontend turns the address into the editor surface the message is
                // rendered on.
                suite::SuiteEntity, suite::SuiteRule, suite::SuiteLocation,
                suite::SuiteDiagnostic, suite::UnparsedFile, suite::PartialSuiteTree,
            ],
        },
    ]
}

/// The JSON Schema documents whose types are all contract types. The backend's
/// documents — including the four that sit in the contract's `core/` and `gg/`
/// directories (`core/tournament`, `gg/query-batch-*`, `gg/saved-query`,
/// `gg/dashboard`) — are `api-codegen`'s.
pub fn contract_schema_docs() -> Vec<SchemaDoc> {
    vec![
        // Core: the run-record document (canonical home of the whole tree).
        SchemaDoc {
            rel_path: "core/run-record.schema.json",
            root: Some("RunRecord"),
            owns: RUN_RECORD_DEFS,
            schema: root_schema::<rr::RunRecord>(),
        },
        // The gg harness contract. The capability set is self-contained (its
        // subtypes are its own). The telemetry event's `Usage` variant references the
        // shared `TokenMetrics`/`CostMetrics` owned by the run-record document, so
        // those refs are rewritten to cross-document URLs.
        // The run's execution ceilings (`GgRunLimits`) are owned here rather than by the
        // session summary, because the capability set is where they are *configured*; the
        // summary's record of the ceilings actually in force references them across
        // documents.
        SchemaDoc {
            rel_path: "gg/capability-set.schema.json",
            root: Some("GgCapabilitySet"),
            owns: &[
                "GgAgentConfig",
                "GgOpeningTurn",
                "GgOpeningTree",
                "GgSubagentRef",
                "GgSubagentScope",
                "GgPromptCacheTtl",
                "GgReasoning",
                "GgReasoningEffort",
                "GgCapabilityConfig",
                "GgModelSlot",
                "GgConfigSlot",
                "GgSlotTarget",
                "GgRunLimits",
                // The run's hooks are configured on the capability set, so they are owned
                // by the same document its ceilings are — for the same reason: this is
                // where an operator declares them.
                "GgHook",
                "GgHookEvent",
                "GgHookAction",
            ],
            schema: root_schema::<gg::GgCapabilitySet>(),
        },
        // The gg session summary: the aggregatable per-run outcome. Referenced by both the
        // telemetry event (its `SessionSummary` variant) and the run-record document (via
        // `RunSubject.gg_summary`), so — like the capability set — it gets its own document
        // and both references become cross-document `$ref`s. Its per-slot cost rollup
        // (`GgSlotCost`) reuses the shared `TokenMetrics`/`CostMetrics` owned by the
        // run-record document, which are rewritten to cross-document URLs. The breach it
        // records (`GgLimitBreach`/`GgLimitKind`) is owned here — the summary is where a
        // breach is durably recorded, and the telemetry event that announces one references
        // it cross-document.
        SchemaDoc {
            rel_path: "gg/session-summary.schema.json",
            root: Some("GgSessionSummary"),
            owns: &["GgSlotCost", "GgLimitBreach", "GgLimitKind"],
            schema: root_schema::<gg::GgSessionSummary>(),
        },
        SchemaDoc {
            rel_path: "gg/telemetry-event.schema.json",
            root: Some("GgTelemetryEvent"),
            owns: &[
                "GgTelemetryKind",
                "GgContextSource",
                "GgContextSourceUsage",
                "GgPromptRef",
                "GgLoggedToolCall",
                "GgLoggedImage",
                "GgSkillState",
                "GgMemoryCaps",
                "GgMemoryEntry",
                "GgMemoryChange",
                "GgMemoryPeak",
                "GgTaskStatus",
                "GgTaskEntry",
                "GgIssueStatus",
                "GgBoardEpic",
                "GgBoardIssue",
                "GgRetainedState",
                "GgContextAction",
                "GgAgentTransitionKind",
                // The module model's vocabulary. These are *also* the documented shape of a
                // capability's `scope` param and of an FSM transition's transfer
                // list — but a params key is free-form JSON in the schema, so the telemetry
                // event is the one schema root that genuinely references them (through
                // `AgentModules` and the reshaped `AgentTransition`), which makes this
                // document their canonical home.
                "GgModuleKind",
                "GgModuleOrigin",
                "GgMemoryScope",
                "GgAgentModule",
                "GgModuleDisposition",
                "GgTransitionModule",
                // The per-agent offered surface's vocabulary, which rides on `AgentSurface` and
                // appears nowhere else in the contract.
                "GgAgentApi",
                "GgAgentApiFunction",
                "GgArchiveEntry",
                "GgIssueReviewPhase",
                "GgReviewer",
                // The program language an instance's surface reports. It is also the
                // session summary's, but a telemetry reader must be able to resolve the
                // reference without loading a second document.
                "GgProgramLanguage",
                // Which of the session's two cost figures a `Usage` delta fed — the
                // event's own vocabulary, appearing nowhere else in the contract.
                "GgUsageFigure",
            ],
            schema: root_schema::<gg::GgTelemetryEvent>(),
        },
        // The gg session record: the seed, the three content-addressed pools, the agent
        // provenance table and the ordered input log. Its `capabilitySet`
        // references `GgCapabilitySet`, and its agent rows reference `GgAgentStatus` /
        // `GgLimitBreach`, all owned by the gg documents above, so those refs are
        // rewritten to cross-document URLs; the pooled message/toolset/response bodies
        // are free-form JSON (the gg binary owns their concrete shapes).
        SchemaDoc {
            rel_path: "gg/session-record.schema.json",
            root: Some("GgSessionRecord"),
            owns: &[
                "GgSessionRecorder",
                "GgSessionSeed",
                "GgSessionModalities",
                "GgSessionMessage",
                "GgSessionToolset",
                "GgSessionTextClip",
                "GgSessionAgent",
                "GgSessionAgentOrigin",
                "GgSessionRequest",
                "GgClientRole",
                "GgSessionRequestShape",
                "GgSessionEntry",
                "GgSessionEntryKind",
                "GgSessionModelError",
                "GgSessionModelErrorKind",
                "GgSessionToolCall",
                "GgSessionToolOutcome",
                "GgSessionImage",
                "GgShellCwd",
                "GgShellOrigin",
                "GgSessionCommand",
                "GgSessionPromptItem",
                "GgSessionPromptSlot",
                "GgSessionRetention",
                "GgSessionFileRegion",
                "GgSessionTruncation",
                "GgSessionTruncationReason",
            ],
            schema: root_schema::<ggr::GgSessionRecord>(),
        },
        // The code-analysis document: the unbounded per-run artifact
        // (`{run}/code-analysis.json.gz`, served at `GET /runs/{id}/code-analysis`).
        // Rooted at the document rather than at the summary because the document embeds
        // the summary, so one schema owns the whole vocabulary and the run-record
        // document's reference to `CodeAnalysisSummary` becomes a cross-document `$ref`.
        SchemaDoc {
            rel_path: "core/code-analysis.schema.json",
            root: Some("CodeAnalysisDocument"),
            owns: CODE_ANALYSIS_DEFS,
            schema: root_schema::<code::CodeAnalysisDocument>(),
        },
        // The test suite format, rooted at the version folder because that is the unit
        // the format defines: a version folder is self-contained, and every entity in
        // it is reachable from this one document. Nothing in it is shared with another
        // contract document, so it owns its whole vocabulary.
        SchemaDoc {
            rel_path: "core/test-suite.schema.json",
            root: Some("SuiteVersion"),
            owns: TEST_SUITE_DEFS,
            schema: root_schema::<suite::SuiteVersion>(),
        },
        // The compiled TCQ query — the single wire form of a gg analysis query. It owns
        // the whole language vocabulary (the filter tree, the aggregation functions,
        // the histogram intervals), which the response and document below
        // cross-reference.
        SchemaDoc {
            rel_path: "gg/query.schema.json",
            root: Some("GgQuery"),
            owns: &[
                "GgValue",
                "GgCompareOp",
                "GgFilter",
                "GgAggFunc",
                "GgAgg",
                "GgIntervalUnit",
                "GgInterval",
                "GgGroupKey",
                "GgStatsStage",
                "GgSortKey",
            ],
            schema: root_schema::<ggq::GgQuery>(),
        },
        // A gg run as the query language sees it: one flat map of dotted field names to
        // scalars. Its own document because it is what the public static site ships as
        // a snapshot artifact and evaluates in the browser, independent of any query.
        SchemaDoc {
            rel_path: "gg/run-document.schema.json",
            root: Some("GgRunDoc"),
            owns: &[],
            schema: root_schema::<ggq::GgRunDoc>(),
        },
        // The result of a TCQ query: the matching documents or the aggregated buckets.
        // `GgValue`, `GgAggFunc` and `GgRunDoc` are owned by the two documents above,
        // so those refs become cross-document URLs.
        SchemaDoc {
            rel_path: "gg/query-response.schema.json",
            root: Some("GgQueryResponse"),
            owns: &[
                "GgDistribution",
                "GgAggValue",
                "GgBucketKeyPart",
                "GgBucket",
                "GgAggColumn",
            ],
            schema: root_schema::<ggq::GgQueryResponse>(),
        },
        // The field catalog: every field observed across the corpus, with its kind,
        // document count and top values — the completer's and the field sidebar's
        // source, and the second mirrored function.
        SchemaDoc {
            rel_path: "gg/field-catalog.schema.json",
            root: Some("GgFieldCatalog"),
            owns: &["GgFieldInfo", "GgFieldKind", "GgFieldValueCount"],
            schema: root_schema::<ggq::GgFieldCatalog>(),
        },
        // gg's model-facing reference, in the two documents it is served as: the index
        // (`GET /gg/reference`) carrying the families, the tools and the arm list, and one
        // arm's whole surface (`GET /gg/reference/{language}`). Wholly self-contained — they
        // share no type with any other document, because they describe gg's *surface* rather
        // than any run — so every one of their subtypes is owned by one of the two and
        // nothing is cross-referenced outward.
        SchemaDoc {
            rel_path: "gg/reference.schema.json",
            root: Some("GgReference"),
            owns: &[
                "GgReferenceCategory",
                "GgReferenceLanguage",
                "GgToolReference",
                "GgToolVariant",
                "GgToolCondition",
                "GgRunDataStandIn",
            ],
            schema: root_schema::<ggref::GgReference>(),
        },
        SchemaDoc {
            rel_path: "gg/reference-api.schema.json",
            root: Some("GgReferenceApi"),
            owns: &[
                "GgReferenceModule",
                "GgReferenceEntry",
                "GgReferenceEntryKind",
            ],
            schema: root_schema::<ggref::GgReferenceApi>(),
        },
    ]
}

/// A schema document with an anonymous root (an array, or an envelope no other
/// document references): no owned `$defs`, so its local subtypes stay inline and
/// only shared types (the run-record tree) become cross-document `$ref`s.
pub fn anon(rel_path: &'static str, schema: serde_json::Value) -> SchemaDoc {
    SchemaDoc {
        rel_path,
        root: None,
        owns: &[],
        schema,
    }
}

/// Write a generated TypeScript module under its package's `src/` directory.
pub fn write_ts(root: &Path, package: &str, file: &str, content: &str) -> Result<()> {
    // Every generated package is an npm workspace member under `packages/`, named
    // after the package's unscoped half, so the scope is all that separates the
    // specifier from the directory.
    let dir = package
        .rsplit_once('/')
        .map(|(_scope, name)| name)
        .unwrap_or(package);
    let src = root.join("packages").join(dir).join("src");
    fs::create_dir_all(&src).with_context(|| format!("creating {}", src.display()))?;
    let path = src.join(file);
    fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// Write a JSON Schema document under `apps/docs/public/schema/`.
pub fn write_schema(root: &Path, rel_path: &str, value: &serde_json::Value) -> Result<()> {
    let path = root.join("apps/docs/public/schema").join(rel_path);
    let mut json = serde_json::to_string_pretty(value)?;
    json.push('\n');
    fs::write(&path, json).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// The workspace root, resolved from this crate's compile-time manifest dir
/// (`crates/contract-codegen` → the workspace root two levels up), so the
/// generator writes to the right paths regardless of the invocation's cwd.
pub fn workspace_root() -> Result<PathBuf> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .ancestors()
        .nth(2)
        .map(Path::to_path_buf)
        .context("resolving the workspace root from CARGO_MANIFEST_DIR")
}
