//! `contract-codegen` — the single generator for the Test Cabinet data contract.
//!
//! It emits **both** the TypeScript bindings (`packages/run-record/src/*.ts`, via
//! [`ts_rs`]) and the JSON Schemas (`apps/docs/public/schema/**`, via [`schemars`])
//! from one set of Rust types — the types in `crates/core` and `crates/backend`
//! that derive `TS` + `JsonSchema` behind their `contract` feature. Because both
//! artifacts come from the same source in one pass, the TS
//! bindings and the JSON Schemas can never drift from each other or from Rust.
//!
//! Run it with `cargo run -p contract-codegen` (or `npm run gen:contract`, which
//! also normalizes the output with Prettier). A CI check regenerates and fails on
//! any diff, so the committed artifacts always match the Rust source.

mod emit;

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use emit::{SchemaDoc, TsModule, finalize_schemas, finalize_ts, root_schema, ts_config, ts_decl};

use test_cabinet_core::{
    accounts as acct, event as ev, match_play as mp, metrics as m, review as rv, run_record as rr,
    test_case as tc, validation as val,
};
use test_cabinet_backend::{api as bapi, error as berr, relay, snapshot as snap};

/// Collect the [`emit::TsDecl`]s for the listed types, in declaration order.
macro_rules! ts_decls {
    ($cfg:expr; $($t:ty),+ $(,)?) => {
        vec![ $( ts_decl::<$t>($cfg) ),+ ]
    };
}

/// The header stamped on every generated TypeScript module.
const TS_HEADER: &str = "\
// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` and `crates/backend`, which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.\n\n";

/// The run-record schema's `$defs`: every type in the `RunRecord` tree except the
/// root. Names are the published (TS-facing) names, so renamed Rust types appear
/// here under their contract name (`TokenMetrics`, `RunValidation`, `AssetSheet`).
const RUN_RECORD_DEFS: &[&str] = &[
    "RunSubject",
    "RunTooling",
    "RunEnvironment",
    "RunMetrics",
    "TokenMetrics",
    "CostMetrics",
    "RunValidation",
    "RunLinks",
    "RunStatus",
    "HarnessSlug",
    "RunState",
    "AuthMode",
    "TestType",
    "MediaKind",
    "StepResult",
    "CheckResult",
    "ProofResult",
    "AssetGenResult",
    "AssetFrameResult",
    "AssetSheet",
    "AssetSheetSequence",
    "AdversarialResult",
    "AdversarialReplay",
    "AdversarialTeam",
    "AdversarialOutcome",
    "PerformanceResult",
    "PerformanceCaseResult",
];

/// The tournament schema's `$defs`. `AdversarialOutcome` is *not* listed: it is
/// owned by the run-record schema, so a reference to it is rewritten to a
/// cross-document `$ref` at that schema's URL.
const TOURNAMENT_DEFS: &[&str] = &["MatchSummary", "Standing", "ControllerRef", "ControllerKind"];

/// The review schema's `$defs`: the canonical home of the review value types, so
/// the backend and snapshot documents (and the console that submits reviews) all
/// reference them here rather than each carrying a copy.
const REVIEW_DEFS: &[&str] = &["Rating", "VerdictStatus", "ReviewVerdict", "DomainRating"];

fn main() -> Result<()> {
    let root = workspace_root()?;
    let cfg = ts_config();

    // --- TypeScript modules ------------------------------------------------
    let modules = vec![
        // The run-record + arena contract. Ordered to mirror the run-record
        // document: identity, metrics, validation results, arena, the record.
        TsModule {
            file: "index.ts",
            decls: ts_decls![&cfg;
                rr::HarnessSlug, rr::RunState, rr::AuthMode, rr::RunEnvironment, rr::RunTooling,
                tc::TestType, rr::RunSubject, m::TokenCounts, m::Cost, m::RunMetrics,
                tc::MediaKind, val::ProofResult, val::CheckResult, val::StepResult,
                val::AssetGenResult, val::AssetFrameResult, tc::SheetSpec, tc::SheetSequence,
                val::AdversarialTeam, val::AdversarialOutcome, val::AdversarialReplay,
                val::AdversarialResult, val::PerformanceCaseResult, val::PerformanceResult,
                mp::ControllerKind, mp::ControllerRef, mp::MatchSummary, mp::Standing,
                mp::TournamentRecord, val::ValidationSummary, rr::RunLinks, rr::RunStatus,
                rr::RunRecord,
            ],
        },
        // The review value types (shared by the backend and snapshot
        // contracts) plus the published `Review` wire shape. The scoring and
        // aggregation logic stays hand-written in the UI.
        TsModule {
            file: "review.ts",
            decls: ts_decls![&cfg;
                rv::Rating, rv::VerdictStatus, rv::ReviewVerdict, rv::DomainRating, snap::Review,
            ],
        },
        // The normalized harness event stream: the live monitor and the
        // published Events tab both render these. `HarnessEvent` carries the
        // common fields with the `EventKind` discriminator flattened inline.
        TsModule {
            file: "event.ts",
            decls: ts_decls![&cfg;
                ev::OrchestrationAction, ev::SystemStage, ev::SystemStatus, ev::EventKind,
                ev::HarnessEvent,
            ],
        },
        // The auth surface: accounts and the register/login request + token
        // response.
        TsModule {
            file: "account.ts",
            decls: ts_decls![&cfg;
                acct::Account, acct::RegisterRequest, acct::LoginRequest, acct::AuthnResponse,
            ],
        },
        // The published snapshot documents (the static gallery's data): the index,
        // the runs index + summary cards, the per-run document, and case metadata.
        TsModule {
            file: "snapshot.ts",
            decls: ts_decls![&cfg;
                snap::SnapshotIndex, snap::SubjectOut, snap::LinksOut, snap::RunSummary,
                snap::RunsIndex, snap::RunProofOut, snap::RunAssetOut, snap::PerRun,
                tc::ReferenceKind, snap::CaseCheckOut, snap::CaseDomainOut,
                snap::CaseReviewItemOut, snap::CaseReferenceOut, snap::CaseVariantOut,
                snap::CaseMetadata,
            ],
        },
        // The backend HTTP API response envelopes (error + catalog/versions).
        TsModule {
            file: "backend-api.ts",
            decls: ts_decls![&cfg;
                berr::ErrorBody, berr::ErrorEnvelope, bapi::CatalogCase, bapi::CatalogResponse,
                bapi::VersionsResponse,
            ],
        },
        // The backend's run-queue control plane (the `/jobs` namespace) — what
        // replaced the worker's run API. The console enqueues a run, observes it
        // via the live stream / status / active list, and is alerted on completion
        // over the notification feed. The shared launch/claim/status shapes live in
        // `core::job_api`; the server outputs and the relay's summary/notification
        // shapes live in `backend`. `ClientConfig` is the console's `GET /config`
        // body (today just the artifact-service base URL).
        TsModule {
            file: "jobs-api.ts",
            decls: ts_decls![&cfg;
                bapi::DriverState, bapi::LaunchBody, bapi::ClaimedJob, bapi::StatusUpdate,
                bapi::JobState, relay::JobSummary, bapi::ActiveJobOut, bapi::JobStatusOut,
                bapi::LaunchAck, relay::NotificationOutcome, relay::NotificationKind,
                relay::Notification, bapi::ClientConfig,
            ],
        },
    ];
    for (file, content) in finalize_ts(modules, TS_HEADER) {
        write_ts(&root, file, &content)?;
    }

    // --- JSON Schema documents ---------------------------------------------
    let schemas = finalize_schemas(vec![
        // Core: the run-record document (canonical home of the whole tree) and the
        // persisted tournament document.
        SchemaDoc {
            rel_path: "core/run-record.schema.json",
            root: Some("RunRecord"),
            owns: RUN_RECORD_DEFS,
            schema: root_schema::<rr::RunRecord>(),
        },
        SchemaDoc {
            rel_path: "core/tournament.schema.json",
            root: Some("TournamentRecord"),
            owns: TOURNAMENT_DEFS,
            schema: root_schema::<mp::TournamentRecord>(),
        },
        // The backend's run-queue (`/jobs`) control plane. These reference the core
        // run-record document by URL (the launch request, the claimed job, and the
        // driver's status update all carry or echo a `RunRecord`); any type local to
        // a single document (its own ack/summary) stays inline.
        anon("jobs-api/launch-run-request.schema.json", root_schema::<bapi::LaunchBody>()),
        anon("jobs-api/launch-run-ack.schema.json", root_schema::<bapi::LaunchAck>()),
        anon("jobs-api/claimed-job.schema.json", root_schema::<bapi::ClaimedJob>()),
        anon("jobs-api/status-update.schema.json", root_schema::<bapi::StatusUpdate>()),
        anon("jobs-api/active-jobs.schema.json", root_schema::<Vec<bapi::ActiveJobOut>>()),
        anon("jobs-api/job-status.schema.json", root_schema::<bapi::JobStatusOut>()),
        anon("jobs-api/notification.schema.json", root_schema::<relay::Notification>()),
        anon("jobs-api/client-config.schema.json", root_schema::<bapi::ClientConfig>()),
        // Backend API: the auth surface (the token response is the canonical home
        // of Account) and the canonical review document (the home of the review
        // value types the backend + snapshot reference).
        SchemaDoc {
            rel_path: "backend-api/auth.schema.json",
            root: Some("AuthResult"),
            owns: &["Account"],
            schema: root_schema::<acct::AuthnResponse>(),
        },
        anon("backend-api/auth-register-request.schema.json", root_schema::<acct::RegisterRequest>()),
        anon("backend-api/auth-login-request.schema.json", root_schema::<acct::LoginRequest>()),
        anon("backend-api/error.schema.json", root_schema::<berr::ErrorEnvelope>()),
        anon("backend-api/test-case-catalog.schema.json", root_schema::<bapi::CatalogResponse>()),
        anon("backend-api/test-case-versions.schema.json", root_schema::<bapi::VersionsResponse>()),
        // The fully-resolved definition of one test-case version (`GET
        // /test-cases/{slug}/{version}`). Self-contained except for the core
        // run-record types it shares (`TestType`, `MediaKind`, `AssetSheet`),
        // which are rewritten to cross-document `$ref`s at the run-record URL.
        anon("backend-api/resolved-test-case-version.schema.json", root_schema::<bapi::VersionResponse>()),
        // The backend's push request (`POST /runs`): the run record, its links,
        // and the recorded event stream. References the core run-record document
        // by URL; its `LinksIn` and the `HarnessEvent`/`EventKind` tree stay
        // inline as this is their only referencer.
        anon("backend-api/publish-run-request.schema.json", root_schema::<bapi::PushRequest>()),
        SchemaDoc {
            rel_path: "backend-api/review.schema.json",
            root: Some("Review"),
            owns: REVIEW_DEFS,
            schema: root_schema::<snap::Review>(),
        },
        // Snapshot documents (the static gallery's published data). Each references
        // the core run-record and review documents by URL; its own summary/envelope
        // subtypes stay inline.
        anon("snapshot/index.schema.json", root_schema::<snap::SnapshotIndex>()),
        anon("snapshot/runs.schema.json", root_schema::<snap::RunsIndex>()),
        anon("snapshot/run.schema.json", root_schema::<snap::PerRun>()),
        anon("snapshot/case.schema.json", root_schema::<snap::CaseMetadata>()),
    ])?;
    for (rel_path, value) in schemas {
        write_schema(&root, rel_path, &value)?;
    }

    Ok(())
}

/// A schema document with an anonymous root (an array, or an envelope no other
/// document references): no owned `$defs`, so its local subtypes stay inline and
/// only shared types (the run-record tree) become cross-document `$ref`s.
fn anon(rel_path: &'static str, schema: serde_json::Value) -> SchemaDoc {
    SchemaDoc {
        rel_path,
        root: None,
        owns: &[],
        schema,
    }
}

/// Write a generated TypeScript module under `packages/run-record/src/`.
fn write_ts(root: &Path, file: &str, content: &str) -> Result<()> {
    let path = root.join("packages/run-record/src").join(file);
    fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// Write a JSON Schema document under `apps/docs/public/schema/`.
fn write_schema(root: &Path, rel_path: &str, value: &serde_json::Value) -> Result<()> {
    let path = root.join("apps/docs/public/schema").join(rel_path);
    let mut json = serde_json::to_string_pretty(value)?;
    json.push('\n');
    fs::write(&path, json).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// The workspace root, resolved from this crate's compile-time manifest dir
/// (`crates/contract-codegen` → the workspace root two levels up), so the
/// generator writes to the right paths regardless of the invocation's cwd.
fn workspace_root() -> Result<PathBuf> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .ancestors()
        .nth(2)
        .map(Path::to_path_buf)
        .context("resolving the workspace root from CARGO_MANIFEST_DIR")
}
