//! `contract-codegen` — the single generator for the Test Cabinet data contract.
//!
//! It emits **both** the TypeScript bindings (`packages/run-record/src/*.ts`, via
//! [`ts_rs`]) and the JSON Schemas (`apps/docs/public/schema/**`, via [`schemars`])
//! from one set of Rust types — the types in `crates/core` and `crates/backend`
//! that derive `TS` + `JsonSchema` behind their `contract` feature. Because both
//! artifacts come from the same source in one pass, the TS
//! bindings and the JSON Schemas can never drift from each other or from Rust.
//!
//! Run it with `cargo run -p contract-codegen` (or `npm run gen:contract`, which
//! also normalizes the output with Prettier). A CI check regenerates and fails on
//! any diff, so the committed artifacts always match the Rust source.

mod emit;

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use emit::{SchemaDoc, TsModule, finalize_schemas, finalize_ts, root_schema, ts_config, ts_decl};

use test_cabinet_backend::{api as bapi, error as berr, relay, snapshot as snap};
use test_cabinet_core::{
    accounts as acct, code_analysis as code, comparison as cmp, comparison_stats as cstats,
    event as ev, gg, gg_query as ggq, gg_replay as ggr, match_play as mp, metrics as m,
    review as rv, run_record as rr, test_case as tc, validation as val,
};

/// Collect the [`emit::TsDecl`]s for the listed types, in declaration order.
macro_rules! ts_decls {
    ($cfg:expr; $($t:ty),+ $(,)?) => {
        vec![ $( ts_decl::<$t>($cfg) ),+ ]
    };
}

/// The header stamped on every generated TypeScript module.
const TS_HEADER: &str = "\
// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` and `crates/backend`, which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.\n\n";

/// The run-record schema's `$defs`: every type in the `RunRecord` tree except the
/// root. Names are the published (TS-facing) names, so renamed Rust types appear
/// here under their contract name (`TokenMetrics`, `RunValidation`, `AssetSheet`).
const RUN_RECORD_DEFS: &[&str] = &[
    "RunSubject",
    "RunTooling",
    "RunEnvironment",
    "RunMetrics",
    "TokenMetrics",
    "CostMetrics",
    "RunValidation",
    "RunLinks",
    "RunStatus",
    "PriorGameJamEntryRef",
    "HarnessSlug",
    "RunState",
    "AuthMode",
    "TestType",
    "MediaKind",
    "StepResult",
    "CheckResult",
    "ProofResult",
    "DebugScriptResult",
    "AutoVerdict",
    "Assertion",
    "DebugScriptOutput",
    "AssetGenResult",
    "AssetFrameResult",
    "AssetSheet",
    "AssetSheetSequence",
    "VoxelGenResult",
    "VoxelPartResult",
    "NineSlice",
    "UiGenResult",
    "UiElementResult",
    "MaterialGenResult",
    "MaterialMapResult",
    "ParticleGenResult",
    "AudioGenResult",
    "ModelSpec",
    "PartSpec",
    "JointSpec",
    "JointKindSpec",
    "AxisSpec",
    "DriveKindSpec",
    "InterpSpec",
    "KeyframeSpec",
    "AnimationSpec",
    "AnimationTrackSpec",
    "AdversarialResult",
    "AdversarialReplay",
    "AdversarialTeam",
    "AdversarialOutcome",
    "PerformanceResult",
    "PerformanceCaseResult",
    "PerformanceCaseKind",
    "PerformanceSnapshotCheck",
];

/// The code-analysis schema's `$defs`: every type in the `CodeAnalysisDocument` tree
/// except the root. `CodeAnalysisSummary` is listed here rather than with the run record's
/// defs even though the record carries it — the document embeds the same block, and one
/// owner per type is what turns the record's reference into a cross-document `$ref`
/// instead of a second copy that can drift.
const CODE_ANALYSIS_DEFS: &[&str] = &[
    "CodeAnalysisSummary",
    "CodeAuthoredBasis",
    "CodeTreeBasis",
    "CodeLanguage",
    "CodeTruncationCap",
    "CodeSizeSummary",
    "CodeComplexitySummary",
    "CodeGraphSummary",
    "CodeApiSummary",
    "CodeTypeScriptSummary",
    "CodeRustSummary",
    "CodeTestSummary",
    "CodeDuplicationSummary",
    "CodeAnalysisNotes",
    "CodeFileEntry",
    "CodeSymbolEntry",
    "CodeImportEdge",
    "CodeCloneGroup",
    "CodeCloneInstance",
];

/// The tournament schema's `$defs`. `AdversarialOutcome` is *not* listed: it is
/// owned by the run-record schema, so a reference to it is rewritten to a
/// cross-document `$ref` at that schema's URL.
const TOURNAMENT_DEFS: &[&str] = &[
    "MatchSummary",
    "Standing",
    "ControllerRef",
    "ControllerKind",
];

/// The review schema's `$defs`: the canonical home of the review value types, so
/// the backend and snapshot documents (and the console that submits reviews) all
/// reference them here rather than each carrying a copy.
const REVIEW_DEFS: &[&str] = &[
    "Rating",
    "VerdictStatus",
    "ReviewVerdict",
    "DomainRating",
    "RatingChange",
    "VerdictChange",
    "WriteupChange",
    "ReviewDiff",
    "ReviewRevision",
];

/// The generated module that carries the `code.*` display catalog.
///
/// Named once because it is referenced twice — as the module's file name and as the
/// target of the appended [`CODE_METRICS`](test_cabinet_core::CODE_METRICS) table — and a
/// mismatch between the two would silently emit the types without the data.
const CODE_METRICS_MODULE: &str = "code-metrics.ts";

/// Render the `code.*` display catalog as a TypeScript value.
///
/// The table is Rust's, verbatim: it is serialized with the same `serde` derive the
/// contract types use, so the emitted rows carry exactly the paths, labels, units,
/// families, polarities and `approximate` flags the analyzer and the CLI read. Prettier
/// (in the generator wrapper) reformats the JSON into idiomatic TypeScript, so the shape
/// written here only has to be valid.
fn code_metrics_catalog() -> Result<String> {
    /// The JSDoc stamped above the emitted table. A constant rather than part of the
    /// format string because the prose contains `{@link …}`, which a Rust format string
    /// would read as an interpolation.
    const DOC: &str = "/**\n\
         * Display metadata for every leaf of the code-analysis summary, in the order a\n\
         * reader wants the figures: by family, and within a family by how much the figure\n\
         * says.\n\
         *\n\
         * This is **not** a query vocabulary — the query language derives its field catalog\n\
         * from the documents it has indexed, so a metric is queryable with or without an\n\
         * entry here. What an entry buys is what a number cannot carry on its own: a label,\n\
         * a unit, a polarity, and the {@link CodeMetricDef.approximate} flag that the Code\n\
         * tab's headers, the field sidebar and the docs page all read, so the four cannot\n\
         * drift apart.\n\
         */\n";
    let rows = serde_json::to_string(&test_cabinet_core::CODE_METRICS)
        .context("serializing the code-metric catalog")?;
    Ok(format!(
        "{DOC}export const CODE_METRICS: readonly CodeMetricDef[] = {rows};\n"
    ))
}

fn main() -> Result<()> {
    let root = workspace_root()?;
    let cfg = ts_config();

    // --- TypeScript modules ------------------------------------------------
    let modules = vec![
        // The run-record + arena contract. Ordered to mirror the run-record
        // document: identity, metrics, validation results, arena, the record.
        TsModule {
            file: "index.ts",
            decls: ts_decls![&cfg;
                rr::HarnessSlug, rr::HarnessFamily, rr::RunState, rr::AuthMode, rr::RunEnvironment, rr::RunTooling,
                tc::TestType, tc::AssetKind, rr::RunSubject, m::TokenCounts, m::Cost, m::RunMetrics,
                tc::MediaKind, val::ProofResult, val::CheckResult, val::StepResult,
                val::DebugScriptResult, val::AutoVerdict, val::Assertion, val::DebugScriptOutput,
                val::AssetGenResult, val::AssetFrameResult, tc::SheetSpec, tc::SheetSequence,
                val::VoxelGenResult, val::VoxelPartResult, tc::ModelSpec, tc::PartSpec,
                tc::JointSpec, tc::JointKindSpec, tc::AxisSpec, tc::DriveKindSpec,
                tc::InterpSpec, tc::KeyframeSpec, tc::AnimationSpec, tc::AnimationTrackSpec,
                tc::NineSlice, val::UiGenResult, val::UiElementResult, val::MaterialGenResult,
                val::MaterialMapResult, val::ParticleGenResult, val::AudioGenResult,
                val::AdversarialTeam, val::AdversarialOutcome, val::AdversarialReplay,
                val::AdversarialResult, val::PerformanceCaseKind, val::PerformanceCaseResult,
                val::PerformanceResult, val::PerformanceSnapshotCheck,
                mp::ControllerKind, mp::ControllerRef, mp::MatchSummary, mp::Standing,
                mp::TournamentRecord, val::ValidationSummary, rr::RunLinks, rr::RunStatus,
                rr::PriorGameJamEntryRef, rr::RunRecord,
            ],
        },
        // The review value types (shared by the backend and snapshot
        // contracts) plus the published `Review` wire shape. The scoring and
        // aggregation logic stays hand-written in the UI.
        TsModule {
            file: "review.ts",
            decls: ts_decls![&cfg;
                rv::Rating, rv::VerdictStatus, rv::ReviewVerdict, rv::DomainRating,
                rv::RatingChange, rv::VerdictChange, rv::WriteupChange, rv::ReviewDiff,
                rv::ReviewRevision, snap::Review,
            ],
        },
        // The normalized harness event stream: the live monitor and the
        // published Events tab both render these. `HarnessEvent` carries the
        // common fields with the `EventKind` discriminator flattened inline.
        TsModule {
            file: "event.ts",
            decls: ts_decls![&cfg;
                ev::OrchestrationAction, ev::SystemStage, ev::SystemStatus, ev::EventKind,
                ev::HarnessEvent,
            ],
        },
        // The gg harness contract: the capability set that configures a gg run
        // (the "independent variable") and the first-party telemetry v1 stream the
        // console renders live. The telemetry `Usage` variant reuses the shared
        // token/cost types (`TokenMetrics`, `CostMetrics`) owned by the run-record
        // document, so they are imported from `index.ts`. The saved-configuration
        // shapes (`/gg/configs`) live here too: a registered configuration is just a
        // named capability set, so it belongs beside the set it wraps.
        TsModule {
            file: "gg.ts",
            decls: ts_decls![&cfg;
                gg::GgAgentConfig, gg::GgSubagentRef, gg::GgSubagentScope,
                gg::GgPromptCacheTtl, gg::GgModelSlot,
                gg::GgCapabilityConfig, gg::GgCapabilitySet,
                gg::GgModuleKind, gg::GgModuleOwnership, gg::GgModuleOrigin,
                gg::GgAgentModule, gg::GgModuleDisposition, gg::GgTransitionModule,
                gg::GgArchiveEntry,
                gg::GgFsmState, gg::GgFsmTransition,
                gg::GgContextSource, gg::GgContextSourceUsage,
                gg::GgPromptRef, gg::GgLoggedToolCall, gg::GgLoggedImage,
                gg::GgSkillState,
                gg::GgMemoryCaps, gg::GgMemoryEntry, gg::GgMemoryChange,
                gg::GgMemoryPeak, gg::GgMemoryScope,
                gg::GgTaskStatus, gg::GgTaskEntry,
                gg::GgIssueStatus, gg::GgBoardEpic, gg::GgBoardIssue,
                gg::GgRetainedState, gg::GgContextAction,
                gg::GgAgentStatus, gg::GgWorkflowPhase, gg::GgAgentTransitionKind,
                gg::GgIssueReviewPhase, gg::GgReviewer,
                gg::GgSpeculationPhase,
                gg::GgRunLimits, gg::GgLimitKind, gg::GgLimitBreach,
                gg::GgHealingStrategy, gg::GgNotAProgram, gg::GgCandidateShape,
                gg::GgResponseHealing, gg::GgHealingSummary,
                gg::GgSlotCost, gg::GgSessionSummary,
                gg::GgTelemetryKind, gg::GgTelemetryEvent,
                gg::GgReplayEntryKindV1, gg::GgReplayEntryV1, gg::GgReplayRecordV1,
                gg::GgReplayToolStep, gg::GgReplayStep,
                bapi::GgConfig, bapi::GgConfigInput,
            ],
        },
        // The gg replay record, format v2: the content-addressed input log a recorded
        // session is reconstructed from. Its own module rather than more of `gg.ts`
        // because it is a self-contained document with its own pools, provenance table
        // and entry vocabulary, and because the console loads it only on the Replay tab.
        // `GgCapabilitySet`, `GgAgentStatus`, `GgLimitBreach` and `GgContextSource` are
        // owned by `gg.ts`, so those imports resolve cross-module.
        TsModule {
            file: "gg-replay.ts",
            decls: ts_decls![&cfg;
                ggr::GgReplayRecorder, ggr::GgReplayFidelity,
                ggr::GgReplayModalities, ggr::GgReplaySeedFile,
                ggr::GgReplaySeed,
                ggr::GgReplayMessage, ggr::GgReplayToolset, ggr::GgReplayBlob,
                ggr::GgReplayTextClip,
                ggr::GgReplayAgentOrigin, ggr::GgReplayAgent,
                ggr::GgClientRole, ggr::GgReplayRequestShape, ggr::GgTurnFingerprint,
                ggr::GgFingerprintComponent, ggr::GgReplayRequest,
                ggr::GgReplayModelErrorKind, ggr::GgReplayModelError,
                ggr::GgShellCwd, ggr::GgShellOrigin, ggr::GgReplayCommand,
                ggr::GgReplayToolCall, ggr::GgReplayToolOutcome,
                ggr::GgReplayPromptSlot, ggr::GgReplayRetention, ggr::GgReplayFileRegion,
                ggr::GgReplayPromptItem,
                ggr::GgReplayEntryKind, ggr::GgReplayEntry,
                ggr::GgReplayTruncationReason, ggr::GgReplayTruncation,
                ggr::GgReplayRecord,
            ],
        },
        // The gg analysis query language (TCQ): the flat run document every query runs
        // over, the compiled query the client sends, the results it produces, and the
        // field catalog the editor's completer and sidebar read. The parser/compiler
        // are TypeScript-only by design, so this module is what they compile *to*; the
        // evaluator is mirrored against these same shapes. The batch envelope is the
        // backend's own (a dashboard answers all its panels from one index read); the
        // public static site evaluates locally and has no use for it.
        //
        // The saved **views** (`/gg/saved-queries`, `/gg/dashboards`) live here too:
        // they are per-account objects over a corpus that is not, and each one stores
        // query *source text* rather than a compiled query — so they belong beside the
        // language they are written in, not beside the run they describe.
        TsModule {
            file: "gg-query.ts",
            decls: ts_decls![&cfg;
                ggq::GgValue, ggq::GgRunDoc,
                ggq::GgCompareOp, ggq::GgFilter,
                ggq::GgAggFunc, ggq::GgAgg,
                ggq::GgIntervalUnit, ggq::GgInterval, ggq::GgGroupKey,
                ggq::GgStatsStage, ggq::GgSortKey, ggq::GgQuery,
                ggq::GgDistribution, ggq::GgAggValue, ggq::GgBucketKeyPart, ggq::GgBucket,
                ggq::GgAggColumn, ggq::GgQueryResponse,
                ggq::GgFieldKind, ggq::GgFieldValueCount, ggq::GgFieldInfo, ggq::GgFieldCatalog,
                bapi::GgQueryBatch, bapi::GgQueryBatchResponse,
                bapi::GgSavedQuery, bapi::GgSavedQueryInput,
                bapi::GgDashboardPanel, bapi::GgDashboard, bapi::GgDashboardInput,
            ],
        },
        // The code-analysis contract: the deterministic, execute-nothing static read of
        // the code a run's model wrote. Two tiers in one module, because they are one
        // pass and the document embeds the summary: `CodeAnalysisSummary` is the bounded
        // block that rides on the run record (so `index.ts` imports it from here), and
        // `CodeAnalysisDocument` is the unbounded per-run artifact the Code tab loads.
        //
        // Its own module rather than more of `index.ts` for the reason the replay record
        // has one: the document is a self-contained artifact fetched on one tab, and
        // nothing that merely lists runs should pay for its types.
        TsModule {
            file: "code-analysis.ts",
            decls: ts_decls![&cfg;
                code::CodeAuthoredBasis, code::CodeTreeBasis, code::CodeLanguage,
                code::CodeTruncationCap,
                code::CodeSizeSummary, code::CodeComplexitySummary, code::CodeGraphSummary,
                code::CodeApiSummary, code::CodeTypeScriptSummary, code::CodeRustSummary,
                code::CodeTestSummary, code::CodeDuplicationSummary, code::CodeAnalysisNotes,
                code::CodeAnalysisSummary,
                code::CodeFileEntry, code::CodeSymbolEntry, code::CodeImportEdge,
                code::CodeCloneInstance, code::CodeCloneGroup, code::CodeAnalysisDocument,
            ],
        },
        // The `code.*` display catalog: the label, unit, family, polarity and — the
        // reason it crosses the contract boundary at all — the `approximate` flag for
        // every leaf of the code-analysis summary.
        //
        // Its own module because it is the one contract artifact that ships *data* and
        // not only types: the table itself is appended below, generated from the Rust
        // `CODE_METRICS` static, so the Code tab's headers, the CLI's report and the
        // docs page cannot disagree about whether a figure rests on approximation. A
        // hand-kept TypeScript copy is exactly the drift the flag exists to prevent.
        TsModule {
            file: CODE_METRICS_MODULE,
            decls: ts_decls![&cfg; code::CodeMetricUnit, code::CodeMetricDef],
        },
        // The harness-comparison (A/B) contract: the stored config (controls and the
        // per-arm configurations) and the computed read model (per-arm distributions,
        // automated-only score, diagnostics, confounds). The descriptive statistics
        // (`MetricSummary`, `PassRate`) are shared leaves the arm results embed.
        TsModule {
            file: "comparison.ts",
            decls: ts_decls![&cfg;
                cstats::MetricSummary, cstats::PassRate,
                cmp::ScorePoint, cmp::ArmScore, cmp::ArmDiagnostics,
                cmp::Confound, cmp::ComparisonControls, cmp::ComparisonArm, cmp::ComparisonConfig,
                cmp::ComparisonArmResult, cmp::Comparison,
                bapi::ComparisonInput,
            ],
        },
        // The auth surface: accounts and the register/login request + token
        // response.
        TsModule {
            file: "account.ts",
            decls: ts_decls![&cfg;
                acct::Account, acct::RegisterRequest, acct::LoginRequest, acct::AuthnResponse,
            ],
        },
        // The published snapshot documents (the static gallery's data): the index,
        // the runs index + summary cards, the per-run document, and case metadata.
        TsModule {
            file: "snapshot.ts",
            decls: ts_decls![&cfg;
                snap::SnapshotIndex, snap::SubjectOut, snap::LinksOut, snap::RunSummary,
                snap::RunScoreOut, snap::PerformanceSummaryOut, snap::RunsIndex, snap::RunProofOut,
                snap::RunAssetOut, snap::RunValidationMediaOut, snap::PerRun,
                tc::ReferenceKind, tc::SpecKind, tc::ErratumSeverity,
                snap::CaseCheckOut, snap::CaseDomainOut,
                snap::CaseErratumOut, snap::CaseReviewItemOut, snap::CaseSubReviewItemOut,
                snap::CaseReferenceOut,
                snap::CaseValidationBaselineOut, snap::CaseSeededInputOut,
                snap::CasePackageOut, snap::CaseReferenceSheetOut, snap::CaseVariantOut,
                snap::CaseMetadata,
                snap::ModelCatalogFile,
                snap::ComparisonsIndex, snap::ComparisonFile,
            ],
        },
        // The backend HTTP API response envelopes (error + catalog/versions).
        TsModule {
            file: "backend-api.ts",
            decls: ts_decls![&cfg;
                berr::ErrorBody, berr::ErrorEnvelope, bapi::CatalogCase, bapi::CatalogResponse,
                bapi::VersionsResponse,
                bapi::ModelCatalogResponse, bapi::AliasOut, bapi::ModelOut, bapi::ModelPricesOut,
                bapi::PriceObservationOut, bapi::AliasInput, bapi::ModelConfigInput,
                bapi::ModelSeedOut, bapi::ModelListingOut, bapi::LogoFetchInput,
                bapi::LogoFetchOut,
            ],
        },
        // The backend's run-queue control plane (the `/jobs` namespace) — what
        // replaced the worker's run API. The console enqueues a run, observes it
        // via the live stream / status / active list, and is alerted on completion
        // over the notification feed. The shared launch/claim/status shapes live in
        // `core::job_api`; the server outputs and the relay's summary/notification
        // shapes live in `backend`. `ClientConfig` is the console's `GET /config`
        // body (today just the artifact-service base URL).
        TsModule {
            file: "jobs-api.ts",
            decls: ts_decls![&cfg;
                bapi::DriverState, bapi::LaunchBody, bapi::GgRunRequest, bapi::ClaimedJob,
                bapi::StatusUpdate,
                bapi::JobState, relay::JobSummary, bapi::ActiveJobOut, bapi::JobStatusOut,
                bapi::LaunchAck, bapi::LaunchBatchBody, bapi::LaunchBatchItem, bapi::LaunchBatchAck,
                relay::NotificationOutcome, relay::NotificationKind, relay::Notification,
                bapi::ClientConfig,
            ],
        },
        // The reviewer coverage surface (console-only): reusable groups, multiple
        // declarative plans (`/coverage-groups`, `/coverage-plans`), and the coverage
        // matrix a plan expands into (`GET /coverage-plans/{id}/coverage`). The
        // combination and cell types reference `HarnessSlug`, owned by the run-record
        // document.
        TsModule {
            file: "coverage.ts",
            decls: ts_decls![&cfg;
                bapi::ReviewPlanCase, bapi::ReviewPlanCombo,
                bapi::CoverageGroupKind, bapi::CoverageGroup, bapi::CoverageGroupInput,
                bapi::CoveragePlan, bapi::CoveragePlanInput, bapi::CoveragePlanSummary,
                bapi::CoverageCell, bapi::CoverageMatrix,
            ],
        },
    ];
    for (file, mut content) in finalize_ts(modules, TS_HEADER) {
        // The one module that carries a value as well as its types. `ts_rs` renders
        // types, not data, so the catalog is serialized here and appended to the module
        // that declares its element type — which is why the file name is a constant
        // rather than a literal in two places.
        if file == CODE_METRICS_MODULE {
            content.push_str(&code_metrics_catalog()?);
        }
        write_ts(&root, file, &content)?;
    }

    // --- JSON Schema documents ---------------------------------------------
    let schemas = finalize_schemas(vec![
        // Core: the run-record document (canonical home of the whole tree) and the
        // persisted tournament document.
        SchemaDoc {
            rel_path: "core/run-record.schema.json",
            root: Some("RunRecord"),
            owns: RUN_RECORD_DEFS,
            schema: root_schema::<rr::RunRecord>(),
        },
        SchemaDoc {
            rel_path: "core/tournament.schema.json",
            root: Some("TournamentRecord"),
            owns: TOURNAMENT_DEFS,
            schema: root_schema::<mp::TournamentRecord>(),
        },
        // The gg harness contract. The capability set is self-contained (its
        // subtypes are its own). The telemetry event's `Usage` variant references the
        // shared `TokenMetrics`/`CostMetrics` owned by the run-record document, so
        // those refs are rewritten to cross-document URLs.
        // The run's execution ceilings (`GgRunLimits`) are owned here rather than by the
        // session summary, because the capability set is where they are *configured*; the
        // summary's record of the ceilings actually in force references them across
        // documents.
        SchemaDoc {
            rel_path: "gg/capability-set.schema.json",
            root: Some("GgCapabilitySet"),
            owns: &[
                "GgAgentConfig",
                "GgSubagentRef",
                "GgSubagentScope",
                "GgPromptCacheTtl",
                "GgCapabilityConfig",
                "GgModelSlot",
                "GgRunLimits",
            ],
            schema: root_schema::<gg::GgCapabilitySet>(),
        },
        // The gg session summary: the aggregatable per-run outcome. Referenced by both the
        // telemetry event (its `SessionSummary` variant) and the run-record document (via
        // `RunSubject.gg_summary`), so — like the capability set — it gets its own document
        // and both references become cross-document `$ref`s. Its per-slot cost rollup
        // (`GgSlotCost`) reuses the shared `TokenMetrics`/`CostMetrics` owned by the
        // run-record document, which are rewritten to cross-document URLs. The breach it
        // records (`GgLimitBreach`/`GgLimitKind`) is owned here — the summary is where a
        // breach is durably recorded, and the telemetry event that announces one references
        // it cross-document.
        SchemaDoc {
            rel_path: "gg/session-summary.schema.json",
            root: Some("GgSessionSummary"),
            owns: &[
                "GgSlotCost",
                "GgHealingSummary",
                "GgLimitBreach",
                "GgLimitKind",
            ],
            schema: root_schema::<gg::GgSessionSummary>(),
        },
        SchemaDoc {
            rel_path: "gg/telemetry-event.schema.json",
            root: Some("GgTelemetryEvent"),
            owns: &[
                "GgTelemetryKind",
                "GgContextSource",
                "GgContextSourceUsage",
                "GgPromptRef",
                "GgLoggedToolCall",
                "GgLoggedImage",
                "GgSkillState",
                "GgMemoryCaps",
                "GgMemoryEntry",
                "GgMemoryChange",
                "GgMemoryPeak",
                "GgTaskStatus",
                "GgTaskEntry",
                "GgIssueStatus",
                "GgBoardEpic",
                "GgBoardIssue",
                "GgRetainedState",
                "GgContextAction",
                "GgWorkflowPhase",
                "GgAgentTransitionKind",
                // The module model's vocabulary. These are *also* the documented shape of a
                // capability's `ownership`/`scope` params and of an FSM transition's transfer
                // list — but a params key is free-form JSON in the schema, so the telemetry
                // event is the one schema root that genuinely references them (through
                // `AgentModules` and the reshaped `AgentTransition`), which makes this
                // document their canonical home.
                "GgModuleKind",
                "GgModuleOwnership",
                "GgModuleOrigin",
                "GgMemoryScope",
                "GgAgentModule",
                "GgModuleDisposition",
                "GgTransitionModule",
                "GgArchiveEntry",
                "GgIssueReviewPhase",
                "GgReviewer",
                "GgSpeculationPhase",
                // The per-turn healing record and its vocabulary ride on the
                // `CodeExecution` event and appear nowhere else in the contract, so this
                // document is their canonical home. The run-level rollup
                // (`GgHealingSummary`) is the session summary's, and is referenced from
                // there.
                "GgResponseHealing",
                "GgHealingStrategy",
                "GgNotAProgram",
                "GgCandidateShape",
            ],
            schema: root_schema::<gg::GgTelemetryEvent>(),
        },
        // The gg replay record, format v2: the seed, the four content-addressed pools,
        // the agent provenance table and the ordered input log. Its `capabilitySet`
        // references `GgCapabilitySet`, and its agent rows reference `GgAgentStatus` /
        // `GgLimitBreach`, all owned by the gg documents above, so those refs are
        // rewritten to cross-document URLs; the pooled message/toolset/response bodies
        // are free-form JSON (the gg binary owns their concrete shapes).
        SchemaDoc {
            rel_path: "gg/replay-record.schema.json",
            root: Some("GgReplayRecord"),
            owns: &[
                "GgReplayRecorder",
                "GgReplayFidelity",
                "GgReplaySeed",
                "GgReplayModalities",
                "GgReplaySeedFile",
                "GgReplayMessage",
                "GgReplayToolset",
                "GgReplayBlob",
                "GgReplayTextClip",
                "GgReplayAgent",
                "GgReplayAgentOrigin",
                "GgReplayRequest",
                "GgClientRole",
                "GgReplayRequestShape",
                "GgTurnFingerprint",
                // `GgFingerprintComponent` is deliberately absent: it is the *result* of
                // comparing two fingerprints, not a member of the document, so claiming
                // it here would register an owner for a `$def` that is never emitted.
                "GgReplayEntry",
                "GgReplayEntryKind",
                "GgReplayModelError",
                "GgReplayModelErrorKind",
                "GgReplayToolCall",
                "GgReplayToolOutcome",
                "GgShellCwd",
                "GgShellOrigin",
                "GgReplayCommand",
                "GgReplayPromptItem",
                "GgReplayPromptSlot",
                "GgReplayRetention",
                "GgReplayFileRegion",
                "GgReplayTruncation",
                "GgReplayTruncationReason",
            ],
            schema: root_schema::<ggr::GgReplayRecord>(),
        },
        // The superseded format v1 record: the flat transcript every record captured
        // before v2 is in. Kept published because those records are stored as opaque
        // bytes and are still served verbatim; the v2 reader upgrades them on read.
        SchemaDoc {
            rel_path: "gg/replay-record-v1.schema.json",
            root: Some("GgReplayRecordV1"),
            owns: &["GgReplayEntryV1", "GgReplayEntryKindV1"],
            schema: root_schema::<gg::GgReplayRecordV1>(),
        },
        // The code-analysis document: the unbounded per-run artifact
        // (`{run}/code-analysis.json.gz`, served at `GET /runs/{id}/code-analysis`).
        // Rooted at the document rather than at the summary because the document embeds
        // the summary, so one schema owns the whole vocabulary and the run-record
        // document's reference to `CodeAnalysisSummary` becomes a cross-document `$ref`.
        SchemaDoc {
            rel_path: "core/code-analysis.schema.json",
            root: Some("CodeAnalysisDocument"),
            owns: CODE_ANALYSIS_DEFS,
            schema: root_schema::<code::CodeAnalysisDocument>(),
        },
        // The gg replay step-through view: the per-agent, per-turn "what the agent saw
        // and did" data model a debugging UI renders, derived from the record above. Its
        // step/tool payloads are free-form JSON (the gg binary owns their concrete shapes),
        // so it references nothing cross-document.
        SchemaDoc {
            rel_path: "gg/replay-steps.schema.json",
            root: Some("GgReplayStep"),
            owns: &["GgReplayToolStep"],
            schema: root_schema::<gg::GgReplayStep>(),
        },
        // The compiled TCQ query — the single wire form of a gg analysis query. It owns
        // the whole language vocabulary (the filter tree, the aggregation functions,
        // the histogram intervals), which the response and document below
        // cross-reference.
        SchemaDoc {
            rel_path: "gg/query.schema.json",
            root: Some("GgQuery"),
            owns: &[
                "GgValue",
                "GgCompareOp",
                "GgFilter",
                "GgAggFunc",
                "GgAgg",
                "GgIntervalUnit",
                "GgInterval",
                "GgGroupKey",
                "GgStatsStage",
                "GgSortKey",
            ],
            schema: root_schema::<ggq::GgQuery>(),
        },
        // A gg run as the query language sees it: one flat map of dotted field names to
        // scalars. Its own document because it is what the public static site ships as
        // a snapshot artifact and evaluates in the browser, independent of any query.
        SchemaDoc {
            rel_path: "gg/run-document.schema.json",
            root: Some("GgRunDoc"),
            owns: &[],
            schema: root_schema::<ggq::GgRunDoc>(),
        },
        // The result of a TCQ query: the matching documents or the aggregated buckets.
        // `GgValue`, `GgAggFunc` and `GgRunDoc` are owned by the two documents above,
        // so those refs become cross-document URLs.
        SchemaDoc {
            rel_path: "gg/query-response.schema.json",
            root: Some("GgQueryResponse"),
            owns: &[
                "GgDistribution",
                "GgAggValue",
                "GgBucketKeyPart",
                "GgBucket",
                "GgAggColumn",
            ],
            schema: root_schema::<ggq::GgQueryResponse>(),
        },
        // The field catalog: every field observed across the corpus, with its kind,
        // document count and top values — the completer's and the field sidebar's
        // source, and the second mirrored function.
        SchemaDoc {
            rel_path: "gg/field-catalog.schema.json",
            root: Some("GgFieldCatalog"),
            owns: &["GgFieldInfo", "GgFieldKind", "GgFieldValueCount"],
            schema: root_schema::<ggq::GgFieldCatalog>(),
        },
        // `POST /gg/query/batch` — a dashboard's panels answered from one index read.
        // Both envelopes are pure wrappers around the query and response documents
        // above, so every ref in them is cross-document.
        anon(
            "gg/query-batch-request.schema.json",
            root_schema::<bapi::GgQueryBatch>(),
        ),
        anon(
            "gg/query-batch-response.schema.json",
            root_schema::<bapi::GgQueryBatchResponse>(),
        ),
        // The operator's saved **views** over the corpus (`/gg/saved-queries`,
        // `/gg/dashboards`) — per-account objects over a population that is not, which is
        // the whole saved-object model. Documented beside the language they are written
        // in rather than beside the run they describe, because what they store is query
        // *source text*: neither schema references a run-record type at all. The
        // dashboard owns its panel type, so that ref stays inline.
        anon(
            "gg/saved-query.schema.json",
            root_schema::<bapi::GgSavedQuery>(),
        ),
        SchemaDoc {
            rel_path: "gg/dashboard.schema.json",
            root: Some("GgDashboard"),
            owns: &["GgDashboardPanel"],
            schema: root_schema::<bapi::GgDashboard>(),
        },
        // The backend's run-queue (`/jobs`) control plane. These reference the core
        // run-record document by URL (the launch request, the claimed job, and the
        // driver's status update all carry or echo a `RunRecord`); any type local to
        // a single document (its own ack/summary) stays inline.
        anon(
            "jobs-api/launch-run-request.schema.json",
            root_schema::<bapi::LaunchBody>(),
        ),
        // The gg run mode's enqueue request. Its `capabilitySet` is the core-owned
        // `GgCapabilitySet` (owned by `gg/capability-set.schema.json`), so that ref is
        // rewritten to a cross-document URL.
        anon(
            "jobs-api/gg-run-request.schema.json",
            root_schema::<bapi::GgRunRequest>(),
        ),
        anon(
            "jobs-api/launch-run-ack.schema.json",
            root_schema::<bapi::LaunchAck>(),
        ),
        anon(
            "jobs-api/launch-batch-request.schema.json",
            root_schema::<bapi::LaunchBatchBody>(),
        ),
        anon(
            "jobs-api/launch-batch-ack.schema.json",
            root_schema::<bapi::LaunchBatchAck>(),
        ),
        anon(
            "jobs-api/claimed-job.schema.json",
            root_schema::<bapi::ClaimedJob>(),
        ),
        anon(
            "jobs-api/status-update.schema.json",
            root_schema::<bapi::StatusUpdate>(),
        ),
        anon(
            "jobs-api/active-jobs.schema.json",
            root_schema::<Vec<bapi::ActiveJobOut>>(),
        ),
        anon(
            "jobs-api/job-status.schema.json",
            root_schema::<bapi::JobStatusOut>(),
        ),
        anon(
            "jobs-api/notification.schema.json",
            root_schema::<relay::Notification>(),
        ),
        anon(
            "jobs-api/client-config.schema.json",
            root_schema::<bapi::ClientConfig>(),
        ),
        // The reviewer coverage surface: a plan, a reusable group, and the coverage
        // matrix a plan expands into. All reference `HarnessSlug`, owned by the
        // run-record document, so that ref is rewritten to a cross-document URL.
        anon(
            "coverage/coverage-plan.schema.json",
            root_schema::<bapi::CoveragePlan>(),
        ),
        anon(
            "coverage/coverage-group.schema.json",
            root_schema::<bapi::CoverageGroup>(),
        ),
        anon(
            "coverage/coverage-matrix.schema.json",
            root_schema::<bapi::CoverageMatrix>(),
        ),
        // Backend API: the auth surface (the token response is the canonical home
        // of Account) and the canonical review document (the home of the review
        // value types the backend + snapshot reference).
        SchemaDoc {
            rel_path: "backend-api/auth.schema.json",
            root: Some("AuthResult"),
            owns: &["Account"],
            schema: root_schema::<acct::AuthnResponse>(),
        },
        anon(
            "backend-api/auth-register-request.schema.json",
            root_schema::<acct::RegisterRequest>(),
        ),
        anon(
            "backend-api/auth-login-request.schema.json",
            root_schema::<acct::LoginRequest>(),
        ),
        anon(
            "backend-api/error.schema.json",
            root_schema::<berr::ErrorEnvelope>(),
        ),
        anon(
            "backend-api/test-case-catalog.schema.json",
            root_schema::<bapi::CatalogResponse>(),
        ),
        anon(
            "backend-api/test-case-versions.schema.json",
            root_schema::<bapi::VersionsResponse>(),
        ),
        // The fully-resolved definition of one test-case version (`GET
        // /test-cases/{slug}/{version}`). Self-contained except for the core
        // run-record types it shares (`TestType`, `MediaKind`, `AssetSheet`),
        // which are rewritten to cross-document `$ref`s at the run-record URL.
        anon(
            "backend-api/resolved-test-case-version.schema.json",
            root_schema::<bapi::VersionResponse>(),
        ),
        SchemaDoc {
            rel_path: "backend-api/review.schema.json",
            root: Some("Review"),
            owns: REVIEW_DEFS,
            schema: root_schema::<snap::Review>(),
        },
        // Snapshot documents (the static gallery's published data). Each references
        // the core run-record and review documents by URL; its own summary/envelope
        // subtypes stay inline.
        anon(
            "snapshot/index.schema.json",
            root_schema::<snap::SnapshotIndex>(),
        ),
        anon(
            "snapshot/runs.schema.json",
            root_schema::<snap::RunsIndex>(),
        ),
        anon("snapshot/run.schema.json", root_schema::<snap::PerRun>()),
        anon(
            "snapshot/case.schema.json",
            root_schema::<snap::CaseMetadata>(),
        ),
    ])?;
    for (rel_path, value) in schemas {
        write_schema(&root, rel_path, &value)?;
    }

    Ok(())
}

/// A schema document with an anonymous root (an array, or an envelope no other
/// document references): no owned `$defs`, so its local subtypes stay inline and
/// only shared types (the run-record tree) become cross-document `$ref`s.
fn anon(rel_path: &'static str, schema: serde_json::Value) -> SchemaDoc {
    SchemaDoc {
        rel_path,
        root: None,
        owns: &[],
        schema,
    }
}

/// Write a generated TypeScript module under `packages/run-record/src/`.
fn write_ts(root: &Path, file: &str, content: &str) -> Result<()> {
    let path = root.join("packages/run-record/src").join(file);
    fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// Write a JSON Schema document under `apps/docs/public/schema/`.
fn write_schema(root: &Path, rel_path: &str, value: &serde_json::Value) -> Result<()> {
    let path = root.join("apps/docs/public/schema").join(rel_path);
    let mut json = serde_json::to_string_pretty(value)?;
    json.push('\n');
    fs::write(&path, json).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// The workspace root, resolved from this crate's compile-time manifest dir
/// (`crates/contract-codegen` → the workspace root two levels up), so the
/// generator writes to the right paths regardless of the invocation's cwd.
fn workspace_root() -> Result<PathBuf> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .ancestors()
        .nth(2)
        .map(Path::to_path_buf)
        .context("resolving the workspace root from CARGO_MANIFEST_DIR")
}
