//! `contract-codegen` — the single generator for the Test Cabinet data contract.
//!
//! It emits **both** the TypeScript bindings (`packages/run-record/src/*.ts`, via
//! [`ts_rs`]) and the JSON Schemas (`apps/docs/public/schema/**`, via [`schemars`])
//! from one set of Rust types — the types in `crates/core`, `crates/worker`, and
//! `crates/backend` that derive `TS` + `JsonSchema` behind their `contract`
//! feature. Because both artifacts come from the same source in one pass, the TS
//! bindings and the JSON Schemas can never drift from each other or from Rust.
//!
//! Run it with `cargo run -p contract-codegen` (or `npm run gen:contract`, which
//! also normalizes the output with Prettier). A CI check regenerates and fails on
//! any diff, so the committed artifacts always match the Rust source.

mod emit;

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use emit::{SchemaDoc, TsModule, finalize_schemas, finalize_ts, root_schema, ts_config, ts_decl};

use test_cabinet_core::{
    accounts as acct, match_play as mp, metrics as m, review as rv, run_record as rr,
    test_case as tc, validation as val,
};
use test_cabinet_backend::{api as bapi, error as berr, snapshot as snap};
use test_cabinet_worker::{api as wapi, jobs as wjobs, notify as wnotify};

/// Collect the [`emit::TsDecl`]s for the listed types, in declaration order.
macro_rules! ts_decls {
    ($cfg:expr; $($t:ty),+ $(,)?) => {
        vec![ $( ts_decl::<$t>($cfg) ),+ ]
    };
}

/// The header stamped on every generated TypeScript module.
const TS_HEADER: &str = "\
// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` (and `crates/worker` / `crates/backend`), which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.\n\n";

/// The run-record schema's `$defs`: every type in the `RunRecord` tree except the
/// root. Names are the published (TS-facing) names, so renamed Rust types appear
/// here under their contract name (`TokenMetrics`, `RunValidation`, `AssetSheet`).
const RUN_RECORD_DEFS: &[&str] = &[
    "RunSubject",
    "RunTooling",
    "RunEnvironment",
    "RunMetrics",
    "TokenMetrics",
    "CostMetrics",
    "RunValidation",
    "RunLinks",
    "RunStatus",
    "HarnessSlug",
    "RunState",
    "AuthMode",
    "TestType",
    "MediaKind",
    "StepResult",
    "CheckResult",
    "ProofResult",
    "AssetGenResult",
    "AssetFrameResult",
    "AssetSheet",
    "AssetSheetSequence",
    "AdversarialResult",
    "AdversarialReplay",
    "AdversarialTeam",
    "AdversarialOutcome",
    "PerformanceResult",
    "PerformanceCaseResult",
];

/// The tournament schema's `$defs`. `AdversarialOutcome` is *not* listed: it is
/// owned by the run-record schema, so a reference to it is rewritten to a
/// cross-document `$ref` at that schema's URL.
const TOURNAMENT_DEFS: &[&str] = &["MatchSummary", "Standing", "ControllerRef", "ControllerKind"];

/// The review schema's `$defs`: the canonical home of the review value types, so
/// the worker (review submission), backend, and snapshot documents all reference
/// them here rather than each carrying a copy.
const REVIEW_DEFS: &[&str] = &["Rating", "VerdictStatus", "ReviewVerdict", "DomainRating"];

fn main() -> Result<()> {
    let root = workspace_root()?;
    let cfg = ts_config();

    // --- TypeScript modules ------------------------------------------------
    let modules = vec![
        // The run-record + arena contract. Ordered to mirror the run-record
        // document: identity, metrics, validation results, arena, the record.
        TsModule {
            file: "index.ts",
            decls: ts_decls![&cfg;
                rr::HarnessSlug, rr::RunState, rr::AuthMode, rr::RunEnvironment, rr::RunTooling,
                tc::TestType, rr::RunSubject, m::TokenCounts, m::Cost, m::RunMetrics,
                tc::MediaKind, val::ProofResult, val::CheckResult, val::StepResult,
                val::AssetGenResult, val::AssetFrameResult, tc::SheetSpec, tc::SheetSequence,
                val::AdversarialTeam, val::AdversarialOutcome, val::AdversarialReplay,
                val::AdversarialResult, val::PerformanceCaseResult, val::PerformanceResult,
                mp::ControllerKind, mp::ControllerRef, mp::MatchSummary, mp::Standing,
                mp::TournamentRecord, val::ValidationSummary, rr::RunLinks, rr::RunStatus,
                rr::RunRecord,
            ],
        },
        // The review value types (shared by the worker, backend, and snapshot
        // contracts) plus the published `Review` wire shape. The scoring and
        // aggregation logic stays hand-written in the UI.
        TsModule {
            file: "review.ts",
            decls: ts_decls![&cfg;
                rv::Rating, rv::VerdictStatus, rv::ReviewVerdict, rv::DomainRating, snap::Review,
            ],
        },
        // The auth surface: accounts and the register/login request + token
        // response.
        TsModule {
            file: "account.ts",
            decls: ts_decls![&cfg;
                acct::Account, acct::RegisterRequest, acct::LoginRequest, acct::AuthnResponse,
            ],
        },
        // The published snapshot documents (the static gallery's data): the index,
        // the runs index + summary cards, the per-run document, and case metadata.
        TsModule {
            file: "snapshot.ts",
            decls: ts_decls![&cfg;
                snap::SnapshotIndex, snap::SubjectOut, snap::LinksOut, snap::RunSummary,
                snap::RunsIndex, snap::RunProofOut, snap::RunAssetOut, snap::PerRun,
                tc::ReferenceKind, snap::CaseCheckOut, snap::CaseDomainOut,
                snap::CaseReviewItemOut, snap::CaseReferenceOut, snap::CaseVariantOut,
                snap::CaseMetadata,
            ],
        },
        // The backend HTTP API response envelopes (error + catalog/versions).
        TsModule {
            file: "backend-api.ts",
            decls: ts_decls![&cfg;
                berr::ErrorBody, berr::ErrorEnvelope, bapi::CatalogCase, bapi::CatalogResponse,
                bapi::VersionsResponse,
            ],
        },
        // The worker HTTP API: job lifecycle, notifications, and the
        // push/review/publish request/response envelopes.
        TsModule {
            file: "worker-api.ts",
            decls: ts_decls![&cfg;
                wjobs::JobState, wjobs::ActiveRunState, wjobs::RunSummary, wjobs::ActiveRun,
                wjobs::JobStatus, wnotify::NotificationOutcome, wnotify::NotificationKind,
                wnotify::WorkerNotification, wapi::SubmitBody, wapi::SubmitAck, wapi::ProducedRun,
                wapi::PushBody, wapi::PushAck, wapi::ReviewBody, wapi::ReviewAck, wapi::PublishBody,
                wapi::PublishAck, wapi::HealthStatus, wapi::WorkerRole, wapi::HealthResponse,
            ],
        },
    ];
    for (file, content) in finalize_ts(modules, TS_HEADER) {
        write_ts(&root, file, &content)?;
    }

    // --- JSON Schema documents ---------------------------------------------
    let schemas = finalize_schemas(vec![
        // Core: the run-record document (canonical home of the whole tree) and the
        // persisted tournament document.
        SchemaDoc {
            rel_path: "core/run-record.schema.json",
            root: Some("RunRecord"),
            owns: RUN_RECORD_DEFS,
            schema: root_schema::<rr::RunRecord>(),
        },
        SchemaDoc {
            rel_path: "core/tournament.schema.json",
            root: Some("TournamentRecord"),
            owns: TOURNAMENT_DEFS,
            schema: root_schema::<mp::TournamentRecord>(),
        },
        // Worker HTTP API. These reference the core run-record document by URL; any
        // type local to a single document (its own envelope/summary) stays inline.
        anon("worker-api/submit-run-request.schema.json", root_schema::<wapi::SubmitBody>()),
        anon("worker-api/submit-run-ack.schema.json", root_schema::<wapi::SubmitAck>()),
        anon("worker-api/active-runs.schema.json", root_schema::<Vec<wjobs::ActiveRun>>()),
        anon("worker-api/job-status.schema.json", root_schema::<wjobs::JobStatus>()),
        anon("worker-api/notification.schema.json", root_schema::<wnotify::WorkerNotification>()),
        anon("worker-api/produced-runs.schema.json", root_schema::<Vec<wapi::ProducedRun>>()),
        anon("worker-api/health.schema.json", root_schema::<wapi::HealthResponse>()),
        anon("worker-api/push-run-request.schema.json", root_schema::<wapi::PushBody>()),
        anon("worker-api/push-run-ack.schema.json", root_schema::<wapi::PushAck>()),
        anon("worker-api/review-run-request.schema.json", root_schema::<wapi::ReviewBody>()),
        anon("worker-api/review-run-ack.schema.json", root_schema::<wapi::ReviewAck>()),
        anon("worker-api/publish-run-request.schema.json", root_schema::<wapi::PublishBody>()),
        anon("worker-api/publish-run-ack.schema.json", root_schema::<wapi::PublishAck>()),
        // Backend API: the auth surface (the token response is the canonical home
        // of Account) and the canonical review document (the home of the review
        // value types the worker + snapshot reference).
        SchemaDoc {
            rel_path: "backend-api/auth.schema.json",
            root: Some("AuthResult"),
            owns: &["Account"],
            schema: root_schema::<acct::AuthnResponse>(),
        },
        anon("backend-api/auth-register-request.schema.json", root_schema::<acct::RegisterRequest>()),
        anon("backend-api/auth-login-request.schema.json", root_schema::<acct::LoginRequest>()),
        anon("backend-api/error.schema.json", root_schema::<berr::ErrorEnvelope>()),
        anon("backend-api/test-case-catalog.schema.json", root_schema::<bapi::CatalogResponse>()),
        anon("backend-api/test-case-versions.schema.json", root_schema::<bapi::VersionsResponse>()),
        SchemaDoc {
            rel_path: "backend-api/review.schema.json",
            root: Some("Review"),
            owns: REVIEW_DEFS,
            schema: root_schema::<snap::Review>(),
        },
        // Snapshot documents (the static gallery's published data). Each references
        // the core run-record and review documents by URL; its own summary/envelope
        // subtypes stay inline.
        anon("snapshot/index.schema.json", root_schema::<snap::SnapshotIndex>()),
        anon("snapshot/runs.schema.json", root_schema::<snap::RunsIndex>()),
        anon("snapshot/run.schema.json", root_schema::<snap::PerRun>()),
        anon("snapshot/case.schema.json", root_schema::<snap::CaseMetadata>()),
    ])?;
    for (rel_path, value) in schemas {
        write_schema(&root, rel_path, &value)?;
    }

    Ok(())
}

/// A schema document with an anonymous root (an array, or an envelope no other
/// document references): no owned `$defs`, so its local subtypes stay inline and
/// only shared types (the run-record tree) become cross-document `$ref`s.
fn anon(rel_path: &'static str, schema: serde_json::Value) -> SchemaDoc {
    SchemaDoc {
        rel_path,
        root: None,
        owns: &[],
        schema,
    }
}

/// Write a generated TypeScript module under `packages/run-record/src/`.
fn write_ts(root: &Path, file: &str, content: &str) -> Result<()> {
    let path = root.join("packages/run-record/src").join(file);
    fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// Write a JSON Schema document under `apps/docs/public/schema/`.
fn write_schema(root: &Path, rel_path: &str, value: &serde_json::Value) -> Result<()> {
    let path = root.join("apps/docs/public/schema").join(rel_path);
    let mut json = serde_json::to_string_pretty(value)?;
    json.push('\n');
    fs::write(&path, json).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// The workspace root, resolved from this crate's compile-time manifest dir
/// (`crates/contract-codegen` → the workspace root two levels up), so the
/// generator writes to the right paths regardless of the invocation's cwd.
fn workspace_root() -> Result<PathBuf> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .ancestors()
        .nth(2)
        .map(Path::to_path_buf)
        .context("resolving the workspace root from CARGO_MANIFEST_DIR")
}
