import { useAppSettings } from "../../store/appSettings";
import backdropStillNoSun from "./backdrop-still-no-sun.jpg";
import backdropStill from "./backdrop-still.jpg";
import styles from "./CssBackdrop.module.scss";

// The non-WebGL synthwave backdrop. Two layers, drawn back to front:
//
//   1. A CSS horizon glow + perspective grid — zero bytes, so it paints on the
//      very first frame as an instant placeholder.
//   2. A baked first frame of the real WebGL scene (generated by
//      apps/site/scripts/capture-backdrop.mjs) layered on top, so once it
//      decodes the fallback matches the WebGL version pixel-for-pixel, just
//      without motion. The grid shows through only until it loads.
//
// The decorative sun is a user toggle, so we keep it working here too: pick the
// with-sun or no-sun still to match `sunEnabled`, mirroring how the WebGL scene
// mounts/unmounts the sun.
//
// Used both as the instant Suspense fallback while the WebGL scene's chunk loads
// and as the permanent fallback when WebGL is unavailable or the user prefers
// reduced motion. Purely decorative; the CRT scanlines are applied over it by
// `Backdrop`.
export function CssBackdrop() {
  const sunEnabled = useAppSettings((s) => s.sunEnabled);
  const still = sunEnabled ? backdropStill : backdropStillNoSun;
  return (
    <>
      <div className={styles.glow} />
      <div className={styles.grid} />
      <img className={styles.still} src={still} alt="" aria-hidden="true" />
    </>
  );
}
