//! **The model-probe fixtures**: per-language turn-1 conversations the backend replays to check a
//! model's responses-as-code readiness, projected out of gg's own machinery.
//!
//! # Projected, never written
//!
//! This is the reference's rule ([`crate::reference`]) applied to the probe: not a word of the
//! model-facing content here is authored a second time. The system prompt is
//! [`prompts::render_system`] over the same context the loop builds, the opening turn's program is
//! the arm's own [`bootstrap_program`](crate::sandbox::ProgramLanguage::bootstrap_program), the
//! module listing is [`render_search_results`](crate::agent::code::render_search_results), every
//! documentation view is the string [`DocsRuntime::read_any`] renders, a file view's heading is
//! [`item_heading`] with its [`ShownLines`]. What this module *does* author is the probe's own
//! material:
//! the task prompts and the small spec files each task reads.
//!
//! # The two scenarios, and at least three prompts
//!
//! Each language's fixture carries one case per (scenario, prompt) pair:
//!
//! - **`baseline`** — the conversation holds an open documentation view of every function the task
//!   needs, and a ready model writes a program calling them. Two prompts: `write-plan`
//!   (`files.write_file`) and `inventory` (`files.list_dir` + `files.write_file`).
//! - **`missing-docview`** — the task needs a function whose documentation view is *not* open, and
//!   the system prompt instructs: "Open a documentation view of each function you intend to call,
//!   and write the call on a later turn." A ready model opens the view and stops; calling the
//!   undocumented function in the same program fails the case. Two prompts: `run-tests`
//!   (`shell.shell`) and `fix-typo` (`files.edit_file`).
//!
//! # Why the fixtures are committed files in the backend crate
//!
//! The backend must not link this crate (see `scripts/gg-reference.sh` for the whole argument), and
//! unlike the reference — served at run time from files an image bakes — the probe embeds its
//! request at compile time, so the projection crosses the crate boundary as **committed** JSON under
//! `crates/backend/src/probe/fixtures/`, regenerated by `scripts/gg-probe-fixtures.sh` whenever the
//! prompt, the catalogue or a case changes. Each file records that provenance inside itself.
//!
//! # The probe agent
//!
//! One fixed grant for every case: responses-as-code plus `shell`, `read-file`, `write-file`,
//! `edit-file` and `list-dir` — the surface a small build task actually reaches for — dispatched as
//! a standard worker with every documentation-view type flag on. The bootstrap's opening program
//! lists the `files` and `shell` modules and opens the base documentation views exactly as a real
//! session's does; a baseline case's target views are appended to that same program's open list.

use std::path::{Path, PathBuf};

use serde::Serialize;
use serde_json::json;
use test_cabinet_core::gg::{
    CAPABILITY_EDIT_FILE, CAPABILITY_LIST_DIR, CAPABILITY_READ_FILE, CAPABILITY_RESPONSES_AS_CODE,
    CAPABILITY_SHELL, CAPABILITY_WRITE_FILE, GgContextSource, GgOpeningTurn, GgProgramLanguage,
};

use crate::agent::{code_heading_views, ending_view, module_views};
use crate::bootstrap::{bootstrap_function, resolve_opening_turn};
use crate::completion::{SUBMIT_PROGRAM_ACK, submit_program_tool};
use crate::context::{ShownLines, item_heading};
use crate::docs::{DocQuery, DocViewTypes, DocsRuntime, MAX_SEARCH_LIMIT};
use crate::ending::EndingRole;
use crate::prompts::{self, ReadFileView, SystemContext};
use crate::sandbox::{
    DocSearchQuery, FILES_EDIT_FILE, FILES_LIST_DIR, FILES_WRITE_FILE, OperationId, SHELL_SHELL,
    VIEWS_OPEN_DOCS_VIEW, capability_operations, catalogue_functions, language, spell,
};

/// The gg capability ids the probe agent holds — the one grant every case is built under.
const PROBE_CAPABILITIES: &[&str] = &[
    CAPABILITY_RESPONSES_AS_CODE,
    CAPABILITY_SHELL,
    CAPABILITY_READ_FILE,
    CAPABILITY_WRITE_FILE,
    CAPABILITY_EDIT_FILE,
    CAPABILITY_LIST_DIR,
];

/// The deterministic id of the synthesized opening submission — the same id gg's own bootstrap
/// stamps on the program it runs on an agent's behalf.
const BOOTSTRAP_CALL_ID: &str = "bootstrap-program";

/// The deterministic id of the synthesized file-opening submission — the same id the
/// autoload-specifications seeding stamps on its program.
const AUTOLOAD_CALL_ID: &str = "autoload-program";

/// The `baseline` scenario id, as the backend and the console spell it.
const SCENARIO_BASELINE: &str = "baseline";

/// The `missing-docview` scenario id.
const SCENARIO_MISSING_DOCVIEW: &str = "missing-docview";

/// One probe case's authored material and expectations, shared by every language: the scenario, the
/// task prompt, the spec file the task reads, which operations' documentation the conversation
/// opens beyond the bootstrap's base set, and what the submitted program is checked for.
struct CaseSpec {
    scenario: &'static str,
    /// The input prompt's stable id — the axis the probe's samples apply per.
    prompt: &'static str,
    /// The task text, under the `Task` heading.
    task: &'static str,
    /// The operations whose documentation views the opening program additionally opens.
    docs: &'static [OperationId],
    /// The operations a passing program must call.
    required: &'static [OperationId],
    /// The operation a passing program must open the documentation of and *not* call.
    target: Option<OperationId>,
    /// The one spec file seeded into the conversation as a file view.
    spec_path: &'static str,
    spec_text: &'static str,
}

const WRITE_PLAN_SPEC: &str = include_str!("probe_fixtures/plan-brief.md");
const INVENTORY_SPEC: &str = include_str!("probe_fixtures/inventory-brief.md");
const RUN_TESTS_SPEC: &str = include_str!("probe_fixtures/test-brief.md");
const FIX_TYPO_SPEC: &str = include_str!("probe_fixtures/errata.md");

/// Every case, in the order the fixture lists them: the two baseline prompts, then the two
/// missing-docview prompts — four input prompts across the two scenarios.
const CASES: &[CaseSpec] = &[
    CaseSpec {
        scenario: SCENARIO_BASELINE,
        prompt: "write-plan",
        task: "Create the file `notes/plan.md` in the workspace. Its required content is \
               specified in `specs/plan-brief.md`, which is already open in your context. Write \
               the file exactly as the brief specifies.",
        docs: &[FILES_WRITE_FILE],
        required: &[FILES_WRITE_FILE],
        target: None,
        spec_path: "specs/plan-brief.md",
        spec_text: WRITE_PLAN_SPEC,
    },
    CaseSpec {
        scenario: SCENARIO_BASELINE,
        prompt: "inventory",
        task: "Produce an inventory of the workspace root: list the entries of the workspace's \
               top-level directory, then write the inventory file described in \
               `specs/inventory-brief.md`, which is already open in your context.",
        docs: &[FILES_LIST_DIR, FILES_WRITE_FILE],
        required: &[FILES_LIST_DIR, FILES_WRITE_FILE],
        target: None,
        spec_path: "specs/inventory-brief.md",
        spec_text: INVENTORY_SPEC,
    },
    CaseSpec {
        scenario: SCENARIO_MISSING_DOCVIEW,
        prompt: "run-tests",
        task: "Run the project's test suite and show yourself the output. \
               `specs/test-brief.md`, already open in your context, says what the suite is and \
               what to check for.",
        docs: &[],
        required: &[],
        target: Some(SHELL_SHELL),
        spec_path: "specs/test-brief.md",
        spec_text: RUN_TESTS_SPEC,
    },
    CaseSpec {
        scenario: SCENARIO_MISSING_DOCVIEW,
        prompt: "fix-typo",
        task: "`specs/errata.md`, already open in your context, names one exact string in \
               `README.md` and the replacement for it. Make exactly that replacement in place.",
        docs: &[],
        required: &[],
        target: Some(FILES_EDIT_FILE),
        spec_path: "specs/errata.md",
        spec_text: FIX_TYPO_SPEC,
    },
];

// ---------------------------------------------------------------------------
// The fixture document
// ---------------------------------------------------------------------------

/// One language's probe fixture, as `crates/backend/src/probe/fixtures/<language>.json` carries it.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct ProbeFixture {
    /// Where these bytes came from and how to regenerate them.
    provenance: String,
    /// The [wire id](GgProgramLanguage::id) of the arm the fixture is spelled in.
    language: &'static str,
    /// The arm's display name, for the console.
    display_name: &'static str,
    /// The one `submit_program` tool the request offers, exactly as gg's own completion module
    /// builds it for this arm.
    tool: ProbeFixtureTool,
    /// One case per (scenario, prompt) pair.
    cases: Vec<ProbeFixtureCase>,
}

/// The `submit_program` tool definition in the chat/completions `function` shape.
#[derive(Debug, Serialize)]
struct ProbeFixtureTool {
    name: String,
    description: String,
    parameters: serde_json::Value,
}

/// One case: its identity, its full message array, and what the submitted program is checked for.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct ProbeFixtureCase {
    scenario: &'static str,
    prompt: &'static str,
    /// Call spellings ([`spell`]) a passing baseline program must all contain.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    expected_calls: Vec<String>,
    /// The target call's spelling a passing missing-docview program must *not* contain.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    forbidden_calls: Vec<String>,
    /// The documentation-view-opening call's spelling, for the missing-docview check.
    #[serde(skip_serializing_if = "Option::is_none")]
    docview_call: Option<String>,
    /// The catalogue key the missing function's documentation view is opened under.
    #[serde(skip_serializing_if = "Option::is_none")]
    docview_key: Option<String>,
    messages: Vec<ProbeFixtureMessage>,
}

/// One message of a case's conversation. `source` records which gg mechanism produced it and is
/// never sent on the wire.
#[derive(Debug, Serialize)]
struct ProbeFixtureMessage {
    role: &'static str,
    source: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    content: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    tool_calls: Vec<ProbeFixtureToolCall>,
    #[serde(skip_serializing_if = "Option::is_none")]
    tool_call_id: Option<String>,
}

/// One synthesized `submit_program` call, in the chat/completions wire shape.
#[derive(Debug, Serialize)]
struct ProbeFixtureToolCall {
    id: &'static str,
    #[serde(rename = "type")]
    kind: &'static str,
    function: ProbeFixtureToolFunction,
}

/// The function half of a synthesized call.
#[derive(Debug, Serialize)]
struct ProbeFixtureToolFunction {
    name: &'static str,
    arguments: String,
}

impl ProbeFixtureMessage {
    /// A synthesized `submit_program` assistant turn carrying `program` under `id`.
    fn submission(id: &'static str, program: &str) -> Self {
        Self {
            role: "assistant",
            source: "assistant",
            content: None,
            tool_calls: vec![ProbeFixtureToolCall {
                id,
                kind: "function",
                function: ProbeFixtureToolFunction {
                    name: crate::completion::SUBMIT_PROGRAM_TOOL,
                    arguments: json!({ "program": program }).to_string(),
                },
            }],
            tool_call_id: None,
        }
    }

    /// The fixed `ok` acknowledgement answering the call `id`.
    fn acknowledgement(id: &'static str) -> Self {
        Self {
            role: "tool",
            source: "tool_result",
            content: Some(SUBMIT_PROGRAM_ACK.to_string()),
            tool_calls: Vec::new(),
            tool_call_id: Some(id.to_string()),
        }
    }

    /// A synthesized `user` view message: the heading, the `----` rule, and the body — the exact
    /// framing [`ContextModel::headed`](crate::context::ContextModel) sends.
    fn view(role_source: (&'static str, &'static str), heading: &str, body: &str) -> Self {
        Self {
            role: role_source.0,
            source: role_source.1,
            content: Some(format!("{heading}\n----\n{body}")),
            tool_calls: Vec::new(),
            tool_call_id: None,
        }
    }
}

// ---------------------------------------------------------------------------
// Building one language's fixture
// ---------------------------------------------------------------------------

/// Build one language's whole fixture, or the sentence naming the gg defect that stopped it.
pub(crate) fn fixture_for(id: GgProgramLanguage) -> Result<ProbeFixture, String> {
    let arm = language(id);
    let capabilities: Vec<String> = PROBE_CAPABILITIES.iter().map(|c| c.to_string()).collect();
    let operations = capability_operations(PROBE_CAPABILITIES.iter().copied());
    let role = EndingRole::Standard;
    let docs = DocsRuntime::new(capabilities.clone(), role, &operations, id);

    // The system prompt, rendered by the loop's own renderer over the same context shape the loop
    // builds: code mode, this arm's language view, the modules the grant reaches, the base code
    // headings (files on — the conversation seeds a file view), an uncapped text-only read, and a
    // standard worker's ending calls.
    let system = prompts::render_system(
        &SystemContext {
            responses_as_code: true,
            language: Some(prompts::language_view(id)),
            modules: module_views(&capabilities, &operations, role, id),
            code_headings: code_heading_views(false, false, true),
            read_file: ReadFileView {
                offered: true,
                line_cap: None,
                images: false,
            },
            ending: ending_view(role, Some(id)),
            ..SystemContext::default()
        },
        None,
    )?;

    // The modules the opening listing covers and the base documentation keys: the opening turn a
    // fresh profile is seeded with, resolved exactly as the bootstrap resolves an agent's own for a
    // real session — so an entry the probe agent does not hold (the workspace search, which its
    // grant does not buy) is dropped here exactly as a run would drop it.
    let resolved = resolve_opening_turn(
        &docs,
        &GgOpeningTurn::seeded(),
        &capabilities,
        &operations,
        role,
    );
    let modules = resolved.modules;
    let base_keys = resolved.keys;

    let tool = submit_program_tool(id);

    let cases = CASES
        .iter()
        .map(|case| build_case(id, &docs, &modules, &base_keys, &system, case))
        .collect::<Result<Vec<_>, String>>()?;

    Ok(ProbeFixture {
        provenance: format!(
            "gg's responses-as-code turn-1 request for the {} arm, projected by `gg \
             probe-fixtures` (regenerate with scripts/gg-probe-fixtures.sh). Nothing model-facing \
             is authored here twice: the system prompt, the opening bootstrap program, the module \
             listing, every documentation view and the file-view headings are the same bytes \
             gg's own machinery produces for a real session; the task \
             prompts and spec files are the probe's own material. The backend replays each case \
             through OpenRouter with the one `submit_program` tool offered and `tool_choice` \
             forced to it, and classifies the program each reply submitted.",
            arm.display_name()
        ),
        language: id.id(),
        display_name: arm.display_name(),
        tool: ProbeFixtureTool {
            name: tool.name,
            description: tool.description,
            parameters: tool.parameters,
        },
        cases,
    })
}

/// A call-site needle for one spelling: its last two segments, joined by the separator between
/// them. [`spell`] answers fully qualified (`gg.files.writeFile`, `gg::files::write_file`), while a
/// call site may drop the qualifier the arm's own rules drop (TypeScript writes `files.writeFile`,
/// Rust may `use gg::files;` and write `files::write_file`). Every correct form ends with these two
/// segments, so the suffix matches both the qualified and the shortened call.
fn call_needle(spelling: &str) -> String {
    let mut boundaries: Vec<usize> = Vec::new();
    let bytes = spelling.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b':' && i + 1 < bytes.len() && bytes[i + 1] == b':' {
            boundaries.push(i);
            i += 2;
        } else if bytes[i] == b'.' {
            boundaries.push(i);
            i += 1;
        } else {
            i += 1;
        }
    }
    match boundaries.len() {
        0 | 1 => spelling.to_string(),
        n => {
            let start = boundaries[n - 2];
            let after = if bytes[start] == b':' {
                start + 2
            } else {
                start + 1
            };
            spelling[after..].to_string()
        }
    }
}

/// Build one case's message array and expectations.
fn build_case(
    id: GgProgramLanguage,
    docs: &DocsRuntime,
    modules: &[String],
    base_keys: &[String],
    system: &str,
    case: &CaseSpec,
) -> Result<ProbeFixtureCase, String> {
    let arm = language(id);
    let functions = catalogue_functions(arm);

    // The catalogue key of each operation the case names, in this arm's own spelling.
    let fqn_of = |operation: OperationId| -> Result<String, String> {
        bootstrap_function(&functions, operation, |function| docs.bound(function))
            .map(|function| function.fqn.to_string())
            .ok_or_else(|| {
                format!(
                    "the {} catalogue binds no `{operation}` for the probe agent's grant",
                    arm.display_name()
                )
            })
    };

    // The opening program: the bootstrap's module listing plus the base documentation views, with a
    // baseline case's target views appended to the same open list.
    let mut keys: Vec<String> = base_keys.to_vec();
    for operation in case.docs {
        let fqn = fqn_of(*operation)?;
        if !keys.contains(&fqn) {
            keys.push(fqn);
        }
    }
    let program = arm.bootstrap_program(
        &modules.iter().map(String::as_str).collect::<Vec<_>>(),
        &keys.iter().map(String::as_str).collect::<Vec<_>>(),
    );

    // The module listing, rendered by the loop's own renderer over the same search the bootstrap
    // program makes, keyed by the modules it lists.
    let query = DocSearchQuery {
        query: String::new(),
        modules: modules.to_vec(),
        declared_type: None,
        kind: None,
        offset: None,
        limit: Some(MAX_SEARCH_LIMIT),
    };
    let page = docs
        .search(DocQuery {
            query: &query.query,
            modules: &query.modules,
            declared_type: None,
            kind: None,
            offset: None,
            limit: query.limit,
        })
        .map_err(|refusal| {
            format!(
                "the bootstrap module listing was refused: {}",
                refusal.message
            )
        })?;
    let listing = crate::agent::code::render_search_results(&query, &page);
    let listing_heading = item_heading(
        GgContextSource::SearchResults,
        Some(&modules.join(", ")),
        None,
    )
    .ok_or_else(|| "a search view renders no heading".to_string())?;

    let mut messages = vec![
        ProbeFixtureMessage {
            role: "system",
            source: "system",
            content: Some(system.to_string()),
            tool_calls: Vec::new(),
            tool_call_id: None,
        },
        ProbeFixtureMessage::view(("user", "user_prompt"), "Task", case.task),
        ProbeFixtureMessage::submission(BOOTSTRAP_CALL_ID, &program),
        ProbeFixtureMessage::acknowledgement(BOOTSTRAP_CALL_ID),
        ProbeFixtureMessage::view(("user", "search_results"), &listing_heading, &listing),
    ];

    // The documentation views the opening program placed: each key's own page, then the type views
    // this agent's flags (every one on) select, deduplicated session-wide — the loop's own
    // one-call-one-level algorithm.
    let mut opened: Vec<String> = Vec::new();
    for key in &keys {
        for view_key in
            std::iter::once(key.clone()).chain(docs.types_to_open(key, DocViewTypes::EVERY))
        {
            if opened.contains(&view_key) {
                continue;
            }
            let body = docs.read_any(&view_key).ok_or_else(|| {
                format!(
                    "the {} documentation renders nothing under `{view_key}`",
                    arm.display_name()
                )
            })?;
            let heading = item_heading(GgContextSource::DocsView, Some(&view_key), None)
                .ok_or_else(|| "a documentation view renders no heading".to_string())?;
            messages.push(ProbeFixtureMessage::view(
                ("user", "docs_view"),
                &heading,
                &body,
            ));
            opened.push(view_key);
        }
    }

    // The spec file, seeded exactly as autoload seeds one: a synthesized program opening the view,
    // the acknowledgement, then the file view headed by its path, the whole 1-based line range and
    // the file's total line count.
    let files_program = arm.open_file_program(&[(case.spec_path, None)]);
    messages.push(ProbeFixtureMessage::submission(
        AUTOLOAD_CALL_ID,
        &files_program,
    ));
    messages.push(ProbeFixtureMessage::acknowledgement(AUTOLOAD_CALL_ID));
    let spec_text = case.spec_text.trim_end_matches('\n');
    let total = spec_text.lines().count() as u64;
    let heading = item_heading(
        GgContextSource::FileView,
        Some(case.spec_path),
        Some(ShownLines {
            first: 1,
            last: total,
            total,
        }),
    )
    .ok_or_else(|| "a file view renders no heading".to_string())?;
    messages.push(ProbeFixtureMessage::view(
        ("user", "file_view"),
        &heading,
        spec_text,
    ));

    Ok(ProbeFixtureCase {
        scenario: case.scenario,
        prompt: case.prompt,
        expected_calls: case
            .required
            .iter()
            .map(|operation| call_needle(&spell(arm, *operation)))
            .collect(),
        forbidden_calls: case
            .target
            .map(|operation| vec![call_needle(&spell(arm, operation))])
            .unwrap_or_default(),
        docview_call: case
            .target
            .map(|_| call_needle(&spell(arm, VIEWS_OPEN_DOCS_VIEW))),
        docview_key: case.target.map(fqn_of).transpose()?,
        messages,
    })
}

// ---------------------------------------------------------------------------
// Writing the projection
// ---------------------------------------------------------------------------

/// Write one fixture per registered language into `directory`, creating it if it is not there.
///
/// Pretty-printed, unlike the reference's compact documents, because these are **committed** files:
/// a regeneration is reviewed as a diff, and a one-line JSON blob diffs as a whole-file rewrite.
pub(crate) fn write_probe_fixtures(directory: &Path) -> Result<(), ProbeFixtureWriteError> {
    std::fs::create_dir_all(directory).map_err(|source| ProbeFixtureWriteError {
        path: directory.to_path_buf(),
        detail: source.to_string(),
    })?;
    for id in GgProgramLanguage::ALL {
        let fixture = fixture_for(*id).map_err(|detail| ProbeFixtureWriteError {
            path: directory.join(format!("{}.json", id.id())),
            detail,
        })?;
        let path = directory.join(format!("{}.json", id.id()));
        let json =
            serde_json::to_string_pretty(&fixture).map_err(|err| ProbeFixtureWriteError {
                path: path.clone(),
                detail: err.to_string(),
            })?;
        std::fs::write(&path, json + "\n").map_err(|source| ProbeFixtureWriteError {
            path,
            detail: source.to_string(),
        })?;
    }
    Ok(())
}

/// A failure while projecting the fixtures, carrying the path it was attempting.
#[derive(Debug, thiserror::Error)]
#[error("{path}: {detail}")]
pub(crate) struct ProbeFixtureWriteError {
    /// The file or directory the failed step was operating on.
    path: PathBuf,
    /// What went wrong.
    detail: String,
}

#[cfg(test)]
#[path = "probe_fixtures.test.rs"]
mod tests;
