#!/usr/bin/env python3
"""Everything derived from where the repositories live: the patch table, the package links and the git rewrites.

    scripts/repos/sources.py patch-table [--write]
    scripts/repos/sources.py package-links [--write]
    scripts/repos/sources.py link-plan
    scripts/repos/sources.py rewrites [--apply | --env]
    scripts/repos/sources.py mirror <name>

Every manifest names a dependency on another repository of The Test Cabinet by
its public source, the GitHub mirror `render.py` derives from the kit's table
of repositories. Two things follow from that table and are generated here
rather than written by hand.

`patch-table` prints the `[patch]` tables of the superrepo's
`.cargo/config.toml`: one per repository carrying a crate, sending its public
source to the sibling checkout. The file holds the superrepo's own aliases and
build settings as well, so the tables are written between two marker lines and
the rest of the file is left as it is. A repository that is not checked out is
left as a comment, because cargo loads every patch path eagerly and an entry
for a missing directory fails every build under the superrepo, the monorepo's
own included. `[net] git-fetch-with-cli` joins the block once an entry is
active, since only then does a build fetch a public source. `--write` writes
the block in place.

`package-links` prints the superrepo's `.package-links.json`, the npm
counterpart of the patch table: every package the npm workspace of each
checked-out repository produces, and the directory it lives in. A
repository's workspace is its root. A repository that is not checked out keeps
the entries the file already holds for it, because its packages cannot be read
here. `--write` writes the file in place. `link-plan` prints, from the written
table, the steps that link every checked-out workspace naming a package
another produces: `install` a workspace with the directories of its links,
tab-separated, and `build` a producer before anything that links it.
`link-packages.sh` runs both. The derivation itself is the kit's
`the_test_cabinet_ci/links.py`, imported by path, so a repository's
`typescript` gate reads the table by the same rules.

`rewrites` prints one `git config` rewrite per repository, sending a fetch of
the public source to the Azure remote. Cargo fetches a patched git source to
resolve the lock file even though nothing is built from it, and a private
mirror answers that fetch with a credential challenge, so the rewrite stays in
place while the mirrors are private. `--apply` writes the rewrites into the
user's git configuration, which is where cargo's command-line fetch reads
them; `--env` prints them as the `GIT_CONFIG_COUNT` environment a single
command can carry instead.

`mirror` prints the mirror's name on GitHub.
"""

from __future__ import annotations

import argparse
import importlib.util
import shlex
import subprocess
import sys
import tomllib
from pathlib import Path
from types import ModuleType

import render

SUPERREPO = render.SUPERREPO
CARGO_CONFIG = SUPERREPO / ".cargo" / "config.toml"
LINKS_MODULE = render.KIT / "ci" / "src" / "the_test_cabinet_ci" / "links.py"
BEGIN = "# BEGIN the patch table: generated by `scripts/repos/sources.py patch-table --write`."
END = "# END the patch table."


def _load_links() -> ModuleType:
    """The kit's package-link derivation, imported from the file the kit renders into every repository."""
    spec = importlib.util.spec_from_file_location("test_cabinet_kit_links", LINKS_MODULE)
    if spec is None or spec.loader is None:
        raise FileNotFoundError(LINKS_MODULE)
    module = importlib.util.module_from_spec(spec)
    # A dataclass resolves its module through sys.modules while it is defined.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


links = _load_links()

PREAMBLE = """\
# Each repository's manifests name a dependency on another repository by its
# public git source, the GitHub mirror, which is what lets a repository build
# on its own. The `[patch]` tables below redirect every one of those sources
# to the sibling checkout, so a build inside the superrepo links the working
# trees rather than the pushed revisions. The Repositories development page
# states the rule; the `dependency-graph` gate holds these tables to the
# repositories.
#
# A table for a repository that is not checked out is a comment: cargo loads
# every patch path eagerly, so an entry for a missing directory would fail
# every build under the superrepo, the monorepo's own included."""

FETCH = """\
# Cargo still fetches a patched git source to resolve the lock file, so the
# source has to be reachable even though nothing is built from it. While the
# mirrors are private, `scripts/repos/sources.py rewrites --apply` rewrites
# each public source to the Azure remote in the user's git configuration,
# which the command-line fetch below honours and cargo's built-in one would
# not.
[net]
git-fetch-with-cli = true"""


def rust_repositories() -> list[str]:
    """The repositories carrying a crate, in the order of the table of repositories."""
    edges = render.edge_table()
    return [repo for repo, kind in edges.REPOSITORIES.items() if edges.KINDS[kind].crate]


def crates_of(repo: str, root: Path = SUPERREPO) -> list[tuple[str, str]]:
    """The (package, directory under crates/) of each crate a repository holds, in a stable order.

    A checked-out repository declares its crates under `crates/`, one manifest
    each, and every one is patched; a repository not checked out, or one that
    declares none yet, is patched at the crate the kit scaffolds for it.
    """
    found: list[tuple[str, str]] = []
    for manifest in sorted((root / repo / "crates").glob("*/Cargo.toml")):
        parsed = tomllib.loads(manifest.read_text(encoding="utf-8"))
        package = parsed.get("package")
        if isinstance(package, dict) and isinstance(package.get("name"), str):
            found.append((package["name"], manifest.parent.name))
    if found:
        return found
    directory, crate = render.crate_of(repo)
    return [(crate, directory)]


def checked_out(root: Path, repo: str) -> bool:
    """Whether a repository's submodule directory holds a checkout."""
    directory = root / repo
    return directory.is_dir() and any(directory.iterdir())


def patch_block(root: Path = SUPERREPO) -> str:
    """The generated block of the superrepo's cargo configuration, its markers included."""
    blocks = [BEGIN, PREAMBLE]
    active = False
    for repo in rust_repositories():
        entries = [f'{crate} = {{ path = "{repo}/crates/{directory}" }}' for crate, directory in crates_of(repo, root)]
        table = f'[patch."{render.public_source(repo)}"]'
        if (root / repo / "Cargo.toml").is_file():
            active = True
            blocks.append("\n".join([table, *entries]))
        else:
            blocks.append(
                "\n".join(
                    [
                        f"# {repo} is not checked out; the table joins once it is bootstrapped:",
                        f"#   {table}",
                        *(f"#   {entry}" for entry in entries),
                    ]
                )
            )
    if active:
        blocks.append(FETCH)
    blocks.append(END)
    return "\n\n".join(blocks) + "\n"


def with_patch_block(config: str, root: Path = SUPERREPO) -> str:
    """The configuration with its generated block replaced, or appended when it holds none."""
    block = patch_block(root)
    if BEGIN in config:
        start = config.index(BEGIN)
        if END not in config[start:]:
            raise ValueError(f"the configuration opens the patch table with {BEGIN!r} and never closes it")
        end = config.index(END, start) + len(END)
        rest = config[end:].removeprefix("\n")
        return config[:start] + block + rest
    return config.rstrip("\n") + "\n\n" + block


def package_links(root: Path = SUPERREPO) -> dict[str, dict[str, str]]:
    """The link table: what each checked-out repository's workspace produces.

    A repository that is not checked out keeps whatever the written table
    already holds for it, since its manifests cannot be read.
    """
    present = [repo for repo in render.repositories() if checked_out(root, repo)]
    table = links.produced(root, present)
    for workspace, packages in links.load_table(root).items():
        repo = workspace.split("/", 1)[0]
        if repo in render.repositories() and repo not in present:
            table[workspace] = dict(packages)
    return dict(sorted(table.items()))


def workspaces(root: Path = SUPERREPO) -> list[str]:
    """Every checked-out repository's npm workspace, in the order of the table of repositories."""
    return [repo for repo in render.repositories() if (root / repo / "package.json").is_file()]


def link_plan(root: Path = SUPERREPO) -> list[str]:
    """The steps `link-packages.sh` runs, one tab-separated line each."""
    steps = links.plan(root, links.load_table(root), workspaces(root))
    return ["\t".join([step.action, step.workspace, *(link.directory for link in step.links)]) for step in steps]


def rewrites() -> list[tuple[str, str]]:
    """Each (remote, source) pair a fetch is rewritten by, the superrepo included."""
    return [(render.azure_remote(repo), render.public_source(repo)) for repo in render.edge_table().MIRRORS]


def rewrite_commands() -> list[list[str]]:
    return [["git", "config", "--global", f"url.{remote}.insteadOf", source] for remote, source in rewrites()]


def rewrite_environment() -> dict[str, str]:
    """The rewrites as the `GIT_CONFIG_*` variables one command carries."""
    pairs = rewrites()
    env = {"GIT_CONFIG_COUNT": str(len(pairs))}
    for index, (azure, public) in enumerate(pairs):
        env[f"GIT_CONFIG_KEY_{index}"] = f"url.{azure}.insteadOf"
        env[f"GIT_CONFIG_VALUE_{index}"] = public
    return env


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    table = commands.add_parser("patch-table", help="the patch tables of the superrepo's .cargo/config.toml")
    table.add_argument("--write", action="store_true", help="write the block in place rather than print it")
    package = commands.add_parser("package-links", help="the superrepo's .package-links.json")
    package.add_argument("--write", action="store_true", help="write it in place rather than print it")
    commands.add_parser("link-plan", help="the steps that link every workspace naming a sibling's package")
    rewrite = commands.add_parser("rewrites", help="the git rewrites from the public sources to Azure")
    how = rewrite.add_mutually_exclusive_group()
    how.add_argument("--apply", action="store_true", help="write them into the user's git configuration")
    how.add_argument("--env", action="store_true", help="print them as GIT_CONFIG_* assignments")
    mirror = commands.add_parser("mirror", help="the GitHub name of a repository")
    mirror.add_argument("name")
    args = parser.parse_args(argv)

    if args.command == "patch-table":
        if args.write:
            try:
                text = with_patch_block(CARGO_CONFIG.read_text(encoding="utf-8"))
            except ValueError as error:
                print(f"sources: {CARGO_CONFIG.relative_to(SUPERREPO)}: {error}", file=sys.stderr)
                return 1
            CARGO_CONFIG.write_text(text, encoding="utf-8")
            print(f"wrote the patch table into {CARGO_CONFIG.relative_to(SUPERREPO)}")
        else:
            sys.stdout.write(patch_block())
    elif args.command == "package-links":
        try:
            text = links.render_table(package_links())
        except links.LinkTableError as error:
            print(f"sources: {error}; move it aside and run this again", file=sys.stderr)
            return 1
        written = SUPERREPO / links.TABLE
        if args.write:
            written.write_text(text, encoding="utf-8")
            print(f"wrote {written.relative_to(SUPERREPO)}")
        else:
            sys.stdout.write(text)
    elif args.command == "link-plan":
        try:
            for line in link_plan():
                print(line)
        except (links.LinkTableError, links.LinkCycleError) as error:
            print(f"sources: {error}", file=sys.stderr)
            return 1
    elif args.command == "rewrites":
        if args.apply:
            commands_run = rewrite_commands()
            for command in commands_run:
                subprocess.run(command, check=True)
            print(f"applied {len(commands_run)} rewrites to the user's git configuration")
        elif args.env:
            for key, value in rewrite_environment().items():
                print(f"{key}={shlex.quote(value)}")
        else:
            for command in rewrite_commands():
                print(shlex.join(command))
    elif args.command == "mirror":
        mirrors = render.edge_table().MIRRORS
        if args.name not in mirrors:
            print(f"sources: {args.name} has no mirror", file=sys.stderr)
            return 1
        print(mirrors[args.name])
    return 0


if __name__ == "__main__":
    sys.exit(main())
