import { GRADE_META, RATING_META, VERDICT_META, isGrade } from "../../../data/ratings";
import type {
  Rating,
  ReviewRevision,
  VerdictStatus,
} from "@test-cabinet/run-record/review";
import { formatReviewedAt } from "./ReviewList";
import styles from "./RunDetailPages.module.scss";

// A rating's human label (e.g. "Great"); a verdict status renders its pass/fail
// label or, for a game-jam grade, its emoji + label.
function ratingLabel(rating: Rating): string {
  return RATING_META[rating].label;
}
function statusLabel(status: VerdictStatus): string {
  return isGrade(status)
    ? `${GRADE_META[status].emoji} ${GRADE_META[status].label}`
    : VERDICT_META[status].label;
}

// The edit history of a single review: one entry per edit, newest first, each with
// the reviewer's note explaining the change and the autogenerated diff of what
// changed (per-domain rating flips, checklist verdict changes, whether the writeup
// was revised). Renders nothing for a review that has never been edited, so it is
// safe to mount unconditionally beneath a review.
export function ReviewHistory({
  revisions,
}: {
  revisions?: ReviewRevision[] | null;
}) {
  if (!revisions || revisions.length === 0) return null;
  // The stored history is oldest-first; show the most recent edit at the top.
  const newestFirst = [...revisions].reverse();
  return (
    <section className={styles.reviewHistory}>
      <h2 className={styles.checklistHeading}>
        Edit history ({revisions.length})
      </h2>
      <ol className={styles.historyList}>
        {newestFirst.map((revision, i) => (
          <li key={`${revision.editedAt}-${i}`} className={styles.historyItem}>
            <div className={styles.historyWhen}>
              {formatReviewedAt(revision.editedAt)}
            </div>
            <p className={styles.historyNote}>{revision.note}</p>
            <ul className={styles.historyDiff}>
              {(revision.diff.ratings ?? []).map((change) => (
                <li key={`r-${change.domain}`}>
                  <span className={styles.diffKey}>{change.domain}</span>{" "}
                  {change.from ? ratingLabel(change.from) : "—"} →{" "}
                  {change.to ? ratingLabel(change.to) : "—"}
                </li>
              ))}
              {(revision.diff.verdicts ?? []).map((change) => {
                const statusChanged = change.from !== change.to;
                return (
                  <li key={`v-${change.id}`}>
                    <span className={styles.diffKey}>{change.id}</span>{" "}
                    {statusChanged ? (
                      <>
                        {change.from ? statusLabel(change.from) : "—"} →{" "}
                        {change.to ? statusLabel(change.to) : "—"}
                      </>
                    ) : (
                      // A note-only change: the status held, so show it once.
                      statusLabel(change.to ?? change.from!)
                    )}
                    {change.noteChanged && (
                      <span className={styles.diffMuted}> (note updated)</span>
                    )}
                  </li>
                );
              })}
              {revision.diff.writeup && (
                <li>
                  <span className={styles.diffKey}>Writeup</span>{" "}
                  <span className={styles.diffMuted}>revised</span>
                </li>
              )}
            </ul>
          </li>
        ))}
      </ol>
    </section>
  );
}
