#!/usr/bin/env bash
# Reflect the Java program language's signature catalogue out of the SDK's own Javadoc, and write
# it to $GG_SIGNATURES_OUT_DIR/java.signatures.json.
#
# WHERE IT WRITES, AND WHY THERE IS NO DEFAULT. The catalogue is a BUILD ARTIFACT.
# `crates/gg/build.rs` runs `scripts/gg-signatures.sh` and embeds what lands in the build's own
# `OUT_DIR`, so the Javadoc a model is shown is reflected on the same build that compiles the host
# showing it — a `@param` edited without a regeneration is not a state this checkout can be in. A
# default here would be a second answer to a question the build already answers, and the old one,
# `crates/gg/src/sandbox/guests/`, is the answer that stopped being right: nothing is committed
# there for this arm any more. Run it by hand, into a directory of your choosing, to READ a
# catalogue — which is what `scripts/gg-signatures.sh` is for, and how a reflector bug gets found.
#
# WHY JAVADOC. Everything a model reads about this surface is written on the declaration it
# describes — a function's description in its doc comment, an argument's in that argument's
# `@param`, a record component's in the `@param` on the record, an enum constant's in the comment
# above it, an API object's on the field of `gg.Gg` that holds it — and the JDK's own doclet API
# is what reads all of it. Nothing here is prose typed into a table: the doclet refuses to emit a
# catalogue with a blank in it, so a missing `@param` is an error on the author rather than a gap
# a model discovers.
#
# `build.sh` compiles the same sources with `-Xdoclint:all -Werror`, which is the JDK's own
# completeness check over the same comments — an undocumented parameter, a `@param` naming an
# argument that is not there, a broken `{@link}` — so two independent readings have to agree
# before anything a model reads is written. (It lives there rather than here because doclint is a
# javac and standard-doclet option, and this runs a doclet of gg's own.)
#
# Usage:
#   GG_SIGNATURES_OUT_DIR=<dir> packages/gg-sandbox-java/signatures.sh
#   scripts/gg-signatures.sh                 # all eleven arms, into one directory
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -z "${GG_SIGNATURES_OUT_DIR:-}" ]; then
	echo "error: GG_SIGNATURES_OUT_DIR is not set. It names the directory this catalogue is" >&2
	echo "       written into, and there is no default — the catalogue is generated by the build" >&2
	echo "       rather than committed anywhere." >&2
	echo "       Run scripts/gg-signatures.sh (which sets it and regenerates every arm), or set" >&2
	echo "       it yourself to a directory you want the JSON in." >&2
	exit 1
fi
# Created, then made absolute: the doclet writes into a `mktemp -d` and the result is moved here, so
# a relative destination would be resolved against whatever directory the caller happened to be in.
mkdir -p "$GG_SIGNATURES_OUT_DIR"
OUT="$(cd "$GG_SIGNATURES_OUT_DIR" && pwd)/java.signatures.json"

# shellcheck source=packages/gg-sandbox-java/java-version.sh
source "$HERE/java-version.sh"

INSTALL_DIR="${JAVA_INSTALL_DIR:-$HOME/.local/share/gg-java}"
JAVAC="${TCAB_GG_JAVAC:-$INSTALL_DIR/jdk/bin/javac}"
JAVADOC="${TCAB_GG_JAVADOC:-$INSTALL_DIR/jdk/bin/javadoc}"
LIBS="${TCAB_GG_TEAVM:-$INSTALL_DIR/libs}"

if [ ! -x "$JAVADOC" ]; then
	echo "error: no javadoc at $JAVADOC — run scripts/ci/install-gg-toolchains.sh" >&2
	exit 1
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

CLASSPATH="$(find "$LIBS" -name '*.jar' | sort | tr '\n' ':')"

# The doclet itself, compiled into a directory javadoc is pointed at. It is gg's own code and it
# runs on the developer's machine rather than in a run container, so there is nothing to commit.
"$JAVAC" -d "$WORK/doclet" "$HERE/tools/GgSignatures.java" "$HERE/tools/GgCatalogue.java"

"$JAVADOC" \
	-doclet tools.GgSignatures \
	-docletpath "$WORK/doclet" \
	-classpath "$CLASSPATH" \
	-sourcepath "$HERE/src" \
	-quiet \
	-o "$WORK/java.signatures.json" \
	--libraries "$HERE/libraries.txt" \
	-subpackages gg \
	-exclude gg.internal

mv "$WORK/java.signatures.json" "$OUT"
echo "wrote $OUT ($(wc -c <"$OUT") bytes)"
