#!/usr/bin/env bash
# Reflect the **C++** program language's signature catalogue out of the SDK's own documentation
# and write `$GG_SIGNATURES_OUT_DIR/cpp.signatures.json`.
#
# WHERE IT WRITES, AND WHY THERE IS NO DEFAULT. The catalogue is a BUILD ARTIFACT.
# `crates/gg/build.rs` runs `scripts/gg-signatures.sh` and embeds what lands in the build's own
# `OUT_DIR`, so the `///` comments a model is shown are reflected on the same build that compiles the
# host showing them — a `\param` edited without a regeneration is not a state this checkout can be
# in. A default here would be a second answer to a question the build already answers, and the old
# one, `crates/gg/src/sandbox/guests/`, is the answer that stopped being right. Run it by hand, into
# a directory of your choosing, to READ a catalogue — which is what `scripts/gg-signatures.sh` is
# for, and how a reflector bug gets found.
#
# WHAT READS THE DOCUMENTATION. `clang++` itself. clang carries a real documentation parser — the
# one `-Wdocumentation` diagnoses against and the one `libclang`'s comment API and `clang-doc` are
# built on — and `-ast-dump=json` prints what it built: which comment belongs to which declaration,
# each `\param`'s prose attached to the parameter it names, and `\returns` and `\throws` as their
# own nodes. So the per-parameter documentation slot here is the LANGUAGE's rather than a convention
# standing in for one, as it is on the Rust and PureScript arms.
#
# `-Werror=documentation` is what makes that a contract rather than a habit: clang refuses the
# reflection outright if a `\param` names an argument the function does not take, or if a documented
# function's arguments are documented in the wrong order — before this script ever gets to check the
# same things itself.
#
# WHY THE AST IS FILTERED. A translation unit that includes this SDK also includes half the standard
# library, and dumping the whole of one is ~300 MB for `<string>` alone. `-ast-dump-filter=gg` keeps
# the declarations whose name matches — which for this SDK is all of them, because its surface lives
# in `namespace gg`. 3 MB and half a second.
#
# WHY IT WRITES EXACTLY ONE FILE. This runs on any build of gg that regenerates a catalogue, which
# is to say under a developer who typed `cargo build`. `crates/gg/src/sandbox/checkers/` holds this
# arm's committed guest archive, re-cut by `build.sh` on purpose and by hand because it costs minutes
# and megabytes. A signature step that reached `build.sh` for the bindings it needs would rewrite
# that archive on the way past — a multi-megabyte binary changed under someone who asked for a
# compile, and a checkout whose committed artifacts no longer say what produced them. Measured on the
# Rust arm, which is why the bindings are their own script here as they are there. Nothing below
# writes into `crates/gg/src/sandbox/checkers/`.
#
# Usage:
#   GG_SIGNATURES_OUT_DIR=<dir> packages/gg-sandbox-cpp/signatures.sh
#   scripts/gg-signatures.sh                 # all eleven arms, into one directory
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=packages/gg-sandbox-cpp/cpp-version.sh
source "$HERE/cpp-version.sh"

# NO BYTECODE CACHE. `tools/signatures.py` imports its sibling `tools/catalogue.py`, and an ordinary
# CPython drops a `__pycache__/` beside a module it imports. That directory is gitignored and
# harmless to a person, but `crates/gg/build.rs` names this package's `tools` subtree as an input
# whose change should re-reflect the catalogue — so a run that writes into it leaves the next
# `cargo build` convinced its inputs moved and re-runs all eleven arms. The export lives here rather
# than only in `scripts/gg-signatures.sh` because running this script BY HAND is the documented way
# to read a catalogue, and a developer who does that should not pay for it on their next build.
export PYTHONDONTWRITEBYTECODE=1

if [ -z "${GG_SIGNATURES_OUT_DIR:-}" ]; then
	echo "error: GG_SIGNATURES_OUT_DIR is not set. It names the directory this catalogue is" >&2
	echo "       written into, and there is no default — the catalogue is generated by the build" >&2
	echo "       rather than committed anywhere." >&2
	echo "       Run scripts/gg-signatures.sh (which sets it and regenerates every arm), or set" >&2
	echo "       it yourself to a directory you want the JSON in." >&2
	exit 1
fi
# Created, then made absolute, and on this arm that is load-bearing rather than tidy: the reflector
# is run with `cd "$HERE"` at the foot of this file, because clang records its paths relative to the
# directory it was given `-I Sources` from. A relative destination would be written inside the
# package instead of where the caller asked for it.
mkdir -p "$GG_SIGNATURES_OUT_DIR"
OUT="$(cd "$GG_SIGNATURES_OUT_DIR" && pwd)/cpp.signatures.json"
WORK="$HERE/.build/reflect"
BINDINGS="$HERE/.build/bindings"

SDK_HOME="$(gg_wasi_sdk_home)"
CLANGXX="$SDK_HOME/bin/clang++"
if [ ! -x "$CLANGXX" ]; then
	cat >&2 <<EOF
error: no wasi-sdk at $SDK_HOME.
       Run scripts/ci/install-gg-toolchains.sh, or set TCAB_GG_WASI_SDK_HOME.
EOF
	exit 1
fi

"$HERE/bindings.sh" >/dev/null

echo "==> dumping the SDK's comment AST"
rm -rf "$WORK"
mkdir -p "$WORK"
# One translation unit that includes nothing but the SDK's umbrella header. It is compiled for the
# target this arm really compiles to, so the types in the dump are the types a program is really
# declared against.
printf '#include "sdk/gg.hpp"\n' >"$WORK/reflect.cpp"
(cd "$HERE" && "$CLANGXX" \
	--target="$GG_CPP_TARGET" -std="$GG_CPP_STD" -fsyntax-only \
	-Wdocumentation -Wdocumentation-pedantic -Werror=documentation \
	-I Sources -I "$BINDINGS" \
	-Xclang -ast-dump=json -Xclang -ast-dump-filter=gg \
	"$WORK/reflect.cpp") >"$WORK/ast.json"
test -s "$WORK/ast.json"

echo "==> reflecting $OUT"
# From this package's own directory, because the paths clang records in the dump are the ones it was
# given — and it is given `-I Sources` from here, so `Sources/sdk/gg/files.hpp` is what a doc
# comment's source range is quoted out of.
(cd "$HERE" && python3 tools/signatures.py "$WORK/ast.json" Sources/prelude.hpp "$OUT")
