// The scored-scenario PORTIONS shown in the preview: representative top-of-factory
// crops of the held-out `bus` scored scenarios (cases/medium.json, large.json),
// generated by gen-preview-scenarios.mjs into preview-scenarios.json, so the
// interconnected main-bus layouts (splitter routing, inserter taps, curves,
// side-load merges, multi-stage crafting) can be eyeballed here without rebuilding
// containers, re-ingesting the case, and doing a full run.
// Regenerate with: node packages/ui/preview/gen-preview-scenarios.mjs
import portions from "./preview-scenarios.json";
import type { Preset } from "./scenarios";

export const SCORED_PORTIONS: Preset[] = portions as Preset[];
