"""Emit the signature catalogue gg renders the Python arm's system prompt and doc views from.

gg has to tell a model, every turn, what functions its program may call and what they do. The wrong
way to do that is a hand-written list in the prompt template: it drifts away from the SDK silently,
and a model shown a signature the sandbox does not have wastes a whole turn discovering that. So the
list is REFLECTED out of the SDK's own declarations and docstrings instead.

The pipeline:

    packages/gg-sandbox-python/src/gg/**.py
        --griffe (static, no import)-->
    $GG_SIGNATURES_OUT_DIR/python.signatures.json

Nothing here imports the SDK. Every capability module imports `wit_world`, which only exists inside
the baked component, so the reflector reads the *sources* with `griffe` — which is also the right
tool for the job: a docstring is documentation, and griffe is Python's own answer to reading it.
`gg.catalogue` is the one module that is loaded rather than parsed, because it is data with no
membrane import in it and re-implementing its module list here would be a second copy of it.

What is written where, and what this refuses to emit
----------------------------------------------------

Everything a model reads about this surface is written on the declaration it describes, and this
reflector's whole job is to fail the build rather than emit a gap. Concretely:

  * the **module** a function lives in is the Python module it is declared in, and the fully-qualified
    name is that module's path plus the function's own name — assembled by nobody, because both
    halves are facts about where the `def` is;
  * the **gg operation** it binds is the `@operation("files.read_file")` decorator on it. A public
    function with no decorator is an error, and two functions claiming one operation is an error;
  * the **public surface** is `__all__`, which is Python's own declaration of one. A name in it that
    is not a function is a type;
  * the **brief** is the docstring's first line and the **detail** is everything after the blank line
    that follows it — PEP 257's own shape. A first paragraph that runs over one line is an error
    naming the declaration, so the split fails where the author is standing rather than three steps
    later in a gate;
  * every **parameter** a signature declares carries an `Args:` entry, and an `Args:` entry naming
    something the signature does not declare is an error too, so a renamed argument cannot leave its
    description behind under the old name;
  * every **type** the catalogue carries is documented, and so is each of its members;
  * every type a signature refers to is **resolved** to the fully-qualified name it is declared
    under, and the reference closure is **transitive**, so a type reachable only through another
    type's field is still reachable, still documented and still openable.

The catalogue carries one thing that is not a signature, on the same rule: the LIBRARY SET a program
may import, read off the module-scope imports of `src/library.py` — the file that decides it, because
`componentize-py` bakes that module's import closure and nothing else. The prompt renders that list,
so what a model is told it may import is what the artifact was built with rather than a sentence
somebody wrote once. See `libraries`.

Usage:
    python tools/signatures.py --out-dir <dir>

There is no "check whether the committed copy is current" mode, because there is no committed copy.
The catalogue is generated by `crates/gg/build.rs` on every build of gg that needs it, so a
docstring edited without a regeneration is not a state this repository can be in — the next build
reflects the edit, and the register gate in `crates/gg/src/sandbox/language/register.rs` reads the
freshly reflected prose rather than a copy a reviewer eyeballed months ago.
`packages/gg-sandbox-python/signatures.sh` is what actually runs this, is what pins the `griffe` it
runs against, and is what turns `GG_SIGNATURES_OUT_DIR` into the `--out-dir` below.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from types import ModuleType
from typing import Any, Iterable

import griffe

PACKAGE_DIR = Path(__file__).resolve().parent.parent
SRC_DIR = PACKAGE_DIR / "src"

LANGUAGE = "python"
"""The `GgProgramLanguage` id this catalogue carries the spellings of, and the stem it is filed
under in whatever directory it is generated into. Written into the catalogue so the emitted file
says whose spellings it carries, and asserted by the host against the language that embedded it —
which is what catches a build that generated eleven catalogues and wired one of them to the wrong
arm."""

SCHEMA = 1
"""The schema this catalogue is written in — the normalized doc model: modules, operations,
fully-qualified names, authored briefs and resolved type references."""

GENERATED_FROM = "packages/gg-sandbox-python/src/gg/ (griffe, static)"
"""The provenance string written into the catalogue, so a reader of the JSON knows it is generated
and where from."""

OPERATION_DECORATOR = "operation"
"""The decorator that names the gg operation a declaration binds.

Matched on the decorator expression's *callee*, so `@operation("files.read_file")` is recognised and
anything else on the declaration is left alone. It is the same fact `gg._registry` reads at run time,
read here out of the source instead — the reflector never imports this package.
"""

ALIAS_DECORATOR = "alias"
"""The decorator that names the gg operation a **method** is a second way to reach.

Read exactly as `OPERATION_DECORATOR` is, off the source text, and kept apart from it for the reason
`gg._registry` keeps the two attributes apart: an alias claims no operation, so a reflector that read
one as a binding would report this arm binding `views.close` twice and the coverage gate would say
so.
"""

ALWAYS_REFERENCED = ("ToolError",)
"""The types every catalogued function refers to whether or not its signature writes them.

Exactly one, and it is not a convenience: every function in this SDK raises `ToolError` on a failure,
which is the half of a signature Python states in prose rather than in the annotation. An arm whose
`Result<_, ToolError>` is written in the return type carries it in every entry's references; this one
would carry it in none, and the failure type would be a declaration no model could open.
"""

def load_catalogue() -> ModuleType:
    """Load `gg/catalogue.py` as a standalone module.

    It is the one SDK module that can be imported outside the component, because it imports nothing
    at all. Loading it by path rather than as `gg.catalogue` is what keeps `gg/__init__.py` — and
    through it `wit_world` — out of the way.
    """
    path = SRC_DIR / "gg" / "catalogue.py"
    spec = importlib.util.spec_from_file_location("gg_catalogue", path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def load_sources() -> griffe.Module:
    """Parse the whole `gg` package statically, with its docstrings in Google style."""
    return griffe.load(
        "gg",
        search_paths=[str(SRC_DIR)],
        docstring_parser=griffe.Parser.google,
        allow_inspection=False,
        force_inspection=False,
    )


# --- Documentation -------------------------------------------------------------------------------


def flatten(text: str) -> str:
    """One paragraph of prose on one line.

    Every newline a docstring wraps at becomes a space, because what this feeds is a markdown prompt
    rather than a fixed-width file.
    """
    return re.sub(r"\s+", " ", text).strip()


def reflow(text: str) -> str:
    """A block of prose with its paragraphs flattened and its fenced examples kept verbatim.

    A docstring wraps at whatever width its author writes to, and those line breaks are an artifact of
    the source file rather than anything a reader of the rendered prompt should see. A fenced block is
    the exception: its line breaks are the code.
    """
    out: list[str] = []
    fenced = False
    paragraph: list[str] = []

    def close() -> None:
        if paragraph:
            out.append(flatten(" ".join(paragraph)))
            paragraph.clear()

    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            close()
            if fenced:
                out[-1] = f"{out[-1]}\n{line}"
                fenced = False
            else:
                out.append(line)
                fenced = True
            continue
        if fenced:
            out[-1] = f"{out[-1]}\n{line}"
            continue
        if line.strip():
            paragraph.append(line.strip())
        else:
            close()
    close()
    return "\n\n".join(out)


@dataclass(frozen=True)
class Prose:
    """One declaration's documentation, split as every arm's catalogue carries it."""

    brief: str
    """The docstring's first line."""

    detail: str | None
    """Everything after it, paragraphs flattened; `None` when the docstring is one line."""


def prose_of(docstring: str | None, where: str) -> Prose:
    """Split one docstring into its brief and its detail, or fail naming the declaration.

    The rule is PEP 257's: a summary line, then a blank line, then the rest. It is enforced here
    rather than in a gate over the emitted JSON because here is where the author is standing — a
    first paragraph that wraps over two lines is a mistake to be told about at the `def`, not three
    steps later under a name the author has to go looking for.
    """
    if docstring is None or not docstring.strip():
        raise SystemExit(
            f"{where} has no docstring. Every catalogued declaration's documentation is shown to a "
            "model, so an undocumented one would reach it as a bare signature."
        )
    lines = docstring.strip("\n").splitlines()
    brief = lines[0].strip()
    if not brief:
        raise SystemExit(f"{where}'s docstring opens with a blank line rather than with a brief.")
    rest = lines[1:]
    if rest and rest[0].strip():
        raise SystemExit(
            f"{where}'s brief runs over more than one line. The first line of a docstring is the "
            "brief and everything after the blank line that follows it is the detail, so a first "
            f"paragraph that wraps has no brief in it: {brief!r}"
        )
    detail = reflow("\n".join(rest))
    return Prose(brief=brief, detail=detail or None)


def sections(function: griffe.Function, kind: griffe.DocstringSectionKind) -> list[Any]:
    """The parsed docstring sections of one kind, or nothing when there is no docstring."""
    docstring = function.docstring
    if docstring is None:
        return []
    return [section for section in docstring.parsed if section.kind is kind]


def returned(function: griffe.Function, where: str) -> list[str]:
    """The `Returns:` section's prose, as the one line it becomes in the detail.

    griffe parses a Google-style `Returns:` into its own section and this reflector used to ask for
    the `text` and `raises` sections alone, so every sentence an author wrote there was parsed,
    discarded, and never seen by a model. That is the failure worth naming: nothing was blank,
    nothing was missing, the build was green, and the only way to find it was to count the sections
    in the sources against the lines in the catalogue.

    Google's own form has no name before the description on a return, so the entry is one paragraph
    and the line reads `Returns: …` — the type is already in the signature above it, and repeating
    it there would be words that carry nothing.

    The one shape refused is a **second entry**, and it is refused because of how it arises. griffe
    reads every line at the section's own indent as a return of its own, so a description wrapped
    back to that indent silently becomes two returns and reaches a model as two sentences filed as
    two answers. Continuation lines are indented one level further, exactly as an `Args:` entry's
    are, and this says so where the author is standing.
    """
    entries = [
        entry
        for section in sections(function, griffe.DocstringSectionKind.returns)
        for entry in section.value
    ]
    if len(entries) > 1:
        raise SystemExit(
            f"{where} documents {len(entries)} returns, and a function has one. A `Returns:` "
            "description that wraps back to the section's own indent is read as a second return; "
            "indent the continuation lines one level further."
        )
    return [f"Returns: {flatten(entry.description)}" for entry in entries]


def check_return_doc(function: griffe.Function, where: str) -> None:
    """A call that hands something back says what, and a call that hands nothing back says nothing.

    Both halves are enforced. A function annotated with anything but `None` puts a value in a
    program's hands, and the annotation alone names its type without saying which part of it answers
    the question that was asked — `ReclaimReport` is four numbers, and only one of them is the
    reason to have called. A function annotated `-> None` already says the whole of it in the
    annotation, so a `Returns:` section there could only restate the brief, which is the unnecessary
    words the register forbids.

    It is checked at the declaration, where the author is standing, rather than left to a count
    somebody takes later.
    """
    documented = bool(sections(function, griffe.DocstringSectionKind.returns))
    annotation = annotation_of(function.returns) or "None"
    hands = annotation != "None"
    if hands and not documented:
        raise SystemExit(
            f"{where} hands back `{annotation}` and its docstring has no `Returns:` section. A "
            "model reading the annotation still has to be told which part of the value answers the "
            "question it asked."
        )
    if not hands and documented:
        raise SystemExit(
            f"{where} hands nothing back and documents a `Returns:` section. `None` is the whole "
            "answer, and a line restating it is words a reader pays for and learns nothing from."
        )


def documentation(function: griffe.Function, where: str) -> Prose:
    """The model-facing brief and detail for one function: its prose, what it hands back, what it raises.

    The `Returns:` and `Raises:` sections are folded into the detail rather than dropped, because
    what a call hands back and what it does when it fails are half of what is needed to write a
    program that uses one and survives the other — and a Google-style docstring is where a Python
    author puts both. Each is folded in as its own paragraph, so the brief is unaffected whatever a
    function returns or raises.

    `Raises` rather than `# Errors` or `Throws`, and that is Python's own word rather than gg's:
    the statement is `raise`, and Google's docstring convention names the section `Raises:`. Nothing
    here renames what the author wrote.
    """
    text = sections(function, griffe.DocstringSectionKind.text)
    prose = prose_of(text[0].value if text else None, where)
    folded = [
        *returned(function, where),
        *(
            f"Raises `{entry.annotation}`: {flatten(entry.description)}"
            for section in sections(function, griffe.DocstringSectionKind.raises)
            for entry in section.value
        ),
    ]
    if not folded:
        return prose
    detail = "\n\n".join(part for part in [prose.detail, *folded] if part)
    return Prose(brief=prose.brief, detail=detail)


def parameter_docs(function: griffe.Function, where: str) -> dict[str, str]:
    """The `Args:` entries, keyed by the parameter each describes."""
    docs: dict[str, str] = {}
    for section in sections(function, griffe.DocstringSectionKind.parameters):
        for described in section.value:
            if described.name in docs:
                raise SystemExit(f"{where} documents `{described.name}` twice.")
            docs[described.name] = flatten(described.description)
    return docs


# --- Identity ------------------------------------------------------------------------------------


def decorated_with(function: griffe.Function, decorator_name: str) -> str | None:
    """The one string literal `decorator_name` was applied with, or `None` when it is not applied.

    Read off the decorator's own source text rather than by importing the module, because griffe never
    imports: the decorator expression arrives as written, and what is wanted from it is the one string
    literal it was called with.
    """
    for decorator in function.decorators:
        written = str(decorator.value)
        match = re.fullmatch(rf"{decorator_name}\(\s*[\"']([^\"']+)[\"']\s*,?\s*\)", written)
        if match is not None:
            return match.group(1)
    return None


def operation_of(function: griffe.Function) -> str | None:
    """The gg operation `function`'s `@operation` decorator names, or `None` when it carries none."""
    return decorated_with(function, OPERATION_DECORATOR)


def alias_of(function: griffe.Function) -> str | None:
    """The gg operation `function`'s `@alias` decorator names, or `None` when it carries none.

    A method carrying one is a **second way to reach** that operation rather than a second binding of
    it: it calls the module-level function, inherits its gate, and adds nothing to what this arm
    covers. The two decorators are read from the same place and are mutually exclusive, which
    [`member_functions`](#member_functions) enforces.
    """
    return decorated_with(function, ALIAS_DECORATOR)


# --- Types ---------------------------------------------------------------------------------------


@dataclass
class Declared:
    """One type this SDK declares, as the catalogue carries it and as the closure resolves it."""

    fqn: str
    """Its module-qualified fully-qualified name — `gg.files.FileRead`."""

    module: str
    """The gg module id it belongs to."""

    name: str
    """Its bare name, which is what every signature in this SDK writes."""

    entry: dict[str, Any]
    """The catalogue entry, ready to emit."""

    mentions: set[str] = field(default_factory=set)
    """The bare names its own declaration refers to — the edges the closure walks."""

    methods: list[griffe.Function] = field(default_factory=list)
    """The public methods declared on it, in declaration order.

    Every one of them is an alias today, and the reflector refuses any other kind: a method that
    bound an operation of its own would be a capability reachable only from a value, which no other
    arm's coverage would include.
    """


def base_names(cls: griffe.Class) -> list[str]:
    """The class's bases, by name."""
    return [str(base) for base in cls.bases]


def annotation_of(expression: Any) -> str:
    """One annotation, as the SDK wrote it."""
    return "" if expression is None else str(expression)


def member_prose(owner: str, name: str, member: Any) -> Prose:
    """One member's brief and detail, or a build error naming what is missing."""
    docstring = getattr(member, "docstring", None)
    return prose_of(
        None if docstring is None else docstring.value, f"the member `{owner}.{name}`"
    )


def declare_type(module: str, path: str, name: str, declared: Any) -> Declared:
    """One type, as the catalogue carries it: its declaration, its prose, and a line per member.

    Three shapes reach a model through this: a **dataclass**, whose members are its fields; an
    **enum**, whose members are values rather than fields and so carry no type of their own; and a
    **union alias**, which is a name for two classes catalogued in their own right and so has no
    members here.
    """
    fqn = f"{path}.{name}"
    docstring = getattr(declared, "docstring", None)
    prose = prose_of(None if docstring is None else docstring.value, f"the type `{fqn}`")

    if isinstance(declared, griffe.Attribute):
        written = annotation_of(declared.value)
        return Declared(
            fqn=fqn,
            module=module,
            name=name,
            entry={
                "fqn": fqn,
                "module": module,
                "name": name,
                "declaration": f"{name} = {written}",
                "brief": prose.brief,
                "detail": prose.detail,
                "members": [],
                "memberFunctions": [],
            },
            mentions=identifiers(written),
        )

    bases = base_names(declared)
    members: list[dict[str, Any]] = []
    lines: list[str] = []
    mentions: set[str] = set()
    if "Enum" in bases:
        header = f"class {name}(Enum):"
        for member_name, member in declared.members.items():
            if not isinstance(member, griffe.Attribute):
                continue
            lines.append(f"    {member_name}")
            member_text = member_prose(name, member_name, member)
            members.append(
                {
                    "name": member_name,
                    # A member is the value, not a field holding one, so it carries no type beside
                    # itself. Its wire spelling is deliberately not shown: the member's NAME is the
                    # API, and a model shown `PENDING = "pending"` would reach for the string.
                    "type": None,
                    "kind": "variant",
                    "brief": member_text.brief,
                    "detail": member_text.detail,
                }
            )
    else:
        decorators = [str(decorator.value) for decorator in declared.decorators]
        inherits = f"({', '.join(bases)})" if bases else ""
        header = "\n".join([*[f"@{decorator}" for decorator in decorators], f"class {name}{inherits}:"])
        mentions.update(*(identifiers(base) for base in bases) or [set()])
        for member_name, member in declared.members.items():
            if not isinstance(member, griffe.Attribute) or member_name.startswith("_"):
                continue
            annotation = annotation_of(member.annotation)
            lines.append(f"    {member_name}: {annotation}")
            mentions.update(identifiers(annotation))
            member_text = member_prose(name, member_name, member)
            members.append(
                {
                    "name": member_name,
                    "type": annotation,
                    "kind": "field",
                    "brief": member_text.brief,
                    "detail": member_text.detail,
                }
            )
    if not members:
        raise SystemExit(f"the type `{fqn}` declares no members a model could read.")
    return Declared(
        fqn=fqn,
        module=module,
        name=name,
        entry={
            "fqn": fqn,
            "module": module,
            "name": name,
            "declaration": "\n".join([header, *lines]),
            "brief": prose.brief,
            "detail": prose.detail,
            "members": members,
            # Filled in below, once every method has an entry of its own to be a one-line brief of.
            "memberFunctions": [],
        },
        mentions=mentions,
        methods=member_functions(fqn, declared),
    )


def member_functions(fqn: str, declared: griffe.Class) -> list[griffe.Function]:
    """The public methods a type declares, refusing one that is not an alias.

    A method here is a **convenience over a value the SDK already handed back** — `hit.read()` for
    the memory a search matched — and the rule that keeps it that is the one this refuses under:
    every public method carries `@alias`, and none carries `@operation`. A method binding an
    operation of its own would be a capability an agent could reach only by first obtaining an
    instance, which is exactly the shape the whole API-object surface was abolished for.

    A private method is skipped by the leading underscore, which is Python's own way of saying a
    declaration is not surface.
    """
    found: list[griffe.Function] = []
    for name, member in declared.members.items():
        if not isinstance(member, griffe.Function) or name.startswith("_"):
            continue
        where = f"the method `{fqn}.{name}`"
        if operation_of(member) is not None:
            raise SystemExit(
                f"{where} carries `@{OPERATION_DECORATOR}`. A method is a second way to reach an "
                "operation a module-level function already binds, so it carries "
                f"`@{ALIAS_DECORATOR}`; an operation reachable only from a value is one no other "
                "arm would cover."
            )
        if alias_of(member) is None:
            raise SystemExit(
                f"{where} is public and names no gg operation. Write "
                f'`@{ALIAS_DECORATOR}("<namespace>.<key>")` on it, or make it private: a method gg '
                "cannot resolve is dropped from search, from every directory and from every "
                "documentation view."
            )
        found.append(member)
    return found


IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
"""Every identifier in a piece of written type text, which is what a reference is looked up by.

The SDK's type names are unique across its thirteen modules, so a bare name resolves to exactly one
declaration and the lookup needs no scope. That uniqueness is asserted below rather than assumed.
"""


def identifiers(text: str) -> set[str]:
    """The identifiers a piece of written text mentions."""
    return set(IDENTIFIER.findall(text))


# --- Signatures ----------------------------------------------------------------------------------


def signature_of(function: griffe.Function, name: str, where: str) -> dict[str, Any]:
    """One shape a function may be called in: the signature a model reads, and its parameters.

    Python has one shape per function — an optional argument is a default, never an overload — so
    every entry this reflector emits carries exactly one signature. The `signatures` array is still an
    array, because the count is *spelling*: an overloading language carries two where this carries
    one, and nothing downstream compares them.
    """
    docs = parameter_docs(function, where)
    rendered: list[str] = []
    parameters: list[dict[str, Any]] = []
    starred = False
    for parameter in function.parameters:
        # The receiver is not an argument. `view.close()` documents nothing and takes the view it
        # closes, because the thing it takes is the thing it hangs off — and a `self` rendered into
        # the signature would tell a model to write a call it cannot write.
        if parameter.name == "self":
            continue
        if parameter.kind is griffe.ParameterKind.keyword_only and not starred:
            rendered.append("*")
            starred = True
        annotation = annotation_of(parameter.annotation)
        default = None if parameter.default is None else str(parameter.default)
        piece = f"{parameter.name}: {annotation}" if annotation else parameter.name
        rendered.append(f"{piece} = {default}" if default is not None else piece)
        description = docs.pop(parameter.name, None)
        if description is None:
            raise SystemExit(
                f"{where} declares `{parameter.name}` and its docstring has no `Args:` entry for "
                "it. Every argument a model is asked to fill in is described where it is declared."
            )
        parameters.append(
            {
                "name": parameter.name,
                "type": annotation,
                "optional": parameter.default is not None,
                # Keyword-only arguments are what this language's optional ones are: `kind` is the
                # one axis of calling convention that changes what a model must WRITE.
                "kind": (
                    "keyword"
                    if parameter.kind is griffe.ParameterKind.keyword_only
                    else "positional"
                ),
                "default": default,
                "doc": description,
                # Python has no structured argument written inline at a call site: this SDK spells a
                # membrane record's fields out as the function's own arguments, so there is never a
                # second level to document.
                "fields": [],
            }
        )
    if docs:
        raise SystemExit(
            f"{where}'s docstring documents {sorted(docs)}, which its signature does not declare. A "
            "renamed argument left behind under its old name reads perfectly and tells a model to "
            "write something the call will not accept."
        )
    returns = annotation_of(function.returns) or "None"
    return {
        "signature": f"{name}({', '.join(rendered)}) -> {returns}",
        "parameters": parameters,
    }


# --- The reference closure -----------------------------------------------------------------------


class Resolver:
    """Every declared type, and the closure over what a piece of written text refers to."""

    def __init__(self, declared: Iterable[Declared]) -> None:
        self.by_name: dict[str, Declared] = {}
        for declaration in declared:
            if declaration.name in self.by_name:
                raise SystemExit(
                    f"two modules declare a type called `{declaration.name}`. This SDK's signatures "
                    "write a bare name, so two declarations answering to one would make the lookup "
                    "that resolves it a coin toss."
                )
            self.by_name[declaration.name] = declaration

    def closure(self, *written: str) -> list[Declared]:
        """Every declaration the written text refers to, closed transitively, in declaration order.

        Transitively, because a declaration that names a type the catalogue does not also carry is a
        dangling reference in front of the model: `context.search_archive` returns an `ArchiveSearch`,
        whose declaration is only useful alongside `ArchiveHit`.
        """
        seen: dict[str, Declared] = {}
        pending = [name for text in written for name in identifiers(text)]
        while pending:
            name = pending.pop()
            declaration = self.by_name.get(name)
            if declaration is None or name in seen:
                continue
            seen[name] = declaration
            pending.extend(declaration.mentions)
        return [
            declaration for declaration in self.by_name.values() if declaration.name in seen
        ]

    def references(self, *written: str) -> list[dict[str, str]]:
        """The closure, as the catalogue's resolved type references."""
        return [
            {"spelled": declaration.name, "fqn": declaration.fqn}
            for declaration in self.closure(*written)
        ]

    def direct(self, written: str) -> list[dict[str, str]]:
        """Only the declarations `written` itself names, as resolved references.

        The **return position** is this rather than the closure, and the difference is what a reader
        of it spends: opening a function's return type is meant to land on the one value the call
        hands back, not on that value's fields and their fields. The closure answers a different
        question — what can this agent reach at all — and is what `types` carries.
        """
        names = identifiers(written)
        return [
            {"spelled": declaration.name, "fqn": declaration.fqn}
            for declaration in self.by_name.values()
            if declaration.name in names
        ]


# --- The libraries -------------------------------------------------------------------------------

LIBRARY_SOURCE = SRC_DIR / "library.py"
"""The module whose module-scope imports *are* the library set.

`componentize-py` bakes the entry module's executed import closure, so what this file imports is
what a program can import — a bake-time fact about the artifact rather than a policy. See its own
docstring for why, and `crates/gg/src/sandbox/language/python.substrate.test.rs` for the test that
asks the baked component whether every name below really landed.
"""

GROUP_HEADER = re.compile(r"^#\s*-{3,}\s*(?P<title>.+?)\s*-{3,}\s*$")
"""The comment a group of imports is filed under: `# --- Time ------`.

Model-facing text that is written **on the code that decides the set**, which is the same rule every
signature and every argument description in this file obeys. A prompt that grouped these libraries in
a table of its own would be a second copy of `library.py` to keep in step.
"""


def libraries() -> list[dict[str, Any]]:
    """The importable library set, grouped as `library.py` groups it.

    Read off the source text rather than out of `griffe`, because what is wanted is the *statements*
    — including the comment headers, which no API reflector reports — and because the answer must be
    the dotted name a program writes: `urllib.parse` is importable and `urllib.robotparser` is not,
    so a list flattened to top-level packages would overclaim exactly the way the prose it replaces
    did.

    Four properties are enforced, on the rule the rest of this reflector obeys — nothing a model
    reads may be written anywhere but on the code it describes, and a gap is a build error rather
    than a blank in a prompt:

      * every module-scope import falls under a group header, so none is silently ungrouped;
      * the statements this scan found are exactly the module-scope imports `ast` reports, so a
        shape the scan does not understand is an error rather than a quiet omission;
      * `library.py` uses `import x` only — a `from x import y` imports a *name*, which is not
        something a program can be told it may import;
      * no name is listed twice, in one group or across two.
    """
    source = LIBRARY_SOURCE.read_text(encoding="utf-8")
    grouped: list[dict[str, Any]] = []
    seen: dict[str, str] = {}
    title: str | None = None
    for number, line in enumerate(source.splitlines(), start=1):
        header = GROUP_HEADER.match(line)
        if header is not None:
            title = header["title"]
            grouped.append({"group": title, "modules": []})
            continue
        if not line.startswith("import "):
            continue
        name = line.removeprefix("import ").strip()
        if title is None:
            raise SystemExit(
                f"{LIBRARY_SOURCE}:{number} imports `{name}` before any `# --- <group> ---` header, "
                "so a model would be told about a library under no heading."
            )
        if name in seen:
            raise SystemExit(
                f"{LIBRARY_SOURCE}:{number} imports `{name}` a second time (already under "
                f"`{seen[name]}`)."
            )
        seen[name] = title
        grouped[-1]["modules"].append(name)

    declared = set()
    for node in ast.parse(source).body:
        if isinstance(node, ast.ImportFrom):
            raise SystemExit(
                f"{LIBRARY_SOURCE}:{node.lineno} uses `from … import …`. This file's imports are the "
                "list of modules a program may import, and a name imported out of one is not a "
                "module."
            )
        if isinstance(node, ast.Import):
            declared.update(alias.name for alias in node.names)
    if declared != set(seen):
        missed = sorted(declared - set(seen)) or sorted(set(seen) - declared)
        raise SystemExit(
            f"{LIBRARY_SOURCE}'s module-scope imports and the grouped scan disagree about {missed}. "
            "The scan reads `import x` at the start of a line; write the import that way, or teach "
            "this function the shape."
        )

    for group in grouped:
        if not group["modules"]:
            raise SystemExit(
                f"the `{group['group']}` group in {LIBRARY_SOURCE} has no imports under it."
            )
        group["modules"].sort()
    return grouped


# --- The catalogue -------------------------------------------------------------------------------


def public_names(module: griffe.Module, where: str) -> list[str]:
    """The names a capability module declares public, in the order `__all__` lists them.

    `__all__` is Python's own declaration of a module's public surface, and it is the whole of this
    arm's public-surface rule: a name in it is model-facing, a name outside it is not. It is read off
    the source rather than evaluated, exactly as every other fact here is.
    """
    exported = module.members.get("__all__")
    if exported is None:
        raise SystemExit(
            f"{where} declares no `__all__`, so nothing says which of its names are model-facing."
        )
    listed = set(re.findall(r"[\"']([^\"']+)[\"']", str(exported.value)))
    # Walked in DECLARATION order rather than in `__all__`'s, because the order is model-facing: it
    # is the sequence a documentation view appends its types in and the sequence the catalogue
    # presents this module in. `__all__` is sorted so that a reader can find a name in it, which is
    # the opposite of the order the SDK was written to be read in.
    declared = [name for name in module.members if name in listed]
    missing = sorted(listed.difference(declared))
    if missing:
        raise SystemExit(f"{where} exports {missing} and does not define them.")
    return declared


def build() -> str:
    """The whole catalogue, as the JSON text the guests directory carries."""
    catalogue = load_catalogue()
    sources = load_sources()
    package = catalogue.PACKAGE

    modules: list[dict[str, Any]] = []
    declared: list[Declared] = []
    functions: list[tuple[str, str, str, griffe.Function]] = []

    for module_id in catalogue.MODULE_ORDER:
        path = f"{package}.{module_id}"
        try:
            module = sources[module_id]
        except KeyError:
            raise SystemExit(f"`{path}` is in MODULE_ORDER and the package has no such module.") from None
        prose = prose_of(
            None if module.docstring is None else module.docstring.value, f"the module `{path}`"
        )
        modules.append(
            {
                "id": module_id,
                "path": path,
                "brief": prose.brief,
                "detail": prose.detail,
                # `None`, and honestly: gg injects this SDK into a program's scope, so a documented
                # import would be a line a model would be wrong to think it had to write.
                "import": None,
            }
        )
        for name in public_names(module, f"`{path}`"):
            member = module.members[name]
            if isinstance(member, griffe.Function):
                functions.append((module_id, path, name, member))
            elif name.isupper():
                # A module-level CONSTANT rather than a type — `UNCHANGED` is the value and
                # `Unchanged` is the type it is a member of — and PEP 8's own casing is what tells
                # the two apart. The value travels with its type's declaration rather than as a
                # declaration of its own, because a documentation view of a single value would carry
                # nothing the type's own view does not.
                continue
            else:
                declared.append(declare_type(module_id, path, name, member))

    resolver = Resolver(declared)
    reached: set[str] = set()
    emitted: list[dict[str, Any]] = []
    claimed: dict[str, str] = {}

    for module_id, path, name, function in functions:
        fqn = f"{path}.{name}"
        where = f"`{fqn}`"
        operation = operation_of(function)
        if operation is None:
            raise SystemExit(
                f"{where} is public and names no gg operation. Write `@operation(\"<namespace>."
                "<key>\")` on the declaration: an entry gg cannot resolve is dropped from search, "
                "from every directory and from every documentation view."
            )
        if operation in claimed:
            raise SystemExit(
                f"{where} and `{claimed[operation]}` both claim the gg operation `{operation}`."
            )
        claimed[operation] = fqn
        check_return_doc(function, where)
        prose = documentation(function, where)
        signature = signature_of(function, name, where)
        returned = annotation_of(function.returns)
        written = [parameter["type"] for parameter in signature["parameters"]]
        types = resolver.references(returned, *written, *ALWAYS_REFERENCED)
        reached.update(reference["fqn"] for reference in types)
        emitted.append(
            {
                "operation": operation,
                # A module-level function is the BINDING of its operation. The second way to reach
                # one, where this SDK offers a second way, is a method on the value the operation's
                # result carries, and those are emitted below with `aliasOf` filled in.
                "aliasOf": None,
                "module": module_id,
                "kind": "function",
                "receiver": None,
                "name": name,
                "fqn": fqn,
                # The fully-qualified name IS what a program writes: `gg.files.read_file` resolves
                # after `import gg`, and the module the scope binds makes `files.read_file` the same
                # object. There is no third spelling for a call site to need.
                "call": None,
                "brief": prose.brief,
                "detail": prose.detail,
                "signatures": [signature],
                "returns": resolver.direct(returned),
                "types": types,
            }
        )

    # The methods, after every module-level function, so that an alias can be held to naming an
    # operation this arm really binds. A dangling one would leave the operation uncovered and gate
    # the method on something the arm does not offer, which the coverage gate would report as a
    # sentence about gg rather than about the SDK.
    for declaration in declared:
        for method in declaration.methods:
            name = method.name
            fqn = f"{declaration.fqn}.{name}"
            where = f"`{fqn}`"
            operation = alias_of(method)
            if operation not in claimed:
                raise SystemExit(
                    f"{where} is an alias of `{operation}`, which no function in this SDK binds. An "
                    "alias is a second way to reach an operation, so one standing alone leaves the "
                    "operation uncovered and itself gated by something the arm does not offer."
                )
            check_return_doc(method, where)
            prose = documentation(method, where)
            signature = signature_of(method, name, where)
            method_returns = annotation_of(method.returns)
            written = [parameter["type"] for parameter in signature["parameters"]]
            types = resolver.references(method_returns, *written, *ALWAYS_REFERENCED)
            reached.update(reference["fqn"] for reference in types)
            emitted.append(
                {
                    "operation": operation,
                    "aliasOf": operation,
                    "module": declaration.module,
                    "kind": "method",
                    "receiver": declaration.name,
                    "name": name,
                    "fqn": fqn,
                    "call": None,
                    "brief": prose.brief,
                    "detail": prose.detail,
                    "signatures": [signature],
                    "returns": resolver.direct(method_returns),
                    "types": types,
                }
            )
            declaration.entry["memberFunctions"].append(
                {
                    "operation": operation,
                    "name": name,
                    "fqn": fqn,
                    # The brief alone. A type's documentation view is a menu of what can be done
                    # next with the value, and the whole of each entry is one docview away.
                    "brief": prose.brief,
                }
            )

    unreached = [declaration.fqn for declaration in declared if declaration.fqn not in reached]
    if unreached:
        raise SystemExit(
            f"{unreached} are declared and nothing refers to them, so no documentation view of one "
            "could ever be opened. Remove them, or refer to them from the signature that produces "
            "one."
        )

    return (
        json.dumps(
            {
                "schema": SCHEMA,
                "language": LANGUAGE,
                "generatedFrom": GENERATED_FROM,
                "libraries": libraries(),
                "modules": modules,
                "functions": emitted,
                "types": [declaration.entry for declaration in declared],
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", required=True, type=Path)
    arguments = parser.parse_args()

    out = arguments.out_dir / f"{LANGUAGE}.signatures.json"
    catalogue = build()
    arguments.out_dir.mkdir(parents=True, exist_ok=True)
    out.write_text(catalogue, encoding="utf-8")
    parsed = json.loads(catalogue)
    print(
        f"Wrote {out} ({len(parsed['modules'])} modules, {len(parsed['functions'])} functions, "
        f"{len(parsed['types'])} types, "
        f"{sum(len(group['modules']) for group in parsed['libraries'])} libraries)."
    )


if __name__ == "__main__":
    sys.exit(main())
