#!/usr/bin/env bash
# Reflect the Rust arm's signature catalogue out of its SDK, and write
# `$GG_SIGNATURES_OUT_DIR/rust.signatures.json`.
#
# gg embeds that file and answers every documentation SEARCH and every documentation VIEW out of it,
# so it is the whole of what a model can learn about this arm's surface. The responses-as-code system
# prompt takes only the module paths and the one-line brief each module introduces itself by, and
# names no function at all; the `libraries` section is the record of the library set rather than
# anything rendered. Every word of it is reflected out of the SDK's own declarations by
# `tools/signatures.py`, which reads the JSON `rustdoc` itself emits — so a sentence a model reads is
# rustdoc's own reading of the declaration it describes rather than prose typed into a table beside
# it.
#
# WHERE IT WRITES, AND WHY THERE IS NO DEFAULT. The catalogue is a BUILD ARTIFACT.
# `crates/gg/build.rs` runs `scripts/gg-signatures.sh` and embeds what lands in the build's own
# `OUT_DIR`, so a doc comment edited without a regeneration is not a state this checkout can be in:
# the next build of gg reflects it. A default here would be a second answer to a question the build
# already answers, and the old one — `crates/gg/src/sandbox/guests/` — is the answer that stopped
# being right. Run it by hand, into a directory of your choosing, to READ a catalogue; that is what
# `scripts/gg-signatures.sh` is for, and it is how a reflector bug gets found.
#
# WHAT IT NEEDS. This checkout's own `cargo` and `rustdoc`, the `wasm32-unknown-unknown` standard
# library (`scripts/ci/install-gg-toolchains.sh`), and `src/bindings.rs` — which is generated rather
# than committed, so it runs `bindings.sh` first when that file is missing, fetching the pinned
# `wit-bindgen` once.
#
# WHAT IT MUST NOT DO IS REBUILD THE LIBRARY SET, and that is why the bindings live in their own
# script rather than inside `build.sh`. `build.sh` cuts this arm's compile inputs —
# `rust.libraries.tar.gz` and `rust.toolchain.json` — and that is 9.4 MB of compiler-version-locked
# rlibs and several seconds of `cargo`. A fresh checkout never has `src/bindings.rs`, so a signature
# step that reached `build.sh` for it would re-cut the whole set every time a catalogue was
# reflected.
#
# THAT ARGUMENT IS STRONGER NOW THAN WHEN IT WAS WRITTEN, not weaker. Both halves are generated
# during `cargo build`: `crates/gg-sandbox-artifacts/rust` runs `build.sh` and `crates/gg/build.rs`
# runs this, each with its own rerun set. Folding the set's build into this one would collapse those
# two sets into one, so editing a doc comment would re-link every rlib — exactly the inner-loop cost
# the artifact crates exist to avoid. `bindings.sh` remains the one step both callers need, split out
# of the one that has side effects. This writes exactly one file: the catalogue named above.
#
# WHY `RUSTC_BOOTSTRAP=1`. `rustdoc`'s JSON output is unstable, and this repository pins a STABLE
# toolchain — deliberately, because an rlib is compiler-version-private and the arm must be built by
# the one compiler every checkout has. The alternative is a second toolchain in every developer's
# checkout and in CI, pinned separately, to read documentation out of a crate the first one compiles.
# The format version is asserted below, so a rustc bump that changes it fails here by name rather
# than producing a catalogue with a field missing.
#
# Usage:
#   GG_SIGNATURES_OUT_DIR=<dir> packages/gg-sandbox-rust/signatures.sh
#   scripts/gg-signatures.sh                 # all eleven arms, into one directory
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# NO BYTECODE CACHE. `tools/signatures.py` imports its sibling `tools/catalogue.py`, and an ordinary
# CPython drops a `__pycache__/` beside a module it imports. That directory is gitignored and
# harmless to a person, but `crates/gg/build.rs` names this package's `tools` subtree as an input
# whose change should re-reflect the catalogue — so a run that writes into it leaves the next
# `cargo build` convinced its inputs moved and re-runs all eleven arms. The export lives here rather
# than only in `scripts/gg-signatures.sh` because running this script BY HAND is the documented way
# to read a catalogue, and a developer who does that should not pay for it on their next build.
export PYTHONDONTWRITEBYTECODE=1

if [ -z "${GG_SIGNATURES_OUT_DIR:-}" ]; then
	echo "error: GG_SIGNATURES_OUT_DIR is not set. It names the directory this catalogue is" >&2
	echo "       written into, and there is no default — the catalogue is generated by the build" >&2
	echo "       rather than committed anywhere." >&2
	echo "       Run scripts/gg-signatures.sh (which sets it and regenerates every arm), or set" >&2
	echo "       it yourself to a directory you want the JSON in." >&2
	exit 1
fi
# Created, then made absolute: `cargo rustdoc` below runs from this package's own directory, so a
# relative destination would mean two different places depending on who called this.
mkdir -p "$GG_SIGNATURES_OUT_DIR"
OUT="$(cd "$GG_SIGNATURES_OUT_DIR" && pwd)/rust.signatures.json"

# shellcheck source=packages/gg-sandbox-rust/rust-version.sh
source "$HERE/rust-version.sh"

# ONE ARM, ONE PROCESS AT A TIME. This package's scratch is a fixed path inside the source tree
# rather than a `mktemp -d`, deliberately — it is a cache — and two cargo processes with two target
# directories do not serialise with each other. See `scripts/gg-scratch-lock.sh`.
# shellcheck source=scripts/gg-scratch-lock.sh
source "$HERE/../../scripts/gg-scratch-lock.sh"
gg_lock_scratch "$HERE"

# The rustdoc JSON format this reflector reads. It is a version of `rustdoc`'s output rather than of
# `rustdoc`, and it moves on its own schedule; pinning it here is what turns "the catalogue came out
# subtly wrong" into "this script stopped".
EXPECTED_FORMAT_VERSION=57

if ! rustc --print target-libdir --target "$GG_RUST_TARGET" >/dev/null 2>&1; then
	echo "error: the $GG_RUST_TARGET standard library is not installed." >&2
	echo "       Run scripts/ci/install-gg-toolchains.sh." >&2
	exit 1
fi

# UNCONDITIONALLY, not "when the file is missing", and the difference is a real defect rather than a
# style choice. `src/bindings.rs` is a pure function of `crates/gg/wit` and the pinned `wit-bindgen`,
# and it is generated rather than committed — so a checkout that has reflected this arm once already
# has one, from whatever the wire said at the time. Regenerating only when it is absent means that an
# edit to `crates/gg/wit` re-runs this reflection (build.rs names the wire as an input, correctly)
# and the reflection then documents the SDK against bindings from the OLD wire. The Swift and C++
# arms call their own `bindings.sh` on every run for exactly this reason; this arm was the odd one
# out, and `.dockerignore` already keeps a developer's `src/bindings.rs` out of an image build to
# stop the same thing happening there. It costs one `wit-bindgen` invocation — a fraction of a second
# against the rustdoc build below — and the pinned binary is fetched only on a cold `.build/`.
#
# Rewriting it on every run is safe for the build's own inputs: `crates/gg/build.rs` enumerates this
# package's `src` a file at a time precisely so that this one generated file is NOT among the paths
# whose mtime would re-trigger the next build.
echo "==> generating the WIT bindings (they are not committed)"
"$HERE/bindings.sh"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Documented for the same target a program is compiled to, so the types in the catalogue are the
# types a program is compiled against rather than a host build's.
echo "==> documenting the SDK with rustdoc"
(
	cd "$HERE"
	RUSTC_BOOTSTRAP=1 CARGO_TARGET_DIR="$WORK/target" \
		cargo rustdoc --quiet --target "$GG_RUST_TARGET" -- \
		-Zunstable-options --output-format json
)

DOC="$WORK/target/$GG_RUST_TARGET/doc/gg.json"
observed="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["format_version"])' "$DOC")"
if [ "$observed" != "$EXPECTED_FORMAT_VERSION" ]; then
	echo "error: rustdoc $GG_RUST_VERSION emits JSON format $observed, and this reflector reads" >&2
	echo "       format $EXPECTED_FORMAT_VERSION. Read tools/signatures.py against the new" >&2
	echo "       format, fix what moved, and update EXPECTED_FORMAT_VERSION here." >&2
	exit 1
fi

echo "==> reflecting the catalogue"
python3 "$HERE/tools/signatures.py" "$DOC" "$HERE/Cargo.toml" "$OUT"
