// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` (and `crates/worker` / `crates/backend`), which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.

/**
 * The `error` member of an [`ErrorEnvelope`]: a stable machine-readable code and
 * a human-readable message.
 */
export type ErrorBody = { code: string; message: string };

/**
 * The JSON body of an error response: `{ "error": { "code", "message" } }`.
 */
export type ErrorEnvelope = { error: ErrorBody };

export type CatalogCase = { slug: string; versions: Array<string> };

export type CatalogResponse = { testCases: Array<CatalogCase> };

export type VersionsResponse = { slug: string; versions: Array<string> };
