// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` and `crates/backend`, which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.

import type { CostMetrics, TokenMetrics } from "./index";

/**
 * A binding of a model to a named slot in a [`GgCapabilitySet`].
 *
 * Model selection is expressed through slots so capabilities reference models by
 * role (`"primary"`, `"reviewer"`, …) rather than by a hardcoded id, and a study can
 * re-point a slot — even to a different provider — without touching capability logic.
 */
export type GgSlotBinding = {
  /**
   * The slot name capabilities reference (for example [`PRIMARY_SLOT`]).
   */
  slot: string;
  /**
   * The opaque model id bound to the slot, passed through to the model client.
   */
  modelId: string;
  /**
   * The provider the model is reached through, when it must be pinned rather than
   * inferred from the id — the seam that makes a slot cross-provider. `None` lets
   * the client resolve the provider from the id.
   */
  provider?: string;
};

/**
 * The configuration of a single capability within a [`GgCapabilitySet`].
 *
 * A capability is identified by a stable [`id`](Self::id) (an open string, not a
 * closed enum, so later phases add capabilities freely), can be toggled
 * [on or off](Self::enabled), can select among alternate
 * [implementations](Self::implementation) for A/B comparisons, and carries
 * free-form [`params`](Self::params) for tuning.
 */
export type GgCapabilityConfig = {
  /**
   * The capability's stable id (for example `"shell"`, `"compaction"`, or
   * `"subagents"`). Stable across versions so recorded configurations stay
   * comparable.
   */
  id: string;
  /**
   * Whether the capability is on. Off means gg behaves as if the feature does not
   * exist — no tools for it are exposed and it consumes no context — which is the
   * basis for ablation studies.
   */
  enabled: boolean;
  /**
   * The selected implementation of the capability, when it offers more than one
   * (for example two compaction strategies or two planners). `None` selects the
   * default. This is the basis for A/B comparisons between implementations.
   */
  implementation?: string;
  /**
   * Free-form parameters for the capability (for example a compaction threshold or
   * a subagent parallelism cap), interpreted by the capability itself. Defaults to
   * an empty object.
   */
  params: Record<string, unknown>;
};

/**
 * The declarative, inspectable configuration of a gg run — its *independent
 * variable*.
 *
 * A gg run is configured by a capability set rather than a harness+model+orchestrator
 * tuple: which capabilities are on, which implementation each uses, their parameters,
 * and how models bind to [slots](GgSlotBinding). The set is expressed as data so a
 * run's exact configuration is recorded on the run and reproducible, and so
 * [result aggregation](https://docs.testcabinet.ai) can slice results by
 * configuration. Freeze the model and the test case, vary the capability set, and
 * the harness becomes a laboratory.
 *
 * The capability collection is intentionally **open**: capabilities are identified
 * by stable string id, not a closed enum, so later phases add capabilities without a
 * breaking change. A capability that is absent from [`Self::capabilities`] is
 * distinguishable from one that is present but disabled — see [`Self::is_enabled`].
 */
export type GgCapabilitySet = {
  /**
   * The name of a saved preset this set was assembled from (for example
   * `"minimal"`, `"full"`, or `"planning-A"`), when it is a named preset rather
   * than a hand-assembled configuration. A study is a sweep over presets, so this
   * records which one produced a run.
   */
  preset?: string;
  /**
   * The capabilities this run is configured with, each identified by a stable id.
   * A capability absent from this list is off *and* unconfigured; one present but
   * [disabled](GgCapabilityConfig::enabled) is off but records the configuration it
   * would have used, which keeps an ablation's on/off arms symmetric.
   */
  capabilities: Array<GgCapabilityConfig>;
  /**
   * The model-slot bindings for this run. Capabilities reference models by slot
   * name, never by a hardcoded id, so a study re-points a slot without touching any
   * capability's logic. Phase 0 binds a single [`PRIMARY_SLOT`]; the type allows
   * many, possibly cross-provider.
   */
  slots: Array<GgSlotBinding>;
  /**
   * Individual tool names to **withhold** from the agent even when the capability
   * that offers them is on — the finest-grained ablation lever, one notch below
   * toggling a whole [capability](GgCapabilityConfig::enabled).
   *
   * Because gg's modularity comes from the toolset, the *set of tools offered* is
   * itself an experimental variable: turning a capability off is the coarse way to
   * withhold its tools, and this list is the fine way — drop a single over-used or
   * competing tool (say `edit_file` while keeping `write_file`, to ask "does
   * whole-file rewriting beat patching?") without disabling the rest of its
   * capability. A named tool is not offered to the model (no schema, not
   * dispatchable) exactly as if its capability were off, and the run records the
   * resulting [effective toolset](GgSessionSummary::effective_tools) so a study can
   * slice by which tools were actually present. A name here that no enabled
   * capability offers withholds nothing (it is reported as a startup warning, not an
   * error, so a sweep can list a tool that only some arms offer).
   */
  disabledTools?: Array<string>;
};

/**
 * The **source** a context-window contribution is attributed to, for the per-source
 * accounting [context visibility] reports.
 *
 * gg's context is not a flat transcript: every item that occupies the window is tagged
 * with the source that produced it, so gg can report *what* is filling the window —
 * the signal [compaction] triggers on and the console renders as a stacked line graph.
 * The set is a **closed, stable taxonomy** (unlike the open capability ids): the
 * console's categories and their colors are keyed to these variants, and
 * [`ALL`](Self::ALL) fixes their order so a breakdown is emitted with every category
 * present (a zero when a source contributed nothing this turn), keeping the graph's
 * bands stable across turns.
 *
 * [context visibility]: https://docs.testcabinet.ai/gg/context-visibility/
 * [compaction]: https://docs.testcabinet.ai/gg/compaction/
 */
export type GgContextSource =
  | "system"
  | "user_prompt"
  | "assistant"
  | "tool_output"
  | "file_view"
  | "skill"
  | "memory"
  | "task_list"
  | "board"
  | "plan"
  | "history";

/**
 * The estimated token cost attributed to one [`GgContextSource`] at a point in the
 * run — one band of a [`ContextBreakdown`](GgTelemetryKind::ContextBreakdown).
 *
 * The token figure is an **estimate**: exact per-provider counts are not available
 * cross-provider, so gg counts with a fixed BPE tokenizer as a documented cross-model
 * approximation (see the `context` module in the `gg` crate).
 */
export type GgContextSourceUsage = {
  /**
   * The source this band accounts for.
   */
  source: GgContextSource;
  /**
   * The estimated tokens that source occupies in the context window.
   */
  tokens: number;
};

/**
 * The state of one [skill](https://docs.testcabinet.ai/gg/skills/) at a point in a run
 * — a band of a [`SkillsState`](GgTelemetryKind::SkillsState) event.
 *
 * A skill is markdown-with-front-matter authored ahead of the run; its
 * [`description`](Self::description) is shown to the model up front (so it knows the
 * skill exists and what it is for), and [`read`](Self::read) reports whether the model
 * has called `read_skill` on it — at which point the skill's body is loaded into the
 * context window and retained across a [compaction] boundary.
 *
 * [compaction]: https://docs.testcabinet.ai/gg/compaction/
 */
export type GgSkillState = {
  /**
   * The skill's stable name (from its front matter), the handle `read_skill` takes.
   */
  name: string;
  /**
   * The skill's one-line description, shown to the model up front.
   */
  description: string;
  /**
   * Whether the model has read the skill this session (loading its body into context).
   */
  read: boolean;
};

/**
 * The bounds gg enforces on the model's self-curated [memories] — a band of the
 * [`MemoryState`](GgTelemetryKind::MemoryState) event so the console can show how close
 * the model is to each limit.
 *
 * Because memories are curated by the *model itself* (unlike [skills], authored ahead of
 * the run), they must be bounded so self-curated notes cannot crowd out the working
 * context. When a write would exceed a cap, gg rejects it and instructs the model to
 * revise or evict rather than silently truncating or dropping. Lengths are measured in
 * characters of a memory's **body** (its `description` is a short one-liner, like a
 * skill's).
 *
 * [memories]: https://docs.testcabinet.ai/gg/memories/
 * [skills]: https://docs.testcabinet.ai/gg/skills/
 */
export type GgMemoryCaps = {
  /**
   * The maximum number of memories that may exist at once.
   */
  maxCount: number;
  /**
   * The maximum length, in characters, of any single memory's body.
   */
  maxLenPerMemory: number;
  /**
   * The maximum total length, in characters, summed across every memory's body.
   */
  maxTotalLen: number;
};

/**
 * The state of one model-curated [memory](https://docs.testcabinet.ai/gg/memories/) at a
 * point in a run — a band of a [`MemoryState`](GgTelemetryKind::MemoryState) event.
 *
 * A memory is written by the model with `write_memory` (and revised with `update_memory`
 * / removed with `delete_memory`): its [`description`](Self::description) is shown up
 * front (so the model — and the console — can see what each memory is for at a glance),
 * and its body is retained in the context window as a
 * [`Memory`](GgContextSource::Memory)-sourced, compaction-retained item. [`len`](Self::len)
 * is the body's length in characters — what the [caps](GgMemoryCaps) are measured against.
 */
export type GgMemoryEntry = {
  /**
   * The memory's stable name — the handle `update_memory`/`delete_memory` take.
   */
  name: string;
  /**
   * The memory's one-line description, shown up front.
   */
  description: string;
  /**
   * The memory body's length in characters (what the caps bound).
   */
  len: number;
};

/**
 * The status of one [task](https://docs.testcabinet.ai/gg/tasks/) — a field of a
 * [`GgTaskEntry`] in a [`TasksState`](GgTelemetryKind::TasksState) event.
 *
 * A task moves from [`Pending`](Self::Pending) (not started) through
 * [`InProgress`](Self::InProgress) (being worked) to [`Done`](Self::Done) (complete). A
 * task is *actionable* only when all of its blockers are [`Done`](Self::Done); the console
 * derives that from the blocked-by edges and each blocker's status rather than a separate
 * flag.
 */
export type GgTaskStatus = "pending" | "in_progress" | "done";

/**
 * One model-curated [task](https://docs.testcabinet.ai/gg/tasks/) — a node of the
 * blocked-by DAG reported in a [`TasksState`](GgTelemetryKind::TasksState) event.
 *
 * The model builds a lightweight to-do list with `add_task` (and revises it with
 * `update_task` / `set_blocked_by` / `complete_task` / `remove_task`). Each task has a
 * stable [`id`](Self::id) the model coins and references, a [`title`](Self::title), an
 * optional [`description`](Self::description), a [`status`](Self::status), and the set of
 * task ids it is [`blocked_by`](Self::blocked_by). The blocking relation is a **DAG** —
 * gg rejects any edge that would introduce a cycle — and the whole list is retained across
 * a [compaction] boundary verbatim, so the model never loses its plan.
 *
 * [compaction]: https://docs.testcabinet.ai/gg/compaction/
 */
export type GgTaskEntry = {
  /**
   * The task's stable id — the handle the other task tools and every `blockedBy`
   * reference use.
   */
  id: string;
  /**
   * The task's short title.
   */
  title: string;
  /**
   * An optional longer description of the task.
   */
  description?: string;
  /**
   * The task's status.
   */
  status: GgTaskStatus;
  /**
   * The ids of the tasks this task is blocked by (must all be
   * [`Done`](GgTaskStatus::Done) before this task is actionable). The relation is
   * acyclic across the whole list.
   */
  blockedBy: Array<string>;
};

/**
 * The status of one [issue](https://docs.testcabinet.ai/gg/epics-and-issues/) on the
 * [board](GgTelemetryKind::BoardState) — the heavyweight counterpart to
 * [`GgTaskStatus`].
 *
 * An issue moves from [`Open`](Self::Open) (not started) through
 * [`InProgress`](Self::InProgress) (being worked) to [`Done`](Self::Done) (complete). Like a
 * task, an issue is *actionable* only when all of its blockers are [`Done`](Self::Done); the
 * console derives that from the blocked-by edges and each blocker's status rather than a
 * separate flag.
 */
export type GgIssueStatus = "open" | "in_progress" | "done";

/**
 * One [epic](https://docs.testcabinet.ai/gg/epics-and-issues/) on the board — a grouping of
 * related [issues](GgBoardIssue) reported in a [`BoardState`](GgTelemetryKind::BoardState)
 * event.
 *
 * An epic is organizational: it has a stable [`id`](Self::id) issues reference through their
 * [`epic_id`](GgBoardIssue::epic_id), a [`title`](Self::title), and a
 * [`description`](Self::description). It carries no status of its own — an epic's progress is
 * read from the status of the issues grouped under it.
 */
export type GgBoardEpic = {
  /**
   * The epic's stable id — the handle an issue's `epicId` references.
   */
  id: string;
  /**
   * The epic's short title.
   */
  title: string;
  /**
   * A longer description of what the epic covers.
   */
  description: string;
};

/**
 * One [issue](https://docs.testcabinet.ai/gg/epics-and-issues/) on the board — a node of the
 * blocked-by DAG reported in a [`BoardState`](GgTelemetryKind::BoardState) event.
 *
 * An issue is the **heavyweight** counterpart to a [task](GgTaskEntry): rather than just a
 * title and description it carries structured sections — [`in_scope`](Self::in_scope),
 * [`out_of_scope`](Self::out_of_scope), and [`completion_criteria`](Self::completion_criteria)
 * — whose explicit scope boundaries and completion criteria are what make an issue **safe to
 * dispatch to a subagent** (Phase 4): they tell the subagent exactly what it is and is not
 * responsible for and how it will be judged done. Issues share the [tasks](GgTaskEntry)
 * blocked-by relation — a **DAG**, so gg rejects any edge that would introduce a cycle — and
 * an issue may be grouped under an [epic](GgBoardEpic) through its
 * [`epic_id`](Self::epic_id). The whole board is retained across a [compaction] boundary
 * verbatim, like the task list.
 *
 * [compaction]: https://docs.testcabinet.ai/gg/compaction/
 */
export type GgBoardIssue = {
  /**
   * The issue's stable id — the handle the other board tools and every `blockedBy`
   * reference use.
   */
  id: string;
  /**
   * The issue's short title.
   */
  title: string;
  /**
   * An optional longer overview of the issue (the structured scope fields carry the
   * dispatch-relevant detail).
   */
  description?: string;
  /**
   * What the issue **is** responsible for — the work in its scope.
   */
  inScope: string;
  /**
   * What the issue is **not** responsible for — the explicit exclusions that bound a
   * dispatched subagent's work.
   */
  outOfScope: string;
  /**
   * How the issue will be judged **done** — the acceptance criteria a dispatched subagent
   * is held to.
   */
  completionCriteria: string;
  /**
   * The issue's status.
   */
  status: GgIssueStatus;
  /**
   * The ids of the issues this issue is blocked by (must all be
   * [`Done`](GgIssueStatus::Done) before this issue is actionable). The relation is acyclic
   * across the whole board.
   */
  blockedBy: Array<string>;
  /**
   * The id of the [epic](GgBoardEpic) this issue is grouped under, when any.
   */
  epicId?: string;
};

/**
 * The pinned state a [compaction] carried across the boundary verbatim — the counts
 * that *survived* summarization — reported on a
 * [`Compaction`](GgTelemetryKind::Compaction) event so the console can prove the
 * retention contract held (the read skills, the task list, and the in-play memories are
 * not summarized away).
 *
 * Each figure is a **count of retained items**, not a token figure: how many read
 * [skills](GgContextSource::Skill), how many [tasks](GgContextSource::TaskList), how many
 * in-play [memories](GgContextSource::Memory), and how many
 * [issues](https://docs.testcabinet.ai/gg/epics-and-issues/) on the
 * [board](GgContextSource::Board) remained pinned after the ephemeral history was replaced by
 * the summary. The epic/issue board is retained across the boundary just like the task list,
 * so its issue count is reported here as part of the retention proof.
 *
 * [compaction]: https://docs.testcabinet.ai/gg/compaction/
 */
export type GgRetainedState = {
  /**
   * The number of read skills whose bodies were carried across the boundary verbatim.
   */
  skills: number;
  /**
   * The number of tasks in the retained task list.
   */
  tasks: number;
  /**
   * The number of in-play memories carried across the boundary verbatim.
   */
  memories: number;
  /**
   * The number of issues on the retained epic/issue board.
   */
  issues: number;
};

/**
 * The kind of agent-managed-context action a [`ContextManaged`](GgTelemetryKind::ContextManaged)
 * event reports — the model-facing window management that is the complement to
 * [compaction](CAPABILITY_COMPACTION).
 *
 * The [agent-managed context](https://docs.testcabinet.ai/gg/agent-managed-context/)
 * capability lets a disciplined agent reclaim window space itself rather than waiting for
 * the automatic backstop: it can [evict file views](Self::EvictFileViews) it no longer
 * needs (safe — it can re-read the file later) or [archive a section of its
 * thread](Self::ArchiveThread) (removed from the live window but kept **searchable** via
 * `search_archive`). Both reclaim tokens; a `search_archive` call reclaims nothing and so
 * is reported only as an ordinary tool result, not as a `ContextManaged` action.
 */
export type GgContextAction = "evict_file_views" | "archive_thread";

/**
 * The phase of a [planning](https://docs.testcabinet.ai/gg/planning/) pass a
 * [`Planning`](GgTelemetryKind::Planning) event reports — the read-only-then-implement
 * lifecycle the console renders as the plan view and the plan → implement transition.
 *
 * The model [enters](Self::Entered) plan mode (the loop restricts the offered toolset to
 * read-only tools so it can only explore and reason), then [submits](Self::Submitted) a plan;
 * on submit gg clears the exploration history — keeping the pinned prefix — and seeds a fresh
 * implementation context from the original prompt plus the plan, entering the
 * [implementing](Self::Implementing) phase where the full (mutating) toolset is restored.
 */
export type GgPlanPhase = "entered" | "submitted" | "implementing";

/**
 * The lifecycle status of an agent in the [subagent tree](https://docs.testcabinet.ai/gg/subagents/),
 * reported by an [`AgentStatus`](GgTelemetryKind::AgentStatus) transition so the console can
 * colour each node of the live tree (running vs waiting) and mark it done or failed.
 *
 * An agent is [`Running`](Self::Running) while it drives its turn loop, [`Blocked`](Self::Blocked)
 * while it has **freed its running slot to wait on its subagents** (the scheduler's
 * blocked-frees-slot state — distinct from merely queuing for a slot), and terminally either
 * [`Done`](Self::Done) (its loop ended normally) or [`Failed`](Self::Failed) (its loop ended in a
 * model error). Like [`AgentSpawned`](GgTelemetryKind::AgentSpawned), the agent's identity rides
 * on the event's own [`agent_id`](GgTelemetryEvent::agent_id), so the payload carries only the
 * status.
 */
export type GgAgentStatus = "running" | "blocked" | "done" | "failed";

/**
 * The boundary a [`WorkflowStage`](GgTelemetryKind::WorkflowStage) event marks — the
 * [start or finish](https://docs.testcabinet.ai/gg/workflows/) of one stage of a declared
 * [workflow](CAPABILITY_WORKFLOWS).
 *
 * A workflow stage emits one event as it [starts](Self::Started) (right before it fans its
 * subagents out) and one as it [finishes](Self::Finished) (once every fanned-out agent has
 * returned and its results are collected to feed the next stage), so the console can render the
 * workflow's structure and each stage's duration on the timeline. The per-agent
 * [`AgentSpawned`](GgTelemetryKind::AgentSpawned)/[`AgentStatus`](GgTelemetryKind::AgentStatus)/[`AgentReturned`](GgTelemetryKind::AgentReturned)
 * events carry the detail of the agents that ran within the stage.
 */
export type GgWorkflowPhase = "started" | "finished";

/**
 * The phase of a [Code Review](https://docs.testcabinet.ai/gg/code-reviews/) a
 * [`CodeReview`](GgTelemetryKind::CodeReview) event reports — the
 * requested → (changes_requested)* → approved lifecycle that gates an
 * [issue](GgBoardIssue)'s acceptance.
 *
 * A Code Review is [requested](Self::Requested) when the model marks an issue done (gg dispatches
 * a reviewer against the diff rather than accepting immediately). The reviewer then either
 * [requests changes](Self::ChangesRequested) — carrying the actionable items a fix agent must
 * address, after which the work is re-reviewed — or [approves](Self::Approved), at which point the
 * issue is finally accepted (marked done). Because there is **no cycle limit**, a single Code
 * Review may emit many [`ChangesRequested`](Self::ChangesRequested) phases before an
 * [`Approved`](Self::Approved) (or none, on a clean first pass).
 */
export type GgCodeReviewPhase = "requested" | "changes_requested" | "approved";

/**
 * The phase of a [speculative execution](https://docs.testcabinet.ai/gg/speculative-execution/) a
 * [`Speculation`](GgTelemetryKind::Speculation) event reports — the `fan-out → judge → merge`
 * lifecycle of a best-of-K attempt.
 *
 * A speculation [fans out](Self::FannedOut) K attempts at the same task (each in its own worktree),
 * then a judge [scores and picks a winner](Self::Judged) among the attempts that produced work, and
 * finally the winner's worktree is [merged](Self::Merged) back into the main tree while the losers'
 * branches are discarded. A speculation that produced no usable work emits [`Judged`](Self::Judged)
 * with no winner and no [`Merged`](Self::Merged).
 */
export type GgSpeculationPhase = "fanned_out" | "judged" | "merged";

/**
 * One `(slot, model)` token+cost rollup in a [`GgSessionSummary`] — the aggregatable
 * tail of the [`SlotUsage`](GgTelemetryKind::SlotUsage) rollups, folded onto the run so a
 * query can total or slice a gg run's spend per model without replaying the stream.
 *
 * A gg run spans several models (subagents can run on different, possibly cross-provider,
 * [slots](GgSlotBinding) than the parent), so cost is accumulated **per slot** rather than
 * as one figure for one model. This is the same shape a `SlotUsage` telemetry event carries,
 * captured once per `(slot, model)` the run touched, so [result aggregation] can answer
 * "does a cheaper subagent slot cost accuracy?" from the durable record.
 *
 * [result aggregation]: https://docs.testcabinet.ai/gg/result-aggregation/
 */
export type GgSlotCost = {
  /**
   * The [slot](GgSlotBinding) this rollup accounts for (for example [`PRIMARY_SLOT`] or a
   * role slot like `reviewer`).
   */
  slot: string;
  /**
   * The model id (within the slot) this rollup accounts for. A slot normally resolves to one
   * model, but the accounting keys on the model too so a re-pointed slot stays attributable.
   */
  modelId: string;
  /**
   * The tokens accumulated on this slot/model across the run, in the shared [`TokenCounts`]
   * units.
   */
  tokens: TokenMetrics;
  /**
   * The cost accumulated on this slot/model, when any turn on it reported one.
   */
  cost?: CostMetrics;
};

/**
 * The compact, aggregatable summary of one whole gg session — the per-run outcome
 * [result aggregation] slices and correlates across many runs.
 *
 * gg's experiments are only analyzable *in aggregate* over fields we **durably record**, so a
 * run must carry a small, flat summary of its own outcome rather than forcing every query to
 * re-parse the whole [telemetry stream](GgTelemetryEvent). gg computes this as the run proceeds
 * — counting each figure as the relevant telemetry is emitted — and emits it as a final
 * [`SessionSummary`](GgTelemetryKind::SessionSummary) event right before
 * [`SessionEnded`](GgTelemetryKind::SessionEnded); `core` then records it on the run
 * ([`RunSubject::gg_summary`](crate::run_record::RunSubject::gg_summary)) alongside the
 * [capability set](GgCapabilitySet) that is the *slice-by dimension*, so a result is both
 * configured-by and outcome-summarized on the one record. Every field is a number, a small
 * status string, or a small list, so a query can `GROUP BY` the capability set and aggregate any
 * of them directly.
 *
 * [result aggregation]: https://docs.testcabinet.ai/gg/result-aggregation/
 */
export type GgSessionSummary = {
  /**
   * How the session ended — the [`SessionEnded`](GgTelemetryKind::SessionEnded) status this
   * summary precedes (for example `"completed"`, `"model_error"`, `"exhausted"`,
   * `"timed_out"`, or `"error"`). A slice-by facet for "how often does configuration X finish
   * cleanly?".
   */
  terminalStatus: string;
  /**
   * The total number of agents that ran, **including the root** — one per
   * [`AgentSpawned`](GgTelemetryKind::AgentSpawned) the run emitted. A single-agent run reports
   * `1`.
   */
  agentsSpawned: number;
  /**
   * The number of **subagents** the run spawned — [`agents_spawned`](Self::agents_spawned)
   * minus the root. `0` for a single-agent run. Recorded alongside the total so a query need
   * not subtract.
   */
  subagentCount: number;
  /**
   * The deepest [subagent depth](GgTelemetryKind::AgentSpawned) reached this run: `0` for a
   * single-agent run (only the root, at depth 0), `1` for a run that spawned children but no
   * grandchildren, and so on — the correlate for "how does delegation depth relate to score?".
   */
  maxSubagentDepth: number;
  /**
   * How many [compaction](GgTelemetryKind::Compaction) boundaries the run crossed. `0` when the
   * compaction capability was off or the thread never neared the window.
   */
  compactions: number;
  /**
   * Whether the run ever **ran out of context** — its window fullness reached the ceiling
   * (`>= 1.0`) at least once. The headline flag behind "with compaction off, how often did the
   * model run out of context?".
   */
  ranOutOfContext: boolean;
  /**
   * How many turns the window fullness hit the ceiling (`>= 1.0`) — the count behind
   * [`ran_out_of_context`](Self::ran_out_of_context), so a query can distinguish a run that
   * brushed the ceiling once from one that spent many turns overflowing.
   */
  contextOverflowCount: number;
  /**
   * The window fullness (`total_tokens / window_limit`) reported by the **last**
   * [`ContextBreakdown`](GgTelemetryKind::ContextBreakdown) of the run, when any carried a
   * fullness figure. `None` when context visibility was off or no limit was known.
   */
  finalFullness?: number;
  /**
   * How many [Code Reviews](GgTelemetryKind::CodeReview) the run triggered — one per
   * [`Requested`](GgCodeReviewPhase::Requested) phase (an issue whose acceptance was gated on a
   * review). `0` when the capability was off.
   */
  codeReviews: number;
  /**
   * The total number of review **verdicts** the run's reviewers rendered — every
   * [`ChangesRequested`](GgCodeReviewPhase::ChangesRequested) plus every
   * [`Approved`](GgCodeReviewPhase::Approved) phase — so a single Code Review that took several
   * fix rounds counts each round. The correlate for "which reviewer/planner produced fewer
   * rework cycles?".
   */
  reviewCycles: number;
  /**
   * How many times a Code Review **reopened** an issue for fixes — one per
   * [`ChangesRequested`](GgCodeReviewPhase::ChangesRequested) phase. `0` when every review
   * approved on the first pass (or the capability was off).
   */
  issuesReopened: number;
  /**
   * How many [speculative execution](GgTelemetryKind::Speculation) best-of-K rounds the run ran
   * — one per [`FannedOut`](GgSpeculationPhase::FannedOut) phase. `0` when the capability was
   * off.
   */
  speculations: number;
  /**
   * Which **execution mode** the run's agents used — the durable record of whether the run was
   * driven with [responses-as-code](CAPABILITY_RESPONSES_AS_CODE) (`"responses_as_code"`, the
   * model emitted programs gg ran in the wasmtime sandbox) or traditional tool calling
   * (`"tool_calling"`, the default). This is the effective-behavior companion to the
   * [`capabilityEnabled`](crate::gg_aggregate::GgFacet::CapabilityEnabled)`{responses-as-code}`
   * facet: the facet slices by the *configured* capability, and this field records the mode the
   * run actually ran in, so "does a code-shaped response help?" is a durable, sliceable outcome
   * dimension. Recorded once off the run's configuration (like [`effective_tools`](Self::effective_tools)),
   * not derived from the telemetry stream.
   */
  executionMode: string;
  /**
   * How many [responses-as-code](GgTelemetryKind::CodeExecution) programs the run executed — one
   * per [`CodeExecution`](GgTelemetryKind::CodeExecution) event (a code-shaped turn). `0` when the
   * responses-as-code capability was off (traditional tool calling), so a non-zero count is the
   * proof the code path actually ran.
   */
  codeExecutions: number;
  /**
   * How many distinct [issues](GgBoardIssue) the run ever created on its
   * [board](GgTelemetryKind::BoardState) — the count of distinct issue ids observed across the
   * run. `0` when the epics-and-issues capability was off.
   */
  issuesCreated: number;
  /**
   * How many distinct issues the run ever drove to [`Done`](GgIssueStatus::Done) — the count of
   * distinct issue ids observed at `Done` at any point (so an issue reopened and re-completed
   * still counts once). At most [`issues_created`](Self::issues_created).
   */
  issuesCompleted: number;
  /**
   * The per-`(slot, model)` token+cost rollup for the run — the durable tail of the
   * [`SlotUsage`](GgTelemetryKind::SlotUsage) rollups, one entry per slot/model the run touched,
   * in first-seen order. Empty only for a run that recorded no usage (a launch that never ran a
   * turn).
   */
  slotCosts: Array<GgSlotCost>;
  /**
   * The **effective toolset**: the exact set of tool names offered to the run's agent,
   * in the order they were presented to the model. This is what the run's
   * [capability set](GgCapabilitySet) *actually resolved to* — a capability contributes
   * its tools only when enabled (and, for the stateful ones, only when its store is
   * non-empty), minus any individually [withheld](GgCapabilitySet::disabled_tools) tool —
   * so recording it durably makes the toolset a first-class experimental variable a query
   * can slice by ("group by whether `edit_file` was offered", "runs with only
   * `write_file`"). Because switching a capability on/off *is* offering/withholding its
   * tools, this is the ground truth an ablation study reads rather than re-deriving the
   * toolset from the capability set. Empty only for a run whose agent was offered no tools
   * at all. Recorded off the root agent's toolset (subagents inherit the same capability
   * set; only the root may additionally be driven by an FSM).
   */
  effectiveTools: Array<string>;
};

/**
 * The type-specific payload of a [`GgTelemetryEvent`], discriminated by the `type`
 * field.
 *
 * This is schema v1 and is designed to be **extended** — later phases add variants
 * (compaction boundaries, subagent spawn/return, context-window breakdowns, board
 * transitions) without breaking existing ones. Field names are camelCased on the
 * wire; variant tags are snake_case.
 */
export type GgTelemetryKind =
  | { type: "session_started" }
  | { type: "turn_started" }
  | {
      type: "assistant_message";
      /**
       * The text the assistant emitted.
       */
      text: string;
    }
  | {
      type: "tool_call";
      /**
       * The tool's name.
       */
      name: string;
      /**
       * The arguments the agent passed, as a free-form JSON object.
       */
      args: Record<string, unknown>;
    }
  | {
      type: "tool_result";
      /**
       * The tool's name.
       */
      name: string;
      /**
       * Whether the tool call succeeded.
       */
      ok: boolean;
      /**
       * A short human-readable summary of the result, when one is available.
       */
      summary?: string;
    }
  | {
      type: "usage";
      /**
       * The normalized token counts for this accounting.
       */
      tokens: TokenMetrics;
      /**
       * The cost of this accounting, when it could be determined.
       */
      cost?: CostMetrics;
    }
  | {
      type: "context_breakdown";
      /**
       * One band per [`GgContextSource`], in [`GgContextSource::ALL`] order (a source
       * that contributed nothing this turn is present with `0`), so the graph's bands
       * stay stable across turns.
       */
      bySource: Array<GgContextSourceUsage>;
      /**
       * The estimated total tokens across every source — the numerator of fullness.
       */
      totalTokens: number;
      /**
       * The active model's context-window limit, when known (a capability param or a
       * built-in per-model default). The denominator of fullness.
       */
      windowLimit?: number;
      /**
       * `total_tokens / window_limit` in `0.0..=1.0+`, when a limit is known — the
       * fullness signal compaction triggers on.
       */
      fullness?: number;
    }
  | {
      type: "skills_state";
      /**
       * One entry per available skill, in the order the catalog lists them.
       */
      skills: Array<GgSkillState>;
    }
  | {
      type: "memory_state";
      /**
       * One entry per memory currently held, in name order.
       */
      memories: Array<GgMemoryEntry>;
      /**
       * The number of memories currently held (the length of `memories`).
       */
      count: number;
      /**
       * The total length, in characters, summed across every memory's body.
       */
      totalLen: number;
      /**
       * The bounds these memories are kept within.
       */
      caps: GgMemoryCaps;
    }
  | {
      type: "tasks_state";
      /**
       * The tasks, in the order the model added them (a stable order for the DAG's
       * nodes). Each carries its status and the ids it is blocked by.
       */
      tasks: Array<GgTaskEntry>;
    }
  | {
      type: "board_state";
      /**
       * The epics, in the order the model created them.
       */
      epics: Array<GgBoardEpic>;
      /**
       * The issues, in the order the model created them (a stable order for the DAG's
       * nodes). Each carries its structured scope sections, its status, the ids it is
       * blocked by, and the epic it is grouped under, if any.
       */
      issues: Array<GgBoardIssue>;
    }
  | {
      type: "compaction";
      /**
       * The fullness threshold (a `0.0..=1.0` fraction, the capability's
       * `triggerFullness` param) that tripped this compaction.
       */
      triggerFullness: number;
      /**
       * The estimated total tokens in the window immediately before compaction.
       */
      beforeTokens: number;
      /**
       * The estimated total tokens after compaction — the pinned prefix plus the
       * single summary item — which is below `before_tokens`.
       */
      afterTokens: number;
      /**
       * The estimated tokens the summary item itself occupies.
       */
      summaryTokens: number;
      /**
       * The pinned state carried across the boundary verbatim (the retention proof).
       */
      retained: GgRetainedState;
    }
  | {
      type: "context_managed";
      /**
       * Which window-management action the agent took.
       */
      action: GgContextAction;
      /**
       * The estimated tokens reclaimed from the live window by the action.
       */
      reclaimedTokens: number;
      /**
       * The number of context items removed from the live window (evicted file views, or
       * archived thread items).
       */
      items: number;
      /**
       * A short human-readable description of the action and what it affected (for
       * example the evicted paths, or how many turns were archived and the archive's new
       * size), for the console feed.
       */
      detail: string;
    }
  | {
      type: "planning";
      /**
       * Which phase of the planning pass this transition is.
       */
      phase: GgPlanPhase;
      /**
       * The submitted plan text, on the [`Submitted`](GgPlanPhase::Submitted) and
       * [`Implementing`](GgPlanPhase::Implementing) phases (absent on
       * [`Entered`](GgPlanPhase::Entered), before any plan exists).
       */
      plan?: string;
    }
  | {
      type: "agent_spawned";
      /**
       * The [model slot](GgSlotBinding) this agent runs on (for example [`PRIMARY_SLOT`], or
       * a role slot like `subagent`). Orthogonal to the parallelism cap.
       */
      slot: string;
      /**
       * The concrete model id the [`slot`](Self::AgentSpawned::slot) resolved to for this
       * agent — the seam that makes a run span several models, one per slot.
       */
      modelId: string;
      /**
       * The agent's depth in the [subagent tree](https://docs.testcabinet.ai/gg/subagents/):
       * `0` for the root, `parent.depth + 1` for a spawned child. A spawn that would exceed
       * the configured maximum depth is refused (Phase 4B).
       */
      depth: number;
      /**
       * The task/issue brief the agent was dispatched with, when it is a subagent spawned to
       * do a scoped piece of work. Absent for the root agent, which is driven by the run's
       * build prompt rather than a delegated brief.
       */
      brief?: string;
      /**
       * The isolated [git worktree](https://docs.testcabinet.ai/gg/worktrees/) this agent runs
       * in — its per-agent branch — when it was dispatched with `worktree: true` (requires the
       * [worktrees](CAPABILITY_WORKTREES) capability). The console renders this as a worktree
       * indicator on the tree node. Absent for an agent running in the shared main tree (the
       * root, and any subagent dispatched without a worktree), whose edits land directly in the
       * workspace. A worktree agent's result is later merged or discarded — observe which with
       * [`WorktreeMerged`](Self::WorktreeMerged).
       */
      worktree?: string;
    }
  | {
      type: "slot_usage";
      /**
       * The slot this rollup accounts for.
       */
      slot: string;
      /**
       * The model id (within the slot) this rollup accounts for. A slot normally resolves to
       * one model, but the accounting keys on the model too so a re-pointed slot stays
       * attributable.
       */
      modelId: string;
      /**
       * The tokens accumulated on this slot/model across the run, in the shared
       * [`TokenCounts`] units.
       */
      tokens: TokenMetrics;
      /**
       * The cost accumulated on this slot/model, when any turn on it reported one.
       */
      cost?: CostMetrics;
    }
  | {
      type: "agent_status";
      /**
       * The agent's new lifecycle status.
       */
      status: GgAgentStatus;
    }
  | {
      type: "agent_returned";
      /**
       * The subagent's return value: its final assistant message, or a short status line when
       * the loop produced no final text.
       */
      summary: string;
    }
  | {
      type: "worktree_merged";
      /**
       * The per-agent branch the worktree's work lived on (for example `gg/agent-3`).
       */
      branch: string;
      /**
       * Whether the branch was merged back into the main tree. `true` only on a clean merge;
       * `false` for a conflict or a discard.
       */
      merged: boolean;
      /**
       * Whether a merge conflict prevented the merge. When `true` the main tree was left
       * unchanged and the clash is reported to the spawner rather than resolved (Phase 4B leaves
       * conflict resolution to a later phase). Always `false` on a clean merge or a discard.
       */
      conflicts: boolean;
    }
  | {
      type: "workflow_stage";
      /**
       * The id of the workflow this stage belongs to, unique within the run — so the console can
       * group a single `run_workflow` invocation's stages together (an agent may run several
       * workflows over its life).
       */
      workflowId: string;
      /**
       * The stage's name (the model's `name` for it, or a `stage-N` fallback), for the timeline
       * label.
       */
      stage: string;
      /**
       * The stage's zero-based index within the workflow, so the console can order the stages.
       */
      stageIndex: number;
      /**
       * How many subagents this stage fans out — one per item it runs over (the prior stage's
       * results when the stage declares no explicit items).
       */
      itemCount: number;
      /**
       * Whether this event marks the stage's [start or finish](GgWorkflowPhase).
       */
      phase: GgWorkflowPhase;
    }
  | {
      type: "code_review";
      /**
       * Which phase of the review lifecycle this transition is.
       */
      phase: GgCodeReviewPhase;
      /**
       * The reviewer's actionable items, on the
       * [`ChangesRequested`](GgCodeReviewPhase::ChangesRequested) phase (the changes a fix agent
       * must address before re-review). Absent on [`Requested`](GgCodeReviewPhase::Requested) and
       * [`Approved`](GgCodeReviewPhase::Approved).
       */
      items?: Array<string>;
      /**
       * The baseline commit the review diffed the work against — the issue's initial commit
       * (captured when its work began) or, failing that, the run's baseline. Absent when no git
       * baseline could be established for the run.
       */
      baseline?: string;
    }
  | {
      type: "fsm_state";
      /**
       * The built-in machine driving the run (for example `"tdd"`, `"review-gated"`, or
       * `"plan-first"`).
       */
      machine: string;
      /**
       * The name of the state just entered (for example `"write_tests"`, `"implement"`,
       * `"verify"`, `"develop"`, `"review"`, `"accept"`, or `"plan"`).
       */
      state: string;
      /**
       * The state's zero-based index in the machine's ordered states, so the console can place it
       * on the machine's path (a `review-gated` loop-back repeats an earlier index).
       */
      stateIndex: number;
    }
  | {
      type: "speculation";
      /**
       * How many attempts were fanned out at the task (the `K` of best-of-K).
       */
      attempts: number;
      /**
       * Which phase of the speculation lifecycle this transition is.
       */
      phase: GgSpeculationPhase;
      /**
       * The winning attempt's agent id, on [`Judged`](GgSpeculationPhase::Judged) (once a winner is
       * picked) and [`Merged`](GgSpeculationPhase::Merged). Absent on
       * [`FannedOut`](GgSpeculationPhase::FannedOut), and on a `Judged` where no attempt produced
       * usable work.
       */
      winner?: string;
      /**
       * The judge's one-line rationale for its pick, on [`Judged`](GgSpeculationPhase::Judged).
       * Absent on the other phases (and when the judge gave none).
       */
      rationale?: string;
    }
  | {
      type: "code_execution";
      /**
       * Whether the program returned normally (`true`) or faulted / the sandbox failed
       * (`false`). A failed code execution is a *turn* outcome fed back to the model, never a
       * crash of the run.
       */
      ok: boolean;
      /**
       * How many tool calls the program composed (bridged to the real toolset), in the order it
       * made them — each also streamed as its own [`ToolCall`](Self::ToolCall)/[`ToolResult`](Self::ToolResult).
       */
      toolCalls: number;
      /**
       * The wasmtime fuel the program's execution consumed, when the sandbox ran to a result. The
       * same per-run efficiency signal the sibling Foray/Lattice hosts expose; absent when the
       * sandbox itself failed to complete (for example a fuel-ceiling trap, where the figure is
       * simply the ceiling).
       */
      fuelUsed?: number;
      /**
       * The failure message, when [`ok`](Self::CodeExecution::ok) is `false` — a program fault
       * (a parse/type error, a runaway-loop step-budget stop) or a sandbox failure (fuel or
       * memory exhaustion, a trap). Absent on a clean execution.
       */
      error?: string;
    }
  | {
      type: "log";
      /**
       * The severity level (for example `"info"`, `"warn"`, or `"error"`).
       */
      level: string;
      /**
       * The log message.
       */
      message: string;
    }
  | {
      type: "session_summary";
      /**
       * The computed summary of the session's outcome. Boxed so this variant does not
       * dominate the size of [`GgTelemetryKind`] (and the [`EventKind`](crate::event::EventKind)
       * that carries a whole [`GgTelemetryEvent`]); `Box<T>` serializes and renders in the
       * contract exactly as `T`.
       */
      summary: GgSessionSummary;
    }
  | {
      type: "session_ended";
      /**
       * How the session ended (for example `"completed"`, `"error"`, or
       * `"timed_out"`).
       */
      status: string;
    };

/**
 * A single event in gg's first-party telemetry stream (schema v1).
 *
 * Because gg is [headless](https://docs.testcabinet.ai/gg/overview/), this stream is
 * the only live window into a run — the console renders it natively. Each event
 * carries common fields (a timestamp and an optional session id) plus the
 * type-specific [`GgTelemetryKind`], flattened into the serialized form so the
 * discriminator and its fields sit inline.
 *
 * The [`agent_id`](Self::agent_id) and [`parent_agent_id`](Self::parent_agent_id)
 * fields identify the node in the [subagent tree](https://docs.testcabinet.ai/gg/subagents/)
 * that emitted the event (Phase 4): every event an agent emits carries its own id and its
 * spawner's id, so the console can reconstruct who-spawned-whom and attribute the stream per
 * agent. A single-agent run tags every event with the root agent's id (`"root"`) and no
 * parent. The [`issue_id`](Self::issue_id) field scopes an event to a board
 * [issue](GgBoardIssue) once work is dispatched against one (Phase 4B); a run that has not
 * dispatched leaves it unset.
 */
export type GgTelemetryEvent = {
  /**
   * RFC 3339 / ISO 8601 time the event was emitted.
   */
  timestamp: string;
  /**
   * The gg session this event belongs to, when one is known.
   */
  sessionId?: string;
  /**
   * The id of the agent that emitted the event, so events can be attributed to a node
   * in the [subagent tree](https://docs.testcabinet.ai/gg/subagents/). A single-agent
   * run stamps every event with the root agent's id (`"root"`); it is unset only for
   * events emitted before any agent context exists.
   */
  agentId?: string;
  /**
   * The id of the agent that spawned the emitting agent, so the subagent tree's
   * parent→child edges can be reconstructed. Unset for the root agent (which has no
   * spawner) and for events with no agent context.
   */
  parentAgentId?: string;
  /**
   * The id of the [issue](GgBoardIssue) this event's work is scoped to, for the live
   * board. The board itself lands in Phase 3, but an event is only *scoped* to a
   * specific issue once work is dispatched against one (Phase 4), so a P3a run — which
   * builds the board but does not yet dispatch — leaves this unset.
   */
  issueId?: string;
} & (
  | { type: "session_started" }
  | { type: "turn_started" }
  | {
      type: "assistant_message";
      /**
       * The text the assistant emitted.
       */
      text: string;
    }
  | {
      type: "tool_call";
      /**
       * The tool's name.
       */
      name: string;
      /**
       * The arguments the agent passed, as a free-form JSON object.
       */
      args: Record<string, unknown>;
    }
  | {
      type: "tool_result";
      /**
       * The tool's name.
       */
      name: string;
      /**
       * Whether the tool call succeeded.
       */
      ok: boolean;
      /**
       * A short human-readable summary of the result, when one is available.
       */
      summary?: string;
    }
  | {
      type: "usage";
      /**
       * The normalized token counts for this accounting.
       */
      tokens: TokenMetrics;
      /**
       * The cost of this accounting, when it could be determined.
       */
      cost?: CostMetrics;
    }
  | {
      type: "context_breakdown";
      /**
       * One band per [`GgContextSource`], in [`GgContextSource::ALL`] order (a source
       * that contributed nothing this turn is present with `0`), so the graph's bands
       * stay stable across turns.
       */
      bySource: Array<GgContextSourceUsage>;
      /**
       * The estimated total tokens across every source — the numerator of fullness.
       */
      totalTokens: number;
      /**
       * The active model's context-window limit, when known (a capability param or a
       * built-in per-model default). The denominator of fullness.
       */
      windowLimit?: number;
      /**
       * `total_tokens / window_limit` in `0.0..=1.0+`, when a limit is known — the
       * fullness signal compaction triggers on.
       */
      fullness?: number;
    }
  | {
      type: "skills_state";
      /**
       * One entry per available skill, in the order the catalog lists them.
       */
      skills: Array<GgSkillState>;
    }
  | {
      type: "memory_state";
      /**
       * One entry per memory currently held, in name order.
       */
      memories: Array<GgMemoryEntry>;
      /**
       * The number of memories currently held (the length of `memories`).
       */
      count: number;
      /**
       * The total length, in characters, summed across every memory's body.
       */
      totalLen: number;
      /**
       * The bounds these memories are kept within.
       */
      caps: GgMemoryCaps;
    }
  | {
      type: "tasks_state";
      /**
       * The tasks, in the order the model added them (a stable order for the DAG's
       * nodes). Each carries its status and the ids it is blocked by.
       */
      tasks: Array<GgTaskEntry>;
    }
  | {
      type: "board_state";
      /**
       * The epics, in the order the model created them.
       */
      epics: Array<GgBoardEpic>;
      /**
       * The issues, in the order the model created them (a stable order for the DAG's
       * nodes). Each carries its structured scope sections, its status, the ids it is
       * blocked by, and the epic it is grouped under, if any.
       */
      issues: Array<GgBoardIssue>;
    }
  | {
      type: "compaction";
      /**
       * The fullness threshold (a `0.0..=1.0` fraction, the capability's
       * `triggerFullness` param) that tripped this compaction.
       */
      triggerFullness: number;
      /**
       * The estimated total tokens in the window immediately before compaction.
       */
      beforeTokens: number;
      /**
       * The estimated total tokens after compaction — the pinned prefix plus the
       * single summary item — which is below `before_tokens`.
       */
      afterTokens: number;
      /**
       * The estimated tokens the summary item itself occupies.
       */
      summaryTokens: number;
      /**
       * The pinned state carried across the boundary verbatim (the retention proof).
       */
      retained: GgRetainedState;
    }
  | {
      type: "context_managed";
      /**
       * Which window-management action the agent took.
       */
      action: GgContextAction;
      /**
       * The estimated tokens reclaimed from the live window by the action.
       */
      reclaimedTokens: number;
      /**
       * The number of context items removed from the live window (evicted file views, or
       * archived thread items).
       */
      items: number;
      /**
       * A short human-readable description of the action and what it affected (for
       * example the evicted paths, or how many turns were archived and the archive's new
       * size), for the console feed.
       */
      detail: string;
    }
  | {
      type: "planning";
      /**
       * Which phase of the planning pass this transition is.
       */
      phase: GgPlanPhase;
      /**
       * The submitted plan text, on the [`Submitted`](GgPlanPhase::Submitted) and
       * [`Implementing`](GgPlanPhase::Implementing) phases (absent on
       * [`Entered`](GgPlanPhase::Entered), before any plan exists).
       */
      plan?: string;
    }
  | {
      type: "agent_spawned";
      /**
       * The [model slot](GgSlotBinding) this agent runs on (for example [`PRIMARY_SLOT`], or
       * a role slot like `subagent`). Orthogonal to the parallelism cap.
       */
      slot: string;
      /**
       * The concrete model id the [`slot`](Self::AgentSpawned::slot) resolved to for this
       * agent — the seam that makes a run span several models, one per slot.
       */
      modelId: string;
      /**
       * The agent's depth in the [subagent tree](https://docs.testcabinet.ai/gg/subagents/):
       * `0` for the root, `parent.depth + 1` for a spawned child. A spawn that would exceed
       * the configured maximum depth is refused (Phase 4B).
       */
      depth: number;
      /**
       * The task/issue brief the agent was dispatched with, when it is a subagent spawned to
       * do a scoped piece of work. Absent for the root agent, which is driven by the run's
       * build prompt rather than a delegated brief.
       */
      brief?: string;
      /**
       * The isolated [git worktree](https://docs.testcabinet.ai/gg/worktrees/) this agent runs
       * in — its per-agent branch — when it was dispatched with `worktree: true` (requires the
       * [worktrees](CAPABILITY_WORKTREES) capability). The console renders this as a worktree
       * indicator on the tree node. Absent for an agent running in the shared main tree (the
       * root, and any subagent dispatched without a worktree), whose edits land directly in the
       * workspace. A worktree agent's result is later merged or discarded — observe which with
       * [`WorktreeMerged`](Self::WorktreeMerged).
       */
      worktree?: string;
    }
  | {
      type: "slot_usage";
      /**
       * The slot this rollup accounts for.
       */
      slot: string;
      /**
       * The model id (within the slot) this rollup accounts for. A slot normally resolves to
       * one model, but the accounting keys on the model too so a re-pointed slot stays
       * attributable.
       */
      modelId: string;
      /**
       * The tokens accumulated on this slot/model across the run, in the shared
       * [`TokenCounts`] units.
       */
      tokens: TokenMetrics;
      /**
       * The cost accumulated on this slot/model, when any turn on it reported one.
       */
      cost?: CostMetrics;
    }
  | {
      type: "agent_status";
      /**
       * The agent's new lifecycle status.
       */
      status: GgAgentStatus;
    }
  | {
      type: "agent_returned";
      /**
       * The subagent's return value: its final assistant message, or a short status line when
       * the loop produced no final text.
       */
      summary: string;
    }
  | {
      type: "worktree_merged";
      /**
       * The per-agent branch the worktree's work lived on (for example `gg/agent-3`).
       */
      branch: string;
      /**
       * Whether the branch was merged back into the main tree. `true` only on a clean merge;
       * `false` for a conflict or a discard.
       */
      merged: boolean;
      /**
       * Whether a merge conflict prevented the merge. When `true` the main tree was left
       * unchanged and the clash is reported to the spawner rather than resolved (Phase 4B leaves
       * conflict resolution to a later phase). Always `false` on a clean merge or a discard.
       */
      conflicts: boolean;
    }
  | {
      type: "workflow_stage";
      /**
       * The id of the workflow this stage belongs to, unique within the run — so the console can
       * group a single `run_workflow` invocation's stages together (an agent may run several
       * workflows over its life).
       */
      workflowId: string;
      /**
       * The stage's name (the model's `name` for it, or a `stage-N` fallback), for the timeline
       * label.
       */
      stage: string;
      /**
       * The stage's zero-based index within the workflow, so the console can order the stages.
       */
      stageIndex: number;
      /**
       * How many subagents this stage fans out — one per item it runs over (the prior stage's
       * results when the stage declares no explicit items).
       */
      itemCount: number;
      /**
       * Whether this event marks the stage's [start or finish](GgWorkflowPhase).
       */
      phase: GgWorkflowPhase;
    }
  | {
      type: "code_review";
      /**
       * Which phase of the review lifecycle this transition is.
       */
      phase: GgCodeReviewPhase;
      /**
       * The reviewer's actionable items, on the
       * [`ChangesRequested`](GgCodeReviewPhase::ChangesRequested) phase (the changes a fix agent
       * must address before re-review). Absent on [`Requested`](GgCodeReviewPhase::Requested) and
       * [`Approved`](GgCodeReviewPhase::Approved).
       */
      items?: Array<string>;
      /**
       * The baseline commit the review diffed the work against — the issue's initial commit
       * (captured when its work began) or, failing that, the run's baseline. Absent when no git
       * baseline could be established for the run.
       */
      baseline?: string;
    }
  | {
      type: "fsm_state";
      /**
       * The built-in machine driving the run (for example `"tdd"`, `"review-gated"`, or
       * `"plan-first"`).
       */
      machine: string;
      /**
       * The name of the state just entered (for example `"write_tests"`, `"implement"`,
       * `"verify"`, `"develop"`, `"review"`, `"accept"`, or `"plan"`).
       */
      state: string;
      /**
       * The state's zero-based index in the machine's ordered states, so the console can place it
       * on the machine's path (a `review-gated` loop-back repeats an earlier index).
       */
      stateIndex: number;
    }
  | {
      type: "speculation";
      /**
       * How many attempts were fanned out at the task (the `K` of best-of-K).
       */
      attempts: number;
      /**
       * Which phase of the speculation lifecycle this transition is.
       */
      phase: GgSpeculationPhase;
      /**
       * The winning attempt's agent id, on [`Judged`](GgSpeculationPhase::Judged) (once a winner is
       * picked) and [`Merged`](GgSpeculationPhase::Merged). Absent on
       * [`FannedOut`](GgSpeculationPhase::FannedOut), and on a `Judged` where no attempt produced
       * usable work.
       */
      winner?: string;
      /**
       * The judge's one-line rationale for its pick, on [`Judged`](GgSpeculationPhase::Judged).
       * Absent on the other phases (and when the judge gave none).
       */
      rationale?: string;
    }
  | {
      type: "code_execution";
      /**
       * Whether the program returned normally (`true`) or faulted / the sandbox failed
       * (`false`). A failed code execution is a *turn* outcome fed back to the model, never a
       * crash of the run.
       */
      ok: boolean;
      /**
       * How many tool calls the program composed (bridged to the real toolset), in the order it
       * made them — each also streamed as its own [`ToolCall`](Self::ToolCall)/[`ToolResult`](Self::ToolResult).
       */
      toolCalls: number;
      /**
       * The wasmtime fuel the program's execution consumed, when the sandbox ran to a result. The
       * same per-run efficiency signal the sibling Foray/Lattice hosts expose; absent when the
       * sandbox itself failed to complete (for example a fuel-ceiling trap, where the figure is
       * simply the ceiling).
       */
      fuelUsed?: number;
      /**
       * The failure message, when [`ok`](Self::CodeExecution::ok) is `false` — a program fault
       * (a parse/type error, a runaway-loop step-budget stop) or a sandbox failure (fuel or
       * memory exhaustion, a trap). Absent on a clean execution.
       */
      error?: string;
    }
  | {
      type: "log";
      /**
       * The severity level (for example `"info"`, `"warn"`, or `"error"`).
       */
      level: string;
      /**
       * The log message.
       */
      message: string;
    }
  | {
      type: "session_summary";
      /**
       * The computed summary of the session's outcome. Boxed so this variant does not
       * dominate the size of [`GgTelemetryKind`] (and the [`EventKind`](crate::event::EventKind)
       * that carries a whole [`GgTelemetryEvent`]); `Box<T>` serializes and renders in the
       * contract exactly as `T`.
       */
      summary: GgSessionSummary;
    }
  | {
      type: "session_ended";
      /**
       * How the session ended (for example `"completed"`, `"error"`, or
       * `"timed_out"`).
       */
      status: string;
    }
);
