// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` and `crates/backend`, which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.

import type { CostMetrics, TokenMetrics } from "./index";

/**
 * A binding of a model to a named slot in a [`GgCapabilitySet`].
 *
 * Model selection is expressed through slots so capabilities reference models by
 * role (`"primary"`, `"reviewer"`, …) rather than by a hardcoded id, and a study can
 * re-point a slot — even to a different provider — without touching capability logic.
 */
export type GgSlotBinding = {
  /**
   * The slot name capabilities reference (for example [`PRIMARY_SLOT`]).
   */
  slot: string;
  /**
   * The opaque model id bound to the slot, passed through to the model client.
   */
  modelId: string;
  /**
   * The provider the model is reached through, when it must be pinned rather than
   * inferred from the id — the seam that makes a slot cross-provider. `None` lets
   * the client resolve the provider from the id.
   */
  provider?: string;
};

/**
 * The configuration of a single capability within a [`GgCapabilitySet`].
 *
 * A capability is identified by a stable [`id`](Self::id) (an open string, not a
 * closed enum, so later phases add capabilities freely), can be toggled
 * [on or off](Self::enabled), can select among alternate
 * [implementations](Self::implementation) for A/B comparisons, and carries
 * free-form [`params`](Self::params) for tuning.
 */
export type GgCapabilityConfig = {
  /**
   * The capability's stable id (for example `"shell"`, `"compaction"`, or
   * `"subagents"`). Stable across versions so recorded configurations stay
   * comparable.
   */
  id: string;
  /**
   * Whether the capability is on. Off means gg behaves as if the feature does not
   * exist — no tools for it are exposed and it consumes no context — which is the
   * basis for ablation studies.
   */
  enabled: boolean;
  /**
   * The selected implementation of the capability, when it offers more than one
   * (for example two compaction strategies or two planners). `None` selects the
   * default. This is the basis for A/B comparisons between implementations.
   */
  implementation?: string;
  /**
   * Free-form parameters for the capability (for example a compaction threshold or
   * a subagent parallelism cap), interpreted by the capability itself. Defaults to
   * an empty object.
   */
  params: Record<string, unknown>;
};

/**
 * The declarative, inspectable configuration of a gg run — its *independent
 * variable*.
 *
 * A gg run is configured by a capability set rather than a harness+model+orchestrator
 * tuple: which capabilities are on, which implementation each uses, their parameters,
 * and how models bind to [slots](GgSlotBinding). The set is expressed as data so a
 * run's exact configuration is recorded on the run and reproducible, and so
 * [result aggregation](https://docs.testcabinet.ai) can slice results by
 * configuration. Freeze the model and the test case, vary the capability set, and
 * the harness becomes a laboratory.
 *
 * The capability collection is intentionally **open**: capabilities are identified
 * by stable string id, not a closed enum, so later phases add capabilities without a
 * breaking change. A capability that is absent from [`Self::capabilities`] is
 * distinguishable from one that is present but disabled — see [`Self::is_enabled`].
 */
export type GgCapabilitySet = {
  /**
   * The name of a saved preset this set was assembled from (for example
   * `"minimal"`, `"full"`, or `"planning-A"`), when it is a named preset rather
   * than a hand-assembled configuration. A study is a sweep over presets, so this
   * records which one produced a run.
   */
  preset?: string;
  /**
   * The capabilities this run is configured with, each identified by a stable id.
   * A capability absent from this list is off *and* unconfigured; one present but
   * [disabled](GgCapabilityConfig::enabled) is off but records the configuration it
   * would have used, which keeps an ablation's on/off arms symmetric.
   */
  capabilities: Array<GgCapabilityConfig>;
  /**
   * The model-slot bindings for this run. Capabilities reference models by slot
   * name, never by a hardcoded id, so a study re-points a slot without touching any
   * capability's logic. Phase 0 binds a single [`PRIMARY_SLOT`]; the type allows
   * many, possibly cross-provider.
   */
  slots: Array<GgSlotBinding>;
};

/**
 * The **source** a context-window contribution is attributed to, for the per-source
 * accounting [context visibility] reports.
 *
 * gg's context is not a flat transcript: every item that occupies the window is tagged
 * with the source that produced it, so gg can report *what* is filling the window —
 * the signal [compaction] triggers on and the console renders as a stacked line graph.
 * The set is a **closed, stable taxonomy** (unlike the open capability ids): the
 * console's categories and their colors are keyed to these variants, and
 * [`ALL`](Self::ALL) fixes their order so a breakdown is emitted with every category
 * present (a zero when a source contributed nothing this turn), keeping the graph's
 * bands stable across turns.
 *
 * [context visibility]: https://docs.testcabinet.ai/gg/context-visibility/
 * [compaction]: https://docs.testcabinet.ai/gg/compaction/
 */
export type GgContextSource =
  | "system"
  | "user_prompt"
  | "assistant"
  | "tool_output"
  | "file_view"
  | "skill"
  | "memory"
  | "task_list"
  | "history";

/**
 * The estimated token cost attributed to one [`GgContextSource`] at a point in the
 * run — one band of a [`ContextBreakdown`](GgTelemetryKind::ContextBreakdown).
 *
 * The token figure is an **estimate**: exact per-provider counts are not available
 * cross-provider, so gg counts with a fixed BPE tokenizer as a documented cross-model
 * approximation (see the `context` module in the `gg` crate).
 */
export type GgContextSourceUsage = {
  /**
   * The source this band accounts for.
   */
  source: GgContextSource;
  /**
   * The estimated tokens that source occupies in the context window.
   */
  tokens: number;
};

/**
 * The state of one [skill](https://docs.testcabinet.ai/gg/skills/) at a point in a run
 * — a band of a [`SkillsState`](GgTelemetryKind::SkillsState) event.
 *
 * A skill is markdown-with-front-matter authored ahead of the run; its
 * [`description`](Self::description) is shown to the model up front (so it knows the
 * skill exists and what it is for), and [`read`](Self::read) reports whether the model
 * has called `read_skill` on it — at which point the skill's body is loaded into the
 * context window and retained across a [compaction] boundary.
 *
 * [compaction]: https://docs.testcabinet.ai/gg/compaction/
 */
export type GgSkillState = {
  /**
   * The skill's stable name (from its front matter), the handle `read_skill` takes.
   */
  name: string;
  /**
   * The skill's one-line description, shown to the model up front.
   */
  description: string;
  /**
   * Whether the model has read the skill this session (loading its body into context).
   */
  read: boolean;
};

/**
 * The bounds gg enforces on the model's self-curated [memories] — a band of the
 * [`MemoryState`](GgTelemetryKind::MemoryState) event so the console can show how close
 * the model is to each limit.
 *
 * Because memories are curated by the *model itself* (unlike [skills], authored ahead of
 * the run), they must be bounded so self-curated notes cannot crowd out the working
 * context. When a write would exceed a cap, gg rejects it and instructs the model to
 * revise or evict rather than silently truncating or dropping. Lengths are measured in
 * characters of a memory's **body** (its `description` is a short one-liner, like a
 * skill's).
 *
 * [memories]: https://docs.testcabinet.ai/gg/memories/
 * [skills]: https://docs.testcabinet.ai/gg/skills/
 */
export type GgMemoryCaps = {
  /**
   * The maximum number of memories that may exist at once.
   */
  maxCount: number;
  /**
   * The maximum length, in characters, of any single memory's body.
   */
  maxLenPerMemory: number;
  /**
   * The maximum total length, in characters, summed across every memory's body.
   */
  maxTotalLen: number;
};

/**
 * The state of one model-curated [memory](https://docs.testcabinet.ai/gg/memories/) at a
 * point in a run — a band of a [`MemoryState`](GgTelemetryKind::MemoryState) event.
 *
 * A memory is written by the model with `write_memory` (and revised with `update_memory`
 * / removed with `delete_memory`): its [`description`](Self::description) is shown up
 * front (so the model — and the console — can see what each memory is for at a glance),
 * and its body is retained in the context window as a
 * [`Memory`](GgContextSource::Memory)-sourced, compaction-retained item. [`len`](Self::len)
 * is the body's length in characters — what the [caps](GgMemoryCaps) are measured against.
 */
export type GgMemoryEntry = {
  /**
   * The memory's stable name — the handle `update_memory`/`delete_memory` take.
   */
  name: string;
  /**
   * The memory's one-line description, shown up front.
   */
  description: string;
  /**
   * The memory body's length in characters (what the caps bound).
   */
  len: number;
};

/**
 * The status of one [task](https://docs.testcabinet.ai/gg/tasks/) — a field of a
 * [`GgTaskEntry`] in a [`TasksState`](GgTelemetryKind::TasksState) event.
 *
 * A task moves from [`Pending`](Self::Pending) (not started) through
 * [`InProgress`](Self::InProgress) (being worked) to [`Done`](Self::Done) (complete). A
 * task is *actionable* only when all of its blockers are [`Done`](Self::Done); the console
 * derives that from the blocked-by edges and each blocker's status rather than a separate
 * flag.
 */
export type GgTaskStatus = "pending" | "in_progress" | "done";

/**
 * One model-curated [task](https://docs.testcabinet.ai/gg/tasks/) — a node of the
 * blocked-by DAG reported in a [`TasksState`](GgTelemetryKind::TasksState) event.
 *
 * The model builds a lightweight to-do list with `add_task` (and revises it with
 * `update_task` / `set_blocked_by` / `complete_task` / `remove_task`). Each task has a
 * stable [`id`](Self::id) the model coins and references, a [`title`](Self::title), an
 * optional [`description`](Self::description), a [`status`](Self::status), and the set of
 * task ids it is [`blocked_by`](Self::blocked_by). The blocking relation is a **DAG** —
 * gg rejects any edge that would introduce a cycle — and the whole list is retained across
 * a [compaction] boundary verbatim, so the model never loses its plan.
 *
 * [compaction]: https://docs.testcabinet.ai/gg/compaction/
 */
export type GgTaskEntry = {
  /**
   * The task's stable id — the handle the other task tools and every `blockedBy`
   * reference use.
   */
  id: string;
  /**
   * The task's short title.
   */
  title: string;
  /**
   * An optional longer description of the task.
   */
  description?: string;
  /**
   * The task's status.
   */
  status: GgTaskStatus;
  /**
   * The ids of the tasks this task is blocked by (must all be
   * [`Done`](GgTaskStatus::Done) before this task is actionable). The relation is
   * acyclic across the whole list.
   */
  blockedBy: Array<string>;
};

/**
 * The type-specific payload of a [`GgTelemetryEvent`], discriminated by the `type`
 * field.
 *
 * This is schema v1 and is designed to be **extended** — later phases add variants
 * (compaction boundaries, subagent spawn/return, context-window breakdowns, board
 * transitions) without breaking existing ones. Field names are camelCased on the
 * wire; variant tags are snake_case.
 */
export type GgTelemetryKind =
  | { type: "session_started" }
  | { type: "turn_started" }
  | {
      type: "assistant_message";
      /**
       * The text the assistant emitted.
       */
      text: string;
    }
  | {
      type: "tool_call";
      /**
       * The tool's name.
       */
      name: string;
      /**
       * The arguments the agent passed, as a free-form JSON object.
       */
      args: Record<string, unknown>;
    }
  | {
      type: "tool_result";
      /**
       * The tool's name.
       */
      name: string;
      /**
       * Whether the tool call succeeded.
       */
      ok: boolean;
      /**
       * A short human-readable summary of the result, when one is available.
       */
      summary?: string;
    }
  | {
      type: "usage";
      /**
       * The normalized token counts for this accounting.
       */
      tokens: TokenMetrics;
      /**
       * The cost of this accounting, when it could be determined.
       */
      cost?: CostMetrics;
    }
  | {
      type: "context_breakdown";
      /**
       * One band per [`GgContextSource`], in [`GgContextSource::ALL`] order (a source
       * that contributed nothing this turn is present with `0`), so the graph's bands
       * stay stable across turns.
       */
      bySource: Array<GgContextSourceUsage>;
      /**
       * The estimated total tokens across every source — the numerator of fullness.
       */
      totalTokens: number;
      /**
       * The active model's context-window limit, when known (a capability param or a
       * built-in per-model default). The denominator of fullness.
       */
      windowLimit?: number;
      /**
       * `total_tokens / window_limit` in `0.0..=1.0+`, when a limit is known — the
       * fullness signal compaction triggers on.
       */
      fullness?: number;
    }
  | {
      type: "skills_state";
      /**
       * One entry per available skill, in the order the catalog lists them.
       */
      skills: Array<GgSkillState>;
    }
  | {
      type: "memory_state";
      /**
       * One entry per memory currently held, in name order.
       */
      memories: Array<GgMemoryEntry>;
      /**
       * The number of memories currently held (the length of `memories`).
       */
      count: number;
      /**
       * The total length, in characters, summed across every memory's body.
       */
      totalLen: number;
      /**
       * The bounds these memories are kept within.
       */
      caps: GgMemoryCaps;
    }
  | {
      type: "tasks_state";
      /**
       * The tasks, in the order the model added them (a stable order for the DAG's
       * nodes). Each carries its status and the ids it is blocked by.
       */
      tasks: Array<GgTaskEntry>;
    }
  | {
      type: "log";
      /**
       * The severity level (for example `"info"`, `"warn"`, or `"error"`).
       */
      level: string;
      /**
       * The log message.
       */
      message: string;
    }
  | {
      type: "session_ended";
      /**
       * How the session ended (for example `"completed"`, `"error"`, or
       * `"timed_out"`).
       */
      status: string;
    };

/**
 * A single event in gg's first-party telemetry stream (schema v1).
 *
 * Because gg is [headless](https://docs.testcabinet.ai/gg/overview/), this stream is
 * the only live window into a run — the console renders it natively. Each event
 * carries common fields (a timestamp and an optional session id) plus the
 * type-specific [`GgTelemetryKind`], flattened into the serialized form so the
 * discriminator and its fields sit inline.
 *
 * The [`agent_id`](Self::agent_id), [`parent_agent_id`](Self::parent_agent_id), and
 * [`issue_id`](Self::issue_id) fields are **reserved for later phases** and are
 * present up front so the schema is designed once: the subagent tree (which the agent
 * ids form) lands in Phase 4 and the epic/issue board (which `issue_id` scopes to)
 * lands in Phase 3. A Phase 0 run leaves them unset.
 */
export type GgTelemetryEvent = {
  /**
   * RFC 3339 / ISO 8601 time the event was emitted.
   */
  timestamp: string;
  /**
   * The gg session this event belongs to, when one is known.
   */
  sessionId?: string;
  /**
   * **Reserved for Phase 4.** The id of the agent that emitted the event, so events
   * can be attributed to a node in the subagent tree. Unset before subagents exist.
   */
  agentId?: string;
  /**
   * **Reserved for Phase 4.** The id of the agent that spawned the emitting agent,
   * so the subagent tree's parent→child edges can be reconstructed. Unset before
   * subagents exist.
   */
  parentAgentId?: string;
  /**
   * **Reserved for Phase 3.** The id of the epic/issue this event's work is scoped
   * to, for the live board. Unset before the board exists.
   */
  issueId?: string;
} & (
  | { type: "session_started" }
  | { type: "turn_started" }
  | {
      type: "assistant_message";
      /**
       * The text the assistant emitted.
       */
      text: string;
    }
  | {
      type: "tool_call";
      /**
       * The tool's name.
       */
      name: string;
      /**
       * The arguments the agent passed, as a free-form JSON object.
       */
      args: Record<string, unknown>;
    }
  | {
      type: "tool_result";
      /**
       * The tool's name.
       */
      name: string;
      /**
       * Whether the tool call succeeded.
       */
      ok: boolean;
      /**
       * A short human-readable summary of the result, when one is available.
       */
      summary?: string;
    }
  | {
      type: "usage";
      /**
       * The normalized token counts for this accounting.
       */
      tokens: TokenMetrics;
      /**
       * The cost of this accounting, when it could be determined.
       */
      cost?: CostMetrics;
    }
  | {
      type: "context_breakdown";
      /**
       * One band per [`GgContextSource`], in [`GgContextSource::ALL`] order (a source
       * that contributed nothing this turn is present with `0`), so the graph's bands
       * stay stable across turns.
       */
      bySource: Array<GgContextSourceUsage>;
      /**
       * The estimated total tokens across every source — the numerator of fullness.
       */
      totalTokens: number;
      /**
       * The active model's context-window limit, when known (a capability param or a
       * built-in per-model default). The denominator of fullness.
       */
      windowLimit?: number;
      /**
       * `total_tokens / window_limit` in `0.0..=1.0+`, when a limit is known — the
       * fullness signal compaction triggers on.
       */
      fullness?: number;
    }
  | {
      type: "skills_state";
      /**
       * One entry per available skill, in the order the catalog lists them.
       */
      skills: Array<GgSkillState>;
    }
  | {
      type: "memory_state";
      /**
       * One entry per memory currently held, in name order.
       */
      memories: Array<GgMemoryEntry>;
      /**
       * The number of memories currently held (the length of `memories`).
       */
      count: number;
      /**
       * The total length, in characters, summed across every memory's body.
       */
      totalLen: number;
      /**
       * The bounds these memories are kept within.
       */
      caps: GgMemoryCaps;
    }
  | {
      type: "tasks_state";
      /**
       * The tasks, in the order the model added them (a stable order for the DAG's
       * nodes). Each carries its status and the ids it is blocked by.
       */
      tasks: Array<GgTaskEntry>;
    }
  | {
      type: "log";
      /**
       * The severity level (for example `"info"`, `"warn"`, or `"error"`).
       */
      level: string;
      /**
       * The log message.
       */
      message: string;
    }
  | {
      type: "session_ended";
      /**
       * How the session ended (for example `"completed"`, `"error"`, or
       * `"timed_out"`).
       */
      status: string;
    }
);
