// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` and `crates/backend`, which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.

/**
 * A reviewer's subjective quality rating for a finished implementation.
 *
 * Assigned by hand while playing the build, ordered best to worst. It is a
 * per-run signal shown alongside a run, never an aggregate or a ranking across
 * runs (see `docs/site.md`).
 */
export type Rating = "flawless" | "great" | "scuffed" | "broken";

/**
 * A reviewer's verdict on one declared checklist item.
 *
 * A test case declares the checklist (see [`crate::test_case::ReviewItem`]); the
 * reviewer records one of these per item while judging the build.
 *
 * Most case types grade an item **binary** — [`Pass`](VerdictStatus::Pass) or
 * [`Fail`](VerdictStatus::Fail) — and the item earns all its weight or none. A
 * [game jam](crate::test_case::TestType::GameJam) instead grades each of its
 * review categories on a five-level **graded** scale worth a fixed number of
 * points ([`Broken`](VerdictStatus::Broken) 0 → [`Incredible`](VerdictStatus::Incredible)
 * 10); the same graded scale carries the reviewer's whole-game
 * [`OVERALL_VERDICT_ID`] mark. Which scale an item uses is declared on the item
 * ([`crate::test_case::ReviewItem::graded`]); the two never mix within a case.
 * Keep the tiers and their point values in lockstep with the TypeScript
 * `VERDICT_META` in `packages/ui/src/ratings.ts`.
 */
export type VerdictStatus =
  | "pass"
  | "fail"
  | "broken"
  | "poor"
  | "neutral"
  | "great"
  | "incredible";

/**
 * A reviewer's recorded verdict on one declared checklist item.
 */
export type ReviewVerdict = {
  /**
   * The declared item's stable id (see [`crate::test_case::ReviewItem::id`]).
   */
  id: string;
  /**
   * The reviewer's verdict on the item.
   */
  status: VerdictStatus;
  /**
   * An optional one-line note recording what the reviewer observed. `None`
   * when the reviewer left no note.
   */
  note?: string;
};

/**
 * A reviewer's quality [`Rating`] for one of a case's scoring domains.
 */
export type DomainRating = {
  /**
   * The declared domain's stable id (see [`crate::test_case::Domain::id`]).
   */
  domain: string;
  /**
   * The reviewer's rating for this domain.
   */
  rating: Rating;
};

/**
 * One published review on a run: the reviewer's public identity, their per-domain
 * ratings, the writeup, and their checklist verdicts. This is the canonical
 * review wire shape (`backend-api/review.schema.json`), referenced by the per-run
 * snapshot document.
 */
export type Review = {
  /**
   * The reviewing account's id (stable across their reviews).
   */
  reviewerId: string;
  /**
   * The reviewer's display name, shown beside their review.
   */
  reviewer: string;
  /**
   * The reviewer's rating for each scoring domain. This review's overall
   * rating is the worst across them.
   */
  ratings: Array<DomainRating>;
  writeup: string;
  checklist: Array<ReviewVerdict>;
  /**
   * RFC 3339 of when the review was submitted.
   */
  reviewedAt: string;
};
