// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` and `crates/backend`, which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.

import type { HarnessSlug } from "./index";

/**
 * One test case in a plan, pinned to an exact version (and variant). Coverage is
 * counted against exactly this version; the matrix flags it when a newer version
 * has since been ingested.
 */
export type ReviewPlanCase = {
  /**
   * The test-case slug (e.g. `caldera`).
   */
  slug: string;
  /**
   * The pinned, exact version (e.g. `v1.2.0`).
   */
  version: string;
  /**
   * The variant to cover (e.g. `base`).
   */
  variant: string;
};

/**
 * One harness+model combination in a plan. The optional provider mirrors the new-
 * run form's per-combination provider for provider-routed harnesses.
 */
export type ReviewPlanCombo = {
  /**
   * The agent harness to drive.
   */
  harness: HarnessSlug;
  /**
   * The opaque model id passed to the harness.
   */
  model: string;
  /**
   * The provider for a provider-routed harness, or null.
   */
  provider?: string;
};

/**
 * A reviewer's saved coverage plan: the combinations and version-pinned cases
 * they want covered, and how many runs they want for each `case × combination`
 * cell. Persisted whole (one row per account) and read back to render the matrix.
 */
export type ReviewPlan = {
  /**
   * The target number of runs desired for each `case × combination` cell.
   */
  runsPerCell: number;
  /**
   * The version-pinned test cases in the plan.
   */
  cases: Array<ReviewPlanCase>;
  /**
   * The harness+model combinations in the plan.
   */
  combinations: Array<ReviewPlanCombo>;
};

/**
 * One cell of the coverage matrix: a plan case (at its pinned version) crossed
 * with a plan combination, with the run/job counts that say how close it is to
 * the target.
 */
export type CoverageCell = {
  /**
   * The test-case slug.
   */
  slug: string;
  /**
   * The pinned version this cell counts against.
   */
  version: string;
  /**
   * The variant.
   */
  variant: string;
  /**
   * The harness.
   */
  harness: HarnessSlug;
  /**
   * The model id.
   */
  model: string;
  /**
   * The provider for a provider-routed harness, or null.
   */
  provider?: string;
  /**
   * The target run count (the plan's `runs_per_cell`).
   */
  desired: number;
  /**
   * Completed runs for this cell.
   */
  completed: number;
  /**
   * In-flight jobs (queued / dispatched / running) for this cell.
   */
  inFlight: number;
  /**
   * How many more runs to trigger: `max(0, desired - (completed + in_flight))`.
   */
  remaining: number;
  /**
   * The newest ingested version of this case (may differ from `version` when
   * the pin is stale). Empty when the case is not ingested.
   */
  latestVersion: string;
  /**
   * Whether the pinned `version` is not the newest ingested one — a hint to the
   * reviewer that they may want to bump the pin.
   */
  stale: boolean;
};

/**
 * The coverage matrix `GET /review-plan/coverage` returns: every cell plus the
 * rollups the Home widget and the matrix header show.
 */
export type CoverageMatrix = {
  /**
   * Every `case × combination` cell, in plan order (cases outer, combinations
   * inner).
   */
  cells: Array<CoverageCell>;
  /**
   * How many cells have met their target (`remaining == 0`).
   */
  cellsSatisfied: number;
  /**
   * The total number of cells.
   */
  cellsTotal: number;
  /**
   * The sum of every cell's `remaining` — the total runs still to trigger.
   */
  runsMissing: number;
};
