// @generated by `contract-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p
// contract-codegen` and formats the output). The source of truth is the Rust
// contract types in `crates/core` (and `crates/worker` / `crates/backend`), which
// derive `ts_rs::TS` + `schemars::JsonSchema` behind their `contract` feature. The
// JSON Schemas under `apps/docs/public/schema/` are generated from the same types
// in the same pass.

/**
 * A reviewer's subjective quality rating for a finished implementation.
 *
 * Assigned by hand while playing the build, ordered best to worst. It is a
 * per-run signal shown alongside a run, never an aggregate or a ranking across
 * runs (see `docs/site.md`).
 */
export type Rating = "flawless" | "great" | "scuffed" | "broken";

/**
 * A reviewer's verdict on one declared checklist item.
 *
 * A test case declares the checklist (see [`crate::test_case::ReviewItem`]); the
 * reviewer records one of these per item while judging the build. Ordered by
 * neither severity nor preference — it simply states what the reviewer found.
 */
export type VerdictStatus = "pass" | "fail";

/**
 * A reviewer's recorded verdict on one declared checklist item.
 */
export type ReviewVerdict = {
  /**
   * The declared item's stable id (see [`crate::test_case::ReviewItem::id`]).
   */
  id: string;
  /**
   * The reviewer's verdict on the item.
   */
  status: VerdictStatus;
  /**
   * An optional one-line note recording what the reviewer observed. `None`
   * when the reviewer left no note.
   */
  note?: string;
};

/**
 * A reviewer's quality [`Rating`] for one of a case's scoring domains.
 */
export type DomainRating = {
  /**
   * The declared domain's stable id (see [`crate::test_case::Domain::id`]).
   */
  domain: string;
  /**
   * The reviewer's rating for this domain.
   */
  rating: Rating;
};
