"""The superrepo's package links: which sibling checkout a workspace resolves a project package from.

A repository's npm workspace names each package of the project it depends on at a
version the package feed holds, so a checkout built apart installs it from the
feed. Inside the superrepo the package resolves from the sibling checkout that
produces it instead, as it is on disk, the npm counterpart of the `[patch]`
table in the superrepo's `.cargo/config.toml`. The Repositories development
page of the documentation site states the rule.

The superrepo holds the table of what each checked-out repository produces in
`.package-links.json` at its root, outside every repository's files, generated
by its `scripts/repos/sources.py package-links --write`:

    {
      "workspaces": {
        "contracts": {
          "@clockwyrks/run-record": "packages/run-record"
        }
      }
    }

Each key under `workspaces` is a workspace relative to the superrepo (a
repository's npm workspace is its root, so the key is the repository), and each
of its entries a package one of its members produces, relative to that
workspace. A workspace is linked by installing it with the producers'
directories given as the packages to install and `--install-links=false`, so
npm writes a symlink for each one in place of the version the lock names and
never fetches that version, and `--no-save`, so the manifests and the lock stay
as committed. A consumer compiles against the producer's `dist/`, so a
producer workspace is built before any workspace that links it.

This module is the one derivation of all of that. It reads the standard
library alone, because the superrepo's `sources.py` and its `dependency-graph`
gate import it from the kit by path, and a repository's `typescript` gate
imports it from the copy the kit renders.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

TABLE = ".package-links.json"
COMMENT = (
    "The TypeScript packages the checked-out repositories produce, each linked into every workspace of "
    "the superrepo that names it. Generated by scripts/repos/sources.py package-links --write, which "
    "scripts/repos/link-packages.sh runs before it links them; the dependency-graph gate holds it to "
    "the checkouts."
)
# The fields of a manifest that name a package a workspace installs.
DEPENDENCY_FIELDS = ("dependencies", "devDependencies", "peerDependencies", "optionalDependencies")
NODE_MODULES = "node_modules"

# workspace (superrepo-relative) -> package -> member directory (workspace-relative)
Table = dict[str, dict[str, str]]


class LinkTableError(ValueError):
    """The superrepo's link table is not the shape `sources.py` writes."""

    code = "invalid-argument"


class LinkCycleError(ValueError):
    """Two workspaces each link a package the other produces, so neither can be built first."""

    code = "conflict"


@dataclass(frozen=True)
class Link:
    """One package a workspace resolves from a sibling checkout."""

    package: str
    # The producing workspace and the package's directory, both relative to the superrepo.
    workspace: str
    directory: str


def _manifest(path: Path) -> dict[str, object]:
    """A `package.json`, or an empty object when it is absent or not an object."""
    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return parsed if isinstance(parsed, dict) else {}


def member_directories(workspace: Path) -> list[Path]:
    """The member directories the workspace manifest's `workspaces` names, each holding a `package.json`."""
    patterns = _manifest(workspace / "package.json").get("workspaces", [])
    if isinstance(patterns, dict):
        patterns = patterns.get("packages", [])
    if not isinstance(patterns, list):
        return []
    found: set[Path] = set()
    for pattern in patterns:
        if not isinstance(pattern, str) or not pattern.strip("./"):
            continue
        for candidate in workspace.glob(pattern.rstrip("/")):
            if (candidate / "package.json").is_file():
                found.add(candidate)
    return sorted(found)


def members(workspace: Path) -> dict[str, str]:
    """Each package the workspace's members produce, to its directory relative to the workspace."""
    produced: dict[str, str] = {}
    for directory in member_directories(workspace):
        name = _manifest(directory / "package.json").get("name")
        if isinstance(name, str) and name:
            produced[name] = directory.relative_to(workspace).as_posix()
    return produced


def named(workspace: Path) -> set[str]:
    """Every package the workspace installs: the ones its manifests name and every entry its lock holds."""
    manifests = [workspace / "package.json", *(d / "package.json" for d in member_directories(workspace))]
    names: set[str] = set()
    for manifest in manifests:
        parsed = _manifest(manifest)
        for field in DEPENDENCY_FIELDS:
            entries = parsed.get(field)
            if isinstance(entries, dict):
                names.update(name for name in entries if isinstance(name, str))
    packages = _manifest(workspace / "package-lock.json").get("packages")
    if isinstance(packages, dict):
        for key in packages:
            if isinstance(key, str) and f"{NODE_MODULES}/" in f"/{key}":
                names.add(key.rsplit(f"{NODE_MODULES}/", 1)[1])
    return names


def produced(root: Path, workspaces: Iterable[str]) -> Table:
    """What each of `workspaces` (relative to `root`) produces, for those that hold a workspace manifest."""
    table: Table = {}
    for workspace in workspaces:
        path = root / workspace
        if (path / "package.json").is_file():
            own = members(path)
            if own:
                table[PurePosixPath(workspace).as_posix()] = dict(sorted(own.items()))
    return dict(sorted(table.items()))


def producers(table: Mapping[str, Mapping[str, str]]) -> dict[str, list[str]]:
    """Each package to every workspace the table says produces it; more than one is a conflict."""
    found: dict[str, list[str]] = {}
    for workspace, packages in table.items():
        for package in packages:
            found.setdefault(package, []).append(workspace)
    return found


def index(table: Mapping[str, Mapping[str, str]]) -> dict[str, Link]:
    """Each package the table links, to the one link that produces it (the first, where two claim it)."""
    links: dict[str, Link] = {}
    for workspace, packages in table.items():
        for package, directory in packages.items():
            links.setdefault(package, Link(package, workspace, (PurePosixPath(workspace) / directory).as_posix()))
    return links


def render_table(table: Mapping[str, Mapping[str, str]]) -> str:
    """The table as `sources.py package-links --write` writes it."""
    ordered = {workspace: dict(sorted(table[workspace].items())) for workspace in sorted(table)}
    return json.dumps({"$comment": COMMENT, "workspaces": ordered}, indent=2) + "\n"


def parse_table(text: str) -> Table:
    """The table a `.package-links.json` holds."""
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError as error:
        raise LinkTableError(f"{TABLE} is not JSON: {error}") from error
    workspaces = parsed.get("workspaces") if isinstance(parsed, dict) else None
    if not isinstance(workspaces, dict):
        raise LinkTableError(f'{TABLE} holds no "workspaces" object')
    table: Table = {}
    for workspace, packages in workspaces.items():
        if not isinstance(packages, dict) or not all(
            isinstance(name, str) and isinstance(directory, str) for name, directory in packages.items()
        ):
            raise LinkTableError(f"{TABLE}: {workspace} does not map each package to a directory")
        table[workspace] = dict(packages)
    return table


def load_table(superrepo: Path) -> Table:
    """The superrepo's table; empty when it has none."""
    path = superrepo / TABLE
    if not path.is_file():
        return {}
    return parse_table(path.read_text(encoding="utf-8"))


def find_superrepo(repository: Path) -> Path | None:
    """The superrepo a repository is checked out inside: the nearest directory above it holding the table."""
    for ancestor in repository.resolve().parents:
        if (ancestor / TABLE).is_file():
            return ancestor
    return None


def surrounding(repository: Path) -> tuple[Path | None, Table]:
    """The superrepo above a repository, and its table; `(None, {})` for a repository checked out on its own."""
    superrepo = find_superrepo(repository)
    if superrepo is None:
        return None, {}
    return superrepo, load_table(superrepo)


def links_of(superrepo: Path, table: Mapping[str, Mapping[str, str]], workspace: str) -> list[Link]:
    """The links a workspace installs with: each package it names that another checked-out workspace produces.

    A package the workspace produces itself is its own workspace's link, and a
    producer whose directory is absent, a repository not checked out, is
    installed from the feed as it would be apart, so neither is linked.
    """
    path = superrepo / workspace
    own = set(members(path))
    names = named(path)
    return [
        link
        for package, link in sorted(index(table).items())
        if package in names
        and package not in own
        and link.workspace != workspace
        and (superrepo / link.directory / "package.json").is_file()
    ]


def build_order(superrepo: Path, table: Mapping[str, Mapping[str, str]], workspace: str) -> list[str]:
    """The producer workspaces to build before `workspace`, each after the ones it links itself."""
    order: list[str] = []
    visiting: list[str] = []

    def visit(current: str) -> None:
        if current in order:
            return
        if current in visiting:
            cycle = " -> ".join([*visiting[visiting.index(current) :], current])
            raise LinkCycleError(f"the workspaces link each other's packages: {cycle}")
        visiting.append(current)
        for producer in dict.fromkeys(link.workspace for link in links_of(superrepo, table, current)):
            visit(producer)
        visiting.pop()
        order.append(current)

    visit(workspace)
    return order[:-1]


@dataclass(frozen=True)
class Step:
    """One step of linking the superrepo: install a workspace with its links, or build it."""

    action: str  # "install" or "build"
    workspace: str
    links: tuple[Link, ...] = ()


def plan(superrepo: Path, table: Mapping[str, Mapping[str, str]], workspaces: Iterable[str]) -> list[Step]:
    """The steps that link every workspace of `workspaces` that names a linked package.

    Every workspace that links a package is installed with its links, and every
    producer it links is installed and built before it, producers of producers
    first.
    """
    consumers = [workspace for workspace in workspaces if links_of(superrepo, table, workspace)]
    ordered: list[str] = []
    built: set[str] = set()
    for consumer in consumers:
        before = build_order(superrepo, table, consumer)
        built.update(before)
        ordered.extend(workspace for workspace in [*before, consumer] if workspace not in ordered)
    steps: list[Step] = []
    for workspace in ordered:
        steps.append(Step("install", workspace, tuple(links_of(superrepo, table, workspace))))
        if workspace in built:
            steps.append(Step("build", workspace))
    return steps


def installed(workspace: Path) -> bool:
    """Whether the workspace has been installed at all."""
    return (workspace / NODE_MODULES).is_dir()


def linked(superrepo: Path, workspace: str, link: Link) -> bool:
    """Whether the workspace's install resolves the package to the producer's directory."""
    entry = superrepo / workspace / NODE_MODULES / link.package
    return entry.is_symlink() and entry.resolve() == (superrepo / link.directory).resolve()


def install_arguments(superrepo: Path, links: Iterable[Link]) -> list[str]:
    """The npm command that installs a workspace with its links; `npm ci` when it links nothing."""
    directories = [str((superrepo / link.directory).resolve()) for link in links]
    if not directories:
        return ["npm", "ci", "--no-audit", "--no-fund"]
    return ["npm", "install", "--no-save", "--install-links=false", "--no-audit", "--no-fund", *directories]


# What a linked install runs first: npm's own check that the lock agrees with
# the manifests, which `npm install` would otherwise settle silently. A dry run
# fetches nothing while they agree.
LOCK_CHECK = ["npm", "ci", "--dry-run", "--no-audit", "--no-fund"]
