#!/usr/bin/env bash
#
# Reflect this guest's signature catalogues out of the SDK's own emitted declarations, and write
# `$GG_SIGNATURES_OUT_DIR/typescript.signatures.json` and `$GG_SIGNATURES_OUT_DIR/javascript.signatures.json`.
#
# TWO files from ONE set of declarations, because gg's TypeScript and JavaScript arms ARE one set of
# declarations: the same guest, the same SDK, the same signatures, and one difference — whether gg
# type-checks the program before evaluating it. A model on either arm therefore reads exactly the
# same surface, and each arm still embeds a catalogue that names itself, so a catalogue wired to the
# wrong arm is a load-time failure rather than documentation describing a sandbox nobody has.
#
# WHY THIS IS A SHELL SCRIPT AND NOT JUST AN NPM SCRIPT. Every other arm's reflection is
# `packages/gg-sandbox-<lang>/signatures.sh`, and `scripts/gg-signatures.sh` — the one place that
# knows the eleven arms — runs them as a list of paths. An `npm run --workspace …` line in that list
# would be the single entry shaped differently from the other ten, invoked through a package manager
# that has to be told which workspace, from a directory it then changes for you. It is also the entry
# that fails worst without `node_modules`: npm's own error names a missing script, not the missing
# install. So the npm script stays (it is how a Node developer reaches this) and delegates HERE, and
# the precondition below says the thing a person can act on. `package.json`'s `signatures` entry runs
# this file.
#
# WHERE IT WRITES, AND WHY THERE IS NO DEFAULT. The catalogues are BUILD ARTIFACTS.
# `crates/gg/build.rs` runs `scripts/gg-signatures.sh` and embeds what lands in the build's own
# `OUT_DIR`, so what a model is told about this arm is reflected out of the SDK on the same build
# that compiles the host telling it — it cannot be stale, because there is no copy old enough to be.
# A default here would be a second answer to a question the build already answers, and the old one —
# `crates/gg/src/sandbox/guests/` — is exactly the answer that stopped being right: that directory
# no longer exists, the component included.
#
# You still run this by hand to READ a catalogue. That is not a fallback, it is the point: an emitted
# catalogue is where a reflector bug shows itself — a dropped `@returns` paragraph, a truncated
# `@param`, only the first overload's prose — and a person has to be able to open one.
# `scripts/gg-signatures.sh` picks a directory, regenerates every arm into it, and prints where.
#
# WHAT IT NEEDS. Node and the pinned `typescript` from a repo-root `npm ci`, and nothing else — no
# Rust toolchain, no network. The guest beside it is `build.sh`'s business, and both are cut into a
# cargo `OUT_DIR` — a different one each, by a different caller, on a different schedule.
#
# Usage:
#   GG_SIGNATURES_OUT_DIR=<dir> packages/gg-sandbox/signatures.sh
#   scripts/gg-signatures.sh                 # all eleven arms, into one directory
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"

if [ -z "${GG_SIGNATURES_OUT_DIR:-}" ]; then
	echo "error: GG_SIGNATURES_OUT_DIR is not set. It names the directory these catalogues are" >&2
	echo "       written into, and there is no default — they are generated by the build rather" >&2
	echo "       than committed anywhere." >&2
	echo "       Run scripts/gg-signatures.sh (which sets it and regenerates every arm), or set" >&2
	echo "       it yourself to a directory you want the JSON in." >&2
	exit 1
fi
mkdir -p "$GG_SIGNATURES_OUT_DIR"
# Made absolute before the reflector is started, because it resolves the path against its own
# working directory and this script runs `tsc` from the package rather than from the caller's cwd.
GG_SIGNATURES_OUT_DIR="$(cd "$GG_SIGNATURES_OUT_DIR" && pwd)"
export GG_SIGNATURES_OUT_DIR

# The pinned `typescript` is this package's one devDependency, hoisted to the repo root by npm's
# workspaces. Both halves below need it — `tsc` emits the declarations, and the reflector loads the
# same install's compiler API to read them — so its absence is worth a sentence naming the fix rather
# than a "command not found" from two directories away.
TSC="$ROOT/node_modules/.bin/tsc"
if [ ! -x "$TSC" ]; then
	echo "error: no \`tsc\` at $TSC — the npm workspaces are not installed." >&2
	echo "       Run \`npm ci\` at the repository root." >&2
	exit 1
fi

# 1. Emit the declarations. `tsconfig.headers.json` is a declaration-only project over the same
#    sources the component is built from, so what is reflected below is the compiler's own reading of
#    each declaration rather than a second parse of the `.ts`.
"$TSC" -p "$HERE/tsconfig.headers.json"

# 2. Reflect both catalogues out of those declarations.
node "$HERE/tools/signatures.mjs"
