#!/usr/bin/env bash
#
# Reflect this package's signature catalogue out of its SDK, and write
# `$GG_SIGNATURES_OUT_DIR/python.signatures.json`.
#
# It is the whole of what a model is *told* about the Python surface — every module, signature,
# argument, type and type member the prompt renders and `views.open_docs_view` answers with, plus the
# set of libraries a program may import — and every word of it is reflected out of the code it
# describes: a docstring for the SDK, and `src/library.py`'s own module-scope imports for the library
# set. Nothing about this arm is authored in a table, a template or a prompt.
#
# WHERE IT WRITES, AND WHY THERE IS NO DEFAULT. The catalogue is a BUILD ARTIFACT. `crates/gg/build.rs`
# runs `scripts/gg-signatures.sh` and embeds what lands in the build's own `OUT_DIR`, so the file a
# model is described by is reflected out of the SDK on the same build that compiles the host — it
# cannot be stale, because there is no copy old enough to be. That is why this script demands
# `GG_SIGNATURES_OUT_DIR` rather than defaulting: a default would be a second answer to a question the
# build already answers, and the old one — `crates/gg/src/sandbox/guests/` — is exactly the answer
# that stopped being right, since nothing is committed there any more.
#
# You still run it by hand to READ a catalogue, which is the point of keeping it a plain script: an
# emitted JSON is where a reflector bug shows itself (a dropped `Returns:` paragraph, a truncated
# argument description), and a person has to be able to open one. `scripts/gg-signatures.sh` is the
# comfortable way in — it picks the directory, regenerates every arm into it, and prints where.
#
# It is deliberately SEPARATE from `build.sh`. Emitting the catalogue reads the sources statically
# and needs only `griffe`; baking the component needs `componentize-py`, a network and ~25 MB of
# output. That split is what lets the *build* reflect this arm's documentation on every machine while
# the component stays a hand-run, committed artifact — exactly as the TypeScript guest's `signatures.sh`
# is separate from its `build.sh`.
#
# Usage:
#   GG_SIGNATURES_OUT_DIR=<dir> packages/gg-sandbox-python/signatures.sh
#   scripts/gg-signatures.sh                 # all eleven arms, into one directory
set -euo pipefail

# Repo root, independent of the caller's working directory.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

PACKAGE="packages/gg-sandbox-python"

if [ -z "${GG_SIGNATURES_OUT_DIR:-}" ]; then
	echo "error: GG_SIGNATURES_OUT_DIR is not set. It names the directory this catalogue is" >&2
	echo "       written into, and there is no default — the catalogue is generated by the build" >&2
	echo "       rather than committed anywhere." >&2
	echo "       Run scripts/gg-signatures.sh (which sets it and regenerates every arm), or set" >&2
	echo "       it yourself to a directory you want the JSON in." >&2
	exit 1
fi
mkdir -p "$GG_SIGNATURES_OUT_DIR"
# Made absolute before it is handed on: `uv run` inherits this script's cwd, but several of the other
# ten arms hand the path to a tool they run from somewhere else, and one relative path meaning two
# directories depending on the arm is the kind of difference nobody finds until a file is missing.
DEST_DIR="$(cd "$GG_SIGNATURES_OUT_DIR" && pwd)"

# The documentation tool the catalogue is reflected with, pinned. `griffe` is Python's own answer to
# reading a package's API: it parses the sources statically — no import, which matters because every
# SDK module imports `wit_world`, and that only exists inside the baked component — and hands back
# each function's parameters, annotations, defaults, and the parsed sections of its Google-style
# docstring.
#
# Pinned rather than floating for the reason `build.sh` pins `componentize-py`: a silent toolchain
# bump would change what a model is told about this arm on the next build of gg, with nothing in the
# diff of the checkout to say why.
GRIFFE_VERSION="2.1.0"

# Run through `uv`, which is this repo's Python toolchain — the devcontainer installs it
# (.devcontainer/tools/uv.sh), `build.sh` requires it, and `scripts/ci/install-uv.sh` puts it on a CI
# agent. It is not a preference: the devcontainer's base image has no usable `pip` and no
# `ensurepip`, and a CI agent's system Python refuses an install outright (PEP 668), so a private
# environment created by anything else does not exist on all three machines.
#
# `--no-project` because this package is not a Python project — it has no `pyproject.toml` and is
# never installed — and `--with` puts the pinned griffe in the ephemeral environment `uv` builds for
# the run. The environment is cached under uv's own cache, so a second run costs no download.
if ! command -v uv >/dev/null 2>&1; then
	echo "error: this needs \`uv\` on PATH to run the pinned griffe with." >&2
	echo "       Run scripts/ci/install-gg-toolchains.sh." >&2
	exit 1
fi

# NO BYTECODE CACHE. The reflector loads `src/gg/catalogue.py` by path — it reads this arm's
# operation table off the module itself rather than off a table typed beside it — and an ordinary
# CPython drops a `__pycache__/` beside every module it imports. That directory is gitignored and
# harmless to a person, but `crates/gg/build.rs` names this package's `src` and `tools` subtrees as
# the inputs whose change should re-reflect the catalogue, so a run that writes into one of them
# leaves the next `cargo build` convinced its inputs moved and re-runs all eleven arms. The export
# lives here rather than only in `scripts/gg-signatures.sh` because running this script BY HAND is
# the documented way to read a catalogue, and a developer who does that should not pay for it on
# their next build. The caches buy nothing either way: this runs once, as a script.
export PYTHONDONTWRITEBYTECODE=1

exec uv run --quiet --no-project --with "griffe==$GRIFFE_VERSION" \
	python "$PACKAGE/tools/signatures.py" --out-dir "$DEST_DIR"
