#!/usr/bin/env bash
# Generate crates/core/publish-targets.toml, the remote publish targets The Spec Cabinet
# and `tcab ingest --env` read, from the per-environment values in scripts/lib/env.sh.
#
# env.sh is the one place a deployed environment's resource group, cluster, namespace,
# and ingest branch are written. The Rust tools cannot source a shell file, so they read
# the committed TOML this script renders from it, and a test in crates/core runs this
# script and fails when its output differs from the committed file. Re-run it after
# editing env.sh:
#
#   scripts/generate-publish-targets.sh            # rewrite crates/core/publish-targets.toml
#   scripts/generate-publish-targets.sh --stdout   # print what it would write
#   scripts/generate-publish-targets.sh --check    # exit 1 when the committed file differs
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
output="${repo_root}/crates/core/publish-targets.toml"
# shellcheck source=scripts/lib/env.sh
source "${script_dir}/lib/env.sh"

# Every environment env.sh resolves, in the order the targets are offered.
environments=(staging prod)

render() {
  echo "# The remote publish targets, generated by scripts/generate-publish-targets.sh from"
  echo "# scripts/lib/env.sh. Edit env.sh and re-run the script rather than editing this file."
  for env in "${environments[@]}"; do
    tcab_env_resolve "$env"
    echo
    echo "[[target]]"
    echo "name = \"${env}\""
    echo "resource_group = \"${TCAB_RG}\""
    echo "cluster = \"${TCAB_CLUSTER}\""
    echo "namespace = \"${TCAB_NAMESPACE}\""
    echo "ingest_branch = \"${TCAB_INGEST_BRANCH}\""
  done
}

case "${1:-}" in
  "") render > "$output" ;;
  --stdout) render ;;
  --check)
    if ! diff -u "$output" <(render); then
      echo "error: ${output} differs from scripts/lib/env.sh; run scripts/generate-publish-targets.sh" >&2
      exit 1
    fi
    ;;
  *) echo "usage: $0 [--stdout|--check]" >&2; exit 2 ;;
esac
