# shellcheck shell=bash
# shellcheck disable=SC2034  # every table below is read by the scripts that source this file
#
# THE ONE LIST OF gg's PROGRAM-LANGUAGE ARMS. Sourced, never executed.
#
# Eleven arms, ten packages — `packages/gg-sandbox` serves TypeScript and JavaScript from one set of
# declarations and one component, because those two arms ARE one guest and differ only in whether gg
# type-checks the program on the way in. A twelfth arm is one row below.
#
# WHY THIS FILE EXISTS RATHER THAN A LIST INSIDE ONE SCRIPT. `scripts/gg-signatures.sh` used to carry
# the list, and its header claimed — correctly, at the time — to be the only place the arms were
# enumerated. There are now TWO things generated per arm on the way to a build of `test-cabinet-gg`:
#
#   * its SIGNATURE CATALOGUE, reflected out of the SDK's own declarations by that language's own
#     documentation tool, which is what a model is *told* the arm offers; and
#   * its BUILD ARTIFACTS — the guest component or the compiled library set or the checker the arm's
#     programs are compiled and evaluated against, which is what the model's program actually meets.
#
# A second script with a second list would be a second source of truth for the same eleven facts, and
# the two would disagree the first time an arm was renamed. So the list moved down one level, and
# both entry points read it. Everything either of them needs is derivable from a row, because both
# scripts are fixed by convention: an arm's reflector is `<package>/signatures.sh` and its artifact
# build is `<package>/build.sh`, always, with no exceptions and no second producer.
#
# WHAT A ROW SAYS.
#
#   gg_arm <id> <package> <label> --catalogues <stem>... --artifacts <file>...
#
#   id           the arm's identity everywhere else in this repository: the language id gg registers,
#                the stem its artifacts are filed under, and (once its artifact crate exists) the
#                suffix of its `links` key and of the `DEP_GG_ARTIFACT_<ID>_ROOT` cargo hands the
#                consuming build script.
#   package      the directory holding `signatures.sh` and `build.sh`. Relative to the repo root.
#   label        what a person reads while it runs. TypeScript's names both arms it serves.
#   --catalogues the `<stem>.signatures.json` files the reflector promises to write. Two for the
#                TypeScript package and one for everybody else — this is where the eleven-arms-ten-
#                packages arithmetic actually lives, rather than in a comment.
#   --artifacts  the files `build.sh` promises to write into `$GG_ARTIFACTS_OUT_DIR`, named exactly
#                as they land there. Both orchestrators check their own half of a row after the run,
#                because an arm that exits 0 having written nothing is the failure mode a generated
#                artifact has, and it is invisible until something four layers away cannot embed it.
#
# THE `--artifacts` LISTS ARE COMPLETE, AND THAT IS NEW. Every file in them is generated by the row's
# `build.sh` and embedded by `crates/gg` out of the cargo `OUT_DIR` it was written into; nothing gg
# embeds is committed. The per-arm DRIFT MANIFESTS that used to be written beside the committed
# copies — `*.component.manifest.json` for the baked guests, `*.sources.manifest.json` for the
# compiled arms, and the C# arm's `csharp.toolchain.json` — are all gone, along with the script that
# wrote them and the tests that read them. They answered "does the committed artifact match the
# sources beside it?", and there is no committed artifact to ask it of.
#
# What a row promises is therefore checked in the only place a check is still meaningful: both
# orchestrators, and `crates/gg-sandbox-artifacts/build-support`, assert after the run that every
# promised file landed and is non-empty. That catches the failure a generated artifact really has —
# a build that exits 0 having written nothing, or having written under a name the host does not
# embed — which is invisible until an `include_bytes!` four layers away cannot find its file.
#
# NOR does a row name the files under `crates/gg/src/sandbox/checkers/`, which are gg's own
# HAND-WRITTEN SOURCE and are all that is left in that directory: `java.compiler.java`,
# `kotlin.compiler.java` and `jvm.backend.java` are the compiler drivers gg feeds to javac, and
# `java.toolchain.json` and `kotlin.toolchain.json` are pins. Nothing generates any of them; they are
# committed and reviewed by reading, like any other source file. (`crates/gg/src/sandbox/guests/`
# does not exist any more at all — it held nothing but generated components.)

# Every arm id, in the order the rows are declared — which is the order both orchestrators run them.
GG_ARM_IDS=()
# Row fields, keyed by arm id.
declare -A GG_ARM_PACKAGE=()
declare -A GG_ARM_LABEL=()
declare -A GG_ARM_CATALOGUES=()
declare -A GG_ARM_ARTIFACTS=()

# Declare one arm. Positional up to the label, then two named lists — named rather than positional
# because a row with two variable-length tails cannot be read any other way, and because a reader
# scanning for "what does this arm produce?" should not have to count fields.
gg_arm() {
	local id="$1" package="$2" label="$3"
	shift 3

	local catalogues="" artifacts="" section=""
	local argument
	for argument in "$@"; do
		case "$argument" in
		--catalogues)
			section=catalogues
			;;
		--artifacts)
			section=artifacts
			;;
		--*)
			echo "error: gg-arms.sh: unknown field '$argument' in the '$id' row." >&2
			return 1
			;;
		*)
			case "$section" in
			catalogues) catalogues="$catalogues $argument" ;;
			artifacts) artifacts="$artifacts $argument" ;;
			*)
				echo "error: gg-arms.sh: '$argument' in the '$id' row is before any --catalogues or --artifacts." >&2
				return 1
				;;
			esac
			;;
		esac
	done

	if [ -z "$catalogues" ]; then
		echo "error: gg-arms.sh: the '$id' row declares no catalogues." >&2
		return 1
	fi
	if [ -z "$artifacts" ]; then
		echo "error: gg-arms.sh: the '$id' row declares no artifacts." >&2
		return 1
	fi

	GG_ARM_IDS+=("$id")
	GG_ARM_PACKAGE["$id"]="$package"
	GG_ARM_LABEL["$id"]="$label"
	# Leading space trimmed so a caller can `for x in ${GG_ARM_CATALOGUES[$id]}` without an empty word.
	GG_ARM_CATALOGUES["$id"]="${catalogues# }"
	GG_ARM_ARTIFACTS["$id"]="${artifacts# }"
}

# ------------------------------------------------------------------------------------------------
# The eleven arms, in ten packages.
#
# `packages/gg-sandbox` is first because it is the cheapest of the reflections by an order of
# magnitude and because it is the one that fails on a checkout nobody ran `npm ci` in — better to
# learn that in two seconds than after four minutes of javadoc, rustdoc and Roslyn. The rest are in
# the order the packages sit on disk, which is the order a reader of this list will look for them in.
# ------------------------------------------------------------------------------------------------

# TypeScript and JavaScript: one guest, one set of declarations, two catalogues, and four checker
# files cut out of the pinned `typescript` — the compiler bundle, the concatenated default library,
# the globals no SDK declaration covers, and the manifest saying which compiler at which level.
# The three `ecmascript.*` files are the SECOND guest this package builds — quickjs-ng inside a
# `wit-bindgen` component (`packages/gg-sandbox/guest/`, built by `guest.sh`) — and they are named
# for what they serve rather than for this row, because they serve three arms: TypeScript,
# JavaScript and PureScript, all of which evaluate JavaScript. They are in THIS row because that
# guest is cut from THIS package's SDK: the same `src/gg/**` the component above is built from is
# baked into it unchanged, so a second row would need a second copy of the SDK.
gg_arm typescript packages/gg-sandbox "typescript + javascript" \
	--catalogues typescript javascript \
	--artifacts typescript.component.wasm typescript.tsc.js typescript.lib.d.ts \
	typescript.globals.d.ts typescript.checker.json \
	ecmascript.core.wasm ecmascript.adapter.wasm ecmascript.guest.json

# Python: one baked CPython component. Nothing on the turn path is compiled, so there is no checker.
gg_arm python packages/gg-sandbox-python "python" \
	--catalogues python \
	--artifacts python.component.wasm

# Ruby: the baked component, plus the host-side Opal compiler bundle and its manifest — this arm
# compiles the model's Ruby to JavaScript before the guest sees it, and that compiler rides inside
# gg's binary because Opal is small enough to be an artifact.
gg_arm ruby packages/gg-sandbox-ruby "ruby" \
	--catalogues ruby \
	--artifacts ruby.component.wasm ruby.opal.cjs ruby.compiler.json

# PureScript: the compiled library set a program is type-checked against, and what compiled it.
gg_arm purescript packages/gg-sandbox-purescript "purescript" \
	--catalogues purescript \
	--artifacts purescript.libraries.tar.gz purescript.compiler.json

# Java: the SDK as the one jar both compilers a program passes through put on their classpath.
gg_arm java packages/gg-sandbox-java "java" \
	--catalogues java \
	--artifacts java.sdk.jar java.adapter.wasm

# Kotlin: the same shape as Java's, compiled by the Kotlin front end against the same TeaVM.
gg_arm kotlin packages/gg-sandbox-kotlin "kotlin" \
	--catalogues kotlin \
	--artifacts kotlin.sdk.jar

# Rust: every rlib a program is linked against, and what built them.
gg_arm rust packages/gg-sandbox-rust "rust" \
	--catalogues rust \
	--artifacts rust.libraries.tar.gz rust.toolchain.json

# Swift: the guest's compile inputs, the curated library archive, the preview1 reactor adapter, and
# the manifest describing all three.
gg_arm swift packages/gg-sandbox-swift "swift" \
	--catalogues swift \
	--artifacts swift.guest.tar.gz swift.libraries.tar.gz swift.adapter.wasm swift.toolchain.json

# C++: the guest's compile inputs, this arm's own copy of the same adapter, and the manifest.
gg_arm cpp packages/gg-sandbox-cpp "cpp" \
	--catalogues cpp \
	--artifacts cpp.guest.tar.gz cpp.adapter.wasm cpp.toolchain.json

# C#: Mono's IL interpreter with the whole class library bundled into it. This is the one arm whose
# artifact build needs toolchains no gg *run* needs — a whole .NET SDK and an unpruned wasi-sdk —
# which is what `scripts/ci/install-gg-build-toolchains.sh` exists for.
#
# ONE FILE, where every other arm with a compiled artifact promises a declaration beside it. This arm
# used to write `csharp.toolchain.json` too, and it was the one declaration nothing on the turn path
# read: the other arms' are consumed by their `*.compile.rs` at run time (crate lists, header lists,
# module lists, compiler levels), while this one existed only for a test asking whether the COMMITTED
# component matched the checkout. It went with the committing. `packages/gg-sandbox-csharp/build.sh`
# records what it held and where each part of it lives now.
gg_arm csharp packages/gg-sandbox-csharp "csharp" \
	--catalogues csharp \
	--artifacts csharp.component.wasm
