# shellcheck shell=bash
#
# Resolve `$GG_ARTIFACTS_OUT_DIR` for one arm's `build.sh`. Sourced, never executed.
#
# WHERE AN ARM'S ARTIFACTS GO, AND WHY THERE IS NO DEFAULT.
#
# Every `packages/gg-sandbox*/build.sh` used to hard-code its destination — `CHECKERS=`, `GUESTS=`,
# `OUT=`, `DEST_DIR=`, `MANIFEST=`, five spellings of the same two directories under
# `crates/gg/src/sandbox/`. That was right while the artifacts were committed there, and they are not
# committed anywhere any more: every arm has a crate under `crates/gg-sandbox-artifacts/` that runs
# its `build.sh` into that crate's own cargo `OUT_DIR` on every build whose inputs moved, and
# `crates/gg` embeds from there. So there is no "the usual place" left for a destination to default
# to — the place is different on every invocation, and only the caller knows it.
#
# It would be easy to default to the old directory anyway, and it would be a mistake with a specific
# shape. A developer who ran `packages/gg-sandbox-swift/build.sh` out of muscle memory would re-create
# 3.6 MB of deleted files as UNTRACKED ones inside `crates/gg/src` — where they appear in `git
# status`, get swept up by a `git add -A`, and reinstate exactly the committed-artifact state this
# whole arrangement exists to abolish. There is no upside to weigh against that: the only two callers
# are the arm's artifact crate, which passes its own `$OUT_DIR`, and `scripts/gg-artifacts.sh`, which
# passes a directory under the gitignored `target/`. There used to be a third caller —
# `scripts/ci/contract-drift.sh` set this to the old directory ON PURPOSE, because re-cutting into it
# and diffing was the whole of what that half of the script did — and it went with the last committed
# artifact it could diff. A default would serve neither of the two that remain and could only harm.
# `scripts/gg-signatures.sh` and the ten `signatures.sh` beside these scripts already took this
# decision for the catalogues; the reasoning transfers verbatim.
#
# ONE DIRECTORY, FLAT. There is no `guests/` or `checkers/` under it. Those were a filing convention
# for committed files, and every artifact is already named for its arm and its kind
# (`swift.guest.tar.gz`, `typescript.tsc.js`, `csharp.component.wasm`), so a flat destination is
# unambiguous and one variable is enough for a script that used to need two.
#
# Sourced rather than copied into eleven scripts because it is one rule, stated once; each arm's
# `build.sh` then names its own outputs relative to `$GG_ARTIFACTS_OUT_DIR` and says nothing about
# where that is.

if [ -z "${GG_ARTIFACTS_OUT_DIR:-}" ]; then
	echo "error: GG_ARTIFACTS_OUT_DIR is not set. It names the directory this arm's artifacts are" >&2
	echo "       written into, and there is no default — they are generated by the build rather" >&2
	echo "       than committed anywhere." >&2
	echo "       Run scripts/gg-artifacts.sh (which sets it and builds every arm), or set it" >&2
	echo "       yourself to a directory you want the files in." >&2
	exit 1
fi
mkdir -p "$GG_ARTIFACTS_OUT_DIR"
# Absolute before anything is written. Several of these builds run from a package directory, a
# staging tree or a `mktemp -d`, and a relative destination would mean a different place in each —
# which is how an artifact ends up in a directory that is deleted on exit.
GG_ARTIFACTS_OUT_DIR="$(cd "$GG_ARTIFACTS_OUT_DIR" && pwd)"
export GG_ARTIFACTS_OUT_DIR
