#!/usr/bin/env bash
#
# Project gg's model-facing reference into a directory the backend can serve.
#
#   scripts/gg-reference.sh [OUT_DIR]        # default: target/gg-reference
#
# WHAT IT WRITES. Twelve documents: `index.json` — every tool gg can offer a model, with the real
# description and parameter schema that go on the wire, grouped into gg's families, plus a line per
# program language — and one `<language>.json` per arm, carrying every responses-as-code function and
# type on that arm with the bytes that arm's own documentation view renders for a model. Not a
# paraphrase of any of it: the tools come out of a maximal `ToolRegistry` and each entry's body out
# of the same `DocsRuntime::read` a program's own lookup goes through.
#
# WHO SERVES IT. `tcab-backend`, at `GET /gg/reference` and `GET /gg/reference/{language}`, reading
# the directory `TCAB_GG_REFERENCE` names. That indirection is the whole reason this script exists:
# the backend must not depend on `test-cabinet-gg` — oxc and tiktoken-rs are nowhere in that server's
# dependency tree, and building gg reflects eleven SDKs' catalogues with eleven language toolchains,
# which would become a prerequisite for compiling the backend — so the projection crosses the crate
# boundary as files beside the binary, exactly as `packages/browser-driver` does for the Playwright
# driver the backend also ships and never links.
#
# WHO RUNS IT, AND WHY THERE ARE EXACTLY TWO ANSWERS — the same two `scripts/gg-signatures.sh` and
# `scripts/gg-artifacts.sh` have:
#
#   1. THE IMAGE BUILD. `deployments/images/services.Dockerfile`'s `gg-build` stage runs
#      `gg reference --out` from the very binary it just linked, and the backend stage COPYs the
#      result to /opt/gg-reference. So a deployed backend serves the documents projected by the same
#      gg its runs execute, out of one build of one checkout. There is nothing committed to gate and
#      no version skew to detect — which is why the artifact this replaced
#      (`crates/backend/src/gg_reference.json`, regenerated by `npm run gen:contract` and diffed by
#      `scripts/ci/contract-drift.sh`) is gone rather than regenerated.
#
#   2. A DEVELOPER running the backend as a bare process (`cargo run -p test-cabinet-backend`, the
#      path `development/running.md` documents), who has no image to bake anything. The backend's
#      default for TCAB_GG_REFERENCE is `<checkout>/target/gg-reference`, which is where this script
#      writes by default, so the two need no coordination:
#
#          scripts/gg-reference.sh                  # -> target/gg-reference/, which the backend finds
#          scripts/gg-reference.sh /tmp/reference   # -> anywhere else, then point TCAB_GG_REFERENCE at it
#
#      Without it the reference endpoints answer 503 with a message naming this script, and nothing
#      else about the backend is affected — a backend with no reference still serves runs, reviews
#      and the catalog.
#
# WHAT IT NEEDS: whatever BUILDING gg needs, and nothing else. Running the projection needs no
# toolchain at all — every arm's signature catalogue is compiled into the binary by
# `crates/gg/build.rs` — but compiling gg reflects all eleven of them out of their guest SDKs and
# builds every arm's artifacts, so this is `scripts/ci/install-gg-toolchains.sh` +
# `scripts/ci/install-gg-build-toolchains.sh` territory. The devcontainer has run both. On a machine
# that has not, the cargo build below stops inside a build script with a sentence naming the tool
# that is missing.
#
# It reaches no network, opens no socket and reads no configuration; that purity is what lets the
# image stage run a freshly linked static binary and get the same twelve files every time.
set -euo pipefail

# Repo root, independent of the caller's working directory — `cargo run` below is resolved against
# the workspace, and a relative OUT_DIR is resolved against this rather than against wherever the
# caller happened to be standing.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# The default lives under `target/`, which is gitignored, is where every other build output in this
# repository goes, and is exactly what `crates/backend`'s `TCAB_GG_REFERENCE` default resolves to
# from the checkout it was pointed at. Nothing here can be committed by any arrangement of `git add`.
#
# Note that this is the CHECKOUT's `target/`, not cargo's — a devcontainer that sets
# `CARGO_TARGET_DIR` elsewhere (this one does) puts compiled artifacts on another disk entirely and
# these twelve documents still land here. That is deliberate and it is what makes the two defaults
# agree: the backend resolves its own default from `TCAB_BACKEND_CHECKOUT`, which knows nothing about
# where cargo was told to build.
OUT_DIR="${1:-target/gg-reference}"

# `gg reference --out` creates the directory itself and writes `index.json` LAST, so a directory that
# exists at all is one whose index does not promise an arm that is not beside it. Nothing is emptied
# first: re-running over a previous projection overwrites all twelve files, and the language list is
# a compile-time constant of the binary rather than something an arm could fail to contribute.
cargo run --quiet -p test-cabinet-gg --bin gg -- reference --out "$OUT_DIR"

echo
echo "Wrote gg's reference to $OUT_DIR:"
for document in "$OUT_DIR"/*.json; do
	printf '  %-24s %8s bytes\n' "$(basename "$document")" "$(wc -c <"$document")"
done
