// @generated by `api-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p api-codegen`
// and formats the output). The source of truth is the Rust API types in
// `crates/backend` and `crates/core`, which derive `ts_rs::TS` +
// `schemars::JsonSchema` behind their `contract` feature. The JSON Schemas under
// `apps/docs/public/schema/` are generated from the same types in the same pass.

import type {
  AestheticRating,
  DomainAesthetic,
  DomainRating,
  ReviewRevision,
  ReviewVerdict,
} from "@clockwyrks/run-record/review";

/**
 * One published review on a run: the reviewer's public identity, their per-domain
 * ratings, the writeup, and their checklist verdicts. This is the canonical
 * review wire shape (`backend-api/review.schema.json`), referenced by the per-run
 * snapshot document.
 */
export type Review = {
  /**
   * The reviewing account's id (stable across their reviews).
   */
  reviewerId: string;
  /**
   * The reviewer's display name, shown beside their review.
   */
  reviewer: string;
  /**
   * The reviewer's functional rating for each scoring domain. This review's
   * overall rating is the worst across them. Empty on a review of a
   * validator-rated run, whose functional rating the validators decide.
   */
  ratings: Array<DomainRating>;
  /**
   * **Legacy:** the reviewer's per-domain aesthetic ratings, from when the
   * channel was rated per scoring domain. No longer emitted — a stored
   * legacy row's tiers are collapsed into [`aesthetic`](Self::aesthetic)
   * instead — but kept in the contract so a freshly deployed site can still
   * read a not-yet-regenerated snapshot (resolve a review's tier as
   * `aesthetic ?? worst(aesthetics)`).
   */
  aesthetics?: Array<DomainAesthetic>;
  /**
   * The reviewer's **run-wide** aesthetic tier, on a review of a
   * validator-rated run (a legacy per-domain row is already collapsed to its
   * worst tier); the run's aesthetic rating is the worst across its reviews'
   * tiers. Absent on a legacy run's review, which has no aesthetic channel.
   */
  aesthetic?: AestheticRating | null;
  writeup: string;
  checklist: Array<ReviewVerdict>;
  /**
   * RFC 3339 of when the review was **first** submitted (unchanged by later
   * edits — see [`Self::edited_at`]).
   */
  reviewedAt: string;
  /**
   * RFC 3339 of when the review was last edited, or `None` if it has never been
   * edited since it was first submitted. The newest [`Self::revisions`] entry
   * carries the same timestamp.
   */
  editedAt?: string | null;
  /**
   * The review's edit history, oldest first: one entry per edit, each with the
   * reviewer's note and the autogenerated diff of what changed. Empty for a
   * review that has never been edited. Public, so a reader can see how a review
   * evolved.
   */
  revisions?: Array<ReviewRevision>;
  /**
   * The snapshot-relative object key of the reviewer's profile picture
   * (`pfp/<reviewer-id>`), or `None` when the reviewer has no picture. The
   * bytes are exported once per reviewer under the content-stable top-level
   * `pfp/` prefix (like run media under `MEDIA_PREFIX`); the site resolves the
   * key against the snapshot base into an absolute avatar URL.
   */
  pictureKey?: string | null;
};
