/**
 * routes.ts — the 24 campaign boards (transcribed exactly from
 * specs/campaign-boards.md) with one solving route set per board, stored as
 * data so course-walk helpers can replay them move-by-move (each route is an
 * ordered cell list, [col, row] pairs, starting at one of the channel's
 * emitters). nodeCounts is the node multiset by notation character, for the
 * boards-as-written check.
 *
 * GENERATED alongside the boards — regenerate rather than editing routes.
 */

import type { Channel } from "./notation";

export interface CampaignBoardData {
  /** Board number, 1..CAMPAIGN_LENGTH, in play order. */
  board: number;
  cols: number;
  rows: number;
  /** Board notation, rows joined by \n, exactly as specs/campaign-boards.md writes it. */
  notation: string;
  /** Node multiset by notation character (boards-as-written check). */
  nodeCounts: Record<string, number>;
  /** One solving route per channel present: ordered [col, row] cells, emitter to emitter. */
  routes: Partial<Record<Channel, ReadonlyArray<readonly [number, number]>>>;
}

export const CAMPAIGN_BOARDS: readonly CampaignBoardData[] = [
  {
    board: 1,
    cols: 3,
    rows: 3,
    notation: ".Tt\nttT\n.tt",
    nodeCounts: { T: 2, t: 5 },
    routes: {
      triangle: [
        [1, 0],
        [2, 0],
        [1, 1],
        [0, 1],
        [1, 2],
        [2, 2],
        [2, 1],
      ],
    },
  },
  {
    board: 2,
    cols: 3,
    rows: 3,
    notation: ".tt\nTtT\ntt.",
    nodeCounts: { T: 2, t: 5 },
    routes: {
      triangle: [
        [0, 1],
        [1, 0],
        [2, 0],
        [1, 1],
        [0, 2],
        [1, 2],
        [2, 1],
      ],
    },
  },
  {
    board: 3,
    cols: 4,
    rows: 3,
    notation: "tTtt\nttTt\nttt.",
    nodeCounts: { T: 2, t: 9 },
    routes: {
      triangle: [
        [1, 0],
        [0, 0],
        [0, 1],
        [1, 1],
        [0, 2],
        [1, 2],
        [2, 2],
        [3, 1],
        [3, 0],
        [2, 0],
        [2, 1],
      ],
    },
  },
  {
    board: 4,
    cols: 4,
    rows: 3,
    notation: "Tt.t\ntTtt\n.ttt",
    nodeCounts: { T: 2, t: 8 },
    routes: {
      triangle: [
        [0, 0],
        [1, 0],
        [0, 1],
        [1, 2],
        [2, 2],
        [3, 2],
        [3, 1],
        [3, 0],
        [2, 1],
        [1, 1],
      ],
    },
  },
  {
    board: 5,
    cols: 4,
    rows: 4,
    notation: ".tTt\n.ttt\nttTt\ntttt",
    nodeCounts: { T: 2, t: 12 },
    routes: {
      triangle: [
        [2, 0],
        [1, 0],
        [1, 1],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [2, 3],
        [1, 3],
        [0, 3],
        [0, 2],
        [1, 2],
        [2, 2],
      ],
    },
  },
  {
    board: 6,
    cols: 4,
    rows: 4,
    notation: "tttT\nttt.\nt.tt\nttTt",
    nodeCounts: { T: 2, t: 12 },
    routes: {
      triangle: [
        [3, 0],
        [2, 0],
        [1, 0],
        [0, 0],
        [0, 1],
        [1, 1],
        [0, 2],
        [0, 3],
        [1, 3],
        [2, 2],
        [2, 1],
        [3, 2],
        [3, 3],
        [2, 3],
      ],
    },
  },
  {
    board: 7,
    cols: 4,
    rows: 4,
    notation: "STtt\nsstt\nssTt\nSss.",
    nodeCounts: { S: 2, T: 2, s: 6, t: 5 },
    routes: {
      triangle: [
        [1, 0],
        [2, 0],
        [3, 0],
        [2, 1],
        [3, 1],
        [3, 2],
        [2, 2],
      ],
      square: [
        [0, 0],
        [0, 1],
        [1, 1],
        [0, 2],
        [1, 2],
        [2, 3],
        [1, 3],
        [0, 3],
      ],
    },
  },
  {
    board: 8,
    cols: 5,
    rows: 4,
    notation: "Sst..\nstTtt\nssttt\nSsstT",
    nodeCounts: { S: 2, T: 2, s: 6, t: 8 },
    routes: {
      triangle: [
        [2, 1],
        [2, 0],
        [1, 1],
        [2, 2],
        [3, 1],
        [4, 1],
        [3, 2],
        [4, 2],
        [3, 3],
        [4, 3],
      ],
      square: [
        [0, 0],
        [1, 0],
        [0, 1],
        [0, 2],
        [1, 2],
        [2, 3],
        [1, 3],
        [0, 3],
      ],
    },
  },
  {
    board: 9,
    cols: 4,
    rows: 4,
    notation: "tSss\n2tss\nTtss\ntTS.",
    nodeCounts: { "2": 1, S: 2, T: 2, s: 6, t: 4 },
    routes: {
      triangle: [
        [0, 2],
        [0, 1],
        [0, 0],
        [1, 1],
        [0, 1],
        [1, 2],
        [0, 3],
        [1, 3],
      ],
      square: [
        [1, 0],
        [2, 0],
        [3, 0],
        [2, 1],
        [3, 1],
        [2, 2],
        [3, 2],
        [2, 3],
      ],
    },
  },
  {
    board: 10,
    cols: 5,
    rows: 4,
    notation: "Tt.T.\nttt..\nt2sSs\ntSsss",
    nodeCounts: { "2": 1, S: 2, T: 2, s: 5, t: 6 },
    routes: {
      triangle: [
        [0, 0],
        [1, 0],
        [0, 1],
        [1, 1],
        [0, 2],
        [0, 3],
        [1, 2],
        [2, 1],
        [3, 0],
      ],
      square: [
        [3, 2],
        [4, 2],
        [4, 3],
        [3, 3],
        [2, 2],
        [1, 2],
        [2, 3],
        [1, 3],
      ],
    },
  },
  {
    board: 11,
    cols: 5,
    rows: 4,
    notation: "..t.s\nttT2s\nttS2S\nt.Tss",
    nodeCounts: { "2": 2, S: 2, T: 2, s: 4, t: 6 },
    routes: {
      triangle: [
        [2, 1],
        [2, 0],
        [1, 1],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 2],
        [2, 3],
      ],
      square: [
        [2, 2],
        [3, 1],
        [4, 0],
        [4, 1],
        [3, 1],
        [3, 2],
        [3, 3],
        [4, 3],
        [3, 2],
        [4, 2],
      ],
    },
  },
  {
    board: 12,
    cols: 5,
    rows: 4,
    notation: "Tttt.\nttsSt\n.22t.\nssST.",
    nodeCounts: { "2": 2, S: 2, T: 2, s: 3, t: 7 },
    routes: {
      triangle: [
        [0, 0],
        [1, 0],
        [0, 1],
        [1, 1],
        [2, 0],
        [3, 0],
        [4, 1],
        [3, 2],
        [2, 2],
        [3, 3],
      ],
      square: [
        [3, 1],
        [2, 1],
        [1, 2],
        [0, 3],
        [1, 3],
        [1, 2],
        [2, 2],
        [2, 3],
      ],
    },
  },
  {
    board: 13,
    cols: 4,
    rows: 5,
    notation: ".Ddd\ntTdD\nt22.\ntsSs\nT.S.",
    nodeCounts: { "2": 2, D: 2, S: 2, T: 2, d: 3, s: 2, t: 3 },
    routes: {
      triangle: [
        [1, 1],
        [0, 1],
        [0, 2],
        [1, 2],
        [0, 3],
        [0, 4],
      ],
      square: [
        [2, 3],
        [2, 2],
        [1, 2],
        [1, 3],
        [2, 2],
        [3, 3],
        [2, 4],
      ],
      diamond: [
        [1, 0],
        [2, 0],
        [3, 0],
        [2, 1],
        [3, 1],
      ],
    },
  },
  {
    board: 14,
    cols: 5,
    rows: 5,
    notation: "..tT.\nt2dD.\nT2t.s\nd2sss\nDSssS",
    nodeCounts: { "2": 3, D: 2, S: 2, T: 2, d: 2, s: 6, t: 3 },
    routes: {
      triangle: [
        [3, 0],
        [2, 0],
        [1, 1],
        [2, 2],
        [1, 2],
        [0, 1],
        [0, 2],
      ],
      square: [
        [1, 4],
        [1, 3],
        [2, 3],
        [2, 4],
        [3, 3],
        [4, 2],
        [4, 3],
        [3, 4],
        [4, 4],
      ],
      diamond: [
        [3, 1],
        [2, 1],
        [1, 1],
        [1, 2],
        [0, 3],
        [1, 3],
        [0, 4],
      ],
    },
  },
  {
    board: 15,
    cols: 5,
    rows: 5,
    notation: ".T.2t\nsDttt\nsS2Td\nss22D\n.S.d.",
    nodeCounts: { "2": 4, D: 2, S: 2, T: 2, d: 2, s: 4, t: 4 },
    routes: {
      triangle: [
        [1, 0],
        [2, 1],
        [3, 0],
        [4, 0],
        [4, 1],
        [3, 0],
        [3, 1],
        [2, 2],
        [3, 2],
      ],
      square: [
        [1, 2],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 3],
        [2, 3],
        [1, 4],
      ],
      diamond: [
        [1, 1],
        [2, 2],
        [3, 3],
        [2, 3],
        [3, 4],
        [3, 3],
        [4, 2],
        [4, 3],
      ],
    },
  },
  {
    board: 16,
    cols: 5,
    rows: 5,
    notation: "..ttt\n.S2tt\nDsTsT\nd22d.\nSddD.",
    nodeCounts: { "2": 3, D: 2, S: 2, T: 2, d: 4, s: 2, t: 5 },
    routes: {
      triangle: [
        [2, 2],
        [2, 1],
        [2, 0],
        [3, 0],
        [4, 0],
        [3, 1],
        [4, 1],
        [4, 2],
      ],
      square: [
        [1, 1],
        [2, 1],
        [3, 2],
        [2, 3],
        [1, 2],
        [1, 3],
        [0, 4],
      ],
      diamond: [
        [0, 2],
        [0, 3],
        [1, 3],
        [2, 3],
        [1, 4],
        [2, 4],
        [3, 3],
        [3, 4],
      ],
    },
  },
  {
    board: 17,
    cols: 6,
    rows: 5,
    notation: "...ttd\nS2Ttdd\nt32Ddd\nTss2d.\nsS.dD.",
    nodeCounts: { "2": 3, "3": 1, D: 2, S: 2, T: 2, d: 7, s: 3, t: 4 },
    routes: {
      triangle: [
        [2, 1],
        [3, 0],
        [4, 0],
        [3, 1],
        [2, 2],
        [1, 1],
        [0, 2],
        [1, 2],
        [0, 3],
      ],
      square: [
        [0, 1],
        [1, 1],
        [1, 2],
        [2, 2],
        [3, 3],
        [2, 3],
        [1, 2],
        [1, 3],
        [0, 4],
        [1, 4],
      ],
      diamond: [
        [3, 2],
        [4, 1],
        [5, 0],
        [5, 1],
        [4, 2],
        [5, 2],
        [4, 3],
        [3, 3],
        [3, 4],
        [4, 4],
      ],
    },
  },
  {
    board: 18,
    cols: 6,
    rows: 5,
    notation: "T.....\nttDsss\ndd3222\n.dt3Ss\nDddTSs",
    nodeCounts: { "2": 3, "3": 2, D: 2, S: 2, T: 2, d: 5, s: 5, t: 3 },
    routes: {
      triangle: [
        [0, 0],
        [0, 1],
        [1, 1],
        [2, 2],
        [2, 3],
        [3, 3],
        [3, 4],
      ],
      square: [
        [4, 3],
        [4, 2],
        [3, 1],
        [3, 2],
        [3, 3],
        [4, 2],
        [5, 2],
        [4, 1],
        [5, 1],
        [5, 2],
        [5, 3],
        [5, 4],
        [4, 4],
      ],
      diamond: [
        [2, 1],
        [3, 2],
        [2, 2],
        [1, 2],
        [0, 2],
        [1, 3],
        [2, 2],
        [3, 3],
        [2, 4],
        [1, 4],
        [0, 4],
      ],
    },
  },
  {
    board: 19,
    cols: 5,
    rows: 5,
    notation: ".Dttt\n.dd3t\n.d2TT\nS2s2D\n.sSss",
    nodeCounts: { "2": 3, "3": 1, D: 2, S: 2, T: 2, d: 3, s: 4, t: 4 },
    routes: {
      triangle: [
        [3, 2],
        [3, 1],
        [2, 0],
        [3, 0],
        [4, 0],
        [3, 1],
        [4, 1],
        [4, 2],
      ],
      square: [
        [0, 3],
        [1, 3],
        [1, 4],
        [2, 3],
        [3, 3],
        [4, 4],
        [3, 4],
        [2, 4],
      ],
      diamond: [
        [1, 0],
        [1, 1],
        [2, 1],
        [3, 1],
        [2, 2],
        [1, 2],
        [1, 3],
        [2, 2],
        [3, 3],
        [4, 3],
      ],
    },
  },
  {
    board: 20,
    cols: 6,
    rows: 5,
    notation: ".S.tT.\ns2ttDd\ns2T2.d\ns22d3.\nssSddD",
    nodeCounts: { "2": 5, "3": 1, D: 2, S: 2, T: 2, d: 5, s: 5, t: 3 },
    routes: {
      triangle: [
        [4, 0],
        [3, 0],
        [3, 1],
        [3, 2],
        [2, 1],
        [1, 1],
        [2, 2],
      ],
      square: [
        [1, 0],
        [0, 1],
        [1, 1],
        [0, 2],
        [1, 2],
        [0, 3],
        [1, 3],
        [1, 2],
        [2, 3],
        [1, 3],
        [0, 4],
        [1, 4],
        [2, 3],
        [2, 4],
      ],
      diamond: [
        [4, 1],
        [5, 1],
        [5, 2],
        [4, 3],
        [3, 2],
        [3, 3],
        [4, 3],
        [3, 4],
        [4, 4],
        [4, 3],
        [5, 4],
      ],
    },
  },
  {
    board: 21,
    cols: 6,
    rows: 5,
    notation: "S2D..T\nd2ssts\n.D3S3s\n.dT32t\n.d2tt.",
    nodeCounts: { "2": 4, "3": 3, D: 2, S: 2, T: 2, d: 3, s: 4, t: 4 },
    routes: {
      triangle: [
        [5, 0],
        [4, 1],
        [4, 2],
        [3, 3],
        [4, 3],
        [5, 3],
        [4, 4],
        [3, 3],
        [3, 4],
        [2, 4],
        [2, 3],
      ],
      square: [
        [0, 0],
        [1, 0],
        [1, 1],
        [2, 1],
        [2, 2],
        [3, 1],
        [4, 2],
        [5, 1],
        [5, 2],
        [4, 3],
        [4, 2],
        [3, 2],
      ],
      diamond: [
        [2, 0],
        [1, 0],
        [0, 1],
        [1, 1],
        [2, 2],
        [1, 3],
        [1, 4],
        [2, 4],
        [3, 3],
        [2, 2],
        [1, 2],
      ],
    },
  },
  {
    board: 22,
    cols: 6,
    rows: 6,
    notation: ".tt2d.\n.t2t2d\nt1DdSd\n2.S3dD\nTT2sd.\n.ssss.",
    nodeCounts: { "1": 1, "2": 5, "3": 1, D: 2, S: 2, T: 2, d: 6, s: 5, t: 5 },
    routes: {
      triangle: [
        [0, 4],
        [0, 3],
        [0, 2],
        [1, 1],
        [1, 0],
        [2, 0],
        [3, 0],
        [3, 1],
        [2, 1],
        [1, 2],
        [0, 3],
        [1, 4],
      ],
      square: [
        [4, 2],
        [3, 3],
        [2, 4],
        [1, 5],
        [2, 5],
        [2, 4],
        [3, 5],
        [4, 5],
        [3, 4],
        [3, 3],
        [2, 3],
      ],
      diamond: [
        [2, 2],
        [2, 1],
        [3, 0],
        [4, 0],
        [4, 1],
        [5, 1],
        [5, 2],
        [4, 1],
        [3, 2],
        [3, 3],
        [4, 3],
        [4, 4],
        [5, 3],
      ],
    },
  },
  {
    board: 23,
    cols: 7,
    rows: 6,
    notation: "s2SST..\n2232.t.\nstTsttt\n..t.t.t\nd22ttdD\ndD2dddd",
    nodeCounts: { "2": 7, "3": 1, D: 2, S: 2, T: 2, d: 7, s: 3, t: 10 },
    routes: {
      triangle: [
        [4, 0],
        [3, 1],
        [4, 2],
        [5, 1],
        [6, 2],
        [6, 3],
        [5, 2],
        [4, 3],
        [4, 4],
        [3, 4],
        [2, 4],
        [2, 3],
        [1, 2],
        [1, 1],
        [0, 1],
        [1, 0],
        [2, 1],
        [2, 2],
      ],
      square: [
        [2, 0],
        [1, 0],
        [0, 0],
        [0, 1],
        [0, 2],
        [1, 1],
        [2, 1],
        [3, 1],
        [3, 2],
        [2, 1],
        [3, 0],
      ],
      diamond: [
        [6, 4],
        [5, 4],
        [6, 5],
        [5, 5],
        [4, 5],
        [3, 5],
        [2, 5],
        [1, 4],
        [0, 4],
        [0, 5],
        [1, 4],
        [2, 4],
        [2, 5],
        [1, 5],
      ],
    },
  },
  {
    board: 24,
    cols: 7,
    rows: 6,
    notation: "ssdd.d.\n2S.dd2d\nssD..d.\nt2ttTdd\n.t323Dd\nttT2sS.",
    nodeCounts: { "2": 5, "3": 2, D: 2, S: 2, T: 2, d: 10, s: 5, t: 6 },
    routes: {
      triangle: [
        [4, 3],
        [4, 4],
        [3, 3],
        [3, 4],
        [2, 4],
        [2, 3],
        [1, 3],
        [0, 3],
        [1, 4],
        [0, 5],
        [1, 5],
        [2, 4],
        [2, 5],
      ],
      square: [
        [1, 1],
        [0, 1],
        [0, 0],
        [1, 0],
        [0, 1],
        [0, 2],
        [1, 2],
        [1, 3],
        [2, 4],
        [3, 5],
        [3, 4],
        [4, 4],
        [3, 5],
        [4, 5],
        [4, 4],
        [5, 5],
      ],
      diamond: [
        [2, 2],
        [3, 1],
        [2, 0],
        [3, 0],
        [4, 1],
        [5, 1],
        [5, 0],
        [6, 1],
        [5, 1],
        [5, 2],
        [5, 3],
        [6, 3],
        [6, 4],
        [5, 4],
      ],
    },
  },
];
