//! **C++** — the third arm whose component is compiled **per turn**, and the second whose program
//! is compiled *verbatim*.
//!
//! Everything this arm owns lives here or in one of this module's siblings:
//!
//! * [`compile`] — the host-side `clang++`, the in-process component encode with the preview1
//!   adapter, what they cost, what they share, and the two failures they tell apart;
//! * [`source`] — the one thing gg reads out of a reply, which is whether it defines `main`, and
//!   what it writes around a **code module**: the named module and namespace its declarations are
//!   opened inside, with the author's own `#include` lines hoisted above them;
//! * [`mask`] — the byte-level scan [`source`] reads;
//! * `packages/gg-sandbox-cpp/Sources/sdk/` — the SDK, hand-written and idiomatic, whose `///`
//!   comments are the model-facing documentation and whose `//` comments are not;
//! * `packages/gg-sandbox-cpp/signatures.sh` — the reflection, out of clang's own comment AST;
//! * `cpp.guest.tar.gz`, `cpp.adapter.wasm` and `cpp.toolchain.json` — the compile inputs, the
//!   adapter, and what built them, generated by `crates/gg-sandbox-artifacts/cpp` into this build's
//!   own `OUT_DIR` rather than committed anywhere, and reached through `GG_ARTIFACTS_CPP`;
//! * the **signature catalogue** that reflection emits, which is the whole of what a model is told
//!   about this surface — generated into this build's `OUT_DIR` rather than committed anywhere (see
//!   `crates/gg/build.rs`).
//!
//! # What the surface looks like, and the one thing a model has to know about it
//!
//! **Every capability module is a `namespace` inside `namespace gg`, with the types it produces
//! nested in it, and one header per module** — so a program writes `#include <gg/files.hpp>` and
//! then `gg::files::read_file(…)`, which is the line the module's own catalogue entry states and
//! the call written in full.
//!
//! Nothing gg passes the compiler puts any of it in scope. The header is on the include path and the
//! bodies are in the `sdk.o` every artifact links, which is
//! [packaging](https://docs.testcabinet.ai/gg/responses-as-code/invariants/); the declaration is the
//! model's own `#include`. **The C++ standard library arrives the same way**: nothing is put in
//! front of a program, so `std::vector` is undeclared until the reply writes `#include <vector>`.
//! There is no using-directive anywhere either — so a program that declares its own
//! `namespace files` has taken a name gg was not using, and `gg::files::` goes on resolving beside
//! it.
//!
//! The nesting is what makes the full name a real C++ path rather than a label, which is the whole
//! point of the surface being modules: it is what a search hit shows, what a documentation view is
//! opened by, and what lets two modules each declare a `close`. `Sources/prelude.hpp` is where the
//! library set a program may reach for is declared — by the file, not in front of the program — and
//! it records the reason `<filesystem>` is off that set.
//!
//! Everything else is spelling, and it is written to read like the standard library it arrives
//! beside: `snake_case` throughout, `enum class` for a fixed choice, aggregates with public members
//! for a record, `std::variant` for a value that is one of two things, a **default argument** for
//! one optional part and a **designated initialiser** for several, and a thrown `gg::core::api_error` —
//! a `std::runtime_error` — for a call that failed.
//!
//! # Why this arm has no guest component
//!
//! For the reason [Rust](super::rust) and [Swift](super::swift) have none. Every arm before those
//! three evaluates a **string**: Python's baked component holds a whole CPython, Ruby's holds
//! Opal, the ECMAScript one holds a JavaScript engine, and a program crosses the membrane as source
//! those runtimes read. `clang++` does not produce a C++ interpreter that later runs a program; it
//! produces the program, and that module *is* the component. There is no artifact of this language
//! that is not one particular program, so there is nothing to bake and nothing a per-process cache
//! could hold.
//!
//! # What a C++ program is, here
//!
//! **The model's reply, unaltered, as a translation unit that defines `main`.** Not a function body
//! and not anything gg wrapped: the bytes the model wrote are the bytes `clang++` reads, so a
//! diagnostic at line 7 is line 7 and there is no offset to subtract anywhere in this arm.
//!
//! That is forced rather than chosen, and C++ forces it harder than Swift did. A function-body
//! wrapper would refuse a `template`, which may not be declared at block scope at all and is most of
//! what generic C++ is; a `namespace`, for the same reason; and a `#include`, which would still
//! *expand* and would expand the whole of `<vector>` inside a function body. A translation unit is
//! the only C++ context that admits all three.
//!
//! The price is the one refusal this arm has, and it is the exact inverse of the
//! [Rust](super::rust) arm's. Rust has no `main` and refuses a program that defines one. C++ has
//! nowhere for a bare statement to live, so a reply that defines **no** `main` is a program with
//! nothing to run — and gg refuses it by name, at prepare time, rather than letting it link. That
//! `wasm-ld` links one at all is the surprising half and is measured rather than assumed: wasi-libc
//! references `main` **weakly**, so the missing entry point resolves to a stub that traps and the
//! compiler exits zero. See [`source`] for why no linker flag asks the question and why gg's
//! lexical answer can only be wrong in the safe direction.
//!
//! # What this arm has that no other does
//!
//! **A real exception mechanism.** [Rust](super::rust) aborts and reaches for a panic hook;
//! [Swift](super::swift) traps and has no hook at all. C++ here has `throw`, `try` and `catch`, and
//! they work — `-fwasm-exceptions` with the standardised encoding, against a wasmtime configured to
//! accept it. What that cost the workspace is written down in [`compile`] rather than quietly
//! absorbed: wasmtime's exception support is behind a build feature that the two other wasm hosts
//! in this repository now also build with, and both pin their own validation surface back
//! explicitly rather than inheriting a wider one.
//!
//! # What this arm has that is worse than any other, and cannot be engineered away
//!
//! **A failure that says nothing.** Three of the four ways a C++ program fails here carry their own
//! words, and each takes a decision to get there. An uncaught `throw` is caught by gg's shell and
//! reported as an ordinary model-facing error carrying the exception's own class and `what()` —
//! without which it would be a bare `thrown Wasm exception`, since an exception escaping `main`
//! under `-fwasm-exceptions` never reaches `std::terminate`. A libc++ **hardening** check —
//! `v[10]`, `.front()` on an empty container — carries libc++'s own sentence *and* the model's own
//! line, out of the artifact's debug information, and only because gg turns hardening on: wasi-sdk
//! ships libc++ configured to check nothing. A non-zero status returned from `main` is read by that
//! same shell and reported with the number the program chose, which is the one failure channel C++
//! gives an entry point and the one that walks past every `catch` there is.
//!
//! The fourth is undefined behaviour, and it arrives as a bare trap: an integer division by zero, a
//! pointer past the end of an array. `-g1` locates it at the model's own line and that is all
//! anything can do. A dereferenced null is worse still and is not a trap at all: address zero is
//! ordinary linear memory on this target, so reading and writing through a null pointer succeeds and
//! the turn is recorded a success.
//!
//! It is worth stating plainly because it is a **comparability** risk rather than only a usability
//! one: on this arm, and on no other here, a failure caused by the language can be hard to tell in
//! the run record from a model that reasoned badly. A study reading this arm beside the others has
//! to know that — and hardening is what keeps the most common shape of it, an out-of-bounds
//! container access, out of that band and in the one above.
//!
//! # And a code module is **linked**, which is why the seam hands a program its modules
//!
//! A code [skill](crate::skills)'s or [memory](crate::memories)'s namespace is `lib::<key>`, and a
//! program reaches it by writing [`import lib.<key>;`](ProgramLanguage::lib_import). On every
//! interpreted arm the module is a value the guest is handed beside the program and evaluates first.
//! C++ has no such moment — a module is C++, C++ links, and the only artifact a module can end up in
//! is the artifact of a program that was compiled against it.
//!
//! So the seam hands [`prepare_program`](super::ProgramLanguage::prepare_program) the modules in
//! scope, and each becomes a named C++ module **the program imports itself**, with its declarations
//! opened inside `namespace lib::<key>` **where they stand**. It is the plainest shape of the three
//! compiled arms — C++ has a real nested namespace, so nothing has to be re-synthesized or declared
//! twice — and the one thing that had to be decided is what happens to a `#include` at a module's
//! top level, which is **hoisted** into the module's global module fragment, where an author's own
//! headers reach the module and nobody who imports it. gg writes the one include that declares its
//! own surface into that same fragment, which is the wrapper
//! [a module is allowed and a program is not](https://docs.testcabinet.ai/gg/responses-as-code/invariants/):
//! a module is a skill author's file that gg wraps, where a program is a model's reply that gg does
//! not touch. See [`source`] for the shape, the hoist and the argument.
//!
//! What a model can see of the difference is that `lib::csv_tools::parse` is a **name the compiler
//! resolves** rather than a property looked up on a value: a key that does not exist, and a module
//! the program forgot to import, are both a diagnostic on the turn that wrote it, where an
//! interpreted arm finds out when the call is reached.
//!
//! A module is compiled **twice**, and that is deliberate rather than an oversight — once alone when
//! it is read, only to be checked, and once as part of every program that uses it. Without the first
//! compile, a module that does not build would take down every program the agent wrote from then on,
//! with the diagnostic landing against the turn's own program in a file the model never saw. See
//! [`compile::compile_module`].

use std::sync::OnceLock;

use test_cabinet_core::gg::GgProgramLanguage;

use crate::sandbox::signatures::SignatureCatalogue;

use super::{
    CodeModule, FileWindow, PrepareContext, PrepareFailure, PreparedModule, PreparedProgram,
    ProgramLanguage, WORKSPACE_TREE_VIEW, spell,
};
use crate::docs::MAX_SEARCH_LIMIT;
use crate::sandbox::operations::{
    DOCS_SEARCH, FILES_TREE, VIEWS_OPEN_DOCS_VIEW, VIEWS_OPEN_FILE, VIEWS_OPEN_TEXT,
};

#[path = "cpp.compile.rs"]
pub(super) mod compile;

#[path = "cpp.mask.rs"]
pub(super) mod mask;

#[path = "cpp.source.rs"]
pub(super) mod source;

/// This arm's catalogue, reflected out of the SDK's own documentation comments by
/// `packages/gg-sandbox-cpp/signatures.sh` — `clang++ -ast-dump=json`, which is clang's own comment
/// parser and the machinery `-Wdocumentation` and `clang-doc` are built on.
///
/// It is not committed. `crates/gg/build.rs` runs that reflection as a step of building this
/// crate and this line embeds what it wrote into the build's own `OUT_DIR`, so what a model is
/// told about this arm is reflected out of the SDK sources in this checkout, on the build that
/// compiles the module telling it.
const SIGNATURES: &str = include_str!(concat!(env!("OUT_DIR"), "/signatures/cpp.signatures.json"));

/// The parsed catalogue, parsed once per process.
static CATALOGUE: OnceLock<SignatureCatalogue> = OnceLock::new();

/// The one instance of this language. A unit struct, so the `static` costs nothing and coerces
/// straight to `&'static dyn ProgramLanguage`.
pub(super) static CPP: Cpp = Cpp;

/// C++: compiled by `clang++` into the wasm component that evaluates it, per turn.
pub(super) struct Cpp;

impl ProgramLanguage for Cpp {
    fn id(&self) -> GgProgramLanguage {
        GgProgramLanguage::Cpp
    }

    fn display_name(&self) -> &'static str {
        GgProgramLanguage::Cpp.display_name()
    }

    /// **`::`** — the second arm that does not write `.`, because here a capability module is a
    /// **namespace** and reaching a function in one is a qualified name rather than a member
    /// access.
    ///
    /// It is the difference between a prompt full of `gg::views::open_text` and a prompt full of
    /// `view.open_text`, which on this arm is *no member named 'open_text' in the global namespace*
    /// — so a model would be taught, in every sentence gg writes about a call, a spelling that
    /// cannot compile.
    fn member_separator(&self) -> &'static str {
        "::"
    }

    /// One `clang++` over the model's file and the code modules in scope, then an in-process
    /// component encode — see [`compile`] for what it costs, what it shares, and how it tells a
    /// program `clang++` refused from a `clang++` that could not run.
    fn prepare_program(
        &self,
        source: &str,
        modules: &[CodeModule],
        context: &PrepareContext,
    ) -> Result<PreparedProgram, PrepareFailure> {
        compile::compile_program(source, modules, context)
    }

    /// `clang++`, which is what a C++ programmer calls the compiler and what the binary gg spawns is
    /// called.
    ///
    /// Not `wit-component`, which encodes the module `clang++` linked into a component and judges
    /// nothing about the program: the same reason the [Rust](super::rust) and [Swift](super::swift)
    /// arms name their front ends and the JVM arms name theirs rather than TeaVM. Naming a checker
    /// is also what has this arm's compile [recorded](crate::sandbox::SandboxOutcome::compile) on
    /// every turn, the failing path included — which matters here because this arm's compile is the
    /// cheapest of the three that produce their own artifact, and an arm that looks free and is not
    /// is exactly what the seam requires a language to declare rather than leave to be inferred.
    fn checker(&self) -> Option<&'static str> {
        Some("clang++")
    }

    /// Unpack the embedded guest archive now, so the first code turn does not.
    ///
    /// The whole of this arm's warm-up, and the whole of what it could be: 32 KB decompressed, once
    /// per machine. Nothing is compiled ahead of a program, because nothing is put in front of one —
    /// every header a compile parses is one the program itself included. Idempotent and best effort:
    /// a failure here is the failure the first compile makes, and there it is classified, counted
    /// and reported as a [toolchain failure](PrepareFailure::Toolchain).
    fn warm_prepare(&self) {
        compile::warm();
    }

    /// The module's own `clang++`, asked to precompile the interface a program imports — and the
    /// names its namespace offers, read from the author's own source.
    ///
    /// What comes back is **source**, which is what a linked language's module has to be: it is an
    /// input to the [program compile](compile::compile_program) that binds it, not something a guest
    /// could load on its own.
    fn prepare_module(
        &self,
        key: &str,
        source: &str,
        context: &PrepareContext,
    ) -> Result<PreparedModule, PrepareFailure> {
        compile::compile_module(key, source, context)
    }

    /// **`import lib.<key>;`** — the line a program writes to reach a code module's namespace, and
    /// the only thing that puts `lib` in scope.
    ///
    /// A module in scope is [precompiled](self::compile::compile_module) into an interface of its own
    /// and named to the compile with `-fmodule-file=`, which says where the module is and declares
    /// nothing, exactly as `-I` says where gg's headers are. So this line is the model's to write,
    /// on the same terms as the `#include <gg/files.hpp>` that reaches gg's surface, and a program
    /// that omits it earns clang's own *use of undeclared identifier 'lib'*.
    ///
    /// It names the [module](source::module_name) rather than the namespace, because that is what an
    /// import declaration resolves: a key of `module` is imported as `import lib.Module;` and
    /// written `lib::module::<name>`.
    fn lib_import(&self, key: &str) -> Option<String> {
        Some(source::module_import(key))
    }

    /// **`.hpp`, and nothing else.**
    ///
    /// What a skill author's C++ file is called. A code module's declarations are what a program
    /// links against rather than a translation unit of their own, which is what a header holds, and
    /// `.hpp` is the extension C++ uses for one when it means C++ rather than C. gg compiles the
    /// file as a [named module](compile::compile_module) of its own and that is gg's
    /// business rather than the author's.
    ///
    /// One rather than the several a C++ author might reach for (`.h`, `.hh`, `.hxx`), because the
    /// seam's reason for the list being a list does not apply here: it is for two languages that
    /// share a module runtime, where withholding a skill from one of them would be a difference
    /// between the arms larger than the one a study of the pair is measuring. Nothing else in the
    /// registry compiles C++, so there is no such pair and no such loss — and one spelling is one
    /// answer to "what does a skill's C++ file have to be called".
    fn module_file_extensions(&self) -> &'static [&'static str] {
        &["hpp"]
    }

    /// [snake_case](self::binding_name) — what this SDK spells every function and every type in, and
    /// what the standard library it arrives beside spells everything in.
    fn binding_name(&self, name: &str) -> String {
        binding_name(name)
    }

    /// **None.** This arm has no guest component, because the component *is* the program: see this
    /// module's own documentation, and [`PreparedProgram::component`].
    fn guest_component(&self) -> Option<&'static [u8]> {
        None
    }

    /// This language's catalogue, parsed once and checked to be **this** language's.
    ///
    /// Every registered language's build reflects one of these under its own stem into the one
    /// `OUT_DIR`, and each carries the language it was generated for; checking it here is what stops
    /// a catalogue written — or embedded — under the wrong stem from reaching a model as a system
    /// prompt describing a sandbox nobody has.
    fn catalogue(&self) -> &'static SignatureCatalogue {
        CATALOGUE.get_or_init(|| {
            let catalogue = SignatureCatalogue::parse(SIGNATURES)
                .expect("the generated signature catalogue is valid JSON of the expected shape");
            assert_eq!(
                catalogue.language,
                GgProgramLanguage::Cpp,
                "`signatures/cpp.signatures.json` was generated for another program language",
            );
            catalogue
        })
    }

    /// [`gg::views::open_file("src/main.cpp");`](self::open_file_statement) — with the window as the
    /// call's own optional second argument, written as a designated initialiser.
    fn open_file_statement(&self, path: &str, window: Option<FileWindow>) -> String {
        open_file_statement(&spell(self, VIEWS_OPEN_FILE), path, window)
    }

    /// [The include the call needs and the `int main` it lives in](self::open_file_program), which
    /// is what a statement list is not on this arm.
    ///
    /// The one arm that has to override the seam's default twice over: C++ has nowhere for a bare
    /// statement to live, and gg's surface is undeclared until a line the program wrote declares it.
    /// A model reads this out of its own transcript as an example of its own output, so a text it
    /// could not have sent would be teaching a shape its next reply is refused for.
    fn open_file_program(&self, views: &[(&str, Option<FileWindow>)]) -> String {
        open_file_program(
            &includes(self, &[VIEWS_OPEN_FILE]),
            &spell(self, VIEWS_OPEN_FILE),
            views,
        )
    }

    /// [An array of names and a range `for` over it](self::open_docs_views_statement), each
    /// iteration opening one documentation view — inside the `int main` this language has nowhere
    /// else to put a statement than, under the `#include` that declares the call and the ones that
    /// declare the standard-library types it holds the names in.
    fn open_docs_views_statement(&self, names: &[&str]) -> String {
        open_docs_views_statement(
            &includes(self, &[VIEWS_OPEN_DOCS_VIEW]),
            &spell(self, VIEWS_OPEN_DOCS_VIEW),
            names,
        )
    }

    /// [One `int main` holding one search and one range `for`](self::bootstrap_program), under the
    /// `#include` lines that declare the calls it makes — every one of them resolved from this
    /// language's own catalogue — and the ones that declare `std::array` and `std::string_view`.
    ///
    /// The lines are resolved for the calls the program really writes rather than for the two this
    /// seam knows about: an agent holding neither `files` nor `shell` is handed no modules and gets
    /// [no search at all](self::bootstrap_program), and an `#include` for a header nothing in the
    /// program names is a habit a model reads out of its own transcript.
    fn bootstrap_program(&self, modules: &[&str], docs: &[&str], tree: Option<u32>) -> String {
        let mut made: Vec<crate::sandbox::OperationId> = Vec::new();
        if tree.is_some() {
            made.push(FILES_TREE);
            made.push(VIEWS_OPEN_TEXT);
        }
        if !modules.is_empty() {
            made.push(DOCS_SEARCH);
        }
        made.push(VIEWS_OPEN_DOCS_VIEW);
        bootstrap_program(
            BootstrapCalls {
                includes: &includes(self, &made),
                search: &spell(self, DOCS_SEARCH),
                open_docs_view: &spell(self, VIEWS_OPEN_DOCS_VIEW),
                tree_call: &spell(self, FILES_TREE),
                open_text: &spell(self, VIEWS_OPEN_TEXT),
            },
            modules,
            docs,
            tree,
        )
    }

    /// One function returning `name` — because a C++ code module is a file of **declarations** and a
    /// C++ program is a translation unit that must define `main`.
    ///
    /// The seam's default subject is this language's generated documentation program, and that
    /// program *would* compile as a module: a `main` inside `namespace lib::<key>` is an ordinary
    /// function rather than an entry point. It is still the wrong subject, because it would be
    /// asserting isolation over a shape no code skill anyone writes has. So this arm answers for
    /// itself, as [Rust](super::rust), [Swift](super::swift) and the [JVM](super::jvm) arms do, and
    /// the `name` rides in as a returned **string literal** — which is where the module's one export
    /// hands it back.
    ///
    /// It writes its own `#include <string>`, which is what a skill author writes and what gg
    /// [hoists](self::source::namespaced) into the module's global module fragment: nothing is in
    /// front of a module either.
    #[cfg(test)]
    fn gate_module(&self, name: &str) -> String {
        format!(
            "#include <string>\n\nstd::string marker() {{\n  return {};\n}}\n",
            serde_json::Value::String(name.to_string())
        )
    }
}

// ---------------------------------------------------------------------------------------------
// The syntax this arm writes
// ---------------------------------------------------------------------------------------------

/// **The `#include` lines a program writes to reach the calls it makes**, one per module, in the
/// order the calls are listed and each written once — followed by the blank line a C++ author leaves
/// between a preamble and the code.
///
/// Resolved out of this arm's own catalogue rather than written out, for the reason [`spell`]
/// resolves a call's name: the catalogue is where a module's [import line](crate::sandbox::ModuleView::import)
/// is composed, a model reads that same line in its own module list, and a second copy here would be
/// the one that drifts. A module that states no line contributes none, which is a state this arm's
/// catalogue never reaches and every other arm's does.
fn includes(language: &dyn ProgramLanguage, calls: &[crate::sandbox::OperationId]) -> String {
    let functions = crate::sandbox::catalogue_functions(language);
    let modules = crate::sandbox::catalogue_modules(language);
    let mut lines: Vec<&str> = Vec::with_capacity(calls.len());
    for call in calls {
        let Some(function) = functions.iter().find(|function| {
            function.alias_of.is_none()
                && crate::sandbox::operation_of(function)
                    .is_some_and(|operation| operation.id == *call)
        }) else {
            continue;
        };
        let Some(line) = modules
            .iter()
            .find(|module| module.id == function.module)
            .and_then(|module| module.import)
        else {
            continue;
        };
        if !lines.contains(&line) {
            lines.push(line);
        }
    }
    match lines.is_empty() {
        true => String::new(),
        false => format!("{}\n\n", lines.join("\n")),
    }
}

/// **The `#include` lines a program gg synthesized writes for the standard library it uses**, above
/// the ones [`includes`] resolves for gg's own surface and separated from them by the blank line a
/// C++ author leaves between the two groups.
///
/// gg's own generated programs obey the rule a model's program obeys: nothing is put in front of a
/// translation unit, so a program that writes `std::array` includes `<array>` itself. It is not
/// decoration — without these lines every program in this file is *use of undeclared identifier
/// 'std'*, and one of them is compiled and run before the model's first request.
///
/// `<string_view>` only where it is really named. A list with entries deduces its `std::array` from
/// string literals, where an empty one has to spell the element type out
/// ([`open_docs_views_statement`] says why) — and a program carrying an include for a type it does
/// not use is a habit a model reads out of its own transcript.
fn standard_includes(names_an_empty_list: bool) -> String {
    match names_an_empty_list {
        true => "#include <array>\n#include <string_view>\n\n".to_string(),
        false => "#include <array>\n\n".to_string(),
    }
}

/// `csv-tools` → `csv_tools`, `my_helpers.v2` → `my_helpers_v2`, `9lives` → `_9lives`.
///
/// snake_case because that is what this SDK spells every function and every type in, and what the
/// standard library it arrives beside spells everything in — so a program reaching
/// `lib::csv_tools::parse(…)` reads like the rest of its own scope.
///
/// Any separator — `-`, `.`, or anything a name should not have had — becomes `_`, a run of them
/// becomes one, an upper-case letter is lowered, a name that is nothing but separators becomes
/// `module`, and a leading digit is prefixed.
///
/// It has to be a valid C++ **identifier** for the same reason the [Rust](super::rust) arm's does:
/// on this arm the key is a namespace the compiler resolves (`lib::<key>`) rather than a string
/// looked up at run time, so a key C++ could not parse would be a program that does not compile.
///
/// Deliberately ASCII-only, though C++ identifiers may carry other Unicode letters, for the reason
/// every other arm gives: a name a model has to reproduce exactly is one that should have no
/// characters it could get wrong.
pub(super) fn binding_name(name: &str) -> String {
    let mut out = String::new();
    let mut separated = false;
    for character in name.chars() {
        if character.is_ascii_alphanumeric() {
            if separated && !out.is_empty() {
                out.push('_');
            }
            separated = false;
            out.extend(character.to_lowercase());
        } else {
            separated = true;
        }
    }
    if out.is_empty() {
        return "module".to_string();
    }
    if out.starts_with(|character: char| character.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// `gg::views::open_file("src/main.cpp");`, or the same call with `{.offset = 400, .limit = 200}`
/// for a window — with the call itself already spelled by the language that asked.
///
/// Deliberately the plainest statement that does the job: no binding, no printing. It is synthesized
/// into the agent's own transcript and read by the model as an example of its own output, so
/// anything clever in it is a style the run did not intend to teach.
///
/// The window is a **designated initialiser** for the call's own optional argument, which is what
/// this SDK offers instead of keyword arguments and what a C++23 author writes. The whole-file form
/// passes nothing at all, because the argument has a default and a C++ author does not write `{}`
/// where the default is what they wanted.
///
/// The path is rendered through [`serde_json`] so a quote or a backslash in one cannot produce a
/// statement that would not parse: C++'s ordinary string literals accept exactly the escapes JSON's
/// do.
pub(super) fn open_file_statement(
    open_file: &str,
    path: &str,
    window: Option<FileWindow>,
) -> String {
    let path = serde_json::Value::String(path.to_string());
    match window {
        Some(window) => format!(
            "{open_file}({path}, {{.offset = {}, .limit = {}}});",
            window.offset, window.limit
        ),
        None => format!("{open_file}({path});"),
    }
}

/// A whole translation unit that opens one file view per entry of `views`: the module's own
/// `#include` line, an `int main`, and one call per view in the order given.
///
/// The seam's default is the statement list, and this arm cannot take it: a bare statement has
/// nowhere to live in C++ and [gg refuses](self::source::defines_main) a reply that defines no
/// `main`. So what gg pushes into the transcript is a program the model really could have sent —
/// which is the whole reason the seam lets a language answer this for itself.
///
/// Each call is written by [`open_file_statement`], indented by two, so the one place a file-view
/// call is spelled stays one place.
pub(super) fn open_file_program(
    includes: &str,
    open_file: &str,
    views: &[(&str, Option<FileWindow>)],
) -> String {
    let calls: String = views
        .iter()
        .map(|(path, window)| format!("  {}\n", open_file_statement(open_file, path, *window)))
        .collect();
    format!("{includes}int main() {{\n{calls}  return 0;\n}}\n")
}

/// A whole translation unit: an array of names and a range `for` over it, each iteration opening one
/// documentation view.
///
/// It is a **whole program** rather than a statement list, and this arm is the one where that is
/// forced by the grammar rather than chosen: C++ has nowhere for a statement to live except a
/// function body, and gg [refuses](self::source::defines_main) a reply that defines no `main`. So
/// what this generates is what it has to be, and what the seam asks for anyway — the on-use script
/// of every [built-in family skill](crate::skills) is a program.
///
/// An array and a loop rather than one call per name because the list is as long as the family —
/// eleven calls written out would be a program a model reads as a style to copy — and a
/// `std::array` deduced from its initialiser rather than a `std::vector`, because it is a fixed list
/// of string literals and allocating for one is what a C++ author would not do. The loop is a range
/// `for` over `const auto &`, which is the same author's default.
///
/// The empty case is spelled with an explicit element type and length, because an empty braced
/// initialiser gives `std::array` nothing to deduce from — *no viable constructor or deduction
/// guide* — and the `(void)` cast keeps a program that declares an array it never reads from being
/// a warning about one.
///
/// [`standard_includes`] is what declares that `std::array`, above the call's own include line: this
/// program obeys the rule a model's program obeys, and nothing is in scope of it that a line in it
/// did not put there.
pub(super) fn open_docs_views_statement(
    includes: &str,
    open_docs_view: &str,
    names: &[&str],
) -> String {
    let entries: Vec<String> = names
        .iter()
        .map(|name| format!("      {}", serde_json::Value::String((*name).to_string())))
        .collect();
    let listed = match entries.is_empty() {
        true => {
            "  const std::array<std::string_view, 0> functions{};\n  (void)functions;\n".to_string()
        }
        false => format!(
            "  const std::array functions{{\n{},\n  }};\n",
            entries.join(",\n")
        ),
    };
    format!(
        "{}{includes}int main() {{\n{listed}  for (const auto &name : functions) {{\n    \
         {open_docs_view}(name);\n  }}\n  return 0;\n}}\n",
        standard_includes(names.is_empty())
    )
}

/// The four calls the [opening program](bootstrap_program) writes, and the `#include` lines that
/// declare them.
///
/// One value rather than five parameters: this arm needs the include block as well as the spellings,
/// and five strings in a row is a call site whose arguments are told apart by counting.
pub(super) struct BootstrapCalls<'a> {
    /// The `#include` lines for exactly the modules this program calls into.
    pub includes: &'a str,
    /// This arm's spelling of the documentation search.
    pub search: &'a str,
    /// This arm's spelling of the documentation-view open.
    pub open_docs_view: &'a str,
    /// This arm's spelling of the workspace tree.
    pub tree_call: &'a str,
    /// This arm's spelling of the text-view open.
    pub open_text: &'a str,
}

/// The opening turn: one `int main` holding one search over every module gg listed and an array of
/// names opened as documentation views, with a range `for` over it.
///
/// A whole translation unit defining `main`, because this arm has nowhere else to put a statement
/// and [refuses](self::source::defines_main) a reply that defines none.
///
/// **One search rather than one per module**, because the filter is a union: the modules are a
/// braced list inside the filters, so the whole listing is read by a single call. A loop of a dozen
/// calls where one would do is a shape a model would copy for its own work — and so is a query of
/// `""` beside a filter that already says everything, which is why the search carries the modules
/// and the page and nothing else.
///
/// The array of keys, the `const auto &` loop, the empty case's explicit element type and the
/// [standard-library include lines](standard_includes) that declare them are what
/// [`open_docs_views_statement`] argues for, unchanged.
///
/// An agent that holds neither `files` nor `shell` is handed **no modules at all**, and a search
/// that names no module and asks no question is the one call this family refuses. That program is
/// written without the search — and without the `#include` that declared it — rather than opening
/// the session on gg's own `invalid-argument`.
///
/// It is the one program in this file that is compiled and run **before the model's first
/// request**, so a missing include here is a run that ends on gg's own defect rather than a turn a
/// model can act on.
///
/// The filters are an aggregate filled in with **designated initialisers**, which is what this
/// language offers in place of named arguments and what its SDK declares.
///
/// A failed call throws and nothing here catches it, which is this arm's failure model: a bootstrap
/// that caught its own failure would be a worked example of swallowing one.
pub(super) fn bootstrap_program(
    calls: BootstrapCalls<'_>,
    modules: &[&str],
    docs: &[&str],
    tree: Option<u32>,
) -> String {
    let BootstrapCalls {
        includes,
        search,
        open_docs_view,
        tree_call,
        open_text,
    } = calls;
    let walked = match tree {
        None => String::new(),
        Some(depth) => format!(
            "  {open_text}({}, {tree_call}({{.depth = {depth}}}));\n\n",
            serde_json::Value::String(WORKSPACE_TREE_VIEW.to_string())
        ),
    };
    let paths: Vec<String> = modules
        .iter()
        .map(|path| serde_json::Value::String((*path).to_string()).to_string())
        .collect();
    let lookup = match paths.is_empty() {
        true => String::new(),
        false => format!(
            "  {search}({{.modules = {{{}}}, .limit = {MAX_SEARCH_LIMIT}}});\n\n",
            paths.join(", ")
        ),
    };
    let entries: Vec<String> = docs
        .iter()
        .map(|name| format!("      {}", serde_json::Value::String((*name).to_string())))
        .collect();
    let functions = match entries.is_empty() {
        true => {
            "  const std::array<std::string_view, 0> functions{};\n  (void)functions;\n".to_string()
        }
        false => format!(
            "  const std::array functions{{\n{},\n  }};\n",
            entries.join(",\n")
        ),
    };
    format!(
        "{}{includes}int main() {{\n{walked}{lookup}{functions}  for (const auto &name : functions) \
         {{\n    {open_docs_view}(name);\n  }}\n  return 0;\n}}\n",
        standard_includes(docs.is_empty())
    )
}

#[cfg(test)]
#[path = "cpp.test.rs"]
mod tests;

/// **The C++ arm's execution substrate**, driven end to end through gg's real compiler, linker,
/// membrane and store.
///
/// A separate test file from any unit tests, because these are a different kind of test: each one
/// runs a real `clang++` and compiles a wasm component, which is tens or hundreds of milliseconds
/// rather than microseconds.
#[cfg(test)]
#[path = "cpp.substrate.test.rs"]
mod substrate;

/// **The [`feedback`](crate::sandbox::membrane::capture) channel, driven from C++ programs** — what
/// the capture keeps of what a program logs, what a program's end hands gg, and what a code module
/// that fails tells the model.
#[cfg(test)]
#[path = "cpp.feedback.test.rs"]
mod feedback;

/// **Every C++ example a model is shown, put through `clang++`** — the prompt's, the notice's and
/// the catalogue's.
///
/// A separate file from [`surface`] because it asks a question no other kind of gate can: not
/// whether the call gg quotes exists, which [`crate::prompts`] already gates in every language, but
/// whether the code around it builds. On a compiled arm an example that does not is a whole turn
/// spent on gg's own prose.
#[cfg(test)]
#[path = "cpp.examples.test.rs"]
mod examples;

/// **The C++ arm's model-facing surface**: the hand-written SDK, the catalogue reflected out of its
/// own documentation, and the library set it says a program may include.
///
/// A separate test file from [`substrate`], because it is a different claim. That one asks whether
/// C++ runs here; this asks whether the thing a model is *told* it may write is the thing the
/// sandbox really has — which is the only question a cross-language study rests on, and the one
/// whose failure is silent.
#[cfg(test)]
#[path = "cpp.surface.test.rs"]
mod surface;
