//! **PureScript** — gg's fifth registered [program language](super::ProgramLanguage), and the first
//! whose compiler is a **binary in the run image** rather than something gg carries inside its own
//! executable.
//!
//! Everything this arm owns lives here or in one of this module's siblings:
//!
//! * [`compile`] — the host-side `purs` and `esbuild` compile that turns a model's PureScript into
//!   the JavaScript the guest evaluates, what it costs, what it shares, and the two failures it
//!   tells apart;
//! * [`modules`] — reading a code [skill](crate::skills)'s or [memory](crate::memories)'s own
//!   module header for the names it offers and the types each of them writes;
//! * [`healing`] — the [dialect](crate::healing::Dialect) response healing asks its lexical
//!   questions of: the fence tags, the two predicates, and the nesting-and-primes lexer;
//! * `packages/gg-sandbox-purescript/src/Gg/**` — the hand-written SDK, compiled **into** the library
//!   tree below, so the surface a model is shown and the surface its program is compiled against are
//!   one artifact;
//! * the **signature catalogue** — reflected out of that SDK by `purs compile --codegen docs`, and
//!   generated into this build's `OUT_DIR` rather than committed anywhere (see
//!   `crates/gg/build.rs`);
//! * `purescript.libraries.tar.gz` and `purescript.compiler.json` — the compiled library set and
//!   the manifest of what is in it, generated by `crates/gg-sandbox-artifacts/purescript` into this
//!   build's own `OUT_DIR` rather than committed anywhere, and reached through
//!   `GG_ARTIFACTS_PURESCRIPT`. That tarball is also what the catalogue above is reflected against,
//!   which is why this is the one arm whose artifact crate is an ORDERING constraint as well as a
//!   source of bytes.
//!
//! # The strategy, in one sentence
//!
//! **A PureScript program is compiled to JavaScript on the host by `purs`, flattened into one ES
//! module by `esbuild`, and evaluated as a module by the [ECMAScript guest](super::ecmascript).**
//!
//! Nothing about it is per-run: the tree a program is compiled against is a build-time artifact, the
//! compiler is a binary in the gg toolchain image, and what crosses the membrane is JavaScript.
//!
//! # What a PureScript program is, here
//!
//! A **module**. PureScript has no loose statements, so a program is a module with its own header,
//! its own `main :: Effect Unit`, and an `import` line for each of gg's capability modules it uses
//! and each code module it has loaded. Every one of those is the model's: `purs` reads the reply and
//! nothing else, `purs` files the emitted JavaScript under the header the model wrote, and gg's
//! entry module imports `main` from there. A reply with no header is `ErrorParsingModule` at line 1
//! and a program that defines no `main` is refused with a sentence saying so, both before anything
//! runs.
//!
//! The bytes that **execute** are `purs`'s emission rather than the model's, which is the position
//! every compiled arm is in. What makes it legitimate is the pair the invariants require: the bytes
//! gg compiles are the model's, and a run-time location is recovered through the compilers' own
//! source maps — see [`locations`](crate::sandbox::ProgramLanguage::locations).
//!
//! The library set a program may import is a **build-time fact about the embedded tree** rather than
//! a policy: `packages/gg-sandbox-purescript/spago.yaml` declares it, the build compiles exactly that
//! set and everything it depends on, and the manifest records what shipped. It is deliberately
//! generous — the collections, the monad transformers and the profunctor lenses a PureScript author
//! reaches for without asking — because an arm that made a model live without its own idioms would be
//! measuring the wrong thing. **The SDK is compiled into that same tree**, which is why the tree
//! rides inside gg's binary rather than in the run image: a tree of one vintage and a binary of
//! another would mean a model shown one surface in its prompt and compiled against a different one.
//!
//! # What the SDK looks like, and why
//!
//! It is **idiomatic PureScript** rather than the TypeScript SDK transliterated, and every difference
//! is a spelling the seam leaves free:
//!
//! * **The surface is eleven capability modules** — `Gg.Files`, `Gg.Shell`, `Gg.Board`, … — plus a
//!   twelfth, `Gg.Core`, that binds no operation and holds the failure types every other module's
//!   signatures name. Each is a real PureScript module with an explicit export list, which is the
//!   best public-surface protocol of the eleven arms: `purs` will not let anything else escape.
//! * **A program writes the module's own name.** It is the one arm with a real import line, and the
//!   line aliases a module to itself: `import Gg.Files as Gg.Files` makes `Gg.Files.readFile` — the
//!   key a documentation view is opened by — the expression a call site writes, so the name a model
//!   reads and the name it types are one string. Verified against `purs`: an *open* import does not
//!   make a fully-qualified reference resolve, and a dotted alias does.
//! * **Free functions over values, and no member functions at all.** Where an arm with objects hangs
//!   `wait` off a handle, this one offers `Gg.Delegation.waitForSubagents` over it. A member on a
//!   record would be a field access no search can reach, which is the same failure an API object was.
//! * **Optional arguments are a record, and the row is checked.** `Union given rest ReadOptions` is
//!   PureScript's own idiom for "these fields, any subset of them": `Gg.Files.readFile "a" {}` and
//!   `Gg.Files.readFile "a" { limit: 20 }` both type-check, and `{ limitt: 20 }` is a type error
//!   naming every field that would have worked.
//! * **A three-way patch field needs no sentinel.** Leave `description` out of the record to keep it,
//!   pass `Nothing` to clear it, pass `Just` to replace it — where Python needs an `UNCHANGED`
//!   because `None` is already taken.
//! * **A fixed choice is a `data` type** (`TaskDone`, `IssueOpen`, `FileEntry`), and a read is a real
//!   sum type a program matches on rather than a `kind` field it compares against a string.
//! * **A failure is thrown and caught with `attempt`**, which is how effectful PureScript expresses a
//!   failure that is usually fatal to what you were doing; `Effect (Either ApiError a)` on every
//!   call would force a branch after every line.
//! * **The brief a child agent is spawned with is a constructor** — `Prompt` or `Issue` — so "both"
//!   and "neither" are programs that do not compile rather than calls the host refuses.
//!
//! The bridge underneath it is `Gg.Internal.Wire`, one foreign module whose JavaScript half writes
//! `import * as gg from "gg"` — the same line a TypeScript program writes, reaching the same SDK
//! instance in the same guest, so both arms produce byte-identical arguments for one capability. A
//! capability this run withheld is refused by the host as an `ApiError` carrying `unavailable`, as
//! it is on every arm. gg's own spellings for the families are the lowering and not the surface:
//! they are written once, beside the function that uses them, and a model never sees one.
//!
//! # What this arm has that no other does
//!
//! It is the only arm whose program is read by a **type system** and is not
//! [TypeScript](super::typescript)'s. That makes it the third point on the axis a study reads to
//! separate *checked* from *typed*: Python is unchecked and interpreted, JavaScript is unchecked and
//! lowered, Ruby is compiled without being typed, TypeScript is type-checked in a gradual system over
//! a dynamic language, and this arm is type-checked in a total one — where a call written with the
//! wrong argument shape, a `case` that misses an arm, or a missing instance is a diagnostic rather
//! than a turn.

use std::sync::OnceLock;

use test_cabinet_core::gg::GgProgramLanguage;

use crate::sandbox::signatures::SignatureCatalogue;

use super::{
    CodeModule, FileWindow, LIB_ACCESS_NAME, PrepareContext, PrepareFailure, PreparedModule,
    PreparedProgram, ProgramLanguage, spell,
};
use crate::docs::MAX_SEARCH_LIMIT;
use crate::sandbox::locate::Locations;
use crate::sandbox::operations::{DOCS_SEARCH, VIEWS_OPEN_DOCS_VIEW, VIEWS_OPEN_FILE};

#[path = "purescript.compile.rs"]
pub(super) mod compile;

#[path = "purescript.modules.rs"]
mod modules;

#[path = "purescript.healing.rs"]
pub(super) mod healing;

/// This arm's catalogue, reflected out of the SDK's own doc comments by
/// `packages/gg-sandbox-purescript/signatures.sh` with `purs compile --codegen docs`.
///
/// It is not committed. `crates/gg/build.rs` runs that reflection as a step of building this
/// crate and this line embeds what it wrote into the build's own `OUT_DIR`, so what a model is
/// told about this arm is reflected out of the SDK sources in this checkout, on the build that
/// compiles the module telling it.
const SIGNATURES: &str = include_str!(concat!(
    env!("OUT_DIR"),
    "/signatures/purescript.signatures.json"
));

/// The parsed catalogue, parsed once per process.
static CATALOGUE: OnceLock<SignatureCatalogue> = OnceLock::new();

/// The one instance of this language. A unit struct, so the `static` costs nothing and coerces
/// straight to `&'static dyn ProgramLanguage`.
pub(super) static PURESCRIPT: PureScript = PureScript;

/// PureScript: compiled to JavaScript on the host by `purs`, bundled by `esbuild`, and evaluated as
/// a module by the shared ECMAScript guest.
pub(super) struct PureScript;

impl ProgramLanguage for PureScript {
    fn id(&self) -> GgProgramLanguage {
        GgProgramLanguage::PureScript
    }

    fn display_name(&self) -> &'static str {
        GgProgramLanguage::PureScript.display_name()
    }

    /// `CsvTools.parse` — a qualified name of the module's own alias, which is what the
    /// [import line](Self::lib_import) beside it bound.
    fn lib_access(&self, key: &str) -> String {
        format!("{}.{LIB_ACCESS_NAME}", alias(key))
    }

    /// `import Lib.CsvTools as CsvTools` — the line a program writes to reach a loaded module, and
    /// the same kind of line it writes to reach `Gg.Files`.
    ///
    /// A code module is [compiled into the program's own `purs` project](compile), under
    /// [`Lib.<Key>`](module_path()), so nothing about reaching it is this arm's invention: the program
    /// imports a module, aliases it, and calls a function `purs` type-checked against the author's
    /// signature.
    fn lib_import(&self, key: &str) -> Option<String> {
        Some(format!("import {} as {}", module_path(key), alias(key)))
    }

    /// The `purs` compile and the `esbuild` bundle, in this preparation's own hard-linked tree — see
    /// [`compile`] for what it costs, what it shares, and how it tells a program `purs` refused from
    /// a `purs` that could not run.
    fn prepare_program(
        &self,
        source: &str,
        modules: &[CodeModule],
        context: &PrepareContext,
    ) -> Result<PreparedProgram, PrepareFailure> {
        compile::compile_program(source, modules, context)
    }

    /// `purs`, which is what a PureScript programmer calls it and what its own binary is called — not
    /// `esbuild`, which flattens what it emitted and judges nothing about the program except that it
    /// has an entry point.
    ///
    /// Naming one is also what has the ~290 ms compile — paid on the failing path as much as the
    /// succeeding one — [recorded](crate::sandbox::SandboxOutcome::compile) rather than absorbed.
    fn checker(&self) -> Option<&'static str> {
        Some("purs")
    }

    /// Unpack the embedded library tree — 1.4 MB into 1,430 files, once per machine — so the first
    /// code turn is not charged for it.
    ///
    /// Idempotent and best effort: the result is cached for the process, and a failure here is
    /// dropped rather than reported, because the first compile makes the same attempt and fails there
    /// as a [toolchain failure](PrepareFailure::Toolchain) the run is told about properly.
    fn warm_prepare(&self) {
        compile::warm();
    }

    /// A `purs` compile of the author's module **on its own**, and the names it offers.
    ///
    /// What travels on is the author's source rather than anything compiled: a module is a module of
    /// the [program's own project](compile), written into it under the key the module was bound at,
    /// so the compile that matters is the one the program's own turn runs. This one exists to answer
    /// the use that loaded it — a module `purs` refuses is refused here, in the author's own
    /// coordinates, rather than by the next program that has it in scope.
    ///
    /// The guest is handed that source as well, and resolves none of it: the module's JavaScript is
    /// already inside the bundle of every program that imported it, so nothing in the guest ever
    /// asks for the module by name.
    ///
    /// What the module offers is read here rather than in the guest, because it is what the model is
    /// *told*: see [`modules`].
    fn prepare_module(
        &self,
        source: &str,
        context: &PrepareContext,
    ) -> Result<PreparedModule, PrepareFailure> {
        compile::check_module(source, context)?;
        Ok(PreparedModule {
            source: source.to_string(),
            exports: modules::exports(source),
        })
    }

    /// `.purs`, and nothing else.
    ///
    /// One extension, like [Python](super::python)'s and [Ruby](super::ruby)'s: nothing else in the
    /// registry can evaluate a PureScript module — this arm's guest could evaluate the *compiled*
    /// output, but a skills directory holds sources rather than artifacts — so a skill whose code is
    /// spelled `skill.rb` is a skill this arm's agents are not offered.
    fn module_file_extensions(&self) -> &'static [&'static str] {
        &["purs"]
    }

    /// [PascalCase](self::binding_name), which is what a PureScript module name is made of: the key
    /// is the last component of `Lib.<Key>` and the alias every call to the module carries.
    fn binding_name(&self, name: &str) -> String {
        binding_name(name)
    }

    /// The [ECMAScript guest](super::ecmascript), which the [TypeScript](super::typescript) and
    /// [JavaScript](super::javascript) arms are also registered against: one artifact, embedded
    /// once, evaluating every module gg compiles to JavaScript.
    fn guest_component(&self) -> Option<&'static [u8]> {
        Some(super::ecmascript::embedded())
    }

    /// This guest arms an interrupt handler off `GG_SANDBOX_DEADLINE_MS`, so a runaway loop is
    /// stopped by quickjs with `InternalError: interrupted` and the JavaScript frames rather than by
    /// gg's epoch trap. See [`stops_itself_at_ggs_deadline`](ProgramLanguage::stops_itself_at_ggs_deadline).
    fn stops_itself_at_ggs_deadline(&self) -> bool {
        true
    }

    /// The **composition** of `purs`'s source map and `esbuild`'s, which `esbuild` performs itself
    /// and inlines into the bundle it writes.
    ///
    /// A frame the engine reports as a position in the bundle therefore reads back as
    /// `program.purs:11:27` — the model's own file at the line it wrote — and a frame in a library
    /// or in this arm's SDK reads as that PureScript module's own path in the shipped tree. The name
    /// each frame takes is the one the map itself records for the token, rather than a single name
    /// gg picks, because a bundle is made of many sources and only the map knows which one a frame
    /// came from.
    ///
    /// Two sources in that map are neither the model's nor a library's, and their frames are struck
    /// rather than reported: [the entry module](compile::ENTRY_FILE) gg generates for the bundler,
    /// and any position in the bundle the composed map resolves nothing for.
    ///
    /// One map covers every frame, code modules included: a module is compiled into the program's
    /// own project, so its JavaScript is part of the one bundle and its `Lib.<Key>.purs` is one of
    /// the sources the composition resolves to.
    fn locations(&self, program: &str, _modules: &[CodeModule]) -> Option<Locations> {
        Locations::read(std::iter::once((
            super::ecmascript::PROGRAM.to_string(),
            None,
            program,
        )))
        .map(|locations| locations.hiding([compile::ENTRY_FILE.to_string()]))
    }

    /// This language's catalogue, parsed once and checked to be **this** language's.
    ///
    /// Every registered language's build reflects one of these under its own stem into the one
    /// `OUT_DIR`, and each carries the language it was generated for; checking it here is what stops
    /// a catalogue written — or embedded — under the wrong stem from reaching a model as a system
    /// prompt describing a sandbox nobody has.
    fn catalogue(&self) -> &'static SignatureCatalogue {
        CATALOGUE.get_or_init(|| {
            let catalogue = SignatureCatalogue::parse(SIGNATURES)
                .expect("the generated signature catalogue is valid JSON of the expected shape");
            assert_eq!(
                catalogue.language,
                GgProgramLanguage::PureScript,
                "`signatures/purescript.signatures.json` was generated for another program language",
            );
            catalogue
        })
    }

    fn healing(&self) -> &'static dyn crate::healing::Dialect {
        &healing::PURESCRIPT_DIALECT
    }

    /// [`void (Gg.Views.openFile "src/Main.purs" {})`](self::open_file_statement) — the call, its
    /// options record, and the `void` that discards what it hands back.
    fn open_file_statement(&self, path: &str, window: Option<FileWindow>) -> String {
        open_file_statement(&spell(self, VIEWS_OPEN_FILE), path, window)
    }

    /// [A module that imports the view module and folds a `for_` over an array of
    /// names](self::open_docs_views_statement), each iteration opening one documentation view.
    fn open_docs_views_statement(&self, names: &[&str]) -> String {
        open_docs_views_statement(&spell(self, VIEWS_OPEN_DOCS_VIEW), names)
    }

    /// [A module whose `main` folds a `for_` over each of two arrays](self::bootstrap_program), with
    /// both calls resolved from this language's own catalogue and both modules imported by name.
    fn bootstrap_program(&self, modules: &[&str], docs: &[&str]) -> String {
        bootstrap_program(
            &spell(self, DOCS_SEARCH),
            &spell(self, VIEWS_OPEN_DOCS_VIEW),
            modules,
            docs,
        )
    }
}

// ---------------------------------------------------------------------------------------------
// The syntax this arm writes
// ---------------------------------------------------------------------------------------------

/// `csv-tools` → `CsvTools`, `my_helpers.v2` → `MyHelpersV2`, `9lives` → `Module9lives`,
/// `CSV-tools` → `CSVTools`.
///
/// The key on this arm is a **proper name**, because [the module a program imports](module_path()) is
/// `Lib.<Key>` and a PureScript module name is a dotted sequence of proper names. So the key is
/// PascalCase: any separator — `-`, `_`, `.`, or anything a name should not have had — joins the
/// next word rather than surviving into an identifier that would not parse, and the front comes up.
/// A name with nothing usable in it, and one that would open with a digit, are prefixed `Module`,
/// which is the one word that leaves the result a name PureScript will read.
///
/// Deliberately ASCII-only, though PureScript identifiers may be Unicode: the key is what the model
/// types in the import line of every program that uses the module, and a name a model has to
/// reproduce exactly is one that should have no characters it could get wrong.
pub(super) fn binding_name(name: &str) -> String {
    let mut out = String::new();
    let mut capitalize = true;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize {
                out.extend(ch.to_uppercase());
                capitalize = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize = true;
        }
    }
    match out.starts_with(|ch: char| ch.is_ascii_uppercase()) {
        true => out,
        false => format!("Module{out}"),
    }
}

/// The module one code module is compiled as, and the one a program imports: `Lib.CsvTools`.
///
/// `Lib` is gg's namespace rather than a package anything publishes, which is what keeps a key from
/// ever colliding with the shipped library set; a program that names one of these itself is
/// [refused](compile) with a sentence naming the key.
pub(super) fn module_path(key: &str) -> String {
    format!("Lib.{}", alias(key))
}

/// The alias a program binds that module under, and the qualifier every call to it carries.
///
/// The key itself, which [`binding_name`] already spells as a proper name. It is written through
/// this rather than used directly so that a key from anywhere else — the seam's own gates ask for
/// `lib_access("csvTools")` — still produces a line PureScript would parse.
fn alias(key: &str) -> String {
    let mut characters = key.chars();
    match characters.next() {
        None => "Module".to_string(),
        Some(first) => first.to_uppercase().collect::<String>() + characters.as_str(),
    }
}

/// `void (open_file "src/Main.purs" {})`, or
/// `void (open_file "src/Main.purs" { offset: 400, limit: 200 })` for a window — with `open_file`
/// already spelled by the language that asked.
///
/// Deliberately the plainest statement that does the job: no binding, no `where`, no logging. It is
/// synthesized into the agent's own transcript and read by the model as an example of its own output,
/// so anything clever in it is a style the run did not intend to teach.
///
/// Three things about it are this language's and are the reason this is a method rather than a
/// `format!` somewhere shared. The window is a **record**, which is this arm's idiom for optional
/// arguments and the shape the system prompt teaches — and the record is written even when there is
/// no window, because `{}` is how a PureScript program says "none of them" to a row-typed argument
/// rather than leaving it off. The call is wrapped in `void`, because a `do` block discards a
/// statement's value only when it is `Unit` and this one hands back a `FileRead`; a bare call would
/// be a `Discard` instance that does not exist. And there is no terminator, because PureScript does
/// not have one.
///
/// The path is rendered through [`serde_json`] so a quote or a backslash in one cannot produce a
/// statement that would not parse: PureScript's string literals accept exactly the escapes JSON's do.
///
/// What a caller does with several of these is join them with newlines, which composes them into the
/// **body** of a `do` block rather than into a whole module. That is the seam's shape rather than
/// this arm's choice — it hands a language one path at a time — and it is the right half to be given,
/// because the body is what a model writing its next program actually types.
pub(super) fn open_file_statement(
    open_file: &str,
    path: &str,
    window: Option<FileWindow>,
) -> String {
    let path = serde_json::Value::String(path.to_string());
    let options = match window {
        Some(window) => format!("{{ offset: {}, limit: {} }}", window.offset, window.limit),
        None => "{}".to_string(),
    };
    format!("void ({open_file} {path} {options})")
}

/// A module with an array of names and a `for_` over it, each iteration opening one documentation
/// view.
///
/// A whole module, because that is what a PureScript program is: this is the on-use script of every
/// built-in family skill, so it is handed straight to the prepare step and really is compiled.
///
/// A top-level array and a `for_` rather than a `let` inside the `do` block, because a top-level
/// declaration carries its own type signature — which is what makes the empty case
/// (`functions = []`, for an object with nothing enabled) a program rather than an ambiguous type.
/// The names are rendered through [`serde_json`] for the reason a path is: a name carrying a quote
/// would otherwise produce a program that does not parse. Leading commas, because that is how
/// PureScript writes a list.
pub(super) fn open_docs_views_statement(open_docs_view: &str, names: &[&str]) -> String {
    let mut entries = String::new();
    for (index, name) in names.iter().enumerate() {
        let separator = if index == 0 { '[' } else { ',' };
        let name = serde_json::Value::String((*name).to_string());
        entries.push_str(&format!("  {separator} {name}\n"));
    }
    if entries.is_empty() {
        entries.push_str("  [\n");
    }
    let module = module_of(open_docs_view);
    format!(
        "module Main where\n\
         \n\
         import Prelude\n\
         \n\
         import Data.Foldable (for_)\n\
         import Effect (Effect)\n\
         import {module} as {module}\n\
         \n\
         functions :: Array String\n\
         functions =\n\
         {entries}  ]\n\
         \n\
         main :: Effect Unit\n\
         main = for_ functions {open_docs_view}\n"
    )
}

/// The opening turn: a module whose `main` folds a `for_` over the module paths, listing each in
/// full, and then a `for_` over the names it opens documentation views of.
///
/// A whole module, because that is what a PureScript program is — and the two arrays are top-level
/// declarations carrying their own type signatures, for the reason
/// [`open_docs_views_statement`]'s one is: a `let` of an empty
/// array inside the `do` block would be an ambiguous type rather than a program.
///
/// Each module the program calls into is imported under its own full name, which is the name the
/// documentation is keyed by and the expression a program writes. The filters are the fields of a
/// **record** argument, which is this language's idiom for optional ones.
///
/// A failed call is thrown rather than returned, and nothing here catches it: that is this arm's
/// failure model, and a bootstrap that handled its own failure would be a worked example of
/// swallowing one.
pub(super) fn bootstrap_program(
    search: &str,
    open_docs_view: &str,
    modules: &[&str],
    docs: &[&str],
) -> String {
    let listed = |names: &[&str]| -> String {
        let mut entries = String::new();
        for (index, name) in names.iter().enumerate() {
            let separator = if index == 0 { '[' } else { ',' };
            let name = serde_json::Value::String((*name).to_string());
            entries.push_str(&format!("  {separator} {name}\n"));
        }
        if entries.is_empty() {
            entries.push_str("  [\n");
        }
        entries
    };
    let paths = listed(modules);
    let functions = listed(docs);
    // Two calls, and on this arm each needs its own import line — unless the SDK ever files both
    // under one module, in which case importing it twice would be the compile error rather than the
    // program.
    let docs_module = module_of(search);
    let views_module = module_of(open_docs_view);
    let mut imports = format!("import {docs_module} as {docs_module}\n");
    if views_module != docs_module {
        imports.push_str(&format!("import {views_module} as {views_module}\n"));
    }
    format!(
        "module Main where\n\
         \n\
         import Prelude\n\
         \n\
         import Data.Foldable (for_)\n\
         import Effect (Effect)\n\
         {imports}\
         \n\
         modules :: Array String\n\
         modules =\n\
         {paths}  ]\n\
         \n\
         functions :: Array String\n\
         functions =\n\
         {functions}  ]\n\
         \n\
         main :: Effect Unit\n\
         main = do\n\
         \x20 for_ modules \\path -> {search} \"\" {{ module: path, limit: {MAX_SEARCH_LIMIT} }}\n\
         \x20 for_ functions {open_docs_view}\n"
    )
}

/// The module a fully-qualified call is documented under, taken off the front of the call itself.
///
/// The one place gg has to write this arm's **import** line, and it is derived from the call rather
/// than looked up beside it so that the two cannot disagree: an import of some other module would
/// leave the call it was written for unresolved, which is a program that does not compile in the one
/// place a model reads gg's own output as an example of its own. Every catalogued name is
/// module-qualified — the name rule (`signatures.fqn.rs`) is what makes that true on
/// every arm — so the module is everything before the last separator, and a call that somehow
/// carried none is imported as itself rather than crashing a turn.
fn module_of(call: &str) -> &str {
    call.rsplit_once('.').map_or(call, |(module, _)| module)
}

#[cfg(test)]
#[path = "purescript.test.rs"]
mod tests;

/// **The PureScript arm's execution substrate and its SDK**, driven end to end through gg's real
/// compiler, linker, membrane and store.
///
/// A separate test file from [`tests`], because these are a different kind of test: each one compiles
/// the guest, unpacks a 1.4 MB library tree and spawns a real `purs`, which is seconds rather
/// than microseconds, where everything next door is a pure function over text.
#[cfg(test)]
#[path = "purescript.substrate.test.rs"]
mod substrate;
