//! **The Opal compile**, driven for real: a real `node`, the real embedded bundle, real Ruby.
//!
//! Nothing here is mocked and nothing is faked. Each case spawns the compiler exactly as a turn
//! would, through a [`PrepareContext`] the sandbox mints, so what is proven is the path a run takes
//! rather than a rehearsal of it.
//!
//! Isolation is **not** here, in any form, and that is the same deletion the
//! [Rust](crate::sandbox::language::rust), [Swift](crate::sandbox::language::swift) and
//! [C++](crate::sandbox::language::cpp) arms each made at registration rather than a gap this arm
//! left. The [seam's own gate](crate::sandbox::language::isolation) drives this arm's program *and*
//! module steps sixteen ways along with every other language's — Ruby is in
//! [`all_languages`](crate::sandbox::all_languages), so both of its halves are in
//! [`preparations`](crate::sandbox::language::isolation::preparations) — and it needs nothing from
//! this arm to do it: it searches an artifact for markers, and the JavaScript Opal writes carries
//! them as the model spelled them.
//!
//! What stood here was a hand-pointed copy of exactly that gate, driving `program.rb` and
//! `module.rb` through the same [`breaches`](crate::sandbox::language::isolation::breaches). It
//! proved nothing the seam's run of it does not, and it cost sixty-four more real `node` compiles to
//! prove it: measured on this repository's dev container at 6.3 s run on its own and **117.5 s**
//! under `cargo nextest run --workspace`, against nextest's default hard kill at 120 s. It passed
//! that run with 2.5 s to spare, which is the coin flip `.config/nextest.toml` bounds every other
//! compiled arm away from — and on a CI runner with a quarter of the cores it is a termination,
//! which reads as a hang rather than as a gate doing what it says. It is deleted rather than
//! bounded, because a duplicate gate is not made correct by being given longer to run.
//!
//! What is left is bounded, and the reason is in `.config/nextest.toml` beside the other compiled
//! arms: the seven tests below were measured with a worst of 7.6 s in one full workspace run and
//! 41.5 s in another taken within the hour, which is what a group of real `node` processes costs
//! depending on what else the scheduler is holding.

use super::*;

/// A context, as the sandbox mints one per preparation.
fn context() -> PrepareContext {
    PrepareContext::new()
}

/// Compile `source` as a program, or panic with what went wrong.
fn compiled(source: &str) -> String {
    match compile_program(source, &context()) {
        Ok(prepared) => prepared.source,
        Err(failure) => panic!("the embedded Opal did not compile valid Ruby: {failure}"),
    }
}

/// How preparing `source` failed, insisting that it did.
fn failed(source: &str) -> PrepareFailure {
    match compile_program(source, &context()) {
        Ok(prepared) => panic!("expected a failure; it compiled to {:?}", prepared.source),
        Err(failure) => failure,
    }
}

#[test]
fn a_real_ruby_program_compiles_to_javascript_the_guest_can_evaluate() {
    // Ordinary Ruby, exercising what a model actually writes: a class with state, a keyword
    // argument, a block, string interpolation, a chained enumerable. The point is not that any one
    // of them is doubtful — it is that a whole Ruby program, not a subset, survives the crossing to
    // JavaScript.
    let javascript = compiled(
        r#"
class Greeter
  def initialize(name)
    @name = name
  end

  def greet(times: 1)
    times.times.map { |i| "hello #{@name} #{i}" }
  end
end

lines = Greeter.new("gg").greet(times: 4).select { |line| line.include?("1") }
lines.each { |line| puts line }
"#,
    );

    // Opal's own preamble: what comes back is a program for the runtime this arm's guest carries,
    // and it says which Opal wrote it.
    assert!(
        javascript.starts_with("Opal.queue(function(Opal) {"),
        "the compiled program is evaluated against the guest's Opal: {}",
        &javascript[..javascript.len().min(120)],
    );
    assert!(
        javascript.contains(&format!("Generated by Opal {}", compiler_version())),
        "the artifact names the compiler that wrote it",
    );
    // The model's own text survives into the artifact, which is what says a compile happened rather
    // than a copy.
    assert!(
        javascript.contains("hello "),
        "the interpolation's literal half"
    );
    assert!(javascript.contains("'$greet'"), "the method it defined");
    // `enable_source_location` is on, so a program that asks where a method came from is told the
    // truth about ITS OWN file rather than about the JavaScript.
    assert!(
        javascript.contains("$$source_location: ['program.rb', "),
        "methods carry the Ruby file they were written in",
    );
}

/// **The bytes the compiler reads are the bytes the model sent**, and the file it reads them from is
/// the one its diagnostics name.
///
/// The [authorship gate](crate::sandbox::language::authorship) drives every arm through this same
/// property with one generated program. This asks it of this arm directly, over the shapes a model's
/// reply actually takes, and reads the answer out of the preparation's own workspace rather than out
/// of anything the arm chose to report.
#[test]
fn the_bytes_the_compiler_reads_are_the_bytes_the_model_sent() {
    for source in [
        "puts 1\n",
        "require \"gg\"\n\nGG::Views.open_text(\"n\", \"body\")\n",
        "# a comment first\n\nclass Ledger\n  def total = 0\nend\n\nputs Ledger.new.total\n",
        // No trailing newline, which is the shape a model's reply most often really has.
        "x = 1\nputs x",
    ] {
        let context = context();
        compile_program(source, &context).expect("this Ruby compiles");
        let workspace = context
            .workspace()
            .expect("the preparation has a workspace");
        let written = std::fs::read_to_string(workspace.work().join(PROGRAM_FILE))
            .expect("the compiler was handed a program.rb");
        assert_eq!(
            written, source,
            "the file the compiler read is not the reply gg was handed"
        );
    }
}

/// **A module in scope leaves the model's own program alone**, both in what the compiler reads and
/// in what the guest is handed.
///
/// The [authorship gate](crate::sandbox::language::authorship) drives the program half with nothing
/// in scope, so the one shape it cannot see is an arm that writes a program's `require "lib"` for it
/// once a module exists. This drives the arm's own
/// [`prepare_program`](crate::sandbox::language::ProgramLanguage::prepare_program) through the
/// registry with a really compiled module beside it and asks both halves: the file the compiler read
/// is the reply byte for byte, and what the guest is handed is what the same reply produces with
/// nothing in scope at all.
#[test]
fn a_module_in_scope_leaves_the_models_own_program_alone() {
    let language = crate::sandbox::language(test_cabinet_core::gg::GgProgramLanguage::Ruby);
    let module = crate::sandbox::CodeModule {
        name: "helpers".to_string(),
        source: compile_module("def double(n) = n * 2\n", &context()).expect("the module compiles"),
    };
    // A program that calls into the module and does NOT write the line that reaches it: the shape an
    // arm reaching for a module on the program's behalf would have to complete.
    let source = "puts lib.helpers.double(21)\n";

    let alone = context();
    let without = language
        .prepare_program(source, &[], &alone)
        .expect("this Ruby compiles")
        .source;

    let scoped = context();
    let with = language
        .prepare_program(source, std::slice::from_ref(&module), &scoped)
        .expect("this Ruby compiles with a module in scope")
        .source;

    let written = std::fs::read_to_string(
        scoped
            .workspace()
            .expect("the preparation has a workspace")
            .work()
            .join(PROGRAM_FILE),
    )
    .expect("the compiler was handed a program.rb");
    assert_eq!(
        written, source,
        "a module in scope changed the file the compiler read"
    );
    assert_eq!(
        with, without,
        "a module in scope changed the program the guest is handed"
    );
}

#[test]
fn ruby_the_parser_rejects_comes_back_as_the_models_own_error() {
    // A refusal is the only thing Opal can say about a program other than "here is your
    // JavaScript" — Ruby has no compile-time type system — so this is the whole of the model-facing
    // rejection band, and it has to arrive with coordinates in the text the model wrote.
    let failure = failed("x = 1\ny = 2 +* 3\nz = 4\n");
    let PrepareFailure::Program(PrepareError::Syntax(diagnostic)) = &failure else {
        panic!("a Ruby parse failure is the model's own syntax error, not {failure:?}");
    };
    assert!(
        diagnostic.starts_with("program.rb:2:"),
        "located in the model's own file at the model's own line: {diagnostic}",
    );
    assert!(
        diagnostic.contains("y = 2 +* 3"),
        "the offending line is quoted back: {diagnostic}",
    );
    assert!(
        diagnostic.contains("unexpected token"),
        "the compiler's own words, not gg's: {diagnostic}",
    );

    // A block left open reports the end of the file rather than a line inside it, which is right:
    // that is where the parser ran out.
    let failure = failed("def half_written(x)\n  puts x\n");
    let PrepareFailure::Program(PrepareError::Syntax(diagnostic)) = &failure else {
        panic!("an unterminated definition is a syntax error, not {failure:?}");
    };
    assert!(
        diagnostic.contains("program.rb:") && diagnostic.contains("unexpected token"),
        "{diagnostic}",
    );

    // The second shape of refusal, and the reason this band is not simply "a parse error": valid
    // Ruby this compiler has no lowering for. Opal raises it as a `SyntaxError` like the others, and
    // it is right that it lands in the same band — the model's answer to both is to write different
    // Ruby — but it arrives without a line, because nothing in the parser located it.
    let failure = failed("BEGIN { puts 'setup' }\nputs 'body'\n");
    let PrepareFailure::Program(PrepareError::Syntax(diagnostic)) = &failure else {
        panic!("Ruby this compiler cannot lower is still the model's to change, not {failure:?}");
    };
    assert!(
        diagnostic.starts_with("program.rb:") && diagnostic.contains("Unsupported sexp"),
        "the compiler says which construct it has no lowering for: {diagnostic}",
    );
}

#[test]
fn a_compiler_that_cannot_run_is_never_reported_as_the_models_failure() {
    // The misattribution this whole split exists to prevent: a broken image told to the model as
    // "your program did not compile" sends it rewriting something nothing ever read. Each `#[test]`
    // is its own process under nextest, so pointing the interpreter somewhere that does not exist
    // affects nothing else.
    let restore = std::env::var(NODE_ENV).ok();
    // SAFETY: single-threaded test process; nothing else reads the environment concurrently.
    unsafe { std::env::set_var(NODE_ENV, "gg-no-such-interpreter") };
    let failure = failed("puts 'this program is fine'\n");
    match restore {
        // SAFETY: as above.
        Some(value) => unsafe { std::env::set_var(NODE_ENV, value) },
        // SAFETY: as above.
        None => unsafe { std::env::remove_var(NODE_ENV) },
    }

    let PrepareFailure::Toolchain(message) = &failure else {
        panic!("a missing interpreter is a toolchain failure, not {failure:?}");
    };
    assert!(
        message.contains("gg-no-such-interpreter") && message.contains(NODE_ENV),
        "it names what gg looked for and the one variable an operator can fix: {message}",
    );
}

#[test]
fn the_embedded_bundle_says_which_opal_and_which_ruby_it_is() {
    // Both are model- and operator-facing facts that a study records, and both are read off the
    // artifact rather than written down in Rust — which is the point of the manifest.
    assert!(
        compiler_version().starts_with(char::is_numeric),
        "the Opal release is a version: {}",
        compiler_version(),
    );
    assert!(
        ruby_version().starts_with('3'),
        "the Ruby this arm's programs are written in: {}",
        ruby_version(),
    );
}

/// **Compiling is a real, repeated cost**: every preparation spawns the compiler and is handed back
/// what *that* process wrote.
///
/// This was a stopwatch — three compiles timed, each asserted at `>= 10 ms` and `< COMPILE_TIMEOUT`
/// — and both bounds were claims about the machine rather than about this arm: a floor saying the
/// box is slow enough, a ceiling saying it is fast enough. Neither is the property the test is named
/// for, and the ceiling could only ever be reached by a compile the seam had already killed, which
/// arrives here as `the embedded Opal did not compile valid Ruby` and names the wrong thing. The
/// floor's real subject is gated without a clock and for every arm at once, by
/// [`every_language_reports_what_compiling_its_program_cost`](crate::sandbox::tests::compile_tests):
/// a compiled arm's per-turn reading has to arrive on the outcome and be greater than zero.
///
/// What is left is the half nothing else asks — that the second compile is a **second compile**. An
/// arm that memoised on the source, or handed back an artifact a previous preparation wrote, would
/// be reporting a compiler it did not run, and that is observable in the preparation's own tree
/// rather than on a clock: each compile must have read its own `program.rb` and been handed back the
/// bytes its own `program.js` holds, in a tree no other preparation was given.
#[test]
fn the_second_compile_is_a_second_compile_rather_than_a_memo() {
    let source = "puts (1..10).reduce(:+)\n";
    let mut outputs = Vec::new();
    for _ in 0..3 {
        let context = context();
        let returned = compile_program(source, &context)
            .expect("this Ruby compiles")
            .source;
        let workspace = context
            .workspace()
            .expect("the preparation has a workspace");

        assert_eq!(
            std::fs::read_to_string(workspace.work().join(PROGRAM_FILE))
                .expect("the compiler was handed a program.rb"),
            source,
            "this compile read something other than the source it was given",
        );
        // The artifact is read back off the filesystem rather than out of the return value, because
        // a file in this preparation's own output directory is what says a process ran *here*.
        let output = workspace.output().join(OUTPUT_FILE);
        let written = std::fs::read_to_string(&output).unwrap_or_else(|error| {
            panic!(
                "this preparation's own tree holds no {OUTPUT_FILE}: {error} — what came back was \
                 not written by a compiler that ran for it",
            )
        });
        assert_eq!(
            written, returned,
            "what the caller was handed is not what this preparation's compiler wrote",
        );
        outputs.push(output);
    }

    // Three preparations, three trees — so the three readings above are three artifacts and not one
    // file read three times.
    for (index, output) in outputs.iter().enumerate() {
        assert!(
            !outputs[..index].contains(output),
            "two compiles were handed the same {}",
            output.display(),
        );
    }
}
