//! **The Opal compile**, driven for real: a real `node`, the real embedded bundle, real Ruby.
//!
//! Nothing here is mocked and nothing is faked. Each case spawns the compiler exactly as a turn
//! would, through a [`PrepareContext`] the sandbox mints, so what is proven is the path a run takes
//! rather than a rehearsal of it.

use std::time::Instant;

use super::*;
use crate::sandbox::language::isolation::{Preparation, breaches};

/// A context, as the sandbox mints one per preparation.
fn context() -> PrepareContext {
    PrepareContext::new()
}

/// Compile `source` as a program, or panic with what went wrong.
fn compiled(source: &str) -> String {
    match compile_program(source, &context()) {
        Ok(prepared) => prepared.source,
        Err(failure) => panic!("the embedded Opal did not compile valid Ruby: {failure}"),
    }
}

/// How preparing `source` failed, insisting that it did.
fn failed(source: &str) -> PrepareFailure {
    match compile_program(source, &context()) {
        Ok(prepared) => panic!("expected a failure; it compiled to {:?}", prepared.source),
        Err(failure) => failure,
    }
}

#[test]
fn a_real_ruby_program_compiles_to_javascript_the_guest_can_evaluate() {
    // Ordinary Ruby, exercising what a model actually writes: a class with state, a keyword
    // argument, a block, string interpolation, a chained enumerable. The point is not that any one
    // of them is doubtful — it is that a whole Ruby program, not a subset, survives the crossing to
    // JavaScript.
    let javascript = compiled(
        r#"
class Greeter
  def initialize(name)
    @name = name
  end

  def greet(times: 1)
    times.times.map { |i| "hello #{@name} #{i}" }
  end
end

lines = Greeter.new("gg").greet(times: 4).select { |line| line.include?("1") }
lines.each { |line| puts line }
"#,
    );

    // Opal's own preamble: what comes back is a program for the runtime this arm's guest carries,
    // and it says which Opal wrote it.
    assert!(
        javascript.starts_with("Opal.queue(function(Opal) {"),
        "the compiled program is evaluated against the guest's Opal: {}",
        &javascript[..javascript.len().min(120)],
    );
    assert!(
        javascript.contains(&format!("Generated by Opal {}", compiler_version())),
        "the artifact names the compiler that wrote it",
    );
    // The model's own text survives into the artifact, which is what says a compile happened rather
    // than a copy.
    assert!(
        javascript.contains("hello "),
        "the interpolation's literal half"
    );
    assert!(javascript.contains("'$greet'"), "the method it defined");
    // `enable_source_location` is on, so a program that asks where a method came from is told the
    // truth about ITS OWN file rather than about the JavaScript.
    assert!(
        javascript.contains("$$source_location: ['program.rb', "),
        "methods carry the Ruby file they were written in",
    );
}

#[test]
fn ruby_the_parser_rejects_comes_back_as_the_models_own_error() {
    // A refusal is the only thing Opal can say about a program other than "here is your
    // JavaScript" — Ruby has no compile-time type system — so this is the whole of the model-facing
    // rejection band, and it has to arrive with coordinates in the text the model wrote.
    let failure = failed("x = 1\ny = 2 +* 3\nz = 4\n");
    let PrepareFailure::Program(PrepareError::Syntax(diagnostic)) = &failure else {
        panic!("a Ruby parse failure is the model's own syntax error, not {failure:?}");
    };
    assert!(
        diagnostic.starts_with("program.rb:2:"),
        "located in the model's own file at the model's own line: {diagnostic}",
    );
    assert!(
        diagnostic.contains("y = 2 +* 3"),
        "the offending line is quoted back: {diagnostic}",
    );
    assert!(
        diagnostic.contains("unexpected token"),
        "the compiler's own words, not gg's: {diagnostic}",
    );

    // A block left open reports the end of the file rather than a line inside it, which is right:
    // that is where the parser ran out.
    let failure = failed("def half_written(x)\n  puts x\n");
    let PrepareFailure::Program(PrepareError::Syntax(diagnostic)) = &failure else {
        panic!("an unterminated definition is a syntax error, not {failure:?}");
    };
    assert!(
        diagnostic.contains("program.rb:") && diagnostic.contains("unexpected token"),
        "{diagnostic}",
    );

    // The second shape of refusal, and the reason this band is not simply "a parse error": valid
    // Ruby this compiler has no lowering for. Opal raises it as a `SyntaxError` like the others, and
    // it is right that it lands in the same band — the model's answer to both is to write different
    // Ruby — but it arrives without a line, because nothing in the parser located it.
    let failure = failed("BEGIN { puts 'setup' }\nputs 'body'\n");
    let PrepareFailure::Program(PrepareError::Syntax(diagnostic)) = &failure else {
        panic!("Ruby this compiler cannot lower is still the model's to change, not {failure:?}");
    };
    assert!(
        diagnostic.starts_with("program.rb:") && diagnostic.contains("Unsupported sexp"),
        "the compiler says which construct it has no lowering for: {diagnostic}",
    );
}

#[test]
fn a_compiler_that_cannot_run_is_never_reported_as_the_models_failure() {
    // The misattribution this whole split exists to prevent: a broken image told to the model as
    // "your program did not compile" sends it rewriting something nothing ever read. Each `#[test]`
    // is its own process under nextest, so pointing the interpreter somewhere that does not exist
    // affects nothing else.
    let restore = std::env::var(NODE_ENV).ok();
    // SAFETY: single-threaded test process; nothing else reads the environment concurrently.
    unsafe { std::env::set_var(NODE_ENV, "gg-no-such-interpreter") };
    let failure = failed("puts 'this program is fine'\n");
    match restore {
        // SAFETY: as above.
        Some(value) => unsafe { std::env::set_var(NODE_ENV, value) },
        // SAFETY: as above.
        None => unsafe { std::env::remove_var(NODE_ENV) },
    }

    let PrepareFailure::Toolchain(message) = &failure else {
        panic!("a missing interpreter is a toolchain failure, not {failure:?}");
    };
    assert!(
        message.contains("gg-no-such-interpreter") && message.contains(NODE_ENV),
        "it names what gg looked for and the one variable an operator can fix: {message}",
    );
}

#[test]
fn the_embedded_bundle_says_which_opal_and_which_ruby_it_is() {
    // Both are model- and operator-facing facts that a study records, and both are read off the
    // artifact rather than written down in Rust — which is the point of the manifest.
    assert!(
        compiler_version().starts_with(char::is_numeric),
        "the Opal release is a version: {}",
        compiler_version(),
    );
    assert!(
        ruby_version().starts_with('3'),
        "the Ruby this arm's programs are written in: {}",
        ruby_version(),
    );
}

#[test]
fn compiling_costs_what_it_costs_and_the_second_one_is_not_free() {
    // Not a threshold — a machine's clock is not a contract — but a floor and a ceiling wide enough
    // that only a real change moves them. What this asserts is that compiling a Ruby program is a
    // real, repeated cost: it spawns a process every time, so an arm that reports it as zero would
    // be an arm reporting a compiler it did not run.
    warm();
    let mut timings = Vec::new();
    for _ in 0..3 {
        let started = Instant::now();
        let _ = compiled("puts (1..10).reduce(:+)\n");
        timings.push(started.elapsed());
    }
    for elapsed in &timings {
        assert!(
            elapsed.as_millis() >= 10,
            "a compile that spawns a process cannot take {elapsed:?}",
        );
        assert!(
            *elapsed < COMPILE_TIMEOUT,
            "a compile that took {elapsed:?} would have been killed",
        );
    }
}

/// One of the two things this arm compiles, driven by the
/// [isolation gate](crate::sandbox::language::isolation).
///
/// Both go through [`compile`] and differ only in the file name their diagnostics are located in, so
/// driving each of them separately is what says the *file name* is not somehow shared either.
struct RubyCompile {
    /// `program.rb` or `module.rb`.
    file: &'static str,
}

impl Preparation for RubyCompile {
    fn describe(&self) -> String {
        format!("Ruby {}", self.file)
    }

    /// A program whose marker rides inside a **call**, so no compiler that eliminates dead code can
    /// drop it and leave two preparations looking identical.
    fn source(&self, marker: &str) -> String {
        format!("puts {marker:?}\n")
    }

    fn prepare(&self, source: &str, context: &PrepareContext) -> Result<String, String> {
        if self.file == MODULE_FILE {
            return compile_module(source, context).map_err(|failure| failure.to_string());
        }
        compile(self.file, source, context).map_err(|failure| failure.to_string())
    }
}

#[test]
fn every_ruby_compile_stands_on_ground_no_other_agent_can_reach() {
    // Sixteen at once — `limits.maxParallel`'s ceiling, which is how many agents may be compiling
    // simultaneously in one process. The gate requires every artifact to carry its own marker, to
    // carry nobody else's, and no two preparations to have been handed the same workspace. Opal
    // writes nothing outside the arguments gg gives it,
    // and this is what makes that a measured fact rather than a belief about a toolchain.
    warm();
    for file in [PROGRAM_FILE, MODULE_FILE] {
        let breaches = breaches(&RubyCompile { file });
        assert!(
            breaches.is_empty(),
            "compiling {file} is not isolated per preparation: {}",
            breaches
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join("; "),
        );
    }
}
