//! **Rust** — the first arm whose component is compiled **per turn**, because the program and the
//! artifact are the same object.
//!
//! Everything this arm owns lives here or in one of this module's siblings:
//!
//! * [`compile`] — the host-side `rustc` and the in-process component encode, what they cost, what
//!   they share, and the two failures they tell apart;
//! * [`source`] — what gg writes around a model's Rust, on one line, the one shape it refuses, and
//!   how a code module is declared below the program that reads it;
//! * [`healing`] — the [dialect](crate::healing::Dialect) response healing asks its lexical
//!   questions of, three of whose answers no other arm gives;
//! * [`PROMPT`] — the responses-as-code system prompt and the "nothing shown" notice, both written
//!   in Rust's syntax;
//! * `packages/gg-sandbox-rust/` — the crate a program is compiled against: the SDK, the shell, the
//!   curated library set, and the build that cuts them;
//! * `rust.libraries.tar.gz` and `rust.toolchain.json` — the compiled library set and what built it,
//!   generated by `crates/gg-sandbox-artifacts/rust` into this build's own `OUT_DIR` rather than
//!   committed anywhere, and reached through `GG_ARTIFACTS_RUST`;
//! * the **signature catalogue**, which is the whole of what a model is told about this surface —
//!   reflected out of the SDK's own rustdoc and generated into this build's `OUT_DIR` rather than
//!   committed anywhere (see `crates/gg/build.rs`).
//!
//! # Why this arm has no guest component at all
//!
//! Every arm before it evaluates a **string**. Python's baked component holds a whole CPython,
//! Ruby's holds Opal, the ECMAScript one holds a JavaScript engine, and a program crosses the
//! membrane as source those runtimes read. Rust has no runtime of that kind: `rustc` does not
//! produce a Rust interpreter that later runs a program, it produces the program. There is no
//! artifact of this language that is not one particular program, so there is nothing to bake and
//! nothing a per-process cache could hold.
//!
//! That is the shape the seam grew for. [`PreparedProgram::component`](super::PreparedProgram)
//! carries the bytes a preparation compiled, [`guest_component`](super::ProgramLanguage) answers
//! `None`, and [`program_component`](super::super::engine) is where the two shapes of arm meet. The
//! C++ and Swift arms are the same shape and inherit it.
//!
//! # What a Rust program is, here
//!
//! A **sequence of statements**, as on every arm but PureScript, put inside the body of a function
//! gg declares — because Rust has nowhere else for a statement to live, and because a function body
//! admits everything a Rust author writes: `use`, `struct`, `enum`, `trait`, `impl`, `fn`, `const`,
//! `static`, `mod`, `#[derive(…)]` and even an inner `#![allow(…)]`. See [`source`] for the
//! wrapper, its one line of cost, and the one program gg refuses: one that defines `fn main` and
//! expects gg to call it.
//!
//! The body returns `Result<(), gg::Failure>`, which is what makes `?` the operator a Rust author
//! reaches for against a `Result`-returning SDK. A wrapper returning `()` would make it a hard
//! `E0277` on the first line of the first program of the arm.
//!
//! The surface a program calls is `packages/gg-sandbox-rust`'s SDK, brought into scope by the one
//! `use ::gg::prelude::*;` the wrapper writes — a **glob**, because Rust lets an explicit `use`
//! shadow one and a program's own `use std::fs;` must win over anything gg imported. The surface is
//! **twelve capability modules** plus a thirteenth, `gg::core`, that declares no function and holds
//! the types every other module's signatures name; each module owns the types it produces, so
//! `gg::files::FileRead` is both the key a documentation view is opened by and a path a program can
//! write. Every call hands back `Result<_, ToolError>`, and optional arguments are a struct with a
//! `Default`. What that looks like in full is in `apps/docs/src/content/docs/gg/program-languages.md`.
//!
//! The library set is `std` plus the five crates `packages/gg-sandbox-rust/Cargo.toml` declares
//! under a `# --- heading ---`: `regex`, `serde_json`, `base64`, `itertools` and `indexmap`. Only
//! those and the SDK are named on `--extern`; the transitive closure under them is present, found
//! by `-L dependency=`, and not a name a program may write. The manifest carries the flag, the
//! catalogue's library list is reflected from the same headings, and a test compares the two before
//! compiling a program that uses all five — because a model told it may reach for something the
//! compile does not offer is a turn spent on gg's build.
//!
//! # What this arm has that no other does
//!
//! A guest with **no exception mechanism at all**. `wasm32-unknown-unknown` has no unwinder, so
//! `panic = "unwind"` is not available on it and a panic aborts, which traps the store — and a trap
//! carries no message, no class and no location. What saves the arm's error surface is that a panic
//! *hook* runs before the abort, on a live guest, and can make an ordinary synchronous host call:
//! `gg::program::begin` installs one that completes `feedback.report-error` carrying the panic's
//! message and the model's own line and column. The host half is
//! [`keep_reported_error`](crate::sandbox), which prefers what the program said about itself over
//! the trap that followed it.
//!
//! # And a code module is **linked**, which is why the seam hands a program its modules
//!
//! A code [skill](crate::skills)'s or [memory](crate::memories)'s namespace is bound at `lib::<key>`
//! for every program the agent writes afterwards. On every arm before this one that binding is made
//! at *run time*: the guest is handed each module's prepared source beside the program and evaluates
//! it first. Rust has no such moment — a module is Rust, Rust links, and the only artifact a module
//! can end up in is the artifact of a program that was compiled against it.
//!
//! So the seam hands [`prepare_program`](super::ProgramLanguage::prepare_program) the modules in
//! scope, this arm writes each one beside the entry file, and
//! [`source`](self::source::exports) declares them below the program where they move none of its
//! lines. The consequence a model can see is that `lib::csv_tools::parse` is a **path** rather than
//! a property lookup: a key that does not exist is a diagnostic on the turn that wrote it, where an
//! interpreted arm finds out when the call is reached.
//!
//! A module is compiled **twice**, and that is deliberate rather than an oversight — once alone when
//! it is read, only to be checked, and once as part of every program that uses it. Without the first
//! compile, a module that does not build would take down every program the agent wrote from then on,
//! with the diagnostic landing against the turn's own program in a file the model never saw. See
//! [`compile::compile_module`].

use std::sync::OnceLock;

use test_cabinet_core::gg::GgProgramLanguage;

use crate::sandbox::signatures::SignatureCatalogue;

use super::{
    CodeModule, FileWindow, PrepareContext, PrepareFailure, PreparedModule, PreparedProgram,
    ProgramLanguage, PromptDialect, VIEW_OPEN_DOCS_VIEW, VIEW_OPEN_FILE, spell,
};

#[path = "rust.compile.rs"]
pub(super) mod compile;

#[path = "rust.source.rs"]
pub(super) mod source;

#[path = "rust.healing.rs"]
pub(super) mod healing;

/// This arm's catalogue, reflected out of the SDK's own rustdoc by
/// `packages/gg-sandbox-rust/signatures.sh` — `rustdoc`'s own JSON, read by `tools/signatures.py`.
///
/// It is not committed. `crates/gg/build.rs` runs that reflection as a step of building this
/// crate and this line embeds what it wrote into the build's own `OUT_DIR`, so what a model is
/// told about this arm is reflected out of the SDK sources in this checkout, on the build that
/// compiles the module telling it.
const SIGNATURES: &str = include_str!(concat!(env!("OUT_DIR"), "/signatures/rust.signatures.json"));

/// The parsed catalogue, parsed once per process.
static CATALOGUE: OnceLock<SignatureCatalogue> = OnceLock::new();

/// Everything gg *says* about a Rust program that is written in Rust's own syntax.
///
/// The two templates are embedded from `crates/gg/templates/`, exactly as every other gg prompt is.
/// Individual function spellings are **not** here and not in the templates either: every name and
/// signature they quote is resolved from this language's catalogue when the template
/// renders.
static PROMPT: PromptDialect = PromptDialect {
    system_template: include_str!("../../../templates/system-code.rust.hbs"),
    system_template_name: "system-code.rust",
    nothing_shown_template: include_str!("../../../templates/code-nothing-shown.rust.hbs"),
    nothing_shown_template_name: "code-nothing-shown.rust",
};

/// The one instance of this language. A unit struct, so the `static` costs nothing and coerces
/// straight to `&'static dyn ProgramLanguage`.
pub(super) static RUST: Rust = Rust;

/// Rust: compiled by `rustc` into the wasm component that evaluates it, per turn.
pub(super) struct Rust;

impl ProgramLanguage for Rust {
    fn id(&self) -> GgProgramLanguage {
        GgProgramLanguage::Rust
    }

    fn display_name(&self) -> &'static str {
        GgProgramLanguage::Rust.display_name()
    }

    /// **`::`** — the one arm that does not write `.`, because here a capability module is a Rust
    /// **module** and reaching a function in one is a path rather than a field access.
    ///
    /// It is the difference between a prompt full of `gg::views::open_text` and a prompt full of
    /// `gg::views.open_text`, which on this arm is `E0423: expected value, found module` — so a
    /// model would be taught, in every sentence gg writes about a call, a spelling that cannot
    /// compile.
    fn member_separator(&self) -> &'static str {
        "::"
    }

    /// One `rustc` over the entry file, the modules in scope and the embedded library set, then an
    /// in-process component encode — see [`compile`] for what it costs, what it shares, and how it
    /// tells a program `rustc` refused from a `rustc` that could not run.
    fn prepare_program(
        &self,
        source: &str,
        modules: &[CodeModule],
        context: &PrepareContext,
    ) -> Result<PreparedProgram, PrepareFailure> {
        compile::compile_program(source, modules, context)
    }

    /// `rustc`, which is what a Rust programmer calls the compiler and what its own binary is
    /// called.
    ///
    /// Not `wit-component`, which encodes the module `rustc` emitted into a component and judges
    /// nothing about the program: the same reason the JVM arms name their front end rather than
    /// TeaVM. Naming a checker is also what has this arm's compile
    /// [recorded](crate::sandbox::SandboxOutcome::compile) on every turn, the failing path included
    /// — which matters more here than anywhere, since this is the arm where the compile *is* the
    /// artifact.
    fn checker(&self) -> Option<&'static str> {
        Some("rustc")
    }

    /// Unpack the embedded library set now, so the first code turn does not.
    ///
    /// The whole of this arm's warm-up, and the smallest of any compiled arm's: there is no daemon
    /// to start and no compiler to load, because `rustc` is a one-shot process whose cost is the
    /// compile rather than the start-up. Idempotent and best effort — a failure here is the failure
    /// the first compile makes, and there it is classified, counted and reported as a
    /// [toolchain failure](PrepareFailure::Toolchain).
    fn warm_prepare(&self) {
        compile::warm();
    }

    /// The module's own `rustc`, asked for metadata rather than an artifact — and the names its
    /// namespace offers, read from the author's own source.
    ///
    /// What comes back is **source**, which is what a linked language's module has to be: it is an
    /// input to the [program compile](compile::compile_program) that binds it, not something a guest
    /// could load on its own.
    fn prepare_module(
        &self,
        source: &str,
        context: &PrepareContext,
    ) -> Result<PreparedModule, PrepareFailure> {
        compile::compile_module(source, context)
    }

    /// `.rs`, and nothing else. Nothing else in the registry compiles Rust.
    fn module_file_extensions(&self) -> &'static [&'static str] {
        &["rs"]
    }

    /// [snake_case](self::binding_name) — Rust's own convention for a name a program writes, and
    /// this SDK's for every function it binds.
    fn binding_name(&self, name: &str) -> String {
        binding_name(name)
    }

    /// **None.** This arm has no guest component, because the component *is* the program: see this
    /// module's own documentation, and [`PreparedProgram::component`].
    fn guest_component(&self) -> Option<&'static [u8]> {
        None
    }

    /// This language's catalogue, parsed once and checked to be **this** language's.
    ///
    /// Every registered language's build reflects one of these under its own stem into the one
    /// `OUT_DIR`, and each carries the language it was generated for; checking it here is what stops
    /// a catalogue written — or embedded — under the wrong stem from reaching a model as a system
    /// prompt describing a sandbox nobody has.
    fn catalogue(&self) -> &'static SignatureCatalogue {
        CATALOGUE.get_or_init(|| {
            let catalogue = SignatureCatalogue::parse(SIGNATURES)
                .expect("the generated signature catalogue is valid JSON of the expected shape");
            assert_eq!(
                catalogue.language,
                GgProgramLanguage::Rust,
                "`signatures/rust.signatures.json` was generated for another program language",
            );
            catalogue
        })
    }

    fn healing(&self) -> &'static dyn crate::healing::Dialect {
        &healing::RUST_DIALECT
    }

    fn prompt(&self) -> &'static PromptDialect {
        &PROMPT
    }

    /// [`gg::views::open_file("src/main.rs", …)?;`](self::open_file_statement) — with the window
    /// as the two fields of this arm's options struct.
    fn open_file_statement(&self, path: &str, window: Option<FileWindow>) -> String {
        open_file_statement(&spell(self, VIEW_OPEN_FILE), path, window)
    }

    /// [An array of names and a `for` over it](self::open_docs_views_statement), each iteration
    /// opening one documentation view.
    fn open_docs_views_statement(&self, names: &[&str]) -> String {
        open_docs_views_statement(&spell(self, VIEW_OPEN_DOCS_VIEW), names)
    }

    /// One `pub fn` returning `name` — because this is the third arm whose module shape is not its
    /// program shape, and the first for which the difference is the whole language.
    ///
    /// A program here is a **sequence of statements** and a module is a **file**, and Rust has no
    /// statement at a file's top level: the seam's default subject (this language's generated
    /// documentation program, which opens with a `let`) is not a Rust module at all and is refused
    /// as a syntax error. The `name` rides in as a returned **string literal**, which is where the
    /// module's one export hands it back.
    #[cfg(test)]
    fn isolation_module(&self, name: &str) -> String {
        format!(
            "pub fn marker() -> &'static str {{
    {}
}}
",
            serde_json::Value::String(name.to_string())
        )
    }
}

// ---------------------------------------------------------------------------------------------
// The syntax this arm writes
// ---------------------------------------------------------------------------------------------

/// `csv-tools` → `csv_tools`, `my_helpers.v2` → `my_helpers_v2`, `9lives` → `_9lives`.
///
/// snake_case because that is what Rust spells a name in and what this SDK spells every bound
/// function in, so a program reaching `lib::csv_tools::parse(…)` reads like the rest of its own
/// scope. Any separator — `-`, `.`, or anything a name should not have had — becomes `_`, a run of
/// them becomes one, an upper-case letter is lowered, a name that is nothing but separators becomes
/// `module`, and a leading digit is prefixed.
///
/// It has to be a valid Rust **identifier** for a stronger reason than any other arm's does: on this
/// arm the key is a path segment the compiler resolves (`lib::<key>`), not a string looked up at run
/// time, so a key Rust could not parse would be a program that does not compile rather than a call
/// that fails.
///
/// Deliberately ASCII-only, though Rust identifiers may be Unicode, for the reason every other arm
/// gives: a name a model has to reproduce exactly is one that should have no characters it could get
/// wrong.
pub(super) fn binding_name(name: &str) -> String {
    let mut out = String::new();
    let mut separated = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            if separated && !out.is_empty() {
                out.push('_');
            }
            separated = false;
            out.extend(ch.to_lowercase());
        } else {
            separated = true;
        }
    }
    if out.is_empty() {
        return "module".to_string();
    }
    if out.starts_with(|ch: char| ch.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// `gg::views::open_file("src/main.rs", files::ReadOptions::default())?;`, or the same call with a
/// `files::ReadOptions { offset: Some(400), limit: Some(200) }` for a window — with the call itself
/// already spelled by the language that asked.
///
/// Deliberately the plainest statement that does the job: no binding, no printing. It is synthesized
/// into the agent's own transcript and read by the model as an example of its own output, so
/// anything clever in it is a style the run did not intend to teach. The one thing it *does* teach is
/// the `?`, which is not decoration — a program's body returns `Result<(), Failure>`, and a call
/// whose `Result` went unused would be the model's first example of ignoring a failure.
///
/// The window is the two fields of this arm's options struct, written out rather than left to
/// `..Default::default()`: `files::ReadOptions` has exactly two fields and this statement sets both,
/// so a functional-update tail would be a construction a Rust author would not write.
///
/// The struct is written **module-qualified**, because the prelude re-exports the modules and not
/// the types inside them — a bare `ReadOptions` here would be a statement gg synthesized into the
/// model's own transcript that does not compile.
///
/// The path is rendered through [`serde_json`] so a quote or a backslash in one cannot produce a
/// statement that would not parse: Rust's string literals accept exactly the escapes JSON's do.
pub(super) fn open_file_statement(
    open_file: &str,
    path: &str,
    window: Option<FileWindow>,
) -> String {
    let path = serde_json::Value::String(path.to_string());
    match window {
        Some(window) => format!(
            "{open_file}({path}, files::ReadOptions {{ offset: Some({}), limit: Some({}) }})?;",
            window.offset, window.limit
        ),
        None => format!("{open_file}({path}, files::ReadOptions::default())?;"),
    }
}

/// An array of names and a `for` over it, each iteration opening one documentation view.
///
/// An array and a loop rather than one statement per name because the list is as long as the family
/// — eleven calls written out would be a program a model reads as a style to copy — and an **array**
/// rather than a `Vec` because it is a fixed list of `&'static str` and `vec![]` would allocate for
/// nothing. `for name in functions` iterates it by value, which is what a Rust author writes for an
/// array of `Copy` elements.
///
/// The empty case carries a type annotation, because an empty array literal has no element type to
/// infer and `[]` alone is `E0282`.
pub(super) fn open_docs_views_statement(open_docs_view: &str, names: &[&str]) -> String {
    let entries: Vec<String> = names
        .iter()
        .map(|name| format!("    {}", serde_json::Value::String((*name).to_string())))
        .collect();
    let listed = match entries.is_empty() {
        true => "let functions: [&str; 0] = [];\n".to_string(),
        false => format!("let functions = [\n{},\n];\n", entries.join(",\n")),
    };
    format!("{listed}for name in functions {{\n    {open_docs_view}(name)?;\n}}\n")
}

#[cfg(test)]
#[path = "rust.test.rs"]
mod tests;

/// **The Rust arm's execution substrate**, driven end to end through gg's real compiler, linker,
/// membrane and store.
///
/// A separate test file from any unit tests, because these are a different kind of test: each one
/// runs a real `rustc` and compiles a wasm component, which is tens of milliseconds rather than
/// microseconds, so each test function there drives several programs rather than one. This arm's own
/// hand-pointed copy of the isolation gate is gone, deleted at registration in favour of the
/// [seam's](super::isolation), so nothing here runs sixteen compiles at once any more.
#[cfg(test)]
#[path = "rust.substrate.test.rs"]
mod substrate;

/// **Every Rust example a model is shown, put through `rustc`** — the prompt's, the notice's and the
/// catalogue's.
///
/// A separate file from [`surface`] because it asks a question no other arm can: not whether the
/// call gg quotes exists, which [`crate::prompts`] already gates in every language, but whether the
/// code around it builds. On a compiled arm an example that does not is a whole turn spent on gg's
/// own prose.
#[cfg(test)]
#[path = "rust.examples.test.rs"]
mod examples;

/// **The Rust arm's model-facing surface** — the hand-written SDK, the catalogue reflected out of
/// its own rustdoc, and the libraries this arm says a program may reach.
///
/// A separate file from [`substrate`] because it is a different claim: that one asks whether Rust
/// runs here, this one asks whether what a model is *told* it may write is what the sandbox really
/// has.
#[cfg(test)]
#[path = "rust.surface.test.rs"]
mod surface;
