//! **Rust** — the first arm whose component is compiled **per turn**, because the program and the
//! artifact are the same object.
//!
//! Everything this arm owns lives here or in one of this module's siblings:
//!
//! * [`compile`] — the host-side `rustc` and the in-process component encode, what they cost, what
//!   they share, and the two failures they tell apart;
//! * [`source`] — what gg writes around a model's Rust (nothing), the names a compile is written
//!   under, and the reading of a code module's exports;
//! * `packages/gg-sandbox-rust/` — the crate a program is compiled against: the SDK, the shell, the
//!   curated library set, and the build that cuts them;
//! * `rust.libraries.tar.gz`, `rust.adapter.wasm` and `rust.toolchain.json` — the compiled library
//!   set, the pinned preview1 reactor adapter the encode needs, and what built them, generated by
//!   `crates/gg-sandbox-artifacts/rust` into this build's own `OUT_DIR` rather than committed
//!   anywhere, and reached through `GG_ARTIFACTS_RUST`;
//! * the **signature catalogue**, which is the whole of what a model is told about this surface —
//!   reflected out of the SDK's own rustdoc and generated into this build's `OUT_DIR` rather than
//!   committed anywhere (see `crates/gg/build.rs`).
//!
//! # Why this arm has no guest component at all
//!
//! Every arm before it evaluates a **string**. Python's baked component holds a whole CPython,
//! Ruby's holds Opal, the ECMAScript one holds a JavaScript engine, and a program crosses the
//! membrane as source those runtimes read. Rust has no runtime of that kind: `rustc` does not
//! produce a Rust interpreter that later runs a program, it produces the program. There is no
//! artifact of this language that is not one particular program, so there is nothing to bake and
//! nothing a per-process cache could hold.
//!
//! That is the shape the seam grew for. [`PreparedProgram::component`](super::PreparedProgram)
//! carries the bytes a preparation compiled, [`guest_component`](super::ProgramLanguage) answers
//! `None`, and [`program_component`](super::super::engine) is where the two shapes of arm meet. The
//! C++ and Swift arms are the same shape and inherit it.
//!
//! # What a Rust program is, here
//!
//! A **whole Rust program**: the `use` lines the model wrote and the `fn main` it declared, compiled
//! as a binary crate under the name `program`. gg writes no prologue, no epilogue, no entry point
//! and no import — the file `rustc` reads is the file the model sent, so every diagnostic and every
//! panic is already in the model's own coordinates and there is nothing to correct.
//!
//! `fn main() -> Result<(), gg::Failure>` is the shape to write against a `Result`-returning SDK,
//! because it is what makes `?` compose; a plain `fn main()` is a Rust program too, and there `?` is
//! Rust's own `E0277` rather than anything gg decided. What calls that `main` is
//! `packages/gg-sandbox-rust/src/program.rs`, through the unmangled C entry symbol `rustc` emits for
//! a binary crate — so the world's `run` export lives in the SDK's rlib and appears in no source a
//! model reads. See [`compile`] for why the crate type is the whole trick.
//!
//! The surface a program calls is `packages/gg-sandbox-rust`'s SDK, reached through `--extern gg=…`
//! — which is packaging on the same terms a jar on a classpath is, and puts **no name** in a
//! program's own scope. A call is written in full (`gg::files::read_file(…)`) or under a line the
//! program wrote (`use gg::files;`, then `files::read_file(…)`). The surface is
//! **twelve capability modules** plus a thirteenth, `gg::core`, that declares no function and holds
//! the types every other module's signatures name; each module owns the types it produces, so
//! `gg::files::FileRead` is both the key a documentation view is opened by and a path a program can
//! write. Every call hands back `Result<_, core::ApiError>`, and optional arguments are a struct
//! with a `Default`. What that looks like in full is in
//! `apps/docs/src/content/docs/gg/languages/rust.md`.
//!
//! The library set is `std` plus the five crates `packages/gg-sandbox-rust/Cargo.toml` declares
//! under a `# --- heading ---`: `regex`, `serde_json`, `base64`, `itertools` and `indexmap`. Only
//! those and the SDK are named on `--extern`; the transitive closure under them is present, found
//! by `-L dependency=`, and not a name a program may write. The manifest carries the flag, the
//! catalogue's library list is reflected from the same headings, and a test compares the two before
//! compiling a program that uses all five — because a model told it may reach for something the
//! compile does not offer is a turn spent on gg's build.
//!
//! # How a failure reaches the model
//!
//! By **capture**, with nothing intercepted. There is no panic hook, no catch chain and no reporting
//! call anywhere in this arm's SDK: the program dies the way its runtime kills it and gg reads what
//! the runtime wrote.
//!
//! `wasm32-wasip1` is what buys that. It gives the guest a real standard error, which
//! [`membrane`](crate::sandbox) wires, so a panic arrives as `std`'s own sentence —
//! `thread 'main' (1) panicked at program.rs:6:5:` — in the model's own file at the model's own line
//! and column. A `main` returning `Err` has `std`'s `Termination` write `Error: …` before the shell
//! propagates the status, and an explicit `std::process::exit` is `proc_exit`, which reaches gg as
//! an `I32Exit`. `packages/gg-sandbox-rust/rust-version.sh` carries the measurement behind the
//! target.
//!
//! # And a code module is **linked**, which is why the seam hands a program its modules
//!
//! A code [skill](crate::skills)'s or [memory](crate::memories)'s Rust is a **crate of its own**,
//! built into an `.rlib` and named to the program's compiler on `--extern <key>=…` — the same
//! packaging the SDK arrives by, and it puts no name in the program's scope. The model writes
//! `csv_tools::parse(…)`, or a `use csv_tools::parse;` of its own, and gg writes nothing into the
//! program. On every arm before this one the binding is made at *run time*: the guest is handed each
//! module's prepared source beside the program and evaluates it first. Rust has no such moment, so
//! the seam hands [`prepare_program`](super::ProgramLanguage::prepare_program) the modules in scope
//! and this arm compiles them.
//!
//! The consequence a model can see is that `csv_tools::parse` is a **path** rather than a property
//! lookup: a key or a name that does not exist is a diagnostic on the turn that wrote it, where an
//! interpreted arm finds out when the call is reached.
//!
//! A module is compiled **twice**, and that is deliberate rather than an oversight — once alone at
//! the read, and once inside every preparation that links it, because a workspace belongs to one
//! preparation and the `.rlib` goes with it. The first compile is what puts a module author's
//! diagnostic at the read instead of against somebody else's program two turns later. See
//! [`compile::compile_module`] and [`compile`] for what the rebuild costs.

use std::sync::OnceLock;

use test_cabinet_core::gg::GgProgramLanguage;

use crate::sandbox::signatures::SignatureCatalogue;

use self::source::SDK_CRATE;
use super::{
    CodeModule, FileWindow, PrepareContext, PrepareFailure, PreparedModule, PreparedProgram,
    ProgramLanguage, spell,
};
use crate::docs::MAX_SEARCH_LIMIT;
use crate::sandbox::operations::{DOCS_SEARCH, VIEWS_OPEN_DOCS_VIEW, VIEWS_OPEN_FILE};

#[path = "rust.compile.rs"]
pub(super) mod compile;

#[path = "rust.source.rs"]
pub(super) mod source;

/// This arm's catalogue, reflected out of the SDK's own rustdoc by
/// `packages/gg-sandbox-rust/signatures.sh` — `rustdoc`'s own JSON, read by `tools/signatures.py`.
///
/// It is not committed. `crates/gg/build.rs` runs that reflection as a step of building this
/// crate and this line embeds what it wrote into the build's own `OUT_DIR`, so what a model is
/// told about this arm is reflected out of the SDK sources in this checkout, on the build that
/// compiles the module telling it.
const SIGNATURES: &str = include_str!(concat!(env!("OUT_DIR"), "/signatures/rust.signatures.json"));

/// The parsed catalogue, parsed once per process.
static CATALOGUE: OnceLock<SignatureCatalogue> = OnceLock::new();

/// The one instance of this language. A unit struct, so the `static` costs nothing and coerces
/// straight to `&'static dyn ProgramLanguage`.
pub(super) static RUST: Rust = Rust;

/// Rust: compiled by `rustc` into the wasm component that evaluates it, per turn.
pub(super) struct Rust;

impl ProgramLanguage for Rust {
    fn id(&self) -> GgProgramLanguage {
        GgProgramLanguage::Rust
    }

    fn display_name(&self) -> &'static str {
        GgProgramLanguage::Rust.display_name()
    }

    /// **`::`** — the one arm that does not write `.`, because here a capability module is a Rust
    /// **module** and reaching a function in one is a path rather than a field access.
    ///
    /// It is the difference between a prompt full of `gg::views::open_text` and a prompt full of
    /// `gg::views.open_text`, which on this arm is `E0423: expected value, found module` — so a
    /// model would be taught, in every sentence gg writes about a call, a spelling that cannot
    /// compile.
    fn member_separator(&self) -> &'static str {
        "::"
    }

    /// One `rustc` over the entry file, the modules in scope and the embedded library set, then an
    /// in-process component encode — see [`compile`] for what it costs, what it shares, and how it
    /// tells a program `rustc` refused from a `rustc` that could not run.
    fn prepare_program(
        &self,
        source: &str,
        modules: &[CodeModule],
        context: &PrepareContext,
    ) -> Result<PreparedProgram, PrepareFailure> {
        compile::compile_program(source, modules, context)
    }

    /// `rustc`, which is what a Rust programmer calls the compiler and what its own binary is
    /// called.
    ///
    /// Not `wit-component`, which encodes the module `rustc` emitted into a component and judges
    /// nothing about the program: the same reason the JVM arms name their front end rather than
    /// TeaVM. Naming a checker is also what has this arm's compile
    /// [recorded](crate::sandbox::SandboxOutcome::compile) on every turn, the failing path included
    /// — which matters more here than anywhere, since this is the arm where the compile *is* the
    /// artifact.
    fn checker(&self) -> Option<&'static str> {
        Some("rustc")
    }

    /// Unpack the embedded library set now, so the first code turn does not.
    ///
    /// The whole of this arm's warm-up, and the smallest of any compiled arm's: there is no daemon
    /// to start and no compiler to load, because `rustc` is a one-shot process whose cost is the
    /// compile rather than the start-up. Idempotent and best effort — a failure here is the failure
    /// the first compile makes, and there it is classified, counted and reported as a
    /// [toolchain failure](PrepareFailure::Toolchain).
    fn warm_prepare(&self) {
        compile::warm();
    }

    /// The module's own `rustc`, asked for metadata rather than an artifact — and the names its
    /// namespace offers, read from the author's own source.
    ///
    /// What comes back is **source**, which is what a linked language's module has to be: it is an
    /// input to the [program compile](compile::compile_program) that binds it, not something a guest
    /// could load on its own.
    fn prepare_module(
        &self,
        source: &str,
        context: &PrepareContext,
    ) -> Result<PreparedModule, PrepareFailure> {
        compile::compile_module(source, context)
    }

    /// `.rs`, and nothing else. Nothing else in the registry compiles Rust.
    fn module_file_extensions(&self) -> &'static [&'static str] {
        &["rs"]
    }

    /// [snake_case](self::binding_name) — Rust's own convention for a name a program writes, and
    /// this SDK's for every function it binds.
    fn binding_name(&self, name: &str) -> String {
        binding_name(name)
    }

    /// **`<key>::<name>`** — a path rooted at the module's own crate, because that is what a module
    /// is here.
    ///
    /// The seam's default roots it at `lib`, which on this arm would name a crate nothing supplies.
    /// A module arrives on `--extern <key>=…`, exactly as gg's SDK arrives on `--extern gg=…`, so
    /// the key is the first segment a program writes and there is nothing above it.
    fn lib_access(&self, key: &str) -> String {
        format!("{key}{}{}", self.member_separator(), super::LIB_ACCESS_NAME)
    }

    /// **None**, because this arm reaches gg's own SDK with no line either.
    ///
    /// `--extern` puts a crate in the **extern prelude**, which makes the name reachable and puts
    /// nothing in the program's own scope: `csv_tools::parse(…)` resolves from a program's first
    /// line, exactly as `gg::files::read_file(…)` does. A program that would rather write
    /// `use csv_tools::parse;` first may, and that line is the program's own choice rather than
    /// something the surface requires of it — quoting one here would tell a model a line is needed
    /// when none is.
    fn lib_import(&self, _key: &str) -> Option<String> {
        None
    }

    /// **None.** This arm has no guest component, because the component *is* the program: see this
    /// module's own documentation, and [`PreparedProgram::component`].
    fn guest_component(&self) -> Option<&'static [u8]> {
        None
    }

    /// This language's catalogue, parsed once and checked to be **this** language's.
    ///
    /// Every registered language's build reflects one of these under its own stem into the one
    /// `OUT_DIR`, and each carries the language it was generated for; checking it here is what stops
    /// a catalogue written — or embedded — under the wrong stem from reaching a model as a system
    /// prompt describing a sandbox nobody has.
    fn catalogue(&self) -> &'static SignatureCatalogue {
        CATALOGUE.get_or_init(|| {
            let catalogue = SignatureCatalogue::parse(SIGNATURES)
                .expect("the generated signature catalogue is valid JSON of the expected shape");
            assert_eq!(
                catalogue.language,
                GgProgramLanguage::Rust,
                "`signatures/rust.signatures.json` was generated for another program language",
            );
            catalogue
        })
    }

    /// [`gg::views::open_file("src/main.rs", …)?;`](self::open_file_statement) — with the window
    /// as two of the three fields of this arm's options struct.
    fn open_file_statement(&self, path: &str, window: Option<FileWindow>) -> String {
        open_file_statement(&spell(self, VIEWS_OPEN_FILE), path, window)
    }

    /// [The `fn main` those calls live in](self::open_file_program), which is what a statement list
    /// is not on this arm.
    ///
    /// A model reads this out of its own transcript as an example of its own output, and a Rust file
    /// has nowhere for a statement to live outside a function — so a statement list would be
    /// teaching a shape `rustc` answers with `error[E0601]: main function not found`.
    fn open_file_program(&self, views: &[(&str, Option<FileWindow>)]) -> String {
        open_file_program(&spell(self, VIEWS_OPEN_FILE), views)
    }

    /// [An array of names and a `for` over it](self::open_docs_views_statement), each iteration
    /// opening one documentation view — inside the `fn main` this language has nowhere else to put
    /// a statement than.
    fn open_docs_views_statement(&self, names: &[&str]) -> String {
        open_docs_views_statement(&spell(self, VIEWS_OPEN_DOCS_VIEW), names)
    }

    /// [One `fn main` holding one search, one array and one `for` loop, each call composed with
    /// `?`](self::bootstrap_program), with both paths resolved from this language's own catalogue.
    fn bootstrap_program(&self, modules: &[&str], docs: &[&str]) -> String {
        bootstrap_program(
            &spell(self, DOCS_SEARCH),
            &spell(self, VIEWS_OPEN_DOCS_VIEW),
            modules,
            docs,
        )
    }

    /// One `pub fn` returning `name` — because this arm's module shape is not its program shape.
    ///
    /// A program here is a whole binary crate and a module is a **file of items**: the seam's default
    /// subject is this language's generated documentation program, which declares `fn main`, and a
    /// code module that declared one would be an entry point in a file nothing runs. The `name`
    /// rides in as a returned **string literal**, which is where the module's one export hands it
    /// back.
    #[cfg(test)]
    fn gate_module(&self, name: &str) -> String {
        format!(
            "pub fn marker() -> &'static str {{
    {}
}}
",
            serde_json::Value::String(name.to_string())
        )
    }
}

// ---------------------------------------------------------------------------------------------
// The syntax this arm writes
// ---------------------------------------------------------------------------------------------

/// `csv-tools` → `csv_tools`, `my_helpers.v2` → `my_helpers_v2`, `9lives` → `_9lives`.
///
/// snake_case because that is what Rust spells a name in and what this SDK spells every bound
/// function in, so a program reaching `csv_tools::parse(…)` reads like the rest of its own scope.
/// Any separator — `-`, `.`, or anything a name should not have had — becomes `_`, a run of them
/// becomes one, an upper-case letter is lowered, a name that is nothing but separators becomes
/// `module`, and a leading digit is prefixed.
///
/// It has to be a valid Rust **identifier** for a stronger reason than any other arm's does: on this
/// arm the key is a **crate name** the compiler resolves a path from, not a string looked up at run
/// time, so a key Rust could not parse would be a program that does not compile rather than a call
/// that fails.
///
/// A key that would name a crate the compile already has takes the same leading underscore a keyword
/// does — the SDK, every crate in the shipped [library set](compile::library_crate_names), the
/// program's own crate name and the [sysroot crates](SYSROOT) a program reaches without asking.
/// Handing `std` or `gg` to `--extern` would either shadow a crate a model was told it may write or
/// leave `rustc` choosing between two candidates for one name, and both fail a program that is
/// correct.
///
/// Deliberately ASCII-only, though Rust identifiers may be Unicode, for the reason every other arm
/// gives: a name a model has to reproduce exactly is one that should have no characters it could get
/// wrong.
pub(super) fn binding_name(name: &str) -> String {
    let mut out = String::new();
    let mut separated = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            if separated && !out.is_empty() {
                out.push('_');
            }
            separated = false;
            out.extend(ch.to_lowercase());
        } else {
            separated = true;
        }
    }
    if out.is_empty() {
        return "module".to_string();
    }
    if out.starts_with(|ch: char| ch.is_ascii_digit()) || is_taken(&out) {
        out.insert(0, '_');
    }
    out
}

/// Whether `key` is a word this arm cannot bind a module under.
fn is_taken(key: &str) -> bool {
    RESERVED.contains(&key)
        || SYSROOT.contains(&key)
        || key == source::CRATE_NAME
        || compile::library_crate_names().any(|library| library == key)
}

/// The crates the sysroot puts in front of every program: a module bound under one of these names
/// would take the standard library's place in the extern prelude.
const SYSROOT: [&str; 5] = ["std", "core", "alloc", "proc_macro", "test"];

/// Every word `rustc` refuses as a path segment: the 2021 edition's strict keywords and the ones it
/// reserves for later.
///
/// `crate`, `self`, `super` and `Self` are among them and are the sharpest of the set — each parses
/// and means something else entirely, so a module bound at one would resolve to somewhere other than
/// the module. The weak keywords (`macro_rules`, `union`, `raw`) are absent: each is a legal
/// identifier.
const RESERVED: [&str; 51] = [
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "crate",
    "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "if", "impl", "in",
    "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
    "unsafe", "unsized", "use", "virtual", "where", "while", "yield", "gen",
];

/// `gg::views::open_file("src/main.rs", gg::views::ViewOptions::default())?;`, or the same call with
/// a `gg::views::ViewOptions { offset: Some(400), limit: Some(200), ..Default::default() }` for a
/// window — with the call itself already spelled by the language that asked.
///
/// Deliberately the plainest statement that does the job: no binding, no printing. It is synthesized
/// into the agent's own transcript and read by the model as an example of its own output, so
/// anything clever in it is a style the run did not intend to teach. The one thing it *does* teach is
/// the `?`, which is not decoration — the `fn main` it lives in returns `Result<(), gg::Failure>`,
/// and a call whose `Result` went unused would be the model's first example of ignoring a failure.
///
/// The window is two of the three fields of this arm's options struct, and the third — the cut a
/// view's long lines get — is left to a `..Default::default()` tail: `gg::views::ViewOptions` has a
/// field this statement does not set, and writing `max_line_chars: None` out beside two `Some`s is
/// a construction a Rust author would not write where the language's own idiom for "the rest as
/// default" exists.
///
/// The struct is written **in full**, `gg::` and all, for the reason every synthesized call is: gg
/// writes no `use` line into a program and there is none above this statement, so a bare
/// `ViewOptions` — or a module-qualified `views::ViewOptions` — would be a text gg put in the
/// model's own transcript that does not compile.
///
/// The path is rendered through [`serde_json`] so a quote or a backslash in one cannot produce a
/// statement that would not parse: Rust's string literals accept exactly the escapes JSON's do.
pub(super) fn open_file_statement(
    open_file: &str,
    path: &str,
    window: Option<FileWindow>,
) -> String {
    let path = serde_json::Value::String(path.to_string());
    let options = format!("{SDK_CRATE}::views::ViewOptions");
    match window {
        Some(window) => format!(
            "{open_file}({path}, {options} {{ offset: Some({}), limit: Some({}), \
             ..Default::default() }})?;",
            window.offset, window.limit
        ),
        None => format!("{open_file}({path}, {options}::default())?;"),
    }
}

/// A whole program: an array of names and a `for` over it, each iteration opening one documentation
/// view.
///
/// A **whole program** rather than a statement list, because Rust has nowhere for a statement to
/// live outside a function body — and because that is what the seam asks for anyway: the on-use
/// script of every [built-in family skill](crate::skills) is a program that is prepared and run.
///
/// An array and a loop rather than one statement per name because the list is as long as the family
/// — eleven calls written out would be a program a model reads as a style to copy — and an **array**
/// rather than a `Vec` because it is a fixed list of `&'static str` and `vec![]` would allocate for
/// nothing. `for name in functions` iterates it by value, which is what a Rust author writes for an
/// array of `Copy` elements.
///
/// The empty case carries a type annotation, because an empty array literal has no element type to
/// infer and `[]` alone is `E0282`.
pub(super) fn open_docs_views_statement(open_docs_view: &str, names: &[&str]) -> String {
    main_program(&open_docs_views_body(open_docs_view, names))
}

/// The array and the `for` that [`open_docs_views_statement`] wraps a `fn main` around, as a body a
/// statement can be written above — which is what the [opening turn](bootstrap_program) does with
/// it, so the loop a model reads there is character for character the one every other program gg
/// writes on this arm shows it.
fn open_docs_views_body(open_docs_view: &str, names: &[&str]) -> String {
    let entries: Vec<String> = names
        .iter()
        .map(|name| format!("        {}", serde_json::Value::String((*name).to_string())))
        .collect();
    let listed = match entries.is_empty() {
        true => "    let functions: [&str; 0] = [];\n".to_string(),
        false => format!("    let functions = [\n{},\n    ];\n", entries.join(",\n")),
    };
    format!(
        "{listed}\
         \x20   for name in functions {{\n\
         \x20       {open_docs_view}(name)?;\n\
         \x20   }}\n"
    )
}

/// A whole program that opens one file view per entry of `views`: a `fn main` and one call in the
/// order given.
///
/// The seam's default is the statement list, and this arm cannot take it: a Rust file has nowhere
/// for a statement to live outside a function body, so what gg pushes into the transcript has to be
/// a program the model really could have sent. Each call is written by [`open_file_statement`], so
/// the one place a file-view call is spelled stays one place.
pub(super) fn open_file_program(open_file: &str, views: &[(&str, Option<FileWindow>)]) -> String {
    let calls: String = views
        .iter()
        .map(|(path, window)| format!("    {}\n", open_file_statement(open_file, path, *window)))
        .collect();
    main_program(&calls)
}

/// The `fn main` every program gg synthesizes for this arm is written as, around `body`.
///
/// `Result<(), gg::Failure>` rather than `()`, because every call in every body gg writes is
/// composed with `?` — and because it is the shape this arm's prompt tells a model to write, so a
/// program in the model's own transcript that used a different one would be teaching against it.
///
/// It writes **no `use` line**, and that is not an omission: every call gg synthesizes is spelled in
/// full out of the catalogue (`gg::views::open_file`), which `--extern gg=…` makes reachable with no
/// line at all. A `use` gg wrote here would be gg teaching an import the program does not need.
fn main_program(body: &str) -> String {
    format!("fn main() -> Result<(), {SDK_CRATE}::Failure> {{\n{body}    Ok(())\n}}\n")
}

/// The opening turn: **one** search listing every module the agent holds, then the array of
/// documentation keys and a `for` over it, each call composed with `?`.
///
/// One call rather than one per module, because a `modules` filter is a **union**: the modules a
/// run granted come back as a single directory, so the shape a model reads first — and the shape it
/// will copy — is one call carrying a list rather than a loop asking the same question a module at
/// a time. It carries no query at all, because a module filter alone *is* the directory and a word
/// beside it would narrow the very listing this is here to open, and it asks for
/// [`MAX_SEARCH_LIMIT`], because the whole of a module is the point rather than its first page.
///
/// The list is written **inline in the call**, unlike the keys below it: it is the agent's `files`
/// and `shell` and nothing else, so a binding above the call would name two strings once each. The
/// keys keep their array and their `for` — and their type annotation when they are none — for the
/// reasons [`open_docs_views_statement`] gives.
///
/// An agent that holds neither module gets the search **left out entirely** rather than written
/// with an empty list: nothing to look for and nothing to look in is `invalid-argument`, so that
/// call would open the session with a failure and with a worked example of the shape that failed.
///
/// A call with two or more optional arguments takes an **options struct with a `Default`, filled in
/// with functional-update syntax**, which is this language's idiom and the one its SDK declares.
///
/// Every call returns a `Result` and every one is propagated with `?`, which is this arm's failure
/// model: a bootstrap that unwrapped, or ignored, what a call handed back would be a worked example
/// of the two things this language's programs are written not to do.
pub(super) fn bootstrap_program(
    search: &str,
    open_docs_view: &str,
    modules: &[&str],
    docs: &[&str],
) -> String {
    let views = open_docs_views_body(open_docs_view, docs);
    if modules.is_empty() {
        return main_program(&views);
    }
    let listed: Vec<String> = modules
        .iter()
        .map(|path| serde_json::Value::String((*path).to_string()).to_string())
        .collect();
    let options = format!("{}::SearchOptions", module_of(search));
    let listing = format!(
        "    {search}({options} {{\n\
         \x20       modules: &[{}],\n\
         \x20       limit: Some({MAX_SEARCH_LIMIT}),\n\
         \x20       ..Default::default()\n\
         \x20   }})?;\n",
        listed.join(", ")
    );
    main_program(&format!("{listing}\n{views}"))
}

/// The module a fully-qualified call is filed under, taken off the front of the call itself.
///
/// The one thing gg has to write here that is a **type** rather than a call, and it is derived from
/// the call rather than written down beside it so the two cannot disagree: this SDK declares a
/// call's options struct in the module the call itself lives in. Every catalogued name is
/// module-qualified — the name rule (`signatures.fqn.rs`) is what makes that true on every arm — so
/// a call that somehow carried no qualifier is used as its own module rather than crashing a turn.
fn module_of(call: &str) -> &str {
    call.rsplit_once("::").map_or(call, |(module, _)| module)
}

#[cfg(test)]
#[path = "rust.test.rs"]
mod tests;

/// **The Rust arm's execution substrate**, driven end to end through gg's real compiler, linker,
/// membrane and store.
///
/// A separate test file from any unit tests, because these are a different kind of test: each one
/// runs a real `rustc` and compiles a wasm component, which is tens of milliseconds rather than
/// microseconds, so each test function there drives several programs rather than one. This arm's own
/// hand-pointed copy of the isolation gate is gone, deleted at registration in favour of the
/// [seam's](super::isolation), so nothing here runs sixteen compiles at once any more.
#[cfg(test)]
#[path = "rust.substrate.test.rs"]
mod substrate;

/// **Every Rust example a model is shown, put through `rustc`** — the prompt's, the notice's and the
/// catalogue's.
///
/// A separate file from [`surface`] because it asks a question no other arm can: not whether the
/// call gg quotes exists, which [`crate::prompts`] already gates in every language, but whether the
/// code around it builds. On a compiled arm an example that does not is a whole turn spent on gg's
/// own prose.
#[cfg(test)]
#[path = "rust.examples.test.rs"]
mod examples;

/// **The Rust arm's model-facing surface** — the hand-written SDK, the catalogue reflected out of
/// its own rustdoc, and the libraries this arm says a program may reach.
///
/// A separate file from [`substrate`] because it is a different claim: that one asks whether Rust
/// runs here, this one asks whether what a model is *told* it may write is what the sandbox really
/// has.
#[cfg(test)]
#[path = "rust.surface.test.rs"]
mod surface;
