//! **Swift** — the second arm whose component is compiled **per turn**, and the only one whose
//! program is compiled *verbatim*.
//!
//! Everything this arm owns lives here or in one of this module's siblings:
//!
//! * [`compile`] — the host-side `swiftc`, the in-process component encode with the preview1
//!   adapter, what they cost, what they share, and the two failures they tell apart;
//! * [`source`] — the one word gg writes, which is not a wrapper around a program but the `public`
//!   a **code module**'s own declarations need to cross a module boundary;
//! * [`mask`] — the byte-level code mask and identifier lexing [`source`] reads;
//! * `packages/gg-sandbox-swift/` — the SDK a program calls, the shell it is compiled beside, the
//!   curated library set, and the build that cuts them;
//! * `swift.guest.tar.gz`, `swift.libraries.tar.gz`, `swift.adapter.wasm` and
//!   `swift.toolchain.json` — the compile inputs, the library set, the adapter, and what built them,
//!   generated by `crates/gg-sandbox-artifacts/swift` into this build's own `OUT_DIR` rather than
//!   committed anywhere, and reached through `GG_ARTIFACTS_SWIFT`;
//! * the **signature catalogue**, which is the whole of what a model is told about this surface —
//!   reflected out of the SDK's own documentation comments and generated into this build's
//!   `OUT_DIR` rather than committed anywhere (see `crates/gg/build.rs`).
//!
//! # What a Swift program calls, and how it is in scope
//!
//! The surface is divided into **thirteen capability modules**, and each is a caseless `enum` —
//! Swift's own namespace inside a module — so `files.readFile("src/main.swift")` is a call on a
//! namespace and nothing is constructed first. A caseless `enum` rather than that many real Swift
//! modules behind an `@_exported` umbrella: the umbrella was measured and does re-export
//! transitively, but a module of its own would have to be called `GgFiles` where the whole scheme's
//! vocabulary is `files`, and a program whose own `let files` shadowed it would be shadowing the
//! same name either way. The fully qualified `gg.files.readFile` is the escape from that shadowing,
//! and it is a real path a program may write, which is why it is the name this arm catalogues.
//!
//! Every call **throws**, so `try` is the whole of the ceremony and a failure is an ordinary Swift
//! `Error` a `catch` branches on. Optional arguments are **default values**, required ones are
//! positional, and everything whose role the function's name does not already carry has an
//! **argument label** — `files.editFile("a", replacing: "x", with: "y")`,
//! `delegation.sendMessage("note", to: id)`. A value a call hands back may carry the call that
//! belongs to it: `handle.send(…)`, `view.close()`, `hit.read()`.
//!
//! It is reached through **one line the program writes**, and that line is
//! [`import gg`](SURFACE_IMPORT). The SDK is compiled ahead of time into a Swift module called `gg`,
//! and what the compile supplies is the `-I` that resolves it — packaging, which tells the compiler
//! the module exists and puts no name in scope. A reply that writes no import reaches nothing gg
//! carries, and `swift.surface.test.rs` asks `swiftc` to say so. A separate module is also what
//! makes the SDK **shadowable**: a program that declares its own `files` or its own `DirEntry`
//! wins, where source compiled into the program's own module would be a redeclaration error on the
//! model's own line.
//!
//! The library set is the Swift standard library, the modules the Swift SDK for WebAssembly ships
//! (Foundation and its companions, `RegexBuilder`, `Synchronization`, `Observation`, `WASILibc`) and
//! three vendored packages — swift-collections, swift-algorithms and swift-numerics — compiled into
//! one static archive. A static archive is why they cost nothing: the linker pulls members, so an
//! artifact for a program that imports none of them is byte for byte the size of one built without
//! the archive at all. `packages/gg-sandbox-swift/libraries.txt` is the one declaration, and
//! `swift.surface.test.rs` compiles a program that imports every module in it.
//!
//! # Why this arm has no guest component
//!
//! For the reason [Rust](super::rust) has none. Every arm before those two evaluates a **string**:
//! Python's baked component holds a whole CPython, Ruby's holds Opal, the ECMAScript one holds
//! a JavaScript engine, and a program crosses the membrane as source those runtimes read. `swiftc`
//! does not produce a Swift interpreter that later runs a program; it produces the program, and
//! that module *is* the component. There is no artifact of this language that is not one particular
//! program, so there is nothing to bake and nothing a per-process cache could hold.
//!
//! # What a Swift program is, here
//!
//! **The model's reply, unaltered, as a top-level Swift file.** Not a function body, not a
//! declaration list, and not anything gg wrapped: the bytes the model wrote are the bytes `swiftc`
//! reads — its own `import gg` on line 1 included — so a diagnostic at line 7 is line 7 and there
//! is no offset to subtract anywhere in this arm.
//!
//! That is forced rather than chosen. Swift refuses `extension`, `protocol` and `import` inside a
//! function body, so the wrapper the Rust arm uses — and that every statement-shaped arm before it
//! uses — would forbid three things a Swift author writes without thinking, one of which
//! (`extension`) is what the language is built around. A top-level file is the only Swift context
//! that admits declarations and bare statements together.
//!
//! What makes it work is that gg's shell is a second file of the **same module**: Swift lowers a
//! top-level file's statements into the target's C entry point, and the shell, sharing the module,
//! names that symbol and calls it from the `run` export. The shell's own two `import` lines are
//! file-scoped, so nothing they name is in scope in the reply. See [`compile`].
//!
//! # What this arm has that no other does
//!
//! A guest whose failures **cannot be caught by anything inside it**. The Rust arm has no unwinder
//! either, but it has a panic *hook* — a function that runs on a live guest before the abort and
//! can complete an ordinary `feedback.report-error` first. Swift has no equivalent, and its
//! top-level code is not a `throws` context a shell can wrap, so an uncaught error, a `fatalError`,
//! a force-unwrapped `nil`, an index out of range and an arithmetic overflow all end as a **trap**.
//!
//! What keeps those from being opaque is not what anyone would guess. Swift at `-Osize` does not
//! *print* its runtime failures: the optimiser replaces the report with a bare `unreachable` and
//! encodes the message in the **debug information**, as the name of a synthetic inlined frame. So
//! the artifact is compiled with `-g`, gg's engine symbolicates a trap's frames, and a model reads
//!
//! ```text
//! Swift runtime failure: Index out of range
//!   … at /gg/work/main.swift:3:22
//! ```
//!
//! — the message and its own line, for a failure it could not have caught. Without the debug
//! information the same program says `program.wasm!main` and nothing else. See
//! [`compile::DEBUG_INFO`](self::compile) for the measurement, and for what those sections record
//! about the environment they were produced in.
//!
//! One failure is the exception and is worth naming, because it is the opposite of the one above:
//! an **uncaught throw** arrives with gg's own sentence and *no line at all*. The runtime hands the
//! error to `swift_errorInMain` from the entry point's synthesized epilogue, so the only frames left
//! are `/<compiler-generated>` and there is nothing to symbolicate. Catching what you expect is what
//! buys the line back. Measured in `swift.surface.test.rs`.
//!
//! # And a code module is **a module**, which is why the seam hands a program its modules
//!
//! A code [skill](crate::skills)'s or [memory](crate::memories)'s code is available to every program
//! the agent writes afterwards. On every interpreted arm that is made at *run time*: the guest is
//! handed each module's prepared source beside the program and evaluates it first. Swift has no such
//! moment — a module is Swift, Swift links, and the only artifact a module can end up in is the
//! artifact of a program that was compiled against it.
//!
//! So the seam hands [`prepare_program`](super::ProgramLanguage::prepare_program) the modules in
//! scope, and each is built into a **Swift module named for the key it is bound under**, which the
//! program's own compile resolves through an `-I` and links the object of. That is the mechanism
//! this arm supplies [its own SDK](SURFACE_MODULE) through, so the line a program writes to reach an
//! author's module is the line it writes to reach gg's — [`import csvTools`](Swift::lib_import), and
//! then `csvTools.parse(…)`. A program that writes no such line reaches nothing the module carries.
//! See [`source`] for the `public` gg writes into a module's own file, which is the whole of what it
//! writes there.
//!
//! A module is compiled **twice**, and that is deliberate rather than an oversight — once alone when
//! it is read, only to be checked, and once as its own module beside every program that uses it.
//! Without the first compile, a module that does not build would take down every program the agent
//! wrote from then on, with the diagnostic landing against the turn's own program in a file the model
//! never saw. See [`compile::compile_module`].

use std::sync::OnceLock;

use test_cabinet_core::gg::GgProgramLanguage;

use crate::sandbox::signatures::SignatureCatalogue;

use super::{
    CodeModule, FileWindow, LIB_ACCESS_NAME, PrepareContext, PrepareFailure, PreparedModule,
    PreparedProgram, ProgramLanguage, spell,
};
use crate::docs::MAX_SEARCH_LIMIT;
use crate::sandbox::operations::{DOCS_SEARCH, VIEWS_OPEN_DOCS_VIEW, VIEWS_OPEN_FILE};

#[path = "swift.compile.rs"]
pub(super) mod compile;

#[path = "swift.source.rs"]
pub(super) mod source;

#[path = "swift.mask.rs"]
pub(super) mod mask;

/// This arm's catalogue, reflected out of the SDK's own documentation comments by
/// `packages/gg-sandbox-swift/signatures.sh` — `swiftc -emit-symbol-graph`, which is DocC's own
/// machinery.
///
/// It is not committed. `crates/gg/build.rs` runs that reflection as a step of building this
/// crate and this line embeds what it wrote into the build's own `OUT_DIR`, so what a model is
/// told about this arm is reflected out of the SDK sources in this checkout, on the build that
/// compiles the module telling it.
const SIGNATURES: &str = include_str!(concat!(
    env!("OUT_DIR"),
    "/signatures/swift.signatures.json"
));

/// The parsed catalogue, parsed once per process.
static CATALOGUE: OnceLock<SignatureCatalogue> = OnceLock::new();

/// The one instance of this language. A unit struct, so the `static` costs nothing and coerces
/// straight to `&'static dyn ProgramLanguage`.
pub(super) static SWIFT: Swift = Swift;

/// Swift: compiled by `swiftc` into the wasm component that evaluates it, per turn.
pub(super) struct Swift;

impl ProgramLanguage for Swift {
    fn id(&self) -> GgProgramLanguage {
        GgProgramLanguage::Swift
    }

    fn display_name(&self) -> &'static str {
        GgProgramLanguage::Swift.display_name()
    }

    /// One `swiftc` over the model's file, the code modules in scope, gg's shell and the prebuilt
    /// library set, then an in-process component encode — see [`compile`] for what it costs, what it
    /// shares, and how it tells a program `swiftc` refused from a `swiftc` that could not run.
    fn prepare_program(
        &self,
        source: &str,
        modules: &[CodeModule],
        context: &PrepareContext,
    ) -> Result<PreparedProgram, PrepareFailure> {
        compile::compile_program(source, modules, context)
    }

    /// `swiftc`, which is what a Swift programmer calls the compiler and what its own binary is
    /// called.
    ///
    /// Not `wit-component`, which encodes the module `swiftc` emitted into a component and judges
    /// nothing about the program: the same reason the [Rust](super::rust) arm names its front end
    /// and the JVM arms name theirs rather than TeaVM. Naming a checker is also what has this arm's
    /// compile [recorded](crate::sandbox::SandboxOutcome::compile) on every turn, the failing path
    /// included — which matters more here than anywhere, since this is the arm where the compile
    /// *is* the artifact and where a turn's own instantiate costs several times what producing it
    /// did.
    fn checker(&self) -> Option<&'static str> {
        Some("swiftc")
    }

    /// Unpack the embedded guest archive and library set now, so the first code turn does not.
    ///
    /// The whole of this arm's warm-up: 185 KB and 3.4 MB decompressed, once per machine. There is
    /// no daemon to start and no compiler to load, because `swiftc` is a one-shot process whose cost
    /// is the compile rather than the start-up. Idempotent and best effort — a failure here is the
    /// failure the first compile makes, and there it is classified, counted and reported as a
    /// [toolchain failure](PrepareFailure::Toolchain).
    fn warm_prepare(&self) {
        compile::warm();
    }

    /// The module's own `swiftc`, asked to type-check rather than to build — and the names it
    /// offers, read from the author's own source.
    ///
    /// What comes back is **source**, which is what a linked language's module has to be: it is an
    /// input to the [program compile](compile::compile_program) that builds it, not something a
    /// guest could load on its own.
    fn prepare_module(
        &self,
        source: &str,
        context: &PrepareContext,
    ) -> Result<PreparedModule, PrepareFailure> {
        compile::compile_module(source, context)
    }

    /// `.swift`, and nothing else. Nothing else in the registry compiles Swift.
    fn module_file_extensions(&self) -> &'static [&'static str] {
        &["swift"]
    }

    /// [camelCase](self::binding_name) — Swift's own convention for a name a program writes, and
    /// this SDK's for every function it binds.
    fn binding_name(&self, name: &str) -> String {
        binding_name(name)
    }

    /// **`import csvTools`** — the line a program writes to reach a module bound at `csvTools`.
    ///
    /// A code module is compiled into a Swift module of its own, named for the key, and the program's
    /// compile is handed the `-I` that resolves it. That is packaging: it tells the compiler the
    /// module exists and puts no name in scope, exactly as the `-I` that resolves
    /// [gg's own](SURFACE_MODULE) does. So the line is the same line, with the module's own name in
    /// it, and a program that writes none reaches nothing the module carries.
    fn lib_import(&self, key: &str) -> Option<String> {
        Some(format!("import {key}"))
    }

    /// **`csvTools.<name>`** — the module's name and then the export's, which is how Swift reaches
    /// anything an imported module declares.
    ///
    /// The qualified form rather than the bare `parse`, though both resolve: it is what a program
    /// writes when one of its own declarations shares the name, and quoting the form that always
    /// works is what a documentation view is for.
    fn lib_access(&self, key: &str) -> String {
        format!("{key}{}{LIB_ACCESS_NAME}", self.member_separator())
    }

    /// **None.** This arm has no guest component, because the component *is* the program: see this
    /// module's own documentation, and [`PreparedProgram::component`].
    fn guest_component(&self) -> Option<&'static [u8]> {
        None
    }

    /// This language's catalogue, parsed once and checked to be **this** language's.
    ///
    /// Every registered language's build reflects one of these under its own stem into the one
    /// `OUT_DIR`, and each carries the language it was generated for; checking it here is what stops
    /// a catalogue written — or embedded — under the wrong stem from reaching a model as a system
    /// prompt describing a sandbox nobody has.
    fn catalogue(&self) -> &'static SignatureCatalogue {
        CATALOGUE.get_or_init(|| {
            let catalogue = SignatureCatalogue::parse(SIGNATURES)
                .expect("the generated signature catalogue is valid JSON of the expected shape");
            assert_eq!(
                catalogue.language,
                GgProgramLanguage::Swift,
                "`signatures/swift.signatures.json` was generated for another program language",
            );
            catalogue
        })
    }

    /// [`try gg.views.openFile("src/main.swift")`](self::open_file_statement) — with the window as
    /// the call's own two optional arguments, passed by label.
    fn open_file_statement(&self, path: &str, window: Option<FileWindow>) -> String {
        open_file_statement(&spell(self, VIEWS_OPEN_FILE), path, window)
    }

    /// The statements under [the one line](SURFACE_IMPORT) that puts the call they make in scope.
    ///
    /// The seam's default is the statement list alone, which on this arm is a text that would not
    /// compile: `gg` is a module, so a program that names it and imports nothing reaches nothing.
    /// gg pushes this into an agent's transcript as an assistant turn a model reads as the example
    /// of a well-formed reply, so the example has to be one.
    fn open_file_program(&self, views: &[(&str, Option<FileWindow>)]) -> String {
        let statements: Vec<String> = views
            .iter()
            .map(|(path, window)| self.open_file_statement(path, *window))
            .collect();
        format!("{SURFACE_IMPORT}\n\n{}", statements.join("\n"))
    }

    /// [An array of names and a `for` over it](self::open_docs_views_statement), each iteration
    /// opening one documentation view.
    fn open_docs_views_statement(&self, names: &[&str]) -> String {
        open_docs_views_statement(&spell(self, VIEWS_OPEN_DOCS_VIEW), names)
    }

    /// [One search, one array and one `for` loop, every call written with
    /// `try`](self::bootstrap_program), with both calls resolved from this language's own
    /// catalogue.
    fn bootstrap_program(&self, modules: &[&str], docs: &[&str]) -> String {
        bootstrap_program(
            &spell(self, DOCS_SEARCH),
            &spell(self, VIEWS_OPEN_DOCS_VIEW),
            modules,
            docs,
        )
    }

    /// One `func` returning `name` — because a Swift code module is a file of **declarations** and a
    /// Swift program is a file that may also carry statements.
    ///
    /// The seam's default subject is this language's generated documentation program, which opens
    /// with a `let` and then loops: legal at the top level of `main.swift`, and *expressions are not
    /// allowed at the top level* in any other file of a module. So this arm answers for itself, as
    /// the [JVM](super::jvm) arms and [Rust](super::rust) do, and the `name` rides in as a returned
    /// **string literal** — which is where the module's one export hands it back.
    ///
    /// It writes **no access level**, which is what makes the probe a probe on this arm: the module
    /// step publishes a declaration the author left unqualified ([`module_source`](source::module_source)),
    /// so a subject that wrote `public` itself would be handed straight back and the gate would
    /// measure a transform this arm does not perform on anything real.
    #[cfg(test)]
    fn gate_module(&self, name: &str) -> String {
        format!(
            "func marker() -> String {{
    {}
}}
",
            serde_json::Value::String(name.to_string())
        )
    }
}

// ---------------------------------------------------------------------------------------------
// The syntax this arm writes
// ---------------------------------------------------------------------------------------------

/// **The one line a Swift program writes to reach gg's surface.**
///
/// `gg` is an ordinary Swift module the compile resolves through an `-I`, so a program either
/// writes this line or reaches nothing gg carries — including the qualified `gg.files.readFile`,
/// since `gg` is itself the module's name. It is the line every module of this arm's catalogue
/// states as its [import](crate::sandbox::ModuleDoc::import), which a documentation view quotes and
/// which `swift.test.rs` holds this constant to; the same string is written by
/// `packages/gg-sandbox-swift/tools/signatures.py`, which is where the catalogue gets it.
///
/// One line for thirteen modules rather than a line each, because that is what a Swift module is:
/// the thirteen are caseless `enum`s declared in one module, and an `import` of it brings all of
/// them.
pub(super) const SURFACE_IMPORT: &str = "import gg";

/// **The Swift module gg's surface is compiled as**, which is the name [that line](SURFACE_IMPORT)
/// carries.
///
/// Named separately from the line because two things read it rather than write it: the compile
/// [refuses a binding key that would collide with it](compile), since a code module is compiled
/// under its own key; and `swift.test.rs` holds the two to being one statement.
pub(super) const SURFACE_MODULE: &str = "gg";

/// `csv-tools` → `csvTools`, `my_helpers.v2` → `myHelpersV2`, `9lives` → `_9lives`.
///
/// camelCase because that is what Swift spells a name in and what this SDK spells every bound
/// function in, so a program writing `import csvTools` and then `csvTools.parse(…)` reads like the
/// rest of its own scope.
/// Any separator — `-`, `.`, or anything a name should not have had — capitalises the letter after
/// it and disappears, a name that is nothing but separators becomes `module`, and a leading digit is
/// prefixed.
///
/// It has to be a valid Swift **identifier** for the same reason the Rust arm's does: on this arm the
/// key names the Swift module a program imports and the file that module is compiled from, not a
/// string looked up at run time, so a key Swift could not parse would be a program that does not
/// compile.
///
/// Deliberately ASCII-only, though Swift identifiers may be Unicode — including emoji — for the
/// reason every other arm gives: a name a model has to reproduce exactly is one that should have no
/// characters it could get wrong.
pub(super) fn binding_name(name: &str) -> String {
    let mut out = String::new();
    let mut separated = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            match separated && !out.is_empty() {
                true => out.extend(ch.to_uppercase()),
                false => out.push(ch),
            }
            separated = false;
        } else {
            separated = true;
        }
    }
    if out.is_empty() {
        return "module".to_string();
    }
    if out.starts_with(|ch: char| ch.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// `try views.openFile("src/main.swift")`, or the same call with `offset:` and `limit:` for a window
/// — with `views.openFile` already spelled by the language that asked.
///
/// Deliberately the plainest statement that does the job: no binding, no printing. It is synthesized
/// into the agent's own transcript and read by the model as an example of its own output, so anything
/// clever in it is a style the run did not intend to teach. The one thing it *does* teach is the
/// `try`, which is not decoration — every call on this surface throws, and a call written without it
/// does not compile.
///
/// The window is passed as the call's own two optional arguments, **by label**, which is what a Swift
/// author writes and what this SDK offers instead of an options record. The whole-file form passes
/// neither, because they have default values and a Swift author does not pass a default.
///
/// The path is rendered through [`serde_json`] so a quote or a backslash in one cannot produce a
/// statement that would not parse: Swift's string literals accept exactly the escapes JSON's do.
pub(super) fn open_file_statement(
    open_file: &str,
    path: &str,
    window: Option<FileWindow>,
) -> String {
    let path = serde_json::Value::String(path.to_string());
    match window {
        Some(window) => format!(
            "try {open_file}({path}, offset: {}, limit: {})",
            window.offset, window.limit
        ),
        None => format!("try {open_file}({path})"),
    }
}

/// An array of names and a `for` over it, each iteration opening one documentation view.
///
/// An array and a loop rather than one statement per name because the list is as long as the family —
/// eleven calls written out would be a program a model reads as a style to copy — and `let` rather
/// than `var` because nothing assigns to it, which is the first thing Swift's own compiler would say
/// about the alternative.
///
/// The empty case carries a type annotation, because an empty array literal has no element type to
/// infer and `[]` alone is *empty collection literal requires an explicit type*.
///
/// It opens with [the one line](SURFACE_IMPORT) that puts the call in scope, because this is a whole
/// program rather than a fragment: it is the on-use script of every built-in family skill, and a
/// script that named `gg` without importing it would not compile.
pub(super) fn open_docs_views_statement(open_docs_view: &str, names: &[&str]) -> String {
    let entries: Vec<String> = names
        .iter()
        .map(|name| format!("    {}", serde_json::Value::String((*name).to_string())))
        .collect();
    let listed = match entries.is_empty() {
        true => "let functions: [String] = []\n".to_string(),
        false => format!("let functions = [\n{},\n]\n", entries.join(",\n")),
    };
    format!(
        "{SURFACE_IMPORT}\n\n{listed}for name in functions {{\n    try {open_docs_view}(name)\n}}\n"
    )
}

/// The opening turn: one search naming every module gg listed, then an array of the documentation
/// keys with a `for` over it, and every call written with `try`.
///
/// **One** search rather than one per module, because `modules` is a filter that takes a list and
/// reads it as a union — naming all of them answers with all of their directories in one page. The
/// array below it stays because the keys are opened a view at a time and no call takes them
/// together; `let` rather than `var`, and a type annotation on an empty array, for the reasons
/// [`open_docs_views_statement`] gives.
///
/// The filters carry **argument labels** and take default values, which is this language's idiom for
/// optional arguments — so the lookup writes `modules:` and `limit:` and no query at all, rather
/// than an empty string standing in for the argument it does not have. The page is bound to `_`
/// rather than dropped, because a result this program does not read is a warning Swift is right to
/// make and a discard the language spells out.
///
/// An agent granted neither of the modules gg lists here is handed none, and then there is no
/// search to write: no query and no filter is the one call `docs.search` refuses, so the program
/// opens straight into its documentation views instead of on a failure gg wrote for it.
///
/// Every call is fallible, so every one is written with `try` and nothing catches: that is this
/// arm's failure model, and a bootstrap that swallowed its own failure would be a worked example of
/// doing so.
///
/// It opens with [the one line](SURFACE_IMPORT) every Swift program that calls gg opens with, which
/// is the first thing this example teaches and the reason it compiles. There is no narrower line to
/// write on this arm: the surface's modules are caseless `enum`s inside one Swift module, so
/// reaching two of them and reaching all thirteen are the same import.
pub(super) fn bootstrap_program(
    search: &str,
    open_docs_view: &str,
    modules: &[&str],
    docs: &[&str],
) -> String {
    let paths: Vec<String> = modules
        .iter()
        .map(|path| serde_json::Value::String((*path).to_string()).to_string())
        .collect();
    let lookup = match paths.is_empty() {
        true => String::new(),
        false => format!(
            "_ = try {search}(modules: [{}], limit: {MAX_SEARCH_LIMIT})\n\n",
            paths.join(", ")
        ),
    };
    let entries: Vec<String> = docs
        .iter()
        .map(|name| format!("    {}", serde_json::Value::String((*name).to_string())))
        .collect();
    let functions = match entries.is_empty() {
        true => "let functions: [String] = []\n".to_string(),
        false => format!("let functions = [\n{},\n]\n", entries.join(",\n")),
    };
    format!(
        "{SURFACE_IMPORT}\n\
         \n\
         {lookup}{functions}for name in functions {{\n    try {open_docs_view}(name)\n}}\n"
    )
}

#[cfg(test)]
#[path = "swift.test.rs"]
mod tests;

/// **The Swift arm's execution substrate**, driven end to end through gg's real compiler, linker,
/// membrane and store.
///
/// A separate test file from any unit tests, because these are a different kind of test: each one
/// runs a real `swiftc` and compiles a wasm component, which is hundreds of milliseconds rather
/// than microseconds — dear enough that each test function there drives several programs rather
/// than one.
#[cfg(test)]
#[path = "swift.substrate.test.rs"]
mod substrate;

/// **Every Swift example a model is shown, put through `swiftc`** — the prompt's, the notice's and
/// the catalogue's.
///
/// A separate file from [`surface`] because it asks a question no other kind of gate can: not
/// whether the call gg quotes exists, which [`crate::prompts`] already gates in every language, but
/// whether the code around it builds. On a compiled arm an example that does not is a whole turn
/// spent on gg's own prose.
#[cfg(test)]
#[path = "swift.examples.test.rs"]
mod examples;

/// **The Swift arm's model-facing surface** — the hand-written SDK, the catalogue reflected out of
/// its own symbol graph, and the libraries this arm says a program may reach.
///
/// A separate file from [`substrate`] because it is a different claim: that one asks whether Swift
/// runs here, this one asks whether what a model is *told* it may write is what the sandbox really
/// has.
#[cfg(test)]
#[path = "swift.surface.test.rs"]
mod surface;
