//! `api-codegen` — the generator for the backend's API package.
//!
//! It emits the TypeScript bindings of `@clockwyrks/backend-api`
//! (`packages/backend-api/src/*.ts`, via `ts_rs`) and the JSON Schemas of the
//! backend's documents (under `apps/docs/public/schema/`, via `schemars`) from the
//! types in `crates/backend` and `crates/core` that derive `TS` + `JsonSchema` behind
//! their `contract` feature: the HTTP API's request and response shapes, the run
//! queue, coverage plans and ladders, the published snapshot documents, accounts,
//! comparisons and the persisted tournament.
//!
//! Those types refer to the data contract (a snapshot carries a run record, a ladder
//! gates on a review rating), which `contract-codegen` writes. So this generator
//! takes that generator's modules and documents as *external* homes
//! ([`contract_codegen::contract_modules`], [`contract_codegen::contract_schema_docs`]):
//! they are not written here, but an import of a contract type resolves to
//! `@clockwyrks/run-record` and a `$ref` to one resolves to the contract document's
//! URL. Nothing in the data contract refers back to a type here.
//!
//! Run it with `cargo run -p api-codegen`, or `npm run gen:contract`, which runs both
//! generators and normalizes the output with Prettier.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use contract_codegen::emit::{
    SchemaDoc, TsModule, finalize_schemas, finalize_ts, root_schema, ts_config,
};
use contract_codegen::{
    anon, contract_modules, contract_schema_docs, ts_decls, write_schema_in, write_ts,
};

use test_cabinet_backend::{
    api as bapi, coverage::gate, coverage::schedule, error as berr, relay, snapshot as snap,
    store as bstore, suite_store as bsuite,
};
use test_cabinet_core::{
    accounts as acct, comparison as cmp, comparison_stats as cstats, match_play as mp,
    test_case as tc,
};

/// The header stamped on every generated module of the backend API package.
const API_TS_HEADER: &str = "\
// @generated by `api-codegen`. DO NOT EDIT BY HAND.
//
// Regenerate with `npm run gen:contract` (which runs `cargo run -p api-codegen`
// and formats the output). The source of truth is the Rust API types in
// `crates/backend` and `crates/core`, which derive `ts_rs::TS` +
// `schemars::JsonSchema` behind their `contract` feature. The JSON Schemas under
// `apps/docs/public/schema/` are generated from the same types in the same pass.\n\n";

/// The directory, relative to this workspace's root, that the backend's JSON Schema
/// documents are written under: where the documentation site publishes them from.
/// Every document here lives in a directory of its own (`backend-api/`, `coverage/`,
/// `jobs-api/`, `snapshot/`), never in one of the data contract's (`core/`, `gg/`),
/// which `contract-codegen` owns.
const SCHEMA_DIR: &str = "apps/docs/public/schema";

/// The package holding the backend's API: what the console and the gallery read
/// from the backend and its published snapshot, beside the data contract it carries
/// (`@clockwyrks/run-record`). Like the run-record package it is never vendored into
/// a run.
const BACKEND_API_PKG: &str = "@clockwyrks/backend-api";

/// The tournament schema's `$defs`. `AdversarialOutcome` is *not* listed: it is
/// owned by the run-record schema, so a reference to it is rewritten to a
/// cross-document `$ref` at that schema's URL.
const TOURNAMENT_DEFS: &[&str] = &[
    "MatchSummary",
    "Standing",
    "ControllerRef",
    "ControllerKind",
];

/// The review schema's `$defs`: the canonical home of the review value types, so
/// the backend and snapshot documents (and the console that submits reviews) all
/// reference them here rather than each carrying a copy.
const REVIEW_DEFS: &[&str] = &[
    "Rating",
    "AestheticRating",
    "FailureCap",
    "VerdictStatus",
    "ReviewVerdict",
    "DomainRating",
    "DomainAesthetic",
    "RatingChange",
    "AestheticChange",
    "VerdictChange",
    "WriteupChange",
    "ReviewDiff",
    "ReviewRevision",
];

/// This workspace's root, resolved from this crate's own compile-time manifest dir
/// (`crates/api-codegen` → two levels up). Not `contract_codegen::workspace_root`:
/// that one is evaluated in the contract generator's crate, so it names the
/// workspace that crate sits in, which need not be this one.
fn workspace_root() -> Result<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .map(Path::to_path_buf)
        .context("resolving the workspace root from CARGO_MANIFEST_DIR")
}

fn main() -> Result<()> {
    let root = workspace_root()?;
    let cfg = ts_config();

    // --- TypeScript modules ------------------------------------------------
    let modules = vec![
        // The harness-comparison (A/B) contract: the stored config (controls and the
        // per-arm configurations) and the computed read model (per-arm distributions,
        // automated-only score, diagnostics, confounds). The descriptive statistics
        // (`MetricSummary`, `PassRate`) are shared leaves the arm results embed.
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "comparison.ts",
            decls: ts_decls![&cfg;
                cstats::MetricSummary, cstats::PassRate,
                cmp::ScorePoint, cmp::ArmScore, cmp::ArmDiagnostics, cmp::ArmRunPoint,
                cmp::Confound, cmp::ComparisonControls, cmp::ComparisonArm, cmp::ComparisonConfig,
                cmp::ComparisonArmResult, cmp::Comparison,
                bapi::ComparisonInput,
            ],
        },
        // The auth surface: accounts and the register/login request + token
        // response.
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "account.ts",
            decls: ts_decls![&cfg;
                acct::Account, acct::RegisterRequest, acct::LoginRequest, acct::AuthnResponse,
            ],
        },
        // The published snapshot documents (the static gallery's data): the index,
        // the runs index + summary cards, the per-run document, and case metadata.
        // `ReferenceKind`, `SpecKind` and `ErratumSeverity` are contract types, but
        // only the case metadata refers to them, so they are declared here.
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "snapshot.ts",
            decls: ts_decls![&cfg;
                snap::SnapshotIndex, snap::SubjectOut, snap::LinksOut, snap::RunSummary,
                snap::RunScoreOut, snap::PerformanceSummaryOut, snap::CodeSummaryOut,
                snap::RunsIndex, snap::RunProofOut,
                snap::RunAssetOut, snap::RunValidationMediaOut, snap::RunShowcaseOut, snap::PerRun,
                tc::ReferenceKind, tc::SpecKind, tc::ErratumSeverity,
                snap::CaseCheckOut, snap::CaseDomainOut,
                snap::CaseErratumOut, snap::CaseReviewValidationOut,
                snap::CaseReviewItemOut, snap::CaseSubReviewItemOut,
                snap::CaseReferenceOut,
                snap::CaseValidationBaselineOut, snap::CaseSeededInputOut,
                snap::CasePackageOut, snap::CaseReferenceSheetOut,
                snap::CaseShowcaseMediaOut, snap::CaseShowcaseOut, snap::CaseWorkspaceFileOut,
                snap::CaseVariantRenderingOut, snap::CaseVariantOut,
                snap::CaseMetadata,
                snap::ModelCatalogFile,
                snap::TestCaseGroupsFile,
                snap::ComparisonsIndex, snap::ComparisonFile,
                snap::GgRunsFile,
            ],
        },
        // The backend HTTP API response envelopes (error + catalog/versions).
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "index.ts",
            decls: ts_decls![&cfg;
                berr::ErrorBody, berr::ErrorEnvelope,
                bapi::ShowcaseMediaOut, bapi::CatalogShowcaseOut,
                bapi::CatalogCase, bapi::CatalogResponse,
                bapi::VersionsResponse,
                bapi::TestCaseGroupOut, bapi::TestCaseGroupsResponse,
                bapi::ModelCatalogResponse, bapi::AliasOut, bapi::ModelOut, bapi::ModelPricesOut,
                bapi::PriceObservationOut, bapi::AliasInput, bapi::ModelConfigInput,
                bapi::ModelSeedOut, bapi::ModelListingOut, bapi::LogoFetchInput,
                bapi::LogoFetchOut,
                bapi::ProbeTriggerInput, bapi::ProbeTriggerResponse, bapi::ModelProbeOut,
                bapi::ModelProbeItemOut, bapi::ModelProbesResponse, bapi::ModelProbeDetailResponse,
                bapi::ProbeMessage, bapi::ProbeToolCall, bapi::ProbeToolFunction,
                bapi::ProbeRequestOut,
                bapi::ProbeProvidersResponse, bapi::ProbeProviderOut,
                bapi::ModelCandidatesOut, bapi::CandidateOut,
                bapi::ProviderStatsResponse, bapi::ProviderStatsOut, bapi::ProviderModelStatsOut,
                bapi::ProviderCallStatsOut, bapi::ProbeProviderStatsOut, bapi::ProbeProviderModelOut,
                bapi::ModelAccuracyResponse, bapi::ModelAccuracyOut, bapi::RacAccuracyOut,
                bapi::ToolCallingAccuracyOut,
                bapi::CabinetStatsResponse, bapi::CabinetTokensOut, bapi::CabinetCostOut,
                bapi::CabinetWeekOut,
                // The test suites the backend ingested: the coordinate a
                // suite-defined test case carries on the catalog and version reads,
                // then the suite listing and the resolved record one version's read
                // serves. The entities the record holds are the format's own types,
                // declared in `test-suite.ts` and imported from it.
                bstore::StoredSuiteCoordinate,
                bsuite::SuiteVersionIdentity, bapi::SuiteOut, bapi::SuitesResponse,
                bsuite::StoredSuiteSpecification, bsuite::StoredSuiteDefinition,
                bsuite::StoredSuiteAsset, bsuite::StoredSuiteDemo,
                bsuite::StoredSuiteShowcase, bsuite::StoredSuite,
                // A suite version's read beside the reference builds uploaded for
                // it, and what an upload answers.
                bapi::SuiteVersionResponse, bapi::ReferenceBuildOut,
            ],
        },
        // The backend's run-queue control plane (the `/jobs` namespace) — what
        // replaced the worker's run API. The console enqueues a run, observes it
        // via the live stream / status / active list, and is alerted on completion
        // over the notification feed. The shared launch/claim/status shapes live in
        // `core::job_api`; the server outputs and the relay's summary/notification
        // shapes live in `backend`. `ClientConfig` is the console's `GET /config`
        // body (today just the artifact-service base URL).
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "jobs-api.ts",
            decls: ts_decls![&cfg;
                bapi::DriverState, bapi::LaunchBody, bapi::GgRunRequest, bapi::ClaimedJob,
                bapi::StatusUpdate,
                bapi::JobState, relay::JobSummary, bapi::ActiveJobOut, bapi::JobStatusOut,
                bapi::LaunchAck, bapi::LaunchBatchBody, bapi::LaunchBatchItem, bapi::LaunchBatchAck,
                bapi::BulkCancelOut,
                relay::NotificationOutcome, relay::NotificationKind, relay::Notification,
                relay::RunEventKind, relay::RunEvent,
                bapi::StreamOpened, bapi::StreamResync, bapi::StreamTopicsBody,
                bapi::ClientConfig,
            ],
        },
        // The reviewer coverage surface (console-only): reusable groups, multiple
        // declarative plans (`/coverage-groups`, `/coverage-plans`), and the coverage
        // matrix a plan expands into (`GET /coverage-plans/{id}/coverage`). The
        // combination and cell types reference `HarnessSlug`, owned by the run-record
        // document.
        //
        // A plan's declaration (`CoveragePlan`, its launch order and runs-in-flight
        // override included) and `CoveragePlanOut`, the shape the console reads, which
        // adds whether it is filling. The rest are the controls around a fill: the
        // account-wide runs-in-flight limit, one launch pass's report, a blocked cell's
        // retry, the plan-scoped review queue, the runs the plan's cells hold, and what a
        // halt or a stop cancelled.
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "coverage.ts",
            decls: ts_decls![&cfg;
                bapi::ReviewPlanCase, bapi::ReviewPlanCombo,
                bapi::CoverageGroupKind, bapi::CoverageGroup, bapi::CoverageGroupInput,
                schedule::InFlightLimit,
                bapi::CoverageAxis,
                bapi::CoveragePlan, bapi::CoveragePlanOut, bapi::CoveragePlanInput,
                bapi::CoveragePlanSummary,
                bapi::CoverageCell, bapi::CoverageMatrix,
                bapi::CoverageSettings, bapi::CoverageSettingsInput,
                bapi::LaunchSkipped, bapi::LaunchedCell, bapi::BlockedCell,
                bapi::LaunchPassResult, bapi::PlanCellRetryInput,
                bapi::CoverageQueueEntry, bapi::CoverageQueue, bapi::CoveragePlanRuns,
                bapi::HaltResult,
            ],
        },
        // Ladders (`/ladders`): an ordered series of rungs that harness+model
        // combinations climb one at a time, gated at each rung by the validators'
        // ratings of its runs. A sibling of the coverage plan rather than a mode of
        // it, so it gets its own module — but it reuses the plan's combination
        // pointers (`ReviewPlanCombo`, imported from `coverage.ts`) and the review
        // document's `Rating`, which is the gate's floor.
        //
        // `Gate`/`GateThreshold` come from `backend::coverage::gate`, where the one
        // parameterised rule lives; every other type here is either the ladder's
        // configuration, its latest dispatch's board and list summary, or one of the
        // controls (stop, retry, reorder) over them.
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "ladders.ts",
            decls: ts_decls![&cfg;
                gate::GateThreshold, gate::Gate,
                bapi::LadderAxis,
                bapi::LadderRung, bapi::LadderRungInput,
                bapi::Ladder, bapi::LadderInput,
                bapi::DispatchStatus, bapi::SlotStatus, bapi::ClimberStatus, bapi::ClimberBlock,
                bapi::SlotCounts, bapi::DispatchRuns, bapi::LadderDispatch,
                bapi::RungTally, bapi::LadderSlot,
                bapi::LadderClimber, bapi::LadderProgressRung, bapi::LadderProgress,
                bapi::LadderSummary, bapi::LadderDispatchSummary,
                bapi::LadderStopInput, bapi::LadderRetryInput, bapi::LadderRungOrderInput,
            ],
        },
        // The persisted tournament document: the arena's record of a set of matches
        // and the standings they came to. Its match summary references the run
        // record's `AdversarialOutcome`, imported from the run-record package.
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "tournament.ts",
            decls: ts_decls![&cfg;
                mp::ControllerKind, mp::ControllerRef, mp::MatchSummary, mp::Standing,
                mp::TournamentRecord,
            ],
        },
        // The saved gg configurations (`/gg/configs`) and agents (`/gg/agents`): a
        // registered configuration is a named capability set, and a saved agent wraps
        // one agent profile out of it, so both import their contents from the
        // run-record package's `gg` module.
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "gg.ts",
            decls: ts_decls![&cfg;
                bapi::GgConfig, bapi::GgConfigInput, bapi::GgAgentSource,
                bapi::GgSavedAgent, bapi::GgSavedAgentInput,
            ],
        },
        // The TCQ batch envelope (a dashboard answers all its panels from one index
        // read; the public static site evaluates locally and has no use for it) and the
        // saved **views** (`/gg/saved-queries`, `/gg/dashboards`): per-account objects
        // over a corpus that is not, each storing query *source text* rather than a
        // compiled query. The language they are written in is the run-record
        // package's `gg-query` module.
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "gg-query.ts",
            decls: ts_decls![&cfg;
                bapi::GgQueryBatch, bapi::GgQueryBatchResponse,
                bapi::GgSavedQuery, bapi::GgSavedQueryInput,
                bapi::GgDashboardPanel, bapi::GgDashboard, bapi::GgDashboardInput,
            ],
        },
        // The published `Review` wire shape. The review value types it is made of are
        // the run-record package's `review` module.
        TsModule {
            package: BACKEND_API_PKG,
            reexports: &[],
            file: "review.ts",
            decls: ts_decls![&cfg; snap::Review],
        },
    ];
    let contract = contract_modules(&cfg);
    for (package, file, content) in finalize_ts(modules, &contract, API_TS_HEADER) {
        write_ts(&root, package, file, &content)?;
    }

    // --- JSON Schema documents ---------------------------------------------
    let docs: Vec<SchemaDoc> = vec![
        SchemaDoc {
            rel_path: "backend-api/tournament.schema.json",
            root: Some("TournamentRecord"),
            owns: TOURNAMENT_DEFS,
            schema: root_schema::<mp::TournamentRecord>(),
        },
        // `POST /gg/query/batch` — a dashboard's panels answered from one index read.
        // Both envelopes are pure wrappers around the query and response documents
        // above, so every ref in them is cross-document.
        anon(
            "backend-api/gg-query-batch-request.schema.json",
            root_schema::<bapi::GgQueryBatch>(),
        ),
        anon(
            "backend-api/gg-query-batch-response.schema.json",
            root_schema::<bapi::GgQueryBatchResponse>(),
        ),
        // The operator's saved **views** over the corpus (`/gg/saved-queries`,
        // `/gg/dashboards`) — per-account objects over a population that is not, which is
        // the whole saved-object model. They are the backend's documents, not the
        // query language's, so they sit with the backend's others under `backend-api/`
        // (named `gg-*` after the language they are written in): what they store is
        // query *source text*, and neither schema references a run-record type at all.
        // The dashboard owns its panel type, so that ref stays inline.
        anon(
            "backend-api/gg-saved-query.schema.json",
            root_schema::<bapi::GgSavedQuery>(),
        ),
        SchemaDoc {
            rel_path: "backend-api/gg-dashboard.schema.json",
            root: Some("GgDashboard"),
            owns: &["GgDashboardPanel"],
            schema: root_schema::<bapi::GgDashboard>(),
        },
        // The backend's run-queue (`/jobs`) control plane. These reference the core
        // run-record document by URL (the launch request, the claimed job, and the
        // driver's status update all carry or echo a `RunRecord`); any type local to
        // a single document (its own ack/summary) stays inline.
        anon(
            "jobs-api/launch-run-request.schema.json",
            root_schema::<bapi::LaunchBody>(),
        ),
        // The gg run mode's enqueue request. Its `capabilitySet` is the core-owned
        // `GgCapabilitySet` (owned by `gg/capability-set.schema.json`), so that ref is
        // rewritten to a cross-document URL.
        anon(
            "jobs-api/gg-run-request.schema.json",
            root_schema::<bapi::GgRunRequest>(),
        ),
        anon(
            "jobs-api/launch-run-ack.schema.json",
            root_schema::<bapi::LaunchAck>(),
        ),
        anon(
            "jobs-api/launch-batch-request.schema.json",
            root_schema::<bapi::LaunchBatchBody>(),
        ),
        anon(
            "jobs-api/launch-batch-ack.schema.json",
            root_schema::<bapi::LaunchBatchAck>(),
        ),
        anon(
            "jobs-api/claimed-job.schema.json",
            root_schema::<bapi::ClaimedJob>(),
        ),
        anon(
            "jobs-api/status-update.schema.json",
            root_schema::<bapi::StatusUpdate>(),
        ),
        anon(
            "jobs-api/active-jobs.schema.json",
            root_schema::<Vec<bapi::ActiveJobOut>>(),
        ),
        anon(
            "jobs-api/job-status.schema.json",
            root_schema::<bapi::JobStatusOut>(),
        ),
        anon(
            "jobs-api/notification.schema.json",
            root_schema::<relay::Notification>(),
        ),
        anon(
            "jobs-api/run-event.schema.json",
            root_schema::<relay::RunEvent>(),
        ),
        anon(
            "jobs-api/stream-topics.schema.json",
            root_schema::<bapi::StreamTopicsBody>(),
        ),
        anon(
            "jobs-api/client-config.schema.json",
            root_schema::<bapi::ClientConfig>(),
        ),
        // The reviewer coverage surface: a plan, a reusable group, and the coverage
        // matrix a plan expands into. All reference `HarnessSlug`, owned by the
        // run-record document, so that ref is rewritten to a cross-document URL.
        anon(
            "coverage/coverage-plan.schema.json",
            root_schema::<bapi::CoveragePlan>(),
        ),
        anon(
            "coverage/coverage-group.schema.json",
            root_schema::<bapi::CoverageGroup>(),
        ),
        anon(
            "coverage/coverage-matrix.schema.json",
            root_schema::<bapi::CoverageMatrix>(),
        ),
        // The account-wide runs-in-flight limit (`GET /coverage-settings`), which
        // every plan and ladder inherits unless it overrides it.
        anon(
            "coverage/coverage-settings.schema.json",
            root_schema::<bapi::CoverageSettings>(),
        ),
        // The ladder counterparts: the configuration (`GET /ladders/{id}`, the
        // analogue of the coverage plan) and its latest dispatch's board
        // (`GET /ladders/{id}/progress`, the analogue of the coverage matrix). The
        // board is where the gate's tally and the slot statuses surface, so it
        // inlines them.
        anon("coverage/ladder.schema.json", root_schema::<bapi::Ladder>()),
        anon(
            "coverage/ladder-progress.schema.json",
            root_schema::<bapi::LadderProgress>(),
        ),
        // Backend API: the auth surface (the token response is the canonical home
        // of Account) and the canonical review document (the home of the review
        // value types the backend + snapshot reference).
        SchemaDoc {
            rel_path: "backend-api/auth.schema.json",
            root: Some("AuthResult"),
            owns: &["Account"],
            schema: root_schema::<acct::AuthnResponse>(),
        },
        anon(
            "backend-api/auth-register-request.schema.json",
            root_schema::<acct::RegisterRequest>(),
        ),
        anon(
            "backend-api/auth-login-request.schema.json",
            root_schema::<acct::LoginRequest>(),
        ),
        anon(
            "backend-api/error.schema.json",
            root_schema::<berr::ErrorEnvelope>(),
        ),
        anon(
            "backend-api/test-case-catalog.schema.json",
            root_schema::<bapi::CatalogResponse>(),
        ),
        anon(
            "backend-api/test-case-versions.schema.json",
            root_schema::<bapi::VersionsResponse>(),
        ),
        // The fully-resolved definition of one test-case version (`GET
        // /test-cases/{slug}/{version}`). Self-contained except for the core
        // run-record types it shares (`TestType`, `MediaKind`, `AssetSheet`),
        // which are rewritten to cross-document `$ref`s at the run-record URL.
        anon(
            "backend-api/resolved-test-case-version.schema.json",
            root_schema::<bapi::VersionResponse>(),
        ),
        SchemaDoc {
            rel_path: "backend-api/review.schema.json",
            root: Some("Review"),
            owns: REVIEW_DEFS,
            schema: root_schema::<snap::Review>(),
        },
        // Snapshot documents (the static gallery's published data). Each references
        // the core run-record and review documents by URL; its own summary/envelope
        // subtypes stay inline.
        anon(
            "snapshot/index.schema.json",
            root_schema::<snap::SnapshotIndex>(),
        ),
        anon(
            "snapshot/runs.schema.json",
            root_schema::<snap::RunsIndex>(),
        ),
        anon("snapshot/run.schema.json", root_schema::<snap::PerRun>()),
        // The gg document corpus the public site's Discover surface evaluates in the
        // browser. `GgRunDoc` is owned by `gg/run-document.schema.json`, so its ref here
        // becomes a cross-document URL.
        anon(
            "snapshot/gg-runs.schema.json",
            root_schema::<snap::GgRunsFile>(),
        ),
        anon(
            "snapshot/case.schema.json",
            root_schema::<snap::CaseMetadata>(),
        ),
    ];
    for (rel_path, value) in finalize_schemas(docs, &contract_schema_docs())? {
        write_schema_in(&root.join(SCHEMA_DIR), rel_path, &value)?;
    }

    Ok(())
}
