//! `gg` — the crate a **Rust** [responses-as-code] program is compiled against.
//!
//! [responses-as-code]: https://docs.testcabinet.ai/gg/responses-as-code/
//!
//! Under that capability a model answers a turn by writing a whole *program* instead of a batch of
//! tool calls, and the language it writes in is a run variable. This is the Rust arm's half of
//! that: the crate `rustc --extern gg=…` puts in scope when gg compiles a model's program, once per
//! turn, into the wasm component that turn is evaluated by.
//!
//! # What is here today
//!
//! The arm's **execution substrate** and nothing else — the shell a program runs inside, the
//! failure it reports through, and the generated WIT bindings both are written against. The
//! idiomatic, namespaced SDK a model actually calls (`gg::fs`, `gg::view`, `gg::agents`, …) lands
//! on top of this, in this same crate, and is where [`program::TOOLS`] stops being empty.
//!
//! # The shape of a program
//!
//! A program is a **sequence of statements**, as on every gg arm but PureScript. gg wraps the
//! model's text in a function body whose return type is `Result<(), `[`Failure`]`>` — which is what
//! makes `?` the operator a Rust author would reach for against a `Result`-returning SDK, rather
//! than the `E0277` a `()`-returning wrapper would have made of it.
//!
//! Everything Rust allows in a function body is therefore allowed in a program: `use`, `struct`,
//! `enum`, `impl`, `trait`, `fn`, `const`, `static`, `mod`, and `#[derive(…)]` on any of them. The
//! one thing that is not is a program that defines `fn main` and expects gg to call it — there is
//! no `main` on this arm, and gg refuses that program by name rather than running the half of it
//! that is not inside the function nobody called.
//!
//! # How a failure gets out
//!
//! Two ways, and they are different failures.
//!
//! * **The program returned `Err`.** Ordinary control flow: the shell reports it over
//!   `feedback.report-error` and the turn ends with a model-facing error.
//! * **The program panicked.** `wasm32-unknown-unknown` has no unwinder — `panic = "unwind"` is not
//!   available on it — so a panic aborts, and an abort traps the whole store. A trap carries no
//!   message and no location, so what a model would be told is "your program trapped" and nothing
//!   else. [`program::begin`] therefore installs a panic hook that completes a
//!   `feedback.report-error` host call **before** the abort, carrying the panic's message and the
//!   line and column of the model's own text. That call is not best-effort: it is a synchronous
//!   host call that finishes, and gg keeps what it recorded even though the store then traps.

/// The generated WIT bindings — every host function the sandbox offers, as `wit-bindgen` binds it.
///
/// **Not the model-facing surface.** These are the raw wire: `kebab-case` interfaces reached by
/// their full package path, results typed as WIT's `result<_, error>` rather than as anything a
/// Rust author would recognise, and — deliberately — the `feedback` interface, which
/// `crates/gg/wit/gg-sandbox.wit` calls "deliberately NOT part of the model-facing surface" and
/// which this arm's shell needs. The SDK is the curated facade over this; a model is never shown
/// this module.
///
/// Generated by `build.sh` with the pinned `wit-bindgen` CLI and **not committed**: it is a pure
/// function of `crates/gg/wit/gg-sandbox.wit` and that pin, and a copy in the tree would be a
/// second thing to keep in step with the wire.
#[allow(warnings)]
pub mod bindings;

pub mod program;

pub use program::Failure;
