#!/usr/bin/env bash
# Reflect the **Swift** program language's signature catalogue out of the SDK's own documentation
# and write `$GG_SIGNATURES_OUT_DIR/swift.signatures.json`.
#
# WHERE IT WRITES, AND WHY THERE IS NO DEFAULT. The catalogue is a BUILD ARTIFACT.
# `crates/gg/build.rs` runs `scripts/gg-signatures.sh` and embeds what lands in the build's own
# `OUT_DIR`, so the doc comments a model is shown are reflected on the same build that compiles the
# host showing them — a `- Parameter` edited without a regeneration is not a state this checkout can
# be in. A default here would be a second answer to a question the build already answers, and the
# old one, `crates/gg/src/sandbox/guests/`, is the answer that stopped being right. Run it by hand,
# into a directory of your choosing, to READ a catalogue — which is what `scripts/gg-signatures.sh`
# is for, and how a reflector bug gets found.
#
# WHAT READS THE DOCUMENTATION. `swiftc -emit-symbol-graph`, which is the same machinery DocC is
# built on: for every public declaration it emits the doc comment, the resolved types, the
# parameter list with each label and internal name, and — for a `- Parameters:` block — nothing at
# all, because a doc comment is text and DocC's parameter sections are a CONVENTION over it. So
# this step gets the types and the declarations from the graph and the per-parameter prose from
# the comment, and `tools/signatures.py` holds the convention to being a contract: a function that
# takes N arguments must document N, in order, under their own names, or the reflection fails.
#
# The graph is emitted for `wasm32-unknown-wasip1`, the target this arm really compiles to, so the
# types in it are the types a program is really compiled against.
#
# WHY IT WRITES EXACTLY ONE FILE, AND WHY THAT MATTERS MORE THAN IT USED TO. This runs on every
# build of gg that regenerates a catalogue, which is to say under a developer who typed
# `cargo build`. `build.sh` cuts this arm's guest and library archives, which is ~22 s and 3.6 MB —
# the dearest artifact build of any arm. A signature step that reached `build.sh` for the bindings it
# needs would re-cut both on the way past, every time a doc comment moved.
#
# Both halves are now generated during the same `cargo build`, each with its own rerun set:
# `crates/gg-sandbox-artifacts/swift` runs `build.sh` and `crates/gg/build.rs` runs this. Folding one
# into the other would collapse those two sets into one, which is the whole cost the artifact crates
# exist to avoid. `bindings.sh` remains the one step both need, split out of the one with side
# effects. This writes exactly one file, into `$GG_SIGNATURES_OUT_DIR`.
#
# Usage:
#   GG_SIGNATURES_OUT_DIR=<dir> packages/gg-sandbox-swift/signatures.sh
#   scripts/gg-signatures.sh                 # all eleven arms, into one directory
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=packages/gg-sandbox-swift/swift-version.sh
source "$HERE/swift-version.sh"

# ONE ARM, ONE PROCESS AT A TIME. This package's scratch is a fixed path inside the source tree
# rather than a `mktemp -d`, deliberately — it is a cache — and two cargo processes with two target
# directories do not serialise with each other. See `scripts/gg-scratch-lock.sh`.
# shellcheck source=scripts/gg-scratch-lock.sh
source "$HERE/../../scripts/gg-scratch-lock.sh"
gg_lock_scratch "$HERE"

# NO BYTECODE CACHE. `tools/signatures.py` imports its sibling `tools/catalogue.py`, and an ordinary
# CPython drops a `__pycache__/` beside a module it imports. That directory is gitignored and
# harmless to a person, but `crates/gg/build.rs` names this package's `tools` subtree as an input
# whose change should re-reflect the catalogue — so a run that writes into it leaves the next
# `cargo build` convinced its inputs moved and re-runs all eleven arms. The export lives here rather
# than only in `scripts/gg-signatures.sh` because running this script BY HAND is the documented way
# to read a catalogue, and a developer who does that should not pay for it on their next build.
export PYTHONDONTWRITEBYTECODE=1

if [ -z "${GG_SIGNATURES_OUT_DIR:-}" ]; then
	echo "error: GG_SIGNATURES_OUT_DIR is not set. It names the directory this catalogue is" >&2
	echo "       written into, and there is no default — the catalogue is generated by the build" >&2
	echo "       rather than committed anywhere." >&2
	echo "       Run scripts/gg-signatures.sh (which sets it and regenerates every arm), or set" >&2
	echo "       it yourself to a directory you want the JSON in." >&2
	exit 1
fi
# Created, then made absolute, because the reflector is handed it as a path to write and everything
# else here is addressed from `$HERE` rather than from the caller's working directory.
mkdir -p "$GG_SIGNATURES_OUT_DIR"
OUT="$(cd "$GG_SIGNATURES_OUT_DIR" && pwd)/swift.signatures.json"
GRAPH="$HERE/.build/symbol-graph"
BINDINGS="$HERE/.build/bindings"

SWIFT_HOME="$(gg_swift_home)"
SWIFTC="$SWIFT_HOME/toolchain/usr/bin/swiftc"
SDK="$SWIFT_HOME/sdk"
if [ ! -x "$SWIFTC" ]; then
	cat >&2 <<EOF
error: no Swift toolchain at $SWIFT_HOME.
       Run scripts/ci/install-gg-toolchains.sh, or set TCAB_GG_SWIFT_HOME.
EOF
	exit 1
fi
export LD_LIBRARY_PATH="$SWIFT_HOME/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

"$HERE/bindings.sh"

echo "==> emitting the SDK's symbol graph"
rm -rf "$GRAPH"
mkdir -p "$GRAPH"
"$SWIFTC" \
	-target "$GG_SWIFT_TARGET" \
	-sdk "$SDK/WASI.sdk" \
	-resource-dir "$SDK/swift.xctoolchain/usr/lib/swift_static" \
	-wmo -parse-as-library -module-name gg \
	-import-objc-header "$BINDINGS/sandbox.h" \
	-emit-module -emit-module-path "$GRAPH/gg.swiftmodule" \
	-emit-symbol-graph -emit-symbol-graph-dir "$GRAPH" \
	"$HERE"/Sources/SDK/Modules/*.swift "$HERE"/Sources/SDK/Internal/*.swift
test -s "$GRAPH/gg.symbols.json"

echo "==> reflecting $OUT"
python3 "$HERE/tools/signatures.py" "$GRAPH/gg.symbols.json" "$HERE/libraries.txt" "$HERE" "$OUT"
